### ISSUE TITLE
Gollum fails to handle X-Forwarded-Host

### ISSUE THREAD

**Issue by TobyHFerguson** [gollum/gollum#1001]
When setting up an Apache 2.2 webserver as a reverse proxy for Gollum 4.0.0 I find that Gollum returns a '404 Not Found' when the header X-Forwarded-Host: is present in the HTTP Get request, but returns '302 Found' when that header is not present. Unfortunately there is not (to my knowledge) a way of stopping Apache 2.2 from sending the X-Forwarded-Host: header.

This seems to me to be a bug in Gollum - it should not respond differently based on the presence of this "standard" header.

Here are two telnet sessions - the first shows how Gollum behaves when all the 'proxying' headers except X-Forwarded-Host: is present, the second shows the failure when X-Forwarded-Host: is added:

```
[Toby@ca-ovsx32 ~]$ telnet localhost 4567
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /wiki HTTP/1.1
Host: localhost:4567
User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Accept: */*
X-Forwarded-For: 10.80.154.88
X-Forwarded-Server: ca-ovsx32.us.oracle.com
Connection: Keep-Alive

HTTP/1.1 302 Found
Content-Type: text/html;charset=utf-8
Location: http://localhost:4567/wiki/Home
Content-Length: 0
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Server: WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13)
Date: Thu, 23 Apr 2015 07:15:22 GMT
Connection: Keep-Alive
```

And now the error case:

```
[Toby@ca-ovsx32 ~]$ telnet localhost 4567
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /wiki HTTP/1.1
Host: localhost:4567
User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Accept: */*
X-Forwarded-For: 10.80.154.88
X-Forwarded-Host: ca-ovsx32
X-Forwarded-Server: ca-ovsx32.us.oracle.com
Connection: Keep-Alive

HTTP/1.1 404 Not Found
Content-Type: text/plain
X-Cascade: pass
Server: WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13)
Date: Thu, 23 Apr 2015 07:16:52 GMT
Content-Length: 16
Connection: Keep-Alive

Not Found: /wiki
```

**Comment by dometto** [comment]
@TobyHFerguson, it would help to have the output from WEBrick, which hopefully contains some kind of stack trace or indication of where the 404 is being returned.

**Comment by dometto** [comment]
@TobyHFerguson, it would be very helpful if you could provide more information of the kind I mentioned.

**Comment by TobyHFerguson** [comment]
Yeah. Sorry. Been busy closing end of year business. Let me see if I can't
find an hour or two after June 1 to investigate further.

**Comment by TobyHFerguson** [comment]
Apologies - still snowed under - I do want to get you the information you requested, but having difficulty scheduling the time ...

**Comment by dometto** [comment]
No problem :)

**Comment by TobyHFerguson** [comment]
Sorry its taken me so long to get this data ...

I ran gollum thus:

```
gollum --base-path wiki
```

and collected the output (I think everything goes to stdout/stderr in this mode)

From the first (correct) response I got:
```
localhost - - [14/Jun/2015:19:50:28 MDT] "GET /wiki HTTP/1.1" 302 0
- -> /wiki
```

And from the second (incorrect) response  got:
```
localhost - - [14/Jun/2015:19:51:47 MDT] "GET /wiki HTTP/1.1" 404 16
- -> /wiki
```
So, as far as I can see, there's no error difference (no stack trace, no error logs). Ugh. Sorry its taken so long to get nowhere :-(

Is there any further tracing I can turn on, maybe at the ruby level? (I don't know Ruby, so will need some guidance here).

**Comment by dometto** [comment]
All very strange. When running with `--base-path`, gollum is run inside a piece of `rack` middleware which returns the 302 [here](https://github.com/gollum/gollum/blob/master/bin/gollum#L214-L216). Seems to me as if this middleware is returning the 404, which means the `/` route is not matched when the `X-Forwarded-Host` is present. Possibly a bug/feature in rack's route matching?

**Comment by dometto** [comment]
Rack is returning the 404 [here](https://github.com/rack/rack/blob/master/lib/rack/urlmap.rb#L69) it seems. To find out what's happening it would be interesting to know the values of `@mapping` and `env` at that point, but I don't know of a way to do this other than modifying the source of the rack gem at that point, adding e.g.:
```ruby
puts "DEBUG"
puts "env: #{env.inspect}"
puts "@mapping: #{@mapping.inspect}"
```

**Comment by dometto** [comment]
@njman @TobyHFerguson, if you're still running into this I would consider asking some rack guru's on stackoverflow about the interplay between X-Forwarded-Host and `Rack::Builder`.

**Comment by bartkamphorst** [comment]
Closing as this issue seems to pertain to rack rather than gollum.

**Comment by nbeijar** [comment]
I had the same problem with Gollum and Apache reverse proxy. I solved it by including the ProxyAddHeaders Off directive in Apache config, which prevents the reverse proxy from setting the X-Forwarded-Host header.
