### ISSUE TITLE
table rendered abnormal in version 4.0.0

### ISSUE THREAD

**Issue by ngloom** [gollum/gollum#1008]
table content as below:

```
    First Header | Second Header
    ------------ | -------------
    Content from cell 1 | Content from cell 2
    Content in the first column | Content in the second column
```

with result rendered like below : 

![table_text](https://cloud.githubusercontent.com/assets/495831/7554180/8249cb62-f750-11e4-829d-e2728821971a.png)

![table-preview](https://cloud.githubusercontent.com/assets/495831/7554181/84a0cae6-f750-11e4-8877-c191e085716b.png)

I'm using the newest **4.0.0 gollum** and start by  `gollum --mathjax --allow-uploads` with no error in logs.
Is anywhere I did wrong? Help needed.

**Comment by ngloom** [comment]
Sorry, guys:
I've forgot `gem install github-markdown`, all's fine now, sorry for disturb.

**Comment by bartkamphorst** [comment]
No problem, glad you got it sorted. :+1:
