### ISSUE TITLE
AsciiDoc include macro does not link to included document

### ISSUE THREAD

**Issue by ellipticview** [gollum/gollum#1010]
To reproduce:
Create a new Asciidoc document named Chapter1.
Gollum saves it as Chapter1.asciidoc
Edit Home.asciidoc and add this line:

```
include::Chapter1.asciidoc[]
```

When the Homepage is rendered, it renders the include as "Chapter1.asciidoc" as the visible text, and the same as the URL of this link.

Clicking on this link results in a download of the file instead navigating to this page.

If I change the line to:
```
include::Chapter1[]
```
then I do get the desired behavior (ie a click on the link navigates to the page). But this syntax is not in line with the AsciiDoc specification, so this cannot be used as a workaround. It would not work with other AsciiDoc tools.

**Comment by SkyCrawl** [comment]
@ellipticview 
With asciidoc's include syntax (`include::page.asciidoc[]`), you're actually relying on `github-markup` gem to render the included page - it is not handled by Gollum. As such, Gollum's many additional features will be useless when it comes to rendering the included page (macros will not be rendered, for example).

Instead of using markup-specific include syntax, use [Gollum's syntax](https://github.com/gollum/gollum/wiki#include-other-pages). When you use it, Gollum will render and include the given page into "main" one.

**Comment by ellipticview** [comment]
Well, in my case I'm using standard Asciidoc file format and the Asciidoctor toolchain to produce my output. My use for Gollum, is for easy navigation and editing of the content. I do not want to add any Gollum-specific syntax to the content because that will break the build process. If Gollum has Asciidoc support as a goal, then I believe it should at least be able to handle the Asciidoc syntax. Maybe not render it perfectly in all cases, but at least allow the content to adhere to the standard.

**Comment by dometto** [comment]
This is a known issue. See the workaround in #878.

**Comment by SkyCrawl** [comment]
@dometto 
Why not simply convert asciidoc's include syntax to Gollum's own dynamically?

**Comment by dometto** [comment]
> @dometto <https://github.com/dometto>
> Why not simply convert asciidoc's include syntax to Gollum's own 
> dynamically?
>

That would be nice, but the problem is that gollum tag filtering is now 
completely disabled for asciidoc (because the double-bracket syntax 
conflicts with asciidoc's own syntax). Of course that can be fixed, PR's 
welcome. :)

**Comment by SkyCrawl** [comment]
Ah, didn't know that... thank you :).

I think we had best to save this for the huge change list that my forks will probably bring (eventually)...

**Comment by ellipticview** [comment]
This issue is different from #878. Issue #878 is about resolving an AsciiDoc include directive, i.e. rendering the content of the included document.
That is a feature that may work for including small snippets. But imagine you're authoring a book, then the top level document would render to the total contents of the book. This is not desirable.

I prefer the includes to be rendered as links. As they currently are. This issue is about handling these links. Currently the link includes the filename extension of the included document. This is consistent with the way other AsciiDoc tools handle includes (e.g. the Chrome AsciidoctorJS plugin)
I think that the cleanest solution is to have Gollum be able to handle the file extensions on the URL. I.e.
```
http://localhost/wiki/home.asciidoctor
```
should be handled the same as
```
http://localhost/wiki/home
```

**Comment by dometto** [comment]
@ellipticview, sorry that I misunderstood your problem. Actually your problem is the same as the one in #1011. See our responses there. For within gollum, you can just use gollum links `[[Page]]` of course, but that won't be usable outside of gollum.

**Comment by ellipticview** [comment]
I would like to re-open this issue. When using Gollum as a user-friendly front end on an Asciidoc repo, this issue is really a deal breaker.
