### ISSUE TITLE
All Pages should sort Folders first, then Pages

### ISSUE THREAD

**Issue by techwiz24** [gollum/gollum#1012]
Like a file manager, the All Pages view should list Folders alphabetically first, then the pages in the current folder. Currently, it looks like this:

![image](https://cloud.githubusercontent.com/assets/794251/7683681/a8b04a34-fd4e-11e4-9cf0-558a9a4082ea.png)

Notice that the pages are sorted alphabetically, but the folders are not. Additionally, the folders are interspersed with the pages.

**Comment by techwiz24** [comment]
Maybe [this logic](https://github.com/gollum/gollum/blob/master/lib/gollum/views/pages.rb#L36-L56) could change to map folders and pages into separate collections, sort them independently, and then output them to the view?

**Comment by techwiz24** [comment]
If it were to be fixed in the View, we could do something like this:

```ruby
def files_folders
    if has_results
        folder_links = []
        folders = {}
        page_files = {}

        @results.each { |page|
            page_path = page.path.sub(/^#{@path}\//, '')

            if page_path.include?('/')
                folder      = page_path.split('/').first
                folder_path = @path ? "#{@path}/#{folder}" : folder
                folder_link = %{<li><a href="#{@base_url}/pages/#{folder_path}/" class="folder">#{folder}</a></li>}

                unless folder_links.include?(folder_link)
                    folder_links << folder_link

                    folders.store(folder, folder_link)
                end
            elsif page_path != ".gitkeep"
                if defined? page.format
                    page_link = %{<li><a href="#{@base_url}/#{page.escaped_url_path}" class="file">#{page.name}</a></li>}
                    page_files.store(page.name, page_link)
                else
                    page_link = %{<li><a href="#{@base_url}/#{page.escaped_url_path}#{page.name}" class="file">#{page.name}</a></li>}
                    page_files.store(page.name, page_link)
                end
            end
        }
        
        result = folders.sort_by{ |k, v|  k.downcase }.map{ |folder| folder[1] }.join("\n")
        result += page_files = page_files.sort_by { |k, v| k.downcase }.map{ |page| page[1] }.join("\n")
        
        result
    else
        ""
    end
end
```

which causes my wiki to output this for `/pages`:
![image](https://cloud.githubusercontent.com/assets/794251/7687215/92000782-fd69-11e4-811c-60d05c8ca646.png)

As with #922, I'm not a ruby developer, so if there's an easier way to approach this, I'm all ears! If not, I'll try to write up a test case and submit a PR

**Comment by bartkamphorst** [comment]
I agree that it makes sense to have folders first. Thanks @techwiz24 for looking into this. RE your code, I think you can do without the `folder_links` array and just work with `folders.values` in that unless statement (which you could then even compress into a single line). For stylistic reasons I would change the outer curly brackets for `@results.each` to `do ... end` and forgo the `#store` method in favor of the more common `hash[key] = value` syntax.

**Comment by techwiz24** [comment]
@bartkamphorst Thank you for the feedback. I will try to get a Test and PR written up sometime this week!

**Comment by dometto** [comment]
:+1: thanks @techwiz24!
