### ISSUE TITLE
Better documentation for integration with Pygments

### ISSUE THREAD

**Issue by techwiz24** [gollum/gollum#1015]
The wiki simply says that "In page files you can get automatic syntax highlighting for a wide range of languages (courtesy of Rouge or Pygments if it is installed)...".

I want to use `Pygments` to provide syntax highlighting because it provides better language coverage than `Rouge`. I've installed both `python-pygments` and `python3-pygments`, but neither seem to be used.

I can verify this by having gollum try to run syntax highlighting for a `powershell` snippet:

    ```powershell
    Write-Host test
    ```

I would expect this to be highlighted correctly by `Pygments` (`Rouge` does not support PowerShell), but instead it is highlighted with an "error" syntax (css class `err`).

I have also tried removing `rouge`, but it seems it's a hard-requirement for github-markup:
```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require': cannot load such file -- github/markup (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from /var/lib/gems/1.9.1/gems/gollum-4.0.0/lib/gollum.rb:8:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /var/lib/gems/1.9.1/gems/gollum-4.0.0/bin/gollum:18:in `<top (required)>'
        from /usr/local/bin/gollum:23:in `load'
        from /usr/local/bin/gollum:23:in `<main>'
```

Is there some additional configuration steps I'm missing?

**Comment by dometto** [comment]
I think you just need https://rubygems.org/gems/pygments.rb. I'll put that link in the readme.

**Comment by bartkamphorst** [comment]
Yes, that should do the trick. Please let us know how it goes.

**Comment by techwiz24** [comment]
Huh, could have sworn I tried installing that gem and my Ubuntu box
couldn't find it. I'll try again tomorrow, thanks!

Nathan

**Comment by techwiz24** [comment]
Ah, the gem is named `pygments.rb`, not `pygments`. That explains it. Seems to be working now, thanks for the pointer!
