### ISSUE TITLE
CriticMarkup

### ISSUE THREAD

**Issue by SkyCrawl** [gollum/gollum#1016]
Just found a potentially interesting "markup" to implement:
https://github.com/CriticMarkup/CriticMarkup-toolkit/#the-basic-syntax

Gollum can already provide some of the functionality and the proposed HTML-diff would only enhance it, even if not completely. On the other hand, having all possible versions of something displayed in the page right away like [CriticMarkup suggests](http://criticmarkup.com/) might be beneficial as well. 
Implementation should be simple - macros  :). Before the source content reaches the renderer, that is...

**EDIT:** I think it could be a worthwhile convenience, especially after Gollum allows to redefine the way it generates HTML snippets (on user-level). That's actually another of my changes that I have implemented in my forks, despite not all the code has been rewritten to respect them yet.

What do you think?

**Comment by bartkamphorst** [comment]
I recently had a use case for CriticMarkup and I quite liked it. So +1 for adding it to gollum at some point down the line.

**Comment by bartkamphorst** [comment]
Implemented in `5.x`. 🙌
