### ISSUE TITLE
Sidebar links rendered as broken images

### ISSUE THREAD

**Issue by kittsville** [gollum/gollum#1021]
When attempting to put internal wiki links on a sidebar it is rendered as HTML <img> tags with the src property as the location of the link.

An extract of the markup:

```
####[[Taxonomies]]  
[[Author]]  
[[Media Type]]  

####[[User Roles]]  
[[Librarian|Librarians]]  
[[Library Admin|Library Admins]]  

####[[Filters]]

####[[Actions]]
```

How GitHub's preview claims it will be displayed:
![editing_sidebar_ _kittsville_wp-librarian_wiki_-_2015-06-11_14 02 28](https://cloud.githubusercontent.com/assets/6013087/8107635/b079a7ae-1042-11e5-8c48-80bc478004e7.png)
How it is actually displayed:
![sidebar_display](https://cloud.githubusercontent.com/assets/6013087/8107638/b615ceae-1042-11e5-899d-28b7e180a995.png)

[Here](/kittsville/WP-Librarian/wiki) is a link to the wiki in question. The offending file is the Technical Documentation's sidebar located at `wiki-dir\Technical-Docs\_sidebar.md`

**Comment by bartkamphorst** [comment]
@kittsville Please note that Github and the open-source project Gollum have diverged. As your issue pertains to a specific wiki on Github, I think you should contact [Github support](https://github.com/contact) instead.

**Comment by kittsville** [comment]
Okay, thanks for your responce. I'll see if GitHub have any idea what's happening.

**Comment by bartkamphorst** [comment]
I'll reopen this until one of us has time to see if it affects open-source Gollum as well. But I just wanted to point you to the right people for support.

**Comment by kittsville** [comment]
After contacting GitHub support they found a workaround for this issue. If the custom link text that is different from the page name is used the bug does not occur. So, if the following were creating the broken links:  
`[[My Page]]`  
This would fix it:  
`[[1. My Page|My Page]]`  

But this would not:  

`[[My Page|My Page]]`  

This is of course just a workaround but it keeps things looking smart while the bug is addressed.

He also said he'd passed the bug on to the GitHub team to look into.

**Comment by bartkamphorst** [comment]
Thanks for reporting back @kittsville , very helpful to have the workaround documented here too!

**Comment by dometto** [comment]
Can't reproduce this on gollum `v3.1.2`.
