### ISSUE TITLE
Support for .. code::<lang>

### ISSUE THREAD

**Issue by renich** [gollum/gollum#1024]
Hello,

It would be awesome if you could support the following syntax in reStructured in terms of syntax highlighting:

```rst
   .. code:: bash
       # some bash code
```

Basically, what that does, is define a code snippet while using restructured. Here's some reference on it: http://docutils.sourceforge.net/docs/ref/rst/directives.html#code

**Comment by dometto** [comment]
Hi @renich! Thanks for the suggestion. Gollum uses the [github-markup gem]() for markup rendering (including rest), so probably you should make your request there!

**Comment by renich** [comment]
Hey guys, it might be on your side: https://github.com/github/markup/issues/510#issuecomment-112456934
