### ISSUE TITLE
How to render task / checkboxes in Markdown format?

### ISSUE THREAD

**Issue by marcinbiegun** [gollum/gollum#1025]
I would like to see `[ ]` rendered as `<input type="checkbox" readonly>`.

Unfortunately `github-markdown` gem doesn't support rendering tasks. GitHub considers tasks as a part of their infrastructure (see https://github.com/github/markup/issues/208#issuecomment-24927799), so they are not rendered by GitHub::Markdown.

Forking the gem (https://rubygems.org/gems/github-markdown) is not trivial for me, as the renderer is written in C. Did anyone try to fork it and add this simple feature?

**Comment by marcinbiegun** [comment]
So far I'm using this monkeypatch:

```ruby
module GitHub
  class Markdown
    def self.render(content)
      html = self.to_html(content, :markdown)
      html.gsub!('[ ]', '<input type="checkbox" readonly>')
      html.gsub!('[x]', '<input type="checkbox" checked="checked" readonly>')
      html
    end
  end
end
```

**Comment by dometto** [comment]
Thanks for sharing the monkeypatch, @marcinbiegun! However, I think this should really be an issue in one of the rendering gems (kramdown supports GFM and is gollum's default now), so closing for now.

**Comment by stsievert** [comment]
@marcinbiegun how did you include that monkeypatch? I copied and pasted that code into `config.rb` and ran with the `--config` option but no results. Can you show you entire `config.rb` file?

**Comment by marcinbiegun** [comment]
@stsievert Probably doesn't work because `github/markdown` gem is loaded after your `config.rb`. Try to put `require 'github/markdown'` before the monkeypatch.

**Comment by mathfour** [comment]
Hey y'all! I'm very late to the party, but hopefully I can get this going.

I'm brand new to github so I'm not sure where this `config.rb` is. Can anyone point me in that direction?

I'm going to google it now and if I find an answer, I'll post it for others like me.

**Comment by marcinbiegun** [comment]
@mathfour I'm not using Gollum anymore, but if I remember correctly I've patched my local gem files. You can find gem's directory by running `gem open gollum`, the `config.rb` file should be somewhere in subdirectories.

**Comment by mathfour** [comment]
Thanks @marcinbiegun. I'm guessing I'll run that in my terminal? And that creates a file that will get updated to my github repository when I push it?

**Comment by mathfour** [comment]
Whoa - I see! I'm in week 7 in my 24 week coding bootcamp and we've not gotten to Ruby yet. Seems the gem is a ruby thing. Maybe I should fake the boxes until I get there.

Then I'll come back to this thread and update the step-by-step process for newbies. Future Bon will be here soon...

**Comment by dometto** [comment]
@mathfour, `config.rb` is wherever you want it to be -- just pass the `--config` option to gollum on the command line (e.g. `--config /path/to/your/config.rb`). Unlike most other files in `gollum`, `config.rb` does not need to be committed in your repository, but it usually lives in the same directory as your repo. Good luck with your ruby adventures!

**Comment by zeigerpuppy** [comment]
I have tried this approach to getting checkboxes too.
However, it doesn't render any checkboxes.

I'm using the latest version of gollum and the following `confg.ru`:

```
#!/usr/bin/env ruby
require 'rubygems'
require 'sinatra'
require 'json'
require 'gollum/app'
require 'openssl'

class Application < Sinatra::Base
  use Rack::SSL

  get '/' do
    'SSL FTW!'
  end
end

require 'github/markdown'
module GitHub
  class Markdown
    def self.render(content)
      html = self.to_html(content, :markdown)
      html.gsub!('[ ]', '<input type="checkbox" readonly>')
      html.gsub!('[x]', '<input type="checkbox" checked="checked" readonly>')
      html
    end
  end
end
```

There are no console errors thrown, does anyone have an idea what I'm missing?

**Comment by zeigerpuppy** [comment]
I wonder if there is any way for this method to be extended to active checkboxes that write a change to the underlying file when checked or unchecked.
Perhaps there's a way to trigger a change using a custom javascript attached to the checkbox object.
