### ISSUE TITLE
Library not loaded ../libicudata.53.1.dylib (LoadError)

### ISSUE THREAD

**Issue by blairrorani** [gollum/gollum#1028]
When I run:
gollum blairrorani$ bundle exec rake test

I get:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I"lib:lib:test:." -I"/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib" "/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" 
/Library/Ruby/Gems/2.0.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes.rb:1:in `require': dlopen(/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/charlock_holmes-0.7.3/charlock_holmes/charlock_holmes.bundle, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.53.1.dylib (LoadError)

In ../lib/ I have libicuuc.54.1 but it seems like I need 53.1?

**Comment by SkyCrawl** [comment]
You have provided very little information but from the top of my head:

Do you use package managers? I think I had a similar issue some time ago... my package manager upgraded the relevant `icu` package through another upgraded package. I had to manually activate the older version for Gollum to run :).

**Comment by blairrorani** [comment]
Yes I use Homebrew.




How is the manual activation done?



—


Blair Rorani (61450105261 / @blairrorani / http://blair.rorani.com)




* Get 10% off my book Everybody Draw Now with the offer code DRAWNOW - http://everybodydrawnow.com

**Comment by SkyCrawl** [comment]
I've never used Homebrew myself but I believe that [this](http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula) may be an answer :).

If it helps, please the close the issue.
