### ISSUE TITLE
Is there support for "../include/page.html#heading4"?

### ISSUE THREAD

**Issue by lpatmo** [gollum/gollum#1029]
In RST, you can load in partial content from another page by including the page file and #heading name. 

For example, say I have a bunch of content written in:
file1.html
#heading1
#heading2

file2.html
#heading1
#heading2

And I want to create a new `file3.html` that automatically loads in content from file1.html -> #heading2 and the content from file2.html -> #heading1. This way, if I make edits to file1.html and file2.html, file3.html will automatically be updated.

Does Gollum support this feature too?

**Comment by SkyCrawl** [comment]
What you're asking is practically a page "view" feature. Gollum doesn't support that at the moment :). While Gollum supports page includes, it only includes whole pages, not particular headings.

The only way for you to do something like that now is:
* Either to include `file2.html` in `file3.html`, where `file2.html` contains both headings.
* Or to define both headings in separate files (with no additional content) and include them both in `file3.html`.

@bartkamphorst @dometto 
Would this feature be worthwhile to implement from your point of view (probably after we implement the "edit section" feature)?

**Comment by dometto** [comment]
From my point of view, the workaround @SkyCrawl  mentioned is sufficient. If someone wants to implement this feature I'm not against it, but we won't prioritize it ourselves.
