### ISSUE TITLE
Live Preview Editor should override cache settings for IE compatibility

### ISSUE THREAD

**Issue by techwiz24** [gollum/gollum#1030]
According to this [blog post](http://www.dashbay.com/2011/05/internet-explorer-caches-ajax/) and [this stackoverflow post](https://stackoverflow.com/questions/4303829/how-to-prevent-a-jquery-ajax-request-from-caching-in-internet-explorer), IE always caches AJAX requests:

> In IE9′s new F12 Developer Console (finally!), cached requests show up as 304 Not Modified with a very suspicious < 1 ms response time.  The 304 is a red herring:  the server is **never** contacted.  It simply means IE in its infinite wisdom has decided the response wouldn’t have been modified IF it had asked the server, and serves it from browser cache.  Debugging on the server side shows that IE is really and truly *not* hitting the server.

This causes IE to load the wrong page content for the Live Preview Editor.

This can be fixed by altering [this ajax call](https://github.com/gollum/gollum/blob/3642370f116e66daecd3f68de351948d5d0bb4a2/lib/gollum/public/gollum/livepreview/js/livepreview.js#L394-L400) to disable the cache:

```js
jQuery.ajax( {
      type: 'GET',
      url: baseUrl + '/data/' + path + key_no_leading_slash( 'page' ),
      cache: false,
      success: function( data ) {
         editorSession.setValue( data );
      }
    });
```

I am unsure if this problem appears elsewhere in the source. The Live Preview Editor is the only place I have noticed it so far.

I've kept the original text of the issue below:
 
---

It seems that the Live Preview Editor is giving the wrong http status code for an XMLHttpRequest at `/data/<Page-Name>` for Internet Explorer, which causes IE to load incorrect page data from the cache:

URL | Protocol | Method | Result | Type | Received | Taken | Initiator
----- | ---- | ---- | ---- | ---- | ---- | ---- | ----
/data/Cache-Testing | HTTP | GET | 304 | text/html | 174 B | < 1 ms | XMLHttpRequest

and a `200` in chrome:

Name | Method | Status | Type | Initiator | Size | Time
-------- | -------- | -------- | ------- | ---------- | ------ | -------
Cache-Testing | GET | 200 | xhr | jquery-1.7.2.min.js:4 | 429B | 28ms

Our wiki instance is behind an nginx proxy (for ssl termination suppport), but this problem also occurs when accessing gollum directly on port `4567`. Clearing the cache in IE corrects the problem until the live preview editor is used to edit the page.

In the IE F12 Developer Tools under the network tab, selecting "Always refresh from server" appears to disable the cache, however it looks like IE thinks that gollum responds with a `200` for the previously mentioned XHR, so I'm not sure if this is a client side issue or if it's with gollum or somewhere further up the stack.

This problem does **not** occur with the standard editor.

### Steps to reproduce
1. Start `gollum` with the Live Preview Editor enabled
2. Open a page in both Chrome and IE
3. In both browsers, edit the page
4. In IE, make a change to the page and hit save
5. In chrome, simply press the back button to return to the page. After the change in IE has been made, refresh the page
6. Edit the page again in both browsers

Notice that IE is displaying the old content for the page, while chrome is displaying the newer content.

**EDIT**: To clarify: This is with IE11.

**Comment by SkyCrawl** [comment]
Hey @techwiz24 

Can you please be more specific on `however it looks like IE thinks that gollum responds with a 200 for the previously mentioned XHR`? I'm afraid I didn't quite understand what's wrong then :).

Also, posting the appropriate HTTP request/response info might be helpful, if that's possible :).

And finally, am I assuming correctly that we're talking about IE11 here?

**Comment by techwiz24** [comment]
@SkyCrawl Sure:

I noticed that if I disabled the cache in IE, the status code for the XHR is always a `200 OK`, regardless if the page has been updated or not (which I think is how it is supposed to work?)

Here's the headers I pulled out of IE and chrome:

### Request
**Headers**:

Key | IE | Chrome
---- | ---- | ----
Request | GET /data/CacheTesting HTTP/1.1 | GET /data/Cache-Testing HTTP/1.1
X-Requested-With | XMLHttpRequest | XMLHttpRequest
Accept | */* | */*
Referer | http://wikitest.mydomain.net:4567/livepreview/?page=Cache-Testing&path=%2F | http://wikitest.mydomain.net:4567/livepreview/?page=Cache-Testing&path=%2F
Accept-Language | en-US | en-US,en;q=0.8
Accept-Encoding | gzip, deflate | gzip, deflate, sdch
User-Agent | Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0;rv:11.0) like Geko | Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36
Host | wikitest.mydomain.net:4567 | wikitest.mydomain.net:4567

**Body**: Empty

### Response
**Headers**:

Key | IE | Chrome
---- | ---- | ---
Response | HTTP/1.1 304 Not Modified | HTTP/1.1 200 OK
Content-Type | text/html;charset=utf-8 | text/html;charset=utf-8
Content-Length | 40 | 38
X-Xss-Protection | 1; mode=block | 1; mode=block
X-Content-Type-Options | nosniff | nosniff
X-Frame-Options | SAMEORIGIN | SAMEORIGIN
Server | | WEBrick/1.3.1 (Ruby/1.9.3/2013-11-22)

**Body (IE)**:
```markdown
# Cache Testing

## Title
qhwerasdfbarbe
```

**Body (Chrome)**:
```markdown
# Cache Testing

## Title
cache update
```

**Comment by SkyCrawl** [comment]
Hmpf... kinda mysterious idd :+1: .

I'd be really interested to see the response info, before it reaches IE. Would that be easy for you, maybe (not completely sure) using Wireshark?

**Comment by techwiz24** [comment]
@SkyCrawl No, Those headers are from a direct connection on `4567`, I don't have another hop in-between, so there's nothing else to capture. I've already checked wireshark and didn't see anything out of the ordinary

**Comment by SkyCrawl** [comment]
> I noticed that if I disabled the cache in IE, the status code for the XHR is always a 200 OK, regardless if the page has been updated or not (which I think is how it is supposed to work?)

Idd. As far as I know, `/data/*` should only return 200 or 404.

---

To clarify - the above printed responses were received when the cache was enabled and that's the case you'd like for livepreview/IE to handle correctly (e.g. disabling the cache is not an option)? If that's the case, I think we can not constructively help you here because obviously, IE is going to use its cache. We can only:
* experiment with how to fool IE's cache then (headers),
* try to report this as a bug (which it probably is anyway).

Speaking of bugs... is `GET /data/CacheTesting HTTP/1.1` a typo? As far as I know, a hyphen is missing :).

**Comment by techwiz24** [comment]
@SkyCrawl 

> To clarify - the above printed responses were received when the cache was enabled and that's the case you'd like for livepreview/IE to handle correctly (e.g. disabling the cache is not an option)?

Correct. When the cache is enabled, IE either doesn't send enough information or sends incorrect information to the server (in which case it returns a `304` thinking the page that IE has is the latest) or it straight up enforces it's own cache policy for that one page. 

This doesn't happen for other pages made over standard web requests, which makes me think it's a bug with whatever method you (or the live preview library) are using to make the XHR (looks like `jquery`?). I'll ask my collegues who develop an IIS app for use with IE to see if they've ever seen this before tomorrow.

**Comment by SkyCrawl** [comment]
> Correct. When the cache is enabled, IE either doesn't send enough information or sends incorrect information to the server (in which case it returns a 304 thinking the page that IE has is the latest) or it straight up enforces it's own cache policy for that one page.

I think it's the last mentioned option since:

| case | response time |
|-----|-----|
| 304; IE | < 1 ms |
| 200; Chrome | 28 ms |

This is most probably a problem with IE's cache.

> This doesn't happen for other pages made over standard web requests, which makes me think it's a bug with whatever method you (or the live preview library) are using to make the XHR (looks like jquery?).

I don't think it directly means that the request is somehow wrong :). It's definitely possible but personally, I think a weird perk of IE is involved here because Chrome obviously  doesn't suffer from the same problem (same request, hopefully... also the requests you printed are identical except for browser specific stuff that shouldn't affect the response).

**Comment by techwiz24** [comment]
I think I am able to trick the IE cache. I've added 

```nginx
expires -1;
sendfile off;
add_header Cache-Control no-cache;
```

to my `nginx` config and am no longer experiencing the problem. I still have no idea why this is only happening in IE and only for the live preview editor. I've attached my whole `nginx` config below for those interested:


```nginx
server {
        listen 80;
        return 301 https://$host$request_uri;
}

server {
        listen 443;
        server_name wikitest.mydomain.net;

        access_log /var/log/gollum/access.log;
        error_log /var/log/gollum/nginx_error.log;

        ssl_certificate /etc/nginx/wikitest.mydomain.net.crt;
        ssl_certificate_key /etc/nginx/wikitest.mydomain.net.key;

        ssl on;
        ssl_session_cache builtin:1000 shared:SSL:10m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;


        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-NginX-Proxy true;


                proxy_pass http://localhost:4567;
                proxy_read_timeout 90;
				
                expires -1;
                sendfile off;
                add_header Cache-Control no-cache;
                
				add_header X-UA-Compatible IE=10;
                add_header Access-Control-Allow-Origin *;

                proxy_redirect http://localhost:4567 https://$server_name/;
        }
}
```

**Comment by techwiz24** [comment]
This may be able to be solved in gollum itself. See https://stackoverflow.com/questions/4303829/how-to-prevent-a-jquery-ajax-request-from-caching-in-internet-explorer

**Comment by SkyCrawl** [comment]
> This may be able to be solved in gollum itself.

Yup. By applying `Cache-Control: no-cache` header to all relevant routes (request URIs) in `app.rb` that are missing it. An easy PR to make :).

**Comment by techwiz24** [comment]
@dometto  @bartkamphorst I think I can write up a PR for this. Would you prefer the problem be fixed in the AJAX call for the Live Preview Editor, or in the route response on gollum's side?

**Comment by bartkamphorst** [comment]
As it's only affecting the Live Preview Editor I would opt for fixing it in the AJAX call. Thanks :+1:

**Comment by techwiz24** [comment]
After a quick and scientific (grep) look through the source, I think that's the only location where IE would experience this problem. I'll have a PR written up by tonight. Thanks for the feedback everyone!
