### ISSUE TITLE
Wrapping errors with long Code Blocks in Markdown

### ISSUE THREAD

**Issue by nlowe** [gollum/gollum#1033]
[This](https://gist.githubusercontent.com/nlowe/919c0d6853e6a7abcb9d/raw/db3ac4cbff6c3e9c438736186ffae0b749335423/Style-Test.md) markdown document generates code blocks with incorrect wrapping:

![image](https://cloud.githubusercontent.com/assets/794251/8557484/a7bb1772-24cb-11e5-8ed4-e0fc9b7ec0d4.png)

Notice that for the inline code blocks the text does not wrap ([as it does on github](https://gist.github.com/nlowe/919c0d6853e6a7abcb9d#file-style-test-md)) and gets cut off.

Additionally, a regular code block incorrectly wraps instead of scrolling (again, see [this example](https://gist.github.com/nlowe/919c0d6853e6a7abcb9d#file-style-test-md) for what github does).

The [html](https://gist.github.com/nlowe/919c0d6853e6a7abcb9d#file-gollum-source-html) includes the full content of the code blocks, so I believe this is a style issue.

**Comment by bartkamphorst** [comment]
The inline code blocks are indeed not styled correctly. On 5.x (using Firefox) the regular block does the correct thing though.

![screen shot 2018-11-12 at 14 18 17](https://user-images.githubusercontent.com/571173/48349934-f4637e00-e685-11e8-9e21-24a84d2ad3c0.png)

**Comment by bartkamphorst** [comment]
What it needs is this:
```css
white-space:pre-wrap;
word-wrap:break-word;
```

I'm just not sure where to add it exactly.

**Comment by bartkamphorst** [comment]
For example, if I just add a CSS `code {white-space:pre-wrap; word-wrap:break-word;}` block to `wiki-content` then it works, but the regular block is distorted:

![screen shot 2018-11-12 at 14 34 26 1](https://user-images.githubusercontent.com/571173/48350654-31307480-e688-11e8-8b81-5621b6850908.png)

**Comment by bartkamphorst** [comment]
Any help would be appreciated. 😄

**Comment by bartkamphorst** [comment]
Actually, adding this to `#wiki-content {` in `_layout.scss` fixes the issue without distorting the regular block.
```css
  p, li {
    code {
      white-space:pre-wrap;
      word-wrap:break-word;
    }
  }
```

@nlowe Is this okay for you, or are there other cases that would not be captured by this?

**Comment by bartkamphorst** [comment]
Proposed solution implemented in https://github.com/gollum/gollum/commit/848cef26ee5bdb22f35407e3b34243045b545e09 (`5.x`).
