### ISSUE TITLE
Create page editor is different to update page editor

### ISSUE THREAD

**Issue by coderbyheart** [gollum/gollum#1036]
When I create a new page I see the *default editor*.

![gollum1](https://cloud.githubusercontent.com/assets/188915/8893793/5c7060b4-339f-11e5-8117-6806e869a298.png)

If I save the page and click *Edit* I see the live editor.

![gollum2](https://cloud.githubusercontent.com/assets/188915/8893794/5dc80fac-339f-11e5-9303-98d25aa2d1d7.png)

Is this behaviour expected?

If yes, as a user I'd like to have the option to switch to the preferred version of the editor.

**Comment by dometto** [comment]
This is by design. Some browsers don't play well with the livepreview option, so for create it just defaults to the default editor. Some ways we could deal with this:
* Improve livepreview support by modernizing the livepreview (#826)
* Offer an option to override this behavior

PRs welcome. :)

**Comment by coderbyheart** [comment]
Ok, thanks for clarification. I'll try to look into it.
