### ISSUE TITLE
Not possible to include custom js

### ISSUE THREAD

**Issue by joshua-paddle** [gollum/gollum#1040]
The --js flag does not work. While it does correctly add a script tag to the page linking to /custom.js, this is useless, because gollum interprets that as a wiki page. I can't find any way to tell gollum to output the raw file contents, nor to have it populate the script tag with any url other than /custom.js, which means there is no way to insert javscript. So, the --js flag does not work.

**Comment by dometto** [comment]
Gollum shouldnt try to render .js files as wiki pages. This means there is either a bug in the logic in the Sinatra app (app.rb), or .js is being registered as a valid page extension somewhere in gollum-lib (markups.rb) or possibly in a config.rb file you're using?

**Comment by joshua-paddle** [comment]
I'm not using a config.rb - just the core Gollum 4.0.0 with no modifications. So, there must be a bug somewhere.

**Comment by joshua-paddle** [comment]
I found why this was not working for me - I had not realized that gollum was unable to see files that had not been committed.

**Comment by dometto** [comment]
Ah yes. This needs to be fixed for security reasons anyway (one might not want to give committers access to the JS and CSS loaded). #1031 requires us to implement a way for gollum to load files from the filesystem, so perhaps that will also allow us to improve the --js and --css flags.
