### ISSUE TITLE
[Windows] Cannot create new pages in windows

### ISSUE THREAD

**Issue by nlowe** [gollum/gollum#1045]
``` powershell
~$ jruby --version
jruby 1.7.21 (1.9.3p551) 2015-07-07 a741a82 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_51-b16 +jit [Windows 8.1-amd64]
```

First off, it seems pages want to be created under `/:/` (related to #1041 ?):

![image](https://cloud.githubusercontent.com/assets/794251/9011697/e4927ce4-377c-11e5-8d89-7f4bcd005c6f.png)
![image](https://cloud.githubusercontent.com/assets/794251/9011837/0da2014e-377e-11e5-97a3-87df870da744.png)

Next, it seems that the page is not saved in the working tree:
![image](https://cloud.githubusercontent.com/assets/794251/9011814/d22627b2-377d-11e5-8ebf-b585ad86349c.png)

**Comment by bartkamphorst** [comment]
I think the latter issue of the page not being saved in the working tree has been resolved in the current `5.x` branch. @nlowe I realize it's been a while, but could you possibly check if that part of the problem has indeed been resolved on Windows?

**Comment by nlowe** [comment]
I don't currently have a windows install on hand but I can try to check sometime next week while I'm at work.
