### ISSUE TITLE
content-length warnings

### ISSUE THREAD

**Issue by Naatan** [gollum/gollum#1053]
The server log is filled with these:

```
[2015-08-12 10:47:44] WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true
```

It doesn't seem to affect anything, but it makes the log hard to scan and it seems like it ought to be easy to fix for someone who knows his way around.

**Comment by bartkamphorst** [comment]
@Naatan This is actually not an issue with gollum but rather with the webrick webserver. I've seen the issue a number of times in other projects, and usually it goes away by explicitly adding webrick as a project dependency. So you could try adding the following to `Gemfile`:
```ruby
gem 'webrick', '~> 1.3.1'
```
Please let me know if that fixes the issue. If it does, we can look into adding webrick as a development dependency to gollum.

**Comment by Naatan** [comment]
Thanks Bart, I've tried adding that line to my Gemfile and running `bundle install`, both on gollum itself as well as my repo. No luck unfortunately.

**Comment by SkyCrawl** [comment]
Judging from [this](http://stackoverflow.com/questions/7082364/what-does-warn-could-not-determine-content-length-of-response-body-mean-and-h), most people seem to recommend switching to another Rack-compatible web server.

However, you could aso try [this answer] which is rather Ruby-based, in the effort to fix WEBrick itself. Note however that this fix is not portable to other Ruby implementations.

Alternatively, feel free to play around with the answers in the thread and let us know :).

**Comment by bartkamphorst** [comment]
> No luck unfortunately.

That's disappointing! Just to be sure, are you running gollum through `bundle exec`?

**Comment by Naatan** [comment]
> are you running gollum through bundle exec?

Ack, I did not do this. Running it through `bundle exec` worked! Thanks! :)

**Comment by bartkamphorst** [comment]
Excellent! I'm glad you got it resolved.

**Comment by Naatan** [comment]
Note that does not resolve this issue; which is that this seems to happen with a default gollum install. Not a big issue but an issue never the less.

**Comment by bartkamphorst** [comment]
You're right. I just added webrick as a development dependency to `gollum.gemspec`. I suppose the issue could still occur depending on how gollum is run, but I think this is the best we can do without monkeypatching webrick.
