### ISSUE TITLE
styles missing due to cache problem

### ISSUE THREAD

**Issue by wzpan** [gollum/gollum#1056]
I found style files often become missing after a period of time. 

![image](https://cloud.githubusercontent.com/assets/1631405/9297620/1f74ab24-44d5-11e5-8d1a-0ab47e9103ae.png)

After I clean the browser's cache, everything works fine again. But it's really not a good enough solution to completely solve the problem.

Does anyone has ever encounter such problem?

**Comment by SkyCrawl** [comment]
Personally, I haven't. And it's kind of strange that somehow, suddenly, Chrome would ignore its own cache and not integrate the styles. To me, it seems like a bug of Chrome but I'm ready to be convinced otherwise.

When this happens, is anything out of normal with the generated HTML or related HTTP requests? (both can be inspected in Chrome's console)

**Comment by wzpan** [comment]
The Network tab in Chrome shows info like this:

![image](https://cloud.githubusercontent.com/assets/1631405/9326293/4af00928-45cb-11e5-9889-a1136489f754.png)

I have the same problem with other browsers like Safari and Firefox. So I think it must be the problem of Gollum itself. Something may block Gollum from rendering its built-in static files.

**Comment by SkyCrawl** [comment]
In that case, you're probably right. Still, I have never encountered the issue myself and I use both Chrome and Firefox :/.

What OS and Ruby are you using? Which version of Gollum?

---

What really puzzles me is the `failed` message in HTTP response code column and missing `Content-Type` in the collumn next to it.

* From the specific times, we can probably deduce that the requests and successfully sent and responses are received.
* If there was a server error, 500 response code should be received (unless it's a really high level error of WEBrick). But instead, the response "fails".

Looks like Chrome can't read the responses for some reason. I've read somewhere that Gollum tends to have problems with `Content-Length` (it must match exactly). But then, why is it acting as it should when the cache is cleared?

**Comment by wzpan** [comment]
> What OS and Ruby are you using? Which version of Gollum?

``` sh
[root@SZB-L0005552 ~]# cat /proc/version
Linux version 2.6.32-504.el6.x86_64 (mockbuild@139.185.51.103) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-9) (GCC) ) #1 SMP Tue Oct 14 01:47:47 PDT 2014
[root@SZB-L0005552 ~]# uname -r
2.6.32-504.el6.x86_64
[root@SZB-L0005552 ~]# uname -a
Linux SZB-L0005552 2.6.32-504.el6.x86_64 #1 SMP Tue Oct 14 01:47:47 PDT 2014 x86_64 x86_64 x86_64 GNU/Linux
[root@SZB-L0005552 ~]# lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: OracleServer
Description:    Oracle Linux Server release 6.6
Release:        6.6
Codename:       n/a
[root@SZB-L0005552 ~]# ruby -v
ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-linux]
[root@SZB-L0005552 ~]# gollum -v
Gollum 4.0.0
```

**Comment by SkyCrawl** [comment]
Thanks :).

> I found style files often become missing after a period of time.

What period of time are we approximately talking about here? Should I be able to reproduce the issue if I just refresh the Home page repeatedly?

Also, would you be willing to create a [config.ru file](https://github.com/gollum/gollum/wiki/Gollum-via-Rack) and try to launch Gollum with another Rack-compatible web server, e.g. [Thin](http://recipes.sinatrarb.com/p/deployment/lighttpd_proxied_to_thin#label-Start+thin+and+your+application.)?

**Comment by techwiz24** [comment]
Are you running behind any sort of reverse proxy such as nginx or apache?

**Comment by wzpan** [comment]
@SkyCrawl ,

> What period of time are we approximately talking about here? Should I be able to reproduce the issue if I just refresh the Home page repeatedly?

It happens occasionally, I don't have a good way to reproduce it either.

> Also, would you be willing to create a config.ru file and try to launch Gollum with another Rack-compatible web server, e.g. Thin?

Sounds like a good idea. I will have a try later.

@techwiz24 ,

> Are you running behind any sort of reverse proxy such as nginx or apache?

I did installed apache on the machine. But I didn't deploy gollum via it. Does that still matters on my case?

**Comment by dometto** [comment]
I had the same hunch as @techwiz24, but if you're not using apache/nginx to serve gollum, that's not the issue. It's a very strange issue and I would be very surprised if this was due to something in gollum's codebase (unless there's a specific pattern in when this occurs, e.g. on specific pages or some such?). My guess would be it's either a bug in WEBrick or sinatra. You could check to see if you have the latest version of those gems.

**Comment by wzpan** [comment]
I found I can temporally restore the page stylesheets by re-enter the address bar to force the browser to reload the page, rather than refreshing the page.

**Comment by dometto** [comment]
I can't reproduce this for the life of me. I think its most probable that this has something to do with your browser/server. As @SkyCrawl you could try a different rack webserver, and of course a different browser or a different version of Chrome. If there's any evidence that this is a bug in gollum specifically, I'll reopen.
