### ISSUE TITLE
Markdown Extensions

### ISSUE THREAD

**Issue by Naatan** [gollum/gollum#1059]
Is there any way to extend the markdown functionality used in gollum?

**Comment by dometto** [comment]
On 20-08-15 17:17, Nathan Rijksen wrote:
>
> Is there any way to extend the markdown functionality used in gollum?
>

See the [readme](https://github.com/gollum/gollum#markups).

 > By default, Gollum ships with the |kramdown| gem to render Markdown. 
However, you can use any Markdown renderer supported by github-markup 
<https://github.com/github/markup/blob/master/lib/github/markup/markdown.rb>. 
The thing to remember is that the first installed renderer from the list 
will be used. So, for example, |redcarpet| will NOT be used if 
|github/markdown| is installed.

**Comment by dometto** [comment]
Uh, sorry for the lack of formatting in my post, looks like markdown is 
not supported when responding via e-mail. I trust you get the idea 
though. :)

**Comment by Naatan** [comment]
Ok, are you saying I need to fork one of the supported gems and modify them? I was hoping there'd be a way of passing config to the used gem. Looking at the markup source this doesn't seem to be the case.

**Comment by dometto** [comment]
On 20-08-15 18:14, Nathan Rijksen wrote:
>
> Ok, are you saying I need to fork one of the supported gems and modify 
> them? I was hoping there'd be a way of passing config to the used gem. 
> Looking at the markup source this doesn't seem to be the case.
>
This being ruby, you can of course tweak the way in which github-markup 
calls whatever markdown gem it is you want to use. For example, 
gollum-lib does this to set kramdown to ordinary markdown mode:

GitHub::Markup::Markdown::MARKDOWN_GEMS['kramdown'] = proc { |content|
Kramdown::Document.new(content, :auto_ids => false, :input => 
"markdown").to_html
}

You can do stuff like this yourself by using a config file, with 
gollum's --config option. For example, if you'd change the above snippet 
to say  :input => "gfm", you could use kramdown in Github Flavored 
Markdown mode.

However, the extent to which you can do configuration of course depends 
on the markdown gem you're using itself.

**Comment by Naatan** [comment]
Thanks @dometto, I have very superficial knowledge of Ruby, so this type of stuff is not immediately obvious to me :) Appreciate the help.

**Comment by dometto** [comment]
On 20-08-15 19:24, Nathan Rijksen wrote:
>
> Thanks @dometto <https://github.com/dometto>, I have very superficial 
> knowledge of Ruby, so this type of stuff is not immediately obvious to 
> me :) Appreciate the help.
>

No problem. This kind of stuff is difficult to document, as it depends 
so much on the APIs of the different markup gems.
