### ISSUE TITLE
Feature request: Custom style adapters

### ISSUE THREAD

**Issue by matthiasbeyer** [gollum/gollum#1063]
Hi,

I'd love it to be able to adapt zurb's foundation style with gollum wiki. Is there a way to do this easily or do I have to fiddle around myself?

regards.

**Comment by matthiasbeyer** [comment]
... And if I have to fiddle around, how to do this? The best way would be to clone this repo and change the mustache files to match the class names of foundation and maintain my fork for new versions of both foundation and gollum, wouldn't it?

I'm kinda not sure about how to do this right, though...

**Comment by bartkamphorst** [comment]
You could play around with the `--template-dir` and `--css` flags of the gollum startup script. The first allows you to point gollum to your custom mustache templates; the second looks for a file called `custom.css` in the root directory (must be committed to the repo). I have no experience styling gollum, but this should hopefully get you started.
