### ISSUE TITLE
Question: Gollum wiki to MkDocs via "static" markdown files?

### ISSUE THREAD

**Issue by twardoch** [gollum/gollum#1064]
I have the following plan: 
* I'd like to use the Github built-in wiki (which is based on Gollum, I believe) to collaboratively edit the user documentation in a private Github repo. 
* I want to use Markdown, but I'd like to use some Gollum-style wiki `[[tags]]`, possibly including some custom tags like `[[_TOC_]]` or `[[include:filename]]` — even if they’re not really supported by the Github wiki engine itself. 
* Then, I'd like to use [MkDocs](http://www.mkdocs.org/) (or ReadTheDocs) to create the "real" user-facing documentation from that wiki. 

MkDocs supports "pure" Markdown but of course does not support the Gollum `[[tags]]`. My [example page](https://github.com/twardoch/dos-font-utils/wiki/index) page on the Github wiki has three links. First two are made using the Markdown syntax `[title](url)`, the third using the Gollum syntax `[[page name]]`. When I build my docs into ReadTheDocs directly, I get [this result](http://dos-font-utils-wiki.readthedocs.org/en/latest/), as expected. The first two links convert well, the third does not. 

So I wonder — is there any package that would allow to take a Gollum wiki and convert it to a set of static Markdown files ("inlining" all the Gollum tags like `[[include:filename]]` or `[[TOC]]` and converting the Gollum links into Markdown links)? 

Then, MkDocs or ReadTheDocs could parse the static site and build the final documentation.

**Comment by SkyCrawl** [comment]
Hello @twardoch 

> So I wonder — is there any package that would allow to take a Gollum wiki and convert it to a set of static Markdown files ("inlining" all the Gollum tags like [[include:filename]] or [[TOC]] and converting the Gollum links into Markdown links)?

As far as I know, there's no such ready-to-use package :(. If I understand your use-case correctly though, a package like that is practically an "export" feature. Ideally, it would take (possibly) all Gollum pages, parse them, convert them and store them into a separate, special repository. This repository may or may not be unique for each run. And then, we're getting at the biggest problem - the exact shape of the result exported markup (Markdown, ..., HTML, CSS, possibly also JavaScript). If any such package existed, it would only be a skeleton (interface), suitable only to be first edited/completed by the user and then used.

Back to your question, however. A package like that can probably be (more or less) easily created from [gollum-lib's](https://github.com/gollum/gollum-lib) API, which is accessible when running Gollum like `gollum --irb` or simply via a custom Ruby script. I imagine you'd only need to:

1. Pass the result folder.
2. List or iterate the pages.
3. Take each Markdown page and call `raw_data` on it.
4. Use the [Ruby String's sub](http://ruby-doc.org/core-2.2.0/String.html#method-i-sub) method for each syntax instance you wish to convert.
5. Write the result in the corresponding result file, into the result folder.

All in all, around 100 lines of code may suffice :). If you get around to writing the script, would you consider making a pull request with it (into the `contrib` folder), when you're finished?

**Comment by twardoch** [comment]
I'm not really a Ruby person but more of a Python person. I’ve just found this extension https://pythonhosted.org/Markdown/extensions/wikilinks.html which will require just some tiny tweaks. Since MkDocs uses the markdown module, which potentially supports this extension, this should be a very small job.

**Comment by dometto** [comment]
@twardoch, good to hear you're on your way to a solution. If you end up with a reasonable solution, would you mind typing something up about it in the wiki?
