### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by tibo** [gollum/gollum#107]
Hi

How can I manage authentication on Gollum? is there a way to manage user's right?
How can I handle http authentication?

Thx
Thibaut

**Comment by Geremia** [comment]
@tibo See [omnigollum](https://github.com/arr2036/omnigollum), "Omniauth authentication for gollum."

**Comment by rgroux** [comment]
@tibo 
you can check the wiki, i wrote it and it work well for me.

https://github.com/gollum/gollum/wiki/Gollum-via-Rack-and-CAS-SSO

you can addapt to you needs.

Actually, i use it at work with jassig cas, and at home with rubycas, and totp
