### ISSUE TITLE
Serve from HEAD

### ISSUE THREAD

**Issue by PaulMakepeace** [gollum/gollum#1071]
How would you feel about having gollum serve from wherever HEAD points versus always serving from `master` or `--ref my-branch`? Our workflow is multiple branches to edit and review so having to specify this rather than rely on `git branch` is more work and error-prone.

**Comment by dometto** [comment]
Can't say that I've tried this, but wouldn't `--ref HEAD` work?

**Comment by PaulMakepeace** [comment]
Awesome, that actually worked. Thanks!

**Comment by fflorent** [comment]
Well, after editing a page through gollum, the `--ref HEAD` option creates a HEAD branch and commits on it. That makes git unhappy (for understandable reasons :)): 

```bash
$ git status
warning: refname 'HEAD' is ambiguous.
warning: refname 'HEAD' is ambiguous.
[...]
```
