### ISSUE TITLE
Image rendered only in preview

### ISSUE THREAD

**Issue by MAccadia** [gollum/gollum#1073]
Hi,

I'm running Gollum 4.0.1 locally.
I'm using a directory structure like this : 
```
Project1/
      page1
      page2
      image1.svg
Project2/
      page1
      page2
```

It may not be a good idea to run Gollum for several project but for now, I'm just testing it.

When I add an image in a page, I'm using `![image1](Project1/image1.svg)`. Preview works just fine but page view shows only the alternative text.

I have tried to put the image in gollum root -> not any better
I have tried the alternative method `[[image1.svg]]` -> not any better but the link to the image is shown in red (even though it works)

**Comment by SkyCrawl** [comment]
Hello @MAccadia ,

I tested Gollum v4.0.1 (clean install, default adapter) with the following test page:
```
## IMAGE - root

![image - root](img.svg)

## IMAGE - subfolder

![image - subfolder](folder/img.svg)

## IMAGE - global

[[img.svg]]
```

All images are displayed and work :). However, when trying to preview the page (from livepreview editor), the following tags don't display the image (alternative text is shown):
```
![image - root](img.svg)
![image - subfolder](folder/img.svg)
```

which is either a bug or feature (not sure now).

So, which adapter are you using? Which markdown renderer?

**Comment by MAccadia** [comment]
I reproduced the experiment you did and I have the same result : all images are displayed correctly.

I have found the problem : as my picture and my page are in the same folder, I need to use `![image1](image1.svg)` instead of the path relative to Gollum root `![image1](Project1/image1.svg)`.

Don't know whether it's a good behavior or not.

Anyway, thanks !

**Comment by bartkamphorst** [comment]
Thanks @MAccadia for following up.

> it's weird that page view and preview handle it the opposite way.

@SkyCrawl Can you confirm this behavior? If it is in fact handled the opposite way then I would consider that a bug.

**Comment by SkyCrawl** [comment]
@bartkamphorst 

I haven't looked into the code so I won't daresay the images are handled in the "opposite way", but I can confirm there are many issues - the behaviour is pretty weird. Personally, I blame code fragmentation and insufficient attention to details, although I may be proven wrong. I think I have noticed this problem in the past, around the time I was trying to propose the "next-gen file referencing" for Gollum. One more thing I noticed in the past too is that livepreview should be much more interactive:
* Do I want to display all images?
* Do I want to render some individual tags like `[[_TOC_]]`?
* Do I want to render macros?
* ...

My repository (root view):
```
folder/
     TestFolder.md
     img.svg
Test.md
img.svg
```

---

Content of `Test.md`:
```
## IMAGE - root

![image - root](img.svg)

## IMAGE - subfolder

![image - subfolder](folder/img.svg)

## IMAGE - global

[[img.svg]]
```

Behaviour of `Test.md`:
* Page view correctly displays all images.
* Livepreview doesn't display ANY of the images.
* Livepreview's "preview" feature only displays the last (global) image tag.

---

Content of `TestFolder.md`:
```
## IMAGE - absolute

![image - subfolder](/folder/img.svg)

## IMAGE - relative

![image - root](img.svg)
```

Behaviour of `TestFolder.md`:
* Page view correctly displays all images.
* Livepreview only displays the relative (second) image.
* Livepreview's "preview" feature only displays the absolute (first) image.

**Comment by SkyCrawl** [comment]
@MAccadia 

> instead of the path relative to Gollum root `![image1](Project1/image1.svg)`. In this case, the picture doesn't display in preview but is rendered correctly in page view.

This particular URL is, however, always relative to the page being displayed, not repository root. Therefore, the image won't be displayed if the page is not in repository root and yet, the image is referenced "from repository root".

If you want URLs relative to repository root (if the page is elsewhere), you have to prefix them with a slash, e.g. `![image1](/Project1/image1.svg)`. See the `TestFolder.md` above :).

**Comment by MAccadia** [comment]
Thanks @SkyCrawl,  using absolute paths `![image1](/Project1/image1.svg)` works both with livepreview's "preview" and page view and this corresponds to expected behavior.

I will adopt this syntax since it's not ambiguous.

**Comment by SkyCrawl** [comment]
@MAccadia 

If that solves your issue, please close it :). I'm going to create a new one regarding the differences in rendering now.
