### ISSUE TITLE
Support sandstorm?

### ISSUE THREAD

**Issue by devon** [gollum/gollum#1075]
Sandstorm is good for one click install. check it out https://sandstorm.io/. 

There are a lot of open source project support this. gitlab, wekan, hacker slide, here is a list: https://apps.sandstorm.io/?host=https://oasis.sandstorm.io

**Comment by SkyCrawl** [comment]
@devon 

Thank you for the suggestion. Sandstorm seems like a nice idea for some applications but I'm not completely sure that Gollum is one of them. Regardless whether it is or is not, I quote:

> Sandstorm is in early beta. Lots of features are not done yet, and more review needs to be done before relying on it for mission-critical tasks. That said, we use it ourselves to get work done every day, and we hope you'll find it useful as well.

This alone is probably enough reason for us not to undertake Sandstorm support yet. When Sandstorm turns into a stable and fully documented release, we could have a look at the SPK file and see just how well Gollum and Sandstorm can work together.

---

For the sake of completeness, you may be interested in [Docker](https://www.docker.com/) which is, to my knowledge, similar to Sandstorm. And better even, there's already supposed to be a [Gollum deployment for Docker](https://github.com/gollum/gollum/wiki/Gollum-via-Docker).

**Comment by devon** [comment]
@SkyCrawl

Thank you for your reply.

I already install sandstorm and I'm trying to test is it stable or not. sandstorm is not similar with Docker. I use both solutions for my work.

**Comment by dometto** [comment]
thanks for letting us know about sandstorm, @devon. I think it looks very promising and I actually think gollum would be a good fit. However, we don't want to maintain any third party support within the gollum project. Things like Docker support are alle in the contrib dir, i.e. contributed by users. If you want to try to make a sandstorm package yourself I'd be glad to help with any gollum related issues you encounter though! The best thing would probably be to start a separate github project for it.
