### ISSUE TITLE
Changing wiki format with page-file-dir creates new directory and a new file

### ISSUE THREAD

**Issue by mpnowacki** [gollum/gollum#1076]
In current version (`4.0.1`) when running with `--page-file-dir=wiki` and editing an existing file,  for example `home.markdown`, changing edit mode to any other, `mediawiki` for example, causes the file `home.mediawiki` to be created in `PROJECT_ROOT/wiki/wiki`. This behaviour seems to be the same every edit mode combination.
Addtional information: debian 7.9, git 1.7.10.4, ruby 1.9.3p194, install with the `gem1.9.3` command, however `gem1.9.3 --version` yields `1.8.23`

**Comment by bartkamphorst** [comment]
Sounds like a bug to me. What happens when you change it to yet another format? `PROJECT_ROOT/wiki/wiki/wiki`?

**Comment by mpnowacki** [comment]
precisely. I didn't go any further than `/wiki/wiki/wiki/wiki/wiki/`, but I guess it's safe to assume it will go on like this until the os starts making trouble. 
Another thing worth mentioning is, that when editing the first page (`host/wiki/home`), with format change, the `save` button redirects (correctly) to `host/wiki/home`, and because there is no such file, this redirects to  `host/create/wiki/home`, which makes everything very confusing.

**Comment by dometto** [comment]
Thanks for reporting this! We're a bit swamped at the moment, so if you yourself or anyone else could try to find out if there's an easy way to fix this, or whether it would require more substantive changes, that would be great. Glad to help of course.

**Comment by mpnowacki** [comment]
It turns out to be problem in `gollum-lib`. I've already submitted a pull request. The description can be found here: https://github.com/gollum/gollum-lib/issues/175

**Comment by dometto** [comment]
Resolved in https://github.com/gollum/gollum-lib/issues/175
