### ISSUE TITLE
Can gollum integrate with flowchart.js ?

### ISSUE THREAD

**Issue by xworks** [gollum/gollum#1080]
flowchart.js(https://github.com/adrai/flowchart.js) needs less configuration and easy to use, can gollum support this kind of flow chart？

**Comment by dometto** [comment]
Have you tried adding it via the `--js` option?

**Comment by SkyCrawl** [comment]
@xworks 

The `--js` option can add custom JavaScript into the page rendering process but this is only for a single file. With `flowchart.js`, you would have to squash all this (taken from the demo) into a single file:
```js
 <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
 <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
 <script src="http://flowchart.js.org/flowchart-latest.js"></script>
 <script>
...
</script>
```

**NOTE** that Gollum already includes `jquery-1.7.2.min.js` into pages, so including `jquery-1.11.0.min.js` might not be necessary. I have no idea about compatibility though and I certainly don't think that including both versions at once will work properly.

If `jQuery` is not going to be a problem, then `flowchart.js` should be supported by Gollum.

**Comment by xworks** [comment]
I have `flowchart.js` loaded into my markdown page, by adding `--js` option and creating a 
`custom.js` file under my git repository's root directory. But what i need is `gollum` to translate
a `flow code` into a `flow chart`, by using `flowchart.js`, how can I do that ? 

> \`\`\`flow
> st=>start: Start
> op=>operation: Your Operation
> cond=>condition: Yes or No?
> e=>end
>
> st->op->cond
> cond(yes)->e
> cond(no)->op
> \`\`\`

**Comment by xworks** [comment]
There are many other chart library written in javascript, such as `flowchart.js` or 
`mermaid`(http://knsv.github.io/mermaid/usage.html#api-usage), I suggest `gollum` to support this kind of
lightweight chart implementation, by making slightly modification.

**Comment by SkyCrawl** [comment]
> But what i need is gollum to translate flow code into a flow chart. How can I do that?

You only need to follow [this guide](https://github.com/adrai/flowchart.js/blob/master/example/index.html) and adapt it for Gollum. There are multiple ways of doing it. 

Below, I will describe how I would do it. I haven't tested it so there's a chance you'll run into minor problems but I think it should work, as long as `flowchart.js` behaves as one would expect it to.

1. Include your flow code into pages like this:  
    ```
    <div id="unique-id-of-this-chart" class="flowchart">here goes your flow code</div>
    ```
2. Adapt the original flowchart JavaScript to automatically search for all elements with the `flowchart` class, take the code from them and replace it with the rendered chart:

    ```
    window.onload = function ()
    {
        $(".flowchart").each(function(container)
        {
            var chart = flowchart.parse(container.val());
            chart.drawSVG(container.id,
            {
                // 'x': 30,
                // 'y': 50,
                'line-width': 3,
                'line-length': 50,
                'text-margin': 10,
                'font-size': 14,
                'font': 'normal',
                'font-family': 'Helvetica',
                'font-weight': 'normal',
                'font-color': 'black',
                'line-color': 'black',
                'element-color': 'black',
                'fill': 'white',
                'yes-text': 'yes',
                'no-text': 'no',
                'arrow-end': 'block',
                'scale': 1,
                'symbols':
                {
                    'start':
                    {
                        'font-color': 'red',
                        'element-color': 'green',
                        'fill': 'yellow'
                    },
                    'end':
                    {
                        'class': 'end-element'
                    }
                },
                'flowstate':
                {
                    'past': { 'fill' : '#CCCCCC', 'font-size' : 12},
                    'current': {'fill' : 'yellow', 'font-color' : 'red', 'font-weight' : 'bold'},
                    'future': { 'fill' : '#FFFF99'},
                    'request': { 'fill' : 'blue'},
                    'invalid': {'fill' : '#444444'},
                    'approved': { 'fill' : '#58C4A3', 'font-size' : 12, 'yes-text' : 'APPROVED', 'no-text' : 'n/a' },
                    'rejected' : { 'fill' : '#C45879', 'font-size' : 12, 'yes-text' : 'n/a', 'no-text' : 'REJECTED' }
                }
            });
        });
    }
    ```

**Comment by SkyCrawl** [comment]
> There are many other chart library written in javascript. I suggest gollum to support this kind of
lightweight chart implementation, by making slightly modification.

That's very easy to say. While adding support for libraries like this could certainly be a little more convenient (like the `<script src=...>` part), I can't see any decent options how to make the process conceptually simpler :). Eventually, some tweaking will still be required in most cases (just like in ours).

**Comment by dometto** [comment]
Note that gollum already supports PlantUML if you want something supported out of the box. Of course there are endless frameworks, but we can't all include them in gollum. The way to go is to make gollum as user-extensible as possible. Any help with that, or with documenting how to do this in the wiki, is appreciated. But we won't be actively pursuing `flowchart.js` integration ourselves.
