### ISSUE TITLE
Need to be able to separate the docs from the server

### ISSUE THREAD

**Issue by PaulMakepeace** [gollum/gollum#1081]
Currently, all docs served from `/` include the server itself, which, if `bundle package` is used means all manner of irrelevant and confusing (and potentially security-compromising) "pages" are available like `vendor/*`, `config.ru`, etc, etc.

Please provide a way to serve `/` from a repository sub-directory.

**Comment by dometto** [comment]
That's what --page-file-dir does, I think? Also, you can run gollum on a repo anywhere on the system, e.g. `gollum /path/to/repo` so the wiki is separated from the server source.

**Comment by PaulMakepeace** [comment]
Hadn't we established in #491 that --page-file-dir doesn't work as advertised? I found that thread and its (non?) resolution confusing hence re-stating here for clarity.

There are circumstances where only one repo is possible or preferable (external restrictions, complexity). I hope you re-open this or get --page-file-dir to work :)

**Comment by dometto** [comment]
#491 is still open, so I suggest we discuss `--page-file-dir` there :)
