### ISSUE TITLE
wiki not supported git submodule

### ISSUE THREAD

**Issue by shiningwang** [gollum/gollum#1082]
i have a git repo. then add a wiki submodule to this git repo.
``` git submodule add https://github.com/shiningwang/wiki.git wiki ```
then enter the wiki folder and run ```gollum```. the web editor do not work for me. Did not display the content for my Home.markdown file, but "Create New Page".

**Comment by bartkamphorst** [comment]
Please elaborate by providing either a bug description or a feature request.

**Comment by bartkamphorst** [comment]
Closing until a better description is provided.

**Comment by shiningwang** [comment]
description updated

**Comment by SkyCrawl** [comment]
Clarification after a little manual hunting:
```
$ gollum --irb
$ access = Gollum::GitAccess.new(wiki.path, nil, false)
$ access.repo.commit('master')
=> nil (as opposed to a regular git repository where a commit is returned)
```

Relevant code:
* [Git Access](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/git_access.rb#L150)

But the actual error is down the rabbit (git) hole. I did not venture there.

**Comment by shiningwang** [comment]
thanks

**Comment by dometto** [comment]
We won't be adding this feature to the grit adapter unless anyone implements it themselves. However, the most recent release of rugged supports submodules, so we could look into that. PRs welcome.

**Comment by dometto** [comment]
Just noticed this is a duplicate of #438.
