### ISSUE TITLE
[Readme] Running gollum from source

### ISSUE THREAD

**Issue by pomber** [gollum/gollum#1083]
The readme says:
>If you wish to run from source, simply:
>
>1. Navigate to your git repository (wiki) via the command line.
>2. Run: bundle exec bin/gollum
>3. Open http://localhost:4567 in your browser.

Is this correct?  
Shouldn't you set the Gemfile location by [specifying BUNDLE_GEMFILE](http://stackoverflow.com/a/6889872/1325646)?

I'm new to ruby so it may be that I'm following the docs too literally.

**Comment by SkyCrawl** [comment]
Hello @pomber ,

you're right, the wording is pretty misleading and it's mostly my fault :). Going to fix it with a PR. Just to be clear, let's go over both ways to run from source...

Running from the project folder (the easy and comfortable way):

1. `git clone https://github.com/gollum/gollum`
2. `cd gollum`
3. `bundle exec bin/gollum`
4. Open `http://localhost:4567` in your browser.

Running from outside the project folder (may be necessary sometimes?):

1. `git clone https://github.com/gollum/gollum`
2. `BUNDLE_GEMFILE=./gollum/Gemfile bundle exec ./gollum/bin/gollum`
3. Open `http://localhost:4567` in your browser.

Like that, gollum assumes the target wiki (git repository) is the project repository itself. If it is not, you'll need to specify it:
* `bundle exec bin/gollum <path-to-wiki>`
* `BUNDLE_GEMFILE=./gollum/Gemfile bundle exec ./gollum/bin/gollum <path-to-wiki>`

If this solves your problem, please close the issue.

**Comment by dometto** [comment]
On 25 okt. 2015, at 11:25, "Jiří Smolík" <notifications@github.com<mailto:notifications@github.com>> wrote:


you're right, the wording is pretty misleading and it's mostly my fault :). Going to fix it with a PR. Just to be clear, let's go over both ways to run from source...

Running from the project folder (the easy and comfortable way):

  1.  git clone https://github.com/gollum/gollum
  2.  cd gollum
  3.  bundle exec bin/gollum
  4.  Open http://localhost:4567 in your browser.

Note that before step 3 you probably need to `bundle install`

**Comment by SkyCrawl** [comment]
Right, somehow I forgot about that even though I used the command several moments ago :(. Thanks.

**Comment by dometto** [comment]
Instructions fixed in #1084. Thanks @pomber for reporting and @SkyCrawl for the readme update.
