### ISSUE TITLE
How to ignore the pictures file when searching?

### ISSUE THREAD

**Issue by Backaway** [gollum/gollum#1085]
Hi, I really like git and markdown, so I chose gollum for personal knowledge management. However, sometimes I need to add picture link in the article, so I put pictures on the images directory under gollum's working directory, when I searched for article, occasionally picture files are in the search results. I wonder if there is a way to ignore these file (such as *.jpg *.png and *.gif)?

**Comment by bartkamphorst** [comment]
@Backaway I would suggest looking at your `.gitattributes` file. Anything declared as binary there should be excluded from search in gollum (by default, gollum defines *.png and *.jpg as binary; you would probably want to add *.gif and *.png). Let me know if this helps!

**Comment by Backaway** [comment]
I place https://github.com/gollum/gollum/blob/master/.gitattributes in my wiki dir and start gollum with the command `gollum --h1-title --port 80`. But the pictures are still in my search results, includeing the jpg and png files

**Comment by bartkamphorst** [comment]
I can confirm the behavior. Which is strange, considering [this](https://github.com/gollum/grit_adapter/pull/2). You are using grit adapter v.1.0.0 I presume?

**Comment by dometto** [comment]
@Backaway, I suggest using the rugged adapter instead. We won't invest much time in improving the grit adapter anymore, although fixes are welcome.

**Comment by bartkamphorst** [comment]
I did find the issue, however. The original grit library used method_missing magic to call the git binary with whatever flags we passed along. The folks over at gitlab have implemented [their own grep implementation](https://github.com/gitlabhq/grit/blob/master/lib/grit/repo.rb#L685-L725) however, which has the flags predefined.

**Comment by dometto** [comment]
That's...annoying. I guess someone could open a PR with gitlab-grit to allow passing optional values to grep. But otherwise I don't think we can fix this.

**Comment by bartkamphorst** [comment]
Well, their own implementation flags which files are deemed binary, so in theory, we could filter those out. The easier way however seems to be to simply bypass their implementation and call the git binary via `#native` directly. See https://github.com/gollum/grit_adapter/pull/13 . All we need is a volunteer to try out this patch. :) @Backaway ?

**Comment by bartkamphorst** [comment]
@Backaway This should be fixed in `master` of the gollum grit adapter and will be included in the next release of the adapter gem.

**Comment by Backaway** [comment]
OK, THX!  I will figure it out.
