### ISSUE TITLE
Unnecessary usages of `Gollum::Page#versions`

### ISSUE THREAD

**Issue by jhominal** [gollum/gollum#1087]
OK, so, while profiling the regular page view action, I have hit the following performance issue (I have a repository that has been migrated, and because of that I already have 30k revisions, but my new pages only have about 3 or 4).

In the code path to render a page, the `Gollum::Page#versions` method is called three times:

 * Once in [`Precious::App#show_page_or_file`](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L499)
```ruby
@page_exists   = !page.versions.empty?
```
 * Once in [`Precious::Views::Page#author`](https://github.com/gollum/gollum/blob/v4.0.1/lib/gollum/views/page.rb#L25-L26), and once in [`Precious::Views::Page#date`](https://github.com/gollum/gollum/blob/v4.0.1/lib/gollum/views/page.rb#L32-L33):
```ruby
page_versions = @page.versions
first         = page_versions ? page_versions.first : false
```

In all three cases, I feel that the call to `Gollum::Page#versions` is mostly unnecessary, as only the last version is pertinent.
However, these calls provoke a rather enormous performance dip in my repository because of these facts:

 1. `#versions` is requested for my page, with the default pagination setting - so Gollum will look for 30 versions of my page;
 2. Because my page only has 2 or 3 versions in the repository, the entire revision range will have to be examined by Gollum in case more versions are actually available;
 3. Because my repository has 30k revisions, that takes about 300 ms for each call (with Grit - it is a lot worse with Rugged);

I can think of 3 distinct solutions for that issue, in decreasing order of personal preference:

 1. Use the `Gollum::Page#version` attribute - however, I am not fully clear on how to use it in the case of a preview page, as it is then filled with the last commit information;
 2. Define a `Gollum::Page#last_version` method, that calls `Gollum::Git::repo#log` with a `:max_count` of 1 - however, it seems awful to have to add a new method for that;
    * Note: that is the solution I have currently implemented on my instance (which led me to raise [that `rugged_adapter` issue](https://github.com/gollum/rugged_adapter/issues/10));
 3. Cache the result of the invocation of `Gollum::Page#versions` - I do not like it because caching is always an issue for invalidation;

Thank you for your help.

**Comment by dometto** [comment]
Thank you for looking into these issues! How about this:

> Define a Gollum::Page#last_version method, that calls Gollum::Git::repo#log with a :max_count of 1

I think it wouldn't be *that* horrible to have this extra method, given the potentially huge performance gains this would deliver. I would certainly :+1: such a PR. Of course the `#last_version` method should cache the result, so:

```ruby
def last_version
  @last_version ||= version({:per_page => 1}).first # Assuming Page#version is never nil
end
```
Currently it seems like this won't work, because the `Pagination::log_pagination_options` will [fallback to the default `:per_page` of 30](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/pagination.rb#L34) when the user passes in a value for `:per_page` lower than 30. So that method would need to respect the value of `:per_page` when it is explicitly set by the user. Something like:

```ruby
options[:max_count] = options.fetch(:per_page, per_page)
```

Then in the templates we could just use `@page.last_version`, and in `app.rb` we could do `@page_exists = !!page.last_version`.

If you would like to try a PR to this effect that would be great -- otherwise I'm afraid we'll have to look into this when I or one of the other main devs has more time.

**Comment by dometto** [comment]
Actually, for `Page#last_version` we want to be able to cache `nil` as a value, so the method should rather do something like:

```ruby
   defined?(@last_version) ? @last_version : @last_version = version({:per_page => 1}).first
```

**Comment by jhominal** [comment]
I intend to make the PR later, I just want to ask some questions about the target API, and implementation plan.

The target API for `Gollum::Page` would have these three methods:
 * `#version`: Returns the `Gollum::Git::Commit` from which the page was loaded, or a pointer to the most recent wiki reference in the case of a preview - (it is never `nil`);
 * `#versions`: Returns an array of `Gollum::Git::Commit` in which the page was modified - this array can be paginated and follow across renames;
 * `#last_version`: Returns the `Gollum::Git::Commit` object that corresponds to the last time that page was modified - it can be `nil`;

And then, I see a few implementation options for `#last_version`, and I would like to know which one you would prefer:

 * Directly call `Git::Gollum::Repo#versions_for_path`, with `:max_count` set to `1` (would be my preference);
 * Call `Gollum::Page#versions` with a `:per_page` set to `1`, and modify `Gollum::Pagination#log_pagination_options` so that it only sets `max_count` to its default value if `per_page` is not set, `nil` or `0`;
 * Call `Gollum::Page#versions` with a `:max_count` argument, and modify `Gollum::Page#versions` so that it only `log_pagination_options` if `:max_count` is not set by its caller;

Also, I would like to put a check to see if the file exists in `#version` before looking for its `last_version` (otherwise, I would fall in the same performance issue when previewing a new file).

**Comment by dometto** [comment]
> The target API for Gollum::Page would have these three methods:

Seems correct to me. :+1: Although I'm not entirely sure we can trust `version` to never be `nil`, as `Page#initialize` doesn't require a `version` param. But it looks like the ways the pages are being set up by gollum will always give them a `version`.

> Directly call Git::Gollum::Repo#versions_for_path, with :max_count set to 1 (would be my preference);

Fine with me. The current behavior of `log_pagination_options` is weird anyway and should be fixed, but that doesn't have to be part of this PR.

> Also, I would like to put a check to see if the file exists in #version before looking for its last_version (otherwise, I would fall in the same performance issue when previewing a new file).

Fine with me -- but is that really cheaper performance wise than `!! last_version`? Either way, I guess this means also adding a `Page#exists?` or `Page#persisted?`.

**Comment by jhominal** [comment]
Given your comments, I will delay the question of checking for file existence before computing `last_version` for another issue, in order to get some data on the question before acting.

**Comment by dometto** [comment]
Sounds fine. :) Thanks again for helping out!
