### ISSUE TITLE
gollum supports multicursor.

### ISSUE THREAD

**Issue by silvio** [gollum/gollum#1089]
I see on https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts#multicursor that ace supports multicursor editing. But _no_ multicursor shortcut is functional on my gollum installation.

My question: Supports gollum multicursor key bindings?

**Comment by bartkamphorst** [comment]
I suspect that this feature in Ace is simply turned off, either by default or on purpose. I have no need for it personally, but if you want to implement a way of optionally enabling it then I wouldn't be opposed.

**Comment by dometto** [comment]
This works in the implementation in #1170.

**Comment by dometto** [comment]
NB that means it will only be released in `v5.x`.
