### ISSUE TITLE
pls add bower package support.

### ISSUE THREAD

**Issue by hetz** [gollum/gollum#1090]
I want use gollum with only webfront part,
but this time,gollum build in ruby.

pls gollum team add to bower.io.

tks.

**Comment by SkyCrawl** [comment]
Hello @hetz 

thank you for your suggestion. Several quick notes for a further discussion (if it's going to happen)...

Sources:
* Ruby integration with Bower:

* [this](https://github.com/stve/bower#non-rails-projects)):

1. Bower support is (at the moment, anyway) predicated by supporting sprockets.
2. Bower support might actually be nice - to outsource, "configure" and automatically handle some Javascript libraries that Gollum uses (will use). In other words, no additional Sinatra-based gems. I think we had this idea in the past but it seems to have been forgotten by everyone.

**Comment by SkyCrawl** [comment]
Hello @hetz 

thank you for your suggestion. What exactly would you like to do with Gollum if Bower is supported? I'm afraid I'm not quite clear on that :).

Several quick notes for a further discussion (if it's going to happen)...

Sources:
* [Bower package configuration](http://bower.io/docs/config/).
* [Bower package manifest](https://github.com/bower/spec/blob/master/json.md).
* Some [tools](http://bower.io/docs/tools/) seem interesting.
* Ruby integration with Bower:
    * [Bower for Sprockets](https://github.com/stve/bower#non-rails-projects). Seems like a usable option.
    * [Bower for Ruby](https://github.com/kaeff/ruby-bower). A very very basic integration at the moment. Avoid for now.

Notes:
* At the moment, Bower support seems to be predicated by also supporting sprockets.
* Bower support might actually be very nice - to outsource, "configure" and automatically handle some Javascript libraries that Gollum uses (will use) - in other words, no additional Sinatra-based gems. Another advantage is complete offline support, once the installation is done. I think we had this idea in the past but it seems to have been forgotten by everyone, including me.
* It is probably worth to consider other alternatives to Bower, like plain npm support.
* The biggest question may be, however, whether introducing a new hard technology requirement (another tool installed) is worth the gain.

**Comment by bartkamphorst** [comment]
Honestly, I don't see this happening any time soon. If anyone with Bower expertise is willing to work on this we can reopen the conversation, but I'm closing it for now.
