### ISSUE TITLE
reStructuredText function bar in editor?

### ISSUE THREAD

**Issue by AnvilStriker** [gollum/gollum#1092]
Is there some thorny technical reason that the reStructuredText edit mode doesn't show a function bar in the editor (the way most of the other markup languages do)?

Or is it simply a matter of no one having gotten around to it yet?  :-)

**Comment by dometto** [comment]
I think the latter. :) I think all that is needed is a language definition in https://github.com/gollum/gollum/tree/master/lib/gollum/public/gollum/javascript/editor/langs

**Comment by AnvilStriker** [comment]
Thanks, just wanted to make sure that if I invested some time in writing such a language definition, that attempt wouldn't be in vain.

**Comment by AnvilStriker** [comment]
Okay, making some progress on this, but have encountered something puzzling:

Does anyone know why [gollum.editor.js at line 607](https://github.com/gollum/gollum/tree/master/lib/gollum/public/gollum/javascript/editor/gollum.editor.js#L607) URL-encodes the selected text before performing the regex search-and-replace? Doing this pretty much guarantees that pattern symbols like `\n` and `\s` in a language-definition's search patterns won't match where one would expect them to. It also messes up character counting -- a URL-encoded "space" character, for example, takes up three characters -- which is important when trying to get a reStructuredText title-underline to be the same length as the string it's marking up.

Also, while we're here: What's the purpose of the `replace()` call at line 610 of the same file? Per the comment it supposedly removes things that look like back-references. But literal back-reference symbols like `$1`, `$2`, etc. should *never* find their way into the string result of the previous `replace()`, unless there are more back-references than capturing patterns. (And if there *are* more back-references than capturing patterns, I'd think one would want to know about it, rather than burying the error!)

**Comment by bartkamphorst** [comment]
> Does anyone know why gollum.editor.js at line 607 URL-encodes the selected text before performing the regex search-and-replace?

The blame info is actually remarkable helpful in this case. See [here](https://github.com/gollum/gollum/commit/08dd36e1b0cb377c4982f0654bf0713e408de4c4). If there are better ways to achieve what MrJaeger was after then please feel free to make changes.

**Comment by dometto** [comment]
Thanks for working on this @AnvilStriker. I have to say my knowledge of the JS parts of gollum is very limited, so I can't see if there is any reason for the strange lines you mention. Your analysis sounds convincing, so I would suggest just changing the relevant code. Unfortunately we have no tests for the JS.

@sunny: do you think we're missing anything here?

**Comment by dometto** [comment]
Ah, good stuff @bartkamphorst!

**Comment by AnvilStriker** [comment]
Oho, so *that's* what the "Blame" button is for! :-)

I've always assumed that "blame" was used there as a verb (i.e., "blame someone for something") rather than as a noun ("who carries the blame for this?").

So, yes, good stuff indeed @bartkamphorst!

**Comment by AnvilStriker** [comment]
@bartkamphorst - Just to follow up a bit: I'm not so sure that MrJaeger was the original source of the problem, despite the dubious nature of his "solution" to the proximate issue. 

To my mind, what's really at issue is why, in the first place, Eston thought it was necessary or advisable to remove back-reference symbols from the result of the original `replace()` call. As I noted a few posts back, such symbols should never make it into the result if the search pattern and the replacement pattern are properly coordinated. At least, that's my understanding of how regex substitution *should* work.

To really get to the bottom of this, I will probably need to look back through several revisions to determine the source of the supposed problem that Eston was trying to address, and from there determine whether it was really a problem in need of soluton.

Unfortunately, a new work-week has now started, so this investigation will probably have to wait for a few days.

**Comment by bartkamphorst** [comment]
@AnvilStriker Take your time, I'd really prefer a well worked-out solution over a quick fix for this. Thanks for your time and efforts!

**Comment by AnvilStriker** [comment]
Okay, so here's what I think happened:

[**tl;dr** - MrJaeger coded a not-fully-though-through workaround for a line of code that Eston had earlier put in as part of a (failed) experiment, and left in by mistake.]

Back at ca5bf8b31e01cabc105b28e1ad42d45c836a7083 (or maybe even before), Eston lays down the basic implementation of function-button execution in `gollum.editor.js`, including search/replace with back-references as a strategy for decorating selected text with markup. 

Then at add9402b7e46425480c30e366b111eb79f1e7349, he decides that the buttons that employe search/replace also ought to do something useful at the current cursor position even when *no* text is selected. So he adds some code to insert the replacement pattern at the cursor position, and to then knock out the back-reference symbols -- which he needed to do in that case, because with nothing selected, there was no existing text to match, and thus nothing that the `replace()` method could substitute for the back-reference symbols. 

Fair enough. But for *some reason I cannot fathom*, he at the same time chooses to replace the original `replace()` call (in the "text-selected" case) with his own code that attempts to replace the back-references in the replacement pattern, **one by one**, with values obtained from the regex `exec()` function applied to the selected text. Frankly, I'm astonished that this code ever worked for him at all -- at least if he had done any halfway relevant testing. At the very least he would have needed to call the `exec()` function in a loop to ensure that he had exhausted all the matches in the selected text (as the "g" flag on his regexes instructs `replace()` to do, typically for selections that span multiple lines).

It's perhaps telling that in the *very next* update to the editor (2de9f5f3967f5f6c3d60e6793b0168cd6176f110) less than two hours later, he adds a single `replace()` call to, as his comment says, "remove any excess backreferences from the replace string," right below his strange new brute-force back-reference replacement code. The commit message is "Fixing backreference bug in WebKit" -- but that seems pretty dubious, because the way his code was constituted at that time, he wasn't actually calling `replace()` in a way that it would have used those `$1` and `$2` symbols as true back-references. 

I suppose it's *possible* that in 2010 there might have been a bug in WebKit that could have caused his one-by-one `replace()` calls (again, not involving any true back-references) to fail. But I'm more inclined to think that he'd merely found a way to make that code fail on its own. (Besides, two hours seems an awfully short time in which to identify a problem as browser/layout-engine specific.)

In any event, by 05b53462df6fb9f32e656f044de825fe73beeb16, he's back to letting `replace()`, now once again using true back-references, do the work that he'd tried unsuccessfully to do by hand in add9402b7e46425480c30e366b111eb79f1e7349. Yet, for whatever reason, he *leaves in* the line of code that removes "excess" back-references. 

The trap is now set for MrJaeger, because that line of code removes anything that even *looks like* a back-reference -- even if it came from the user's input text (which, in MrJaeger's case, I'm sure it did).

So, MrJaeger, believing there's actually some valid reason for that extra line of code to exist, works around it in a way that *seems* reasonable -- or, well... at any rate, works for *his* use case. Of course, it breaks the backs of most of Eston's regexes (and mine!) since `escape()` URL-encodes newlines and other whitespace characters, as well as URL-encoding the dollar-sign.

*Anyway...*

I think the conclusion to draw from all this is that there was never any reason to retain that `replace()` call to "remove backreferences" once Eston reverted his one-by-one back-reference replacement experiment. And while it's not a conclusive piece of evidence, it's worth pointing out that he *did* manage to do without "excess back-reference removal" from at least 4 Nov 2010 to 6 Dev 2010, when he introduced his questionable code and his "WebKit bug fix." 

If there was indeed a real WebKit issue with `replace()`'s handling of *true* back-references (which, to reiterate, I find a dubious claim), I have not so far found a way to evoke it today on a recent version of Safari, apart from committing the obvious programmer error of having back-reference symbols in the replacement pattern for which no corresponding capturing groups exist in the search pattern.

So I'm going to proceed by removing *both* the unneeded "remove backreferences" call to `replace()` *and* the `escape()`/`unescape()` calls that bracket both it and the `replace()` call that actually does the work -- and then try to create a bunch of QUnit tests to see if I can find a way to break it.

If anyone has a circa-2010 WebKit browser lying around, it might be fun to try the new code out on it and see what happens...

**Comment by bartkamphorst** [comment]
That exegesis cracked me up! :smile: Thanks for putting in the time to uncover all of this.
> So I'm going to proceed by removing both the unneeded "remove backreferences" call to replace() and the escape()/unescape() calls that bracket both it and the replace() call that actually does the work -- and then try to create a bunch of QUnit tests to see if I can find a way to break it.

Seems like a good way forward. Let us know how it goes!

**Comment by AnvilStriker** [comment]
Glad you found it entertaining -- and hopefully also somewhat informative. 

My initial trial of the proposed solution is looking good, and producing results much closer to what GitHub's wiki editor produces. 

Now I need to figure out how to set up a QUnit test scaffold to exercise the editor code... and the weekend is almost over... :-(

**Comment by bartkamphorst** [comment]
> hopefully also somewhat informative.

Absolutely; I didn't mean to imply otherwise.

**Comment by AnvilStriker** [comment]
Sorry this is taking me longer than I'd expected. 

The quick four-line patch to the editor's Javascript code was easy and works fine, but getting QUnit to run in the gollum environment is proving to be... uh... challenging, since I'm starting from **zero** knowledge of ruby, sinatra, mustache, etc. (I'm a Python/PHP/Javascript kind of guy...)

I was able to get some representative QUnit tests to run against the gollum editor in a static web page modeled on the page returned by `get /create/*`, so it seemed like I was well on my way.  But when I include the same testing scripts from a new template (`jstests.mustache`, cloned from `create.mustache`), every test that utilizes JQuery in any way dies with `ReferenceError: $ is not defined`. 

Underlying *that* error is a sequence of messages in the Javascript console that say:

```
Refused to execute script from 'http://localhost:4567/javascript/<scriptname>.js' because 
its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

This happens for *every* JS script included from `layout.mustache` (and happened even *before* I edited that template to include the QUnit css file), but not for the `qunit.js` file nor for my `tests.js` file (included from my new `jstests.mustache` file). 

The only (and perhaps irrelevant) clue I have at the moment is that my testing scripts are referenced from the HTML page body, whereas all the others are referenced from the page head -- although I don't see why that would cause the server to send those scripts from the head with the wrong MIME type. I suspect a more likely explanation might be that I'm missing something important in my new `get '/jstest'` endpoint in `app.rb`, which is simply:

```
    get '/jstest' do
      mustache :jstest
    end
```

If this is in any way a familiar-sounding problem, I'd love to read any insight anyone may be able to share.

**Comment by bartkamphorst** [comment]
@AnvilStriker We're working on gollum `v.5.x`, and I would love to incorporate your work into that release. For one, can we use your [rest language definition](https://raw.githubusercontent.com/AnvilStriker/gollum/editor-functions-fix/lib/gollum/public/gollum/javascript/editor/langs/rest.js)? And if possible, would you mind opening a PR for your changes to the `gollum.editor.js` to `5.x` branch?

**Comment by bartkamphorst** [comment]
> And if possible, would you mind opening a PR for your changes to the gollum.editor.js to 5.x branch?
Actually, we should also consider [this PR](https://github.com/gollum/gollum/pull/1173), and determine whether the bugs you encountered are still present after that PR is merged.

**Comment by dometto** [comment]
I think the rest language definition by @AnvilStriker is part of a PR he opened to gollum, so I assume that means we're allowed to use it -- but it would be great if you could let us know!

**Comment by bartkamphorst** [comment]
A basic language definition for rest will be included in the `5.x` release. PRs for improvements are welcome.

**Comment by dometto** [comment]
🎆
