### ISSUE TITLE
Error with cli

### ISSUE THREAD

**Issue by ManuCart** [gollum/gollum#1093]
With ```` gimli -f texte.md````
I have this error
````
/var/lib/gems/2.1.0/gems/wkhtmltopdf-binary-0.9.9.3/bin/wkhtmltopdf_linux_386: 1: /var/lib/gems/2.1.0/gems/wkhtmltopdf-binary-0.9.9.3/bin/wkhtmltopdf_linux_386: Syntax error: "(" unexpecte
````

with ````ruby 2.1.5p273 (2014-11-13) [arm-linux-gnueabihf]````

**Comment by dometto** [comment]
This doesn't look like a gollum issue at all? Try https://github.com/walle/gimli

**Comment by ManuCart** [comment]
Sorry I'm testing the twice
