### ISSUE TITLE
AsciiDoctor attributes support

### ISSUE THREAD

**Issue by eshepelyuk** [gollum/gollum#1100]
Does `gollum` support `AsciiDoctor` attributes, e.g. `:icons: font`  to display admonitions properly ?

For instance, this doesn't display `FontAwesome` icons, only plain text.

````
[NOTE]
====
Some note.
====
````

Or maybe attributes can only be enabled via `--config` option ? If true, can someone explain howto make it work ?

**Comment by bartkamphorst** [comment]
I can confirm that this doesn't work, but I'm not sure why that is yet.

**Comment by dometto** [comment]
@eschepelyuk, please check if the `asciidoctor` gem (which gollum uses to render asciidoc) supports this. If not, open an issue there. If it does, I'll consider this a bug in gollum.

**Comment by eshepelyuk** [comment]
It works in `AsciiDoctor`

**Comment by bartkamphorst** [comment]
This is what Asciidoctor does in irb:
```bash
2.0.0-p643 :001 > require 'asciidoctor'
 => true 
2.0.0-p643 :002 > content = "NOTE: admonition style message"
 => "NOTE: admonition style message" 
2.0.0-p643 :003 > Asciidoctor.convert content
 => "<div class=\"admonitionblock note\">\n<table>\n<tr>\n<td class=\"icon\">\n<div class=\"title\">Note</div>\n</td>\n<td class=\"content\">\nadmonition style message\n</td>\n</tr>\n</table>\n</div>" 
```
And gollum shows the same HTML. So I suspect there is an issue with `iconsdir` and the icons not being found, and possibly also with CSS.

**Comment by dometto** [comment]
Thanks. So it's a bug, and in gollum rather than in gollum-lib. Possibly we just need to update the version of fontawesome that's released with gollum.

**Comment by bartkamphorst** [comment]
Wait, I spoke too soon. The HTML in my example does not include an `<i>` tag. This is only added with the `:icons` directive that @eshepelyuk mentioned, and only works in safe mode:
```bash
2.0.0-p643 :004 > content = ":icons: font\n\nNOTE: admonition style message"
 => ":icons: font\n\nNOTE: admonition style message" 
2.0.0-p643 :005 > Asciidoctor.convert content, safe: 'safe'
 => "<div class=\"admonitionblock note\">\n<table>\n<tr>\n<td class=\"icon\">\n<i class=\"fa icon-note\" title=\"Note\"></i>\n</td>\n<td class=\"content\">\nadmonition style message\n</td>\n</tr>\n</table>\n</div>" 
```

**Comment by bartkamphorst** [comment]
(As a side note, github currently exhibits the same behavior as gollum by not displaying admonition icons.)

**Comment by dometto** [comment]
If you add the `<i>` to gollum's html (e.g. in your browser's debugger), does it render the icon?

**Comment by bartkamphorst** [comment]
I turned safe mode on using [this snippet](https://github.com/gollum/gollum/wiki/Formats-and-extensions#changing-github-markups-default-renderings-settings-eg-turning-asciidoctors-safe-mode-on), which changed the HTML (`<i class="fa icon-note" title="Note"></i>`), but did not render any icon.

**Comment by dometto** [comment]
Then we should consider this a bug. We don't need to turn on safe mode by default, but if it's on, this behavior should (and could) work.

**Comment by bartkamphorst** [comment]
> Possibly we just need to update the version of fontawesome that's released with gollum.

I suspect that this might well solve the issue.
