### ISSUE TITLE
[windows] - utf-8 Page Title incorrect

### ISSUE THREAD

**Issue by liuweizzuie** [gollum/gollum#1102]
``` ruby
jruby --version
jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 25.65-b01 on 1.8.0_65-b17 +jit [Windows 10-amd64]
gollum --version
Gollum 4.0.1
```
# can not create utf-8 titled page

When I create a page with utf-8 like this:
![image](https://cloud.githubusercontent.com/assets/2696315/11948483/540bc2b2-a8af-11e5-9ead-58657e9e620f.png)
it turns out to be: 
![image](https://cloud.githubusercontent.com/assets/2696315/11948491/689b6b38-a8af-11e5-95c2-caaa22f84b61.png)
may be it's ok, though it should be the same as the utf-8 chars, but it works fine, cus I can use English words as my title. 
# can not edit utf-8 titled page

when wiki cloned  from another remote server, like [oschina](http://git.oschina.net), like this:
![image](https://cloud.githubusercontent.com/assets/2696315/11948538/eef83062-a8af-11e5-8e81-c6e6aee3ac10.png)
I want to edit the wiki pages locally then push it to oschina.  
seems ok(I'll talk of  äº®ç¯ç  later, sorry about this Invisible char):
![image](https://cloud.githubusercontent.com/assets/2696315/11948589/4de08958-a8b0-11e5-9d07-12a55e86df7e.png)
the mk files were encoded with uft-8:
![image](https://cloud.githubusercontent.com/assets/2696315/11948865/d0d2c5f8-a8b3-11e5-9927-17a5a51004cf.png)

 I tried to edit this page, then I save it,   created the page : äº®ç¯ç, and the initial page remains to what it was. 
![image](https://cloud.githubusercontent.com/assets/2696315/11948699/cf1f3da6-a8b1-11e5-9268-c98c5e5815a1.png)

I'v read about #547 and #824  (the latter didn't help),  so i believe it's been solved, however It appeared on my windows workstation.

**Comment by karas1999** [comment]
@liuweizzuie 
I'm using the MAC OS X and met this issue too. Maybe this would help:

I assume you can read Chinese. If not, tell me. 

## 1.中文变成拼音的问题

### 问题现象

1. 输入中文链接, 点击链接创建链接文件, 会变成拼音形式

### 问题原因

1. 是因为默认的git-adapter grit本身会对UTF-8字符进行转换, 例如会自动将中文转成拼音. 

### 解决方案

1. 把adapter换成rugged
	2. 安装rugged, 具体参见: [Git Adapters](https://github.com/gollum/gollum/wiki/Git-adapters)
	3. 运行时带参数: `gollum --adapter rugged`

**Comment by chengxinsun** [comment]
me too at mac os x 10.10.x

**Comment by liuweizzuie** [comment]
@karas1999 
感谢回复提供的解决方案。然而我使用的是JRuby,貌似rugged_adapter依赖于rugged，而Windows下安装rugged却是个比较麻烦的事情，因为总是无法编译C语言文件。我之前尝试过在Windows上使用ruby，但体验并不好，因为gollum无法安装于ruby，后来装了Jruby才能用的。  
暂时先将就着用吧。

**Comment by ptux** [comment]
We should fix this by ourselves who live in the multi-byte world.
So, I raise my hand.

**Comment by bartkamphorst** [comment]
@ptux Any help would be appreciated!

**Comment by dometto** [comment]
This should be fixed in https://github.com/gollum/gollum-lib/commit/f397fec9730cdcccc44404a02aa8b62f39fd9f0e which is part of the `5.x` branch. Anyone care to test it on windows and let us know about it?

**Comment by bartkamphorst** [comment]
I'm considering this fixed unless I hear otherwise from someone working on Windows.
