### ISSUE TITLE
How to get the current page name dynamically inside a sidebar?

### ISSUE THREAD

**Issue by karas1999** [gollum/gollum#1103]
Hi, I'm new to Gollum. I'm trying to get the current page name inside a sidebar, and then generate a tag link to a discussion page, for example:

If the main page called XXX, then in the side bar, automatically include a file like:

```
[[include|discussions/talk-XXX]]
```

Then we can write the comments in that talk-XXX page like other wikis. 

I don't know if can use a dynamic tag to get the page name, so I tried to make a custom macro get_page_name.rb like this:

```ruby
module Gollum
  class Macro
    class GetPageName < Gollum::Macro
      def render
        @page.name
      end
    end
  end
end
```

But the problem is I don't know how to register the custom page to the config.rb file. I can't find any guide to this. 

My questions are:
1. Is there a guide or example the can tell how to register a custom macro to the config.rb file?
2. Is there any other way to get the dynamic page title in the *.md files? For example like an html.erb syntax:
```
[[include|discussions/talk-<%= @page.name %>]]
```

**Comment by bartkamphorst** [comment]
The easiest way to include a custom Macro is to define it inside `config.rb` and start gollum with the ``--config`` flag. The Macro will then be picked up by gollum. See [here](https://github.com/gollum/gollum/wiki#custom-macros) for a (brief) guide. There is no `erb` in gollum, so using this macro approach seems to be your best bet. Feel free to reopen if you run into any trouble using this approach.

**Comment by karas1999** [comment]
@bartkamphorst , thank you for you answer. Finally I can understand what you mean now. I think there are two ways to custom a macro, right?
1. Make a new rb file in the gollum-lib-4.1.0/lib/gollum-lib/macro folder and define the macro into that file. 
2. Define the whole macro into the config.rb file and start gollum with --config.

I can make it work now. And use the `@page.parent_page` to get the home page name. The macro feature is really powerful.

**Comment by bartkamphorst** [comment]
That's right. Glad you got it to work!
