### ISSUE TITLE
How to exclude a folder from being presented in the wikis list ?

### ISSUE THREAD

**Issue by chrisvel** [gollum/gollum#1108]
For example licenses or lib ones, or the readme markdown in the root folder. How do I choose what to exclude ?

**Comment by dometto** [comment]
Gollum does not support filtering out certain documents. However, you can:

* just not link to the files in question (although they will show up in 
the file listing and/or global table of contents)
* use `--page-file-dir pathtopagefiles` to limit the wiki to just one 
directory. So then you can have a repo structure with readme and license 
in the repo root, and your files in `pathtopagefiles`.

**Comment by chrisvel** [comment]
@dometto The second solution sound pretty good. Thanks.
