### ISSUE TITLE
Test failure on MRI 2.3.0

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1110]
Due to `test-unit` gem dependency. See https://travis-ci.org/gollum/gollum/jobs/109233252

**Comment by jhominal** [comment]
From what I can see, the `test-unit` dependency exists in the `gollum.gemspec`, on [line 38](https://github.com/gollum/gollum/blob/master/gollum.gemspec#L38):

```ruby
s.add_development_dependency 'test-unit', '~> 3.1.0' if RUBY_VERSION =~ /^2.2/
```

I would be in favor of adding the `test-unit` dependency unconditionally (as in [`gollum-lib`](https://github.com/gollum/gollum-lib/blob/master/gemspec.rb#L45)).
