### ISSUE TITLE
OSX El Capitan and Gollum::InvalidGitRepositoryError - Gollum::InvalidGitRepositoryError

### ISSUE THREAD

**Issue by chrisvel** [gollum/gollum#1113]
I have successfully followed instructions and installed with `gem install gollum` then I try to start the Sinatra WEBrick with `gollum` and it does so, but fails when I load the page with `Gollum::InvalidGitRepositoryError - Gollum::InvalidGitRepositoryError error`. If I git clone the repo then it also does not work. I am using rvm with ruby 2.3.0.

**Comment by chrisvel** [comment]
`git init` inside the current folder that contains the docu files. Maybe documentation needs update.

**Comment by zfrenchee** [comment]
Did this work?

**Comment by voncay** [comment]
It worked for me !
Indeed the `gollum` command must run inside a git repository to work because that is where the files will be save from the web interface.
The documentation do need an update on that troubleshooting.
