### ISSUE TITLE
Is Live preview disabled or not working?

### ISSUE THREAD

**Issue by Pysis868** [gollum/gollum#1115]
### Problem Summary
By going off of the readme, I am starting the program by running `gollum --live-preview` with that option, inside of a sample git repository (not a GitHub wiki repository), just to test the functionality.  Not sure what the default for this flag is, or the current state of this feature in general.
By visiting `/`, I am redirected to `/create/Home`, but I see no difference in the UI.
Going to `/livepreview` simply redirects to `/create/livepreview`, and only presents a non-live page editor page again.
I have tried searching online for what to expect, [but do not see a "Preview" tab appear](https://github.com/gollum/gollum/issues/826), [or anything beside the normal page editor](https://camo.githubusercontent.com/61bf20cd86cbaaa7fbcb856d47071dd2323c1d81/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f35323135342f3337383638322f38336238656131612d613535332d313165322d383862342d6130393964333732343939352e706e67), and still see only the non-live "Preview" button at the bottom.

### Environment
* I am running Gollum 4.0.1 installed by gem on my Mac 10.11.3.
* "INFO  ruby 2.0.0 (2015-12-16) [x86_64-darwin15.3.0]" is being used, as it is set through RVM as my default ruby version.
* "WEBrick 1.3.1" seems to start up, and on the following line I get: "== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from WEBrick", if that is correct to be using.

**Note:** I did not install `icu4c` or `charlock_holmes` per the instructions found on this page [gollum/gollum - Installation - OS X](https://github.com/gollum/gollum/wiki/Installation#os-x), since after following the main set-up instruction `gem install gollum` and running to test it, the application seemed to work fine.

**Comment by SkyCrawl** [comment]
Hello @Pysis868 

the live preview is only available for already existing pages, by clicking on the `Edit` button on the top of that page. What you see is another editor (Gollum has 2 atm) which is only used when creating new pages, or (maybe, not sure atm) trying to access a non-existing page. In your case, your repository lacks the default (`Home`) page and hence the redirection to `/create/Home`. Then you're trying to access the `livepreview` page which obviously doesn't exist too and hence the redirection to `/create/livepreview`.

Either create the `Home` page or try to access an already existing page :).

**Comment by Pysis868** [comment]
That's a bit strange.  Couldn't it simply use 1 editor, and have it work for a page that does not exist yet?

I got around to trying it now, and have found the default to be 'off' or 'disabled'.  If that is correct, could this be added to the documentation?

As a follow-up question, do you think I need to (manually) install those other packages I mentioned in my note for OS X?  If not, could that be removed from the documentation?

**Comment by SkyCrawl** [comment]
> That's a bit strange. Couldn't it simply use 1 editor, and have it work for a page that does not exist yet?

Indeed, it is strange. It's actually a known and ancient issue but Gollum's development has pretty much stopped.

> I got around to trying it now, and have found the default to be 'off' or 'disabled'. If that is correct, could this be added to the documentation?

Sorry, I don't follow here...

> Do you think I need to (manually) install those other packages I mentioned in my note for OS X? If not, could that be removed from the documentation?

You don't. If it works, it works :). I think we had best not to remove it but rather say something about the packages not being necessary since a certain implementation and version of Ruby. I'm not exactly sure about the older versions...

**Comment by Pysis868** [comment]
ok, I think my questions are mostly answered, so I can close the issue.

I meant that live preview seems to be off by default.

Yea, if the README could be updated to say additional installation is not needed, that would be nice.

**Comment by polyzen** [comment]
@Pysis868, have you tried live-preview on existing pages? Not having any luck, myself.
