### ISSUE TITLE
GitHub Flavored Markdown does not appear as an edit mode, even after apparent plug-in installation.

### ISSUE THREAD

**Issue by Pysis868** [gollum/gollum#1116]
### Problem Summary
By going off of the [readme#markups](https://github.com/gollum/gollum#markups), I ran `gem install github-markdown`, but do not see it appear in the "Edit Mode" dropdown box in the UI, looking for "GitHub Flavored Markdown'.
I'm tempted to install `redcarpet` next, but curious what anyone has to say first.

### Environment
* I am running Gollum 4.0.1 installed by gem on my Mac 10.11.3.
* "INFO  ruby 2.0.0 (2015-12-16) [x86_64-darwin15.3.0]" is being used, as it is set through RVM as my default ruby version.
* "WEBrick 1.3.1" seems to start up, and on the following line I get: "== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from WEBrick", if that is correct to be using.
* Running the `gem list github` command results with:
```
*** LOCAL GEMS ***
 
 github-markdown (0.6.9)
 github-markup (1.4.0)
```

**Note:** I did not install `icu4c` or `charlock_holmes` per the instructions found on this page [gollum/gollum - Installation - OS X](https://github.com/gollum/gollum/wiki/Installation#os-x), since after following the main set-up instruction `gem install gollum` and running to test it, the application seemed to work fine.

**Comment by SkyCrawl** [comment]
I may be mistaken but I think that `github-markdown` renders GFM by default. Which means that you won't find GFM in the list of formats as it should be supported along with the `Markdown` format (all markdown is rendered with the same gem).

Have you tried it? :)

**Comment by Pysis868** [comment]
So would we need to install a separate package to get it to work, under the same edit mode, or is it included by default now?

It looks to be working, but I wasn't sure about the exact differences between normal Markdown and GitHub-flavored Markdown, to be able to test it accurately.

**Comment by SkyCrawl** [comment]
As far as I know, [GFM](https://guides.github.com/features/mastering-markdown/) doesn't make the original markdown behave much differently, it mainly extends it. Yes, it is included by default after `gem install github-markdown`.

**Comment by Pysis868** [comment]
ok, so the package is still needed.  Thanks!
