### ISSUE TITLE
mermaid support

### ISSUE THREAD

**Issue by dhalsim** [gollum/gollum#1118]
Hello,

I wanted to add [mermaid](http://knsv.github.io/mermaid) diagrams to wiki pages like this one [Haroopad ](http://pad.haroopress.com/page.html?f=how-to-draw-diagram) does.
But if I add the code snippet of mermaid to a markdown page this HTML is created:

```html
<span class="err">graph TD;
    A--&amp;gt;B;
    A--&amp;gt;C;
    B--&amp;gt;D;
    C--&amp;gt;D;</span>
```

I'm no expert at Ruby and can't understand the exact place to look in the source code (and its dependencies). I need a basic guidance here.

P.S: I know gollum uses PlantUML for this purpose but I like to use mermaid if possible.

Thanks,

**Comment by dometto** [comment]
I suspect this is an issue with html sanitization. You should whitelist whatever elements mermaid uses. Use the --config option to specify a config file and see:

https://github.com/gollum/gollum/wiki/Security#customization

**Comment by rgroux** [comment]
awesome lib, 
very easy to integrate (nothing to do)

you can use it in 6 steps, hope someone (maybe me) will create a gem and use it as gem or maybe as native(far more better)

GIT_REPO=<path to your wiki git repo>

1. download the mermaid.js and memaid.css from github
1. move and rename mermaid.js -> $GIT_REPO/custom.js
1. move and rename mermaid.css -> $GIT_REPO/custom.css
1. git add custom.css custom.js
1. git commit custom.css custom.js -m 'feature(js): add support for memaid diagrams'
1. start gollum with --js --css (bundle exec bin/gollum --js --css $GIT_REPO)
1. enjoy

for example create a new page and add this

```html
<div class="mermaid">
graph RL
    A[Hard edge] -->|Link text| B(Round edge)
    B --> C{Decision}
    C -->|One| D[Result one]
    C -->|Two| E[Result two]
</div>
<div class="mermaid">
graph LR
    A[Hard edge] -->|Link text| B(Round edge)
    B --> C{Decision}
    C -->|One| D[Result one]
    C -->|Two| E[Result two]
</div>
```

**Comment by dhalsim** [comment]
Yeah, it worked like a charm :+1: 
 
Thanks

**Comment by rgroux** [comment]
@dhalsim 

i create a pull request #1119 to add mermaid js inside gollum and use it natively without custom.[js|css].

I hope it will be accepted in the upstream :)

/R

**Comment by wf5w** [comment]
Just installed gollum.

In my wiki page just how do I code a mermaid graph?
I tried:
\```mermaid
graph LR
    A[find] --> |stdout| B[grep for doc]
    B --> |stdout| C[grep for linux]
    C --> E(stdout)
\```

and noting but an error.

I did a git clone, and followed the directions for installing and running.
