### ISSUE TITLE
Push/Pull or Sync buttons.

### ISSUE THREAD

**Issue by postmodern** [gollum/gollum#112]
For working on local Gollum repositories, Gollum should provide Push/Pull or Sync buttons that will rebase and sync changes with the remote repository.

**Comment by stevearm** [comment]
I run with the following `config.rb` which does a sync every time I edit. It's not ideal (a machine not doing any edit will fall behind), but it's something.

    #!/usr/bin/env ruby
    require 'gollum/app'

    wiki = Gollum::Wiki.new(".")

    # Per https://github.com/gollum/gollum-lib/issues/12
    Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
      wiki.repo.git.pull("origin", "master")
      wiki.repo.git.push("origin", "master")
    end
