### ISSUE TITLE
[Windows] First page (/Home) unusable after creation

### ISSUE THREAD

**Issue by recomark1** [gollum/gollum#1120]
Environment:
- Ruby: jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.77-b03 on 1.8.0_77-b03 +jit [Windows 10-amd64]
- Gollum: Gollum 4.0.1
- Git: git version 2.7.1.windows.2

Steps:
1. Create new dir.
2. Run git init.
3. Run gollum.
4. WEBrick starts.
5. In browser access localhost:4567/, page "Create New Page" displays in edit mode "Markdown".
6. Type "Some text."
7. Push "Save" button.
8. Error page displays: "NoMethodError at /Home undefined method `objectId' for Java::OrgEclipseJgitTreewalk::TreeWalk:0x52bc2a54".
9. Page Home.md is created and committed.

**Comment by recomark1** [comment]
Seems like bug in RJGit:

`C:/app/x86_64/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rjgit-4.2.0.1/lib/rjgit_helpers.rb in get_file_mode`

>     walk = RevWalk.new(jrepo)
>     jcommit = walk.parse_commit(last_commit_hash)
>     treewalk = TreeWalk.new(jrepo)
>     jtree = jcommit.get_tree
>     treewalk.add_tree(jtree)
>     treewalk.set_recursive(true)
>     while treewalk.next
>       jblob_lookup = walk.lookup_blob(treewalk.objectId(0))
>       if jblob_lookup.get_name == jblob.get_name
>         mode = treewalk.get_file_mode(0).get_bits
>         return mode
>       end
>     end

**Comment by blablatros** [comment]
I am having the same issue.

Changing
`jblob_lookup = walk.lookup_blob(treewalk.objectId(0))` to
`jblob_lookup = walk.lookup_blob(treewalk.getObjectId(0))`
in `rjgit_helpers.rb` solved the problem.

**Comment by dometto** [comment]
This should be fixed in the new release of the `rjgit_adapter` (`v0.3.4`). Please update the `adapter` with `gem update` or `bundle update`. If the problem persists, please let us know by reopening this issue!
