### ISSUE TITLE
Mount gollum to suburl

### ISSUE THREAD

**Issue by KHN190** [gollum/gollum#1121]
I mounted gollum in my application at `/wiki`, however I couldn't adapt grit to rugged. I want to do so because I had utf encoding problem as issued [here](https://github.com/gollum/gollum/issues/843).

I have set up my application as below:
```
# routes.rb
require 'gollum/app'

MyApplication::Application.routes.draw do
  Precious::App.set(:gollum_path, Rails.root.join('wiki').to_s)
  Precious::App.set(:default_markup, :mediawiki)
  Precious::App.set(:wiki_options, {:universal_toc => false})
  mount Precious::App, at: 'wiki'
end

# Gemfile
gem 'gollum'
gem 'wikicloth'

# config.ru
module Gollum
  Gollum::GIT_ADAPTER = "rugged"
end
```

I'm not confident that it's really switching to rugged, since I still couldn't create utf-8 titles. The [wiki](https://github.com/gollum/gollum/wiki/Git-adapters#rack-configuration-file) shortly mentioned it within a line, but the situation is slightly different from mine. Thanks for instructions!

**Comment by KHN190** [comment]
Yet another bug I believe:

1. set default extension to mediawiki
2. create a markdown page
3. edit the markdown page, you'll find it impossible - gollum redirects it to create a page named "livepreview"

**Comment by dometto** [comment]
What you want is the equivalent of the `--base-path` option while using gollum as a piece of rack middleware. See [the wiki](https://github.com/gollum/gollum/wiki/Gollum-via-Rack#the---base-path-option) for instructions. You'll have to tweak this for your own rails app, but also see [here](https://github.com/repotag/repotag/blob/master/app/classes/repotag_auth_proxy.rb#L163-L168) for an example of using gollum as a rack middleware in rails.

I'm not sure if there is still a distinct utf-8 issue left that is not already reported. If so, please open a new issue. To use the rugged adapter you have to make sure that the adapter constant is set *before* gollum is loaded.
