### ISSUE TITLE
Turning gollum-lib adapter to rugged

### ISSUE THREAD

**Issue by KHN190** [gollum/gollum#1124]
Sorry to post here. This is an usage issue, I opened an issue at https://github.com/gollum/gollum-lib/issues/180 but over the past week seemed no one responding. Neither much chance I can get an answer from stackoverflow.

I'm aware of [this wiki](https://github.com/gollum/gollum/wiki/Git-adapters#changing-adapters), but gollum-lib insisted on grit adapter, thus utf-8 title breaks it.

```
# Write markdown to wiki
def save(commit)
  WIKI.write_page(name, :markdown, raw_data, commit)
end
```

```
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)

Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT:
  gitlab-grit (2.7.3) lib/grit/index.rb:176:in `block in write_tree'
  gitlab-grit (2.7.3) lib/grit/index.rb:171:in `write_tree'
  gitlab-grit (2.7.3) lib/grit/index.rb:123:in `commit'
  gollum-grit_adapter (1.0.1) lib/grit_adapter/git_layer_grit.rb:250:in `commit'
  gollum-lib (4.2.0) lib/gollum-lib/committer.rb:170:in `commit'
  gollum-lib (4.2.0) lib/gollum-lib/wiki.rb:354:in `write_page'
  ...
```

I have this in config.ru: (apparently, runs before rails server)
```
module Gollum
	Gollum::GIT_ADAPTER = "rugged"
end
```

**Comment by dometto** [comment]
Probably you are not setting the adapter constant *before* gollum-lib is loaded?

**Comment by KHN190** [comment]
@dometto in Gemfile to require rugged adpter and gollum-lib, also in config.ru:
```
module Gollum
	Gollum::GIT_ADAPTER = "rugged"
end

require 'gollum-lib'
```
logger still insisted:
```
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT:
  gitlab-grit (2.7.3) lib/grit/index.rb:176:in `block in write_tree'
  gitlab-grit (2.7.3) lib/grit/index.rb:171:in `write_tree'
  gitlab-grit (2.7.3) lib/grit/index.rb:123:in `commit'
  ...
```
However in my earlier tests the configuration should work with gollum (app).

**Comment by dometto** [comment]
Have you tried to get rid of the `Gollum::` bit? Just GIT_ADAPTER = "rugged" that is.

**Comment by KHN190** [comment]
@dometto Um, no. I entered in `rails console`:
```
> GIT_ADAPTER
NameError: uninitialized constant GIT_ADAPTER
> Gollum::GIT_ADAPTER
NameError: uninitialized constant Gollum::GIT_ADAPTER
```
when I actually had:
```
module Gollum
	Gollum::GIT_ADAPTER = "rugged"
	GIT_ADAPTER = "rugged"
end

require 'gollum-lib'
```
Weired. I didn't remember this would happen. The last time I checked the constant was here, just using grit instead.

**Comment by dometto** [comment]
Weird. Seems like it's falling back to DEFAULT_ADAPTER then. Sure nothing is already requiring gollum-lib (e.g. as a gem dependency) before you set the constant?

**Comment by KHN190** [comment]
```
Gollum::GIT_ADAPTER = "rugged"
GIT_ADAPTER = "rugged"
```
Here they do the same thing, but both failed (where can I check out why they fail?).
```
# Gemfile
# User system
gem "devise"
# Paginate
gem "will_paginate"

# Permission
gem "cancancan"
# Translation
gem "rails-i18n"

# Markdown
gem "redcarpet"
# Git control
# gem 'gollum'
gem 'gollum-lib'
gem 'gollum-rugged_adapter'
```

**Comment by KHN190** [comment]
@dometto can I just change https://github.com/gollum/gollum-lib/blob/master/gollum-lib.gemspec#L3 to `default_adapter = ['gollum-rugged_adapter']` and make use of it?

**Comment by KHN190** [comment]
Fixed. I updated gollum-lib to use grit as default: 
- https://github.com/KHN190/gollum-lib/blob/master/lib/gollum-lib.rb#L8
- https://github.com/KHN190/gollum-lib/blob/master/gollum-lib.gemspec#L3

Should I make a push to origin?
