### ISSUE TITLE
EmojiOne for Gollum

### ISSUE THREAD

**Issue by svoop** [gollum/gollum#1125]
I know, not everybody likes emoji. But they do come in handy at times. Here are just a few of my use cases:

* In an international or multilingual context, I like to mark parts with the corresponding flag such as :us: or :fr:.
* Bits of information can easily be highlighted with :warning:, :bulb: or alike.
* Todo lists can be ticked with :white_circle: and :red_circle:

#722 was closed due to the lack of an open license source of emoji, but these days, we have [EmojiOne](http://emojione.com) (licensed under CC).

I've implemented basic support for emoji as PNG images in order to support as many browsers as possible. However, it takes modifications in both gollum and gollum-lib, hence this issue to bundle.

Thanks for considering this addition!

**Comment by svoop** [comment]
Whoops, I've broken some tests, working on it.

**Comment by dometto** [comment]
Seeing as @dekimsey and @bootstraponline already ok'd the feature in the past, I'm not against this. @bartkamphorst?

In general, it would be great to have some benchmarks for the various parts of the filter chain, so we can assess the performance impact of adding a particular filter. It's a fairly expensive regex there, I think. Perhaps we can turn emoji's off by default?

**Comment by svoop** [comment]
> Perhaps we can turn emoji's off by default?

Sure, good idea!

**Comment by svoop** [comment]
I've added `--emoji` (default: false) which kicks emoji from the filter chain unless set.

**Comment by svoop** [comment]
@dometto Is there anything else I can do in order to get this merged?

**Comment by svoop** [comment]
@bartkamphorst Just a heads up: In order to merge the emoji feature, there are two PR:
* #1126
* gollum/gollum-lib#203
