### ISSUE TITLE
cant send ip address via nginx (reverse proxy)

### ISSUE THREAD

**Issue by xfarm001** [gollum/gollum#1129]
always gollum's access logs show "from 127.0.0.1".

why cant work x-forwarded option on nginx.

**Comment by dometto** [comment]
I don't see any reason why X-forward shouldn't work. Gollum by default uses WEBrick as its server, consult its documentation if need be. If there is a bug or missing feature in gollum that makes it impossible to use it with nginx, I'll be glad to reopen this.
