### ISSUE TITLE
add i18n support

### ISSUE THREAD

**Issue by hfl** [gollum/gollum#1130]
Gollum is not support i18n. I think should add this funtion.

**Comment by bartkamphorst** [comment]
I agree. PRs welcome!

**Comment by jokester** [comment]
Want i18n on the web interface (not content of pages) as well. Is anybody already working on this?

**Comment by bartkamphorst** [comment]
Not that I know of.

**Comment by bartkamphorst** [comment]
@jokester Care to contribute a PR?

**Comment by jokester** [comment]
bartkamphorst: guess I can do something on i18n of Web UI. Do we have a todo list on this topic?

**Comment by bartkamphorst** [comment]
Great! No, there's no todo list as of yet. @dometto Any thoughts about this? One note, when you start work on this, make sure to branch from the `5.x` branch.

**Comment by dometto** [comment]
No experience with this. @jokester, maybe you can give an indication of how'd you go about this and we can comment on any issues we (hopefully) foresee?

**Comment by jokester** [comment]
I made a small list after looking at `5.x` branch. Does these todos look valid?

- extract text resources to separated file (yaml or plain ruby)
- provide a `i18n(phrase_key)` method to mustache views/templates
    - in template there will be `i18n('home')` instead of current `Home`.
    - simple substitution can be done with `i18n(phrase_key, *params)`, but stuff beyond that (pluralize, date, etc) can make things more complex. Are they needed in gollum at all?
- some mechanism to select language / pass selection to view
    - a `gollum_lang` cookie seems valid to me
    - selection is initialized via `Accept-Language` header, and changed by some `<select>` / JavaScript in the UI
- custom templates may choose to do i18n (and follow the same convention) or not.

**Comment by dometto** [comment]
@jokester, sorry for the late reply. We would be very happy with this, if you're still able and willing to work on it. The main pointer I can give you now is to open your PR against the `5.x` branch. You can open a development PR and we'll be very happy to provide feedback along the way!

**Comment by bartkamphorst** [comment]
@jokester I know it's been a while, but would you still be willing to work on `i18n` support for gollum 5.x?

**Comment by bartkamphorst** [comment]
Ping @jokester .

**Comment by dometto** [comment]
Implemented by @benjaminwil in #1679! 🥇

**Comment by benjaminwil** [comment]
I plan to i18n all of the English hard-coded strings in the next couple of weeks.
