### ISSUE TITLE
Gollum Auth with OAUTH

### ISSUE THREAD

**Issue by iTsFILIPOficial** [gollum/gollum#1131]
Is there a way to use google/twitter/facebook/github oauth with gollum wiki?

Filipe

**Comment by rroller** [comment]
Yes. You can use Gollum OmniAuth. I just recently did this and documented
it here: http://toadjaw.com/Gollum

**Comment by iTsFILIPOficial** [comment]
@rroller  Does it do github only or can you add google as well?

**Comment by bartkamphorst** [comment]
Thanks @rroller for the write-up! I think many users will find that resource helpful. If you want, feel free to link to it from our wiki.

**Comment by rroller** [comment]
You can add Google and many other auth providers. It's based on
https://github.com/intridea/omniauth

**Comment by rroller** [comment]
Thanks! And done https://github.com/gollum/gollum/wiki#authentication

**Comment by iTsFILIPOficial** [comment]
So I was able to set everything up following the give a quick question I wanted to known on the 

` :authorized_users => ["example@example.com"] `
is there a way to run a regex that checks for any user of a domain like:

`:authorized_users => ["\A[\w.-]+\w@example.com"],`

**Comment by mreider** [comment]
Is it possible to put a domain, rather than specific users, into the config.rb file. i.e. the equivalent of ':authorized_users => ["*@example.com"],
