### ISSUE TITLE
Gollum Auth 

### ISSUE THREAD

**Issue by iTsFILIPOficial** [gollum/gollum#1133]
Hi, 

I followed the guide provided for the authentication, in the authorised user list is there a way to do a regex call for all user of a domain?

I have posted this on the omnigollum github page but  there is no response from then, can you guys help?

> In the
> 
> options[:authorized_users] = ["example0@example.org", "example1@example.org", "example2@example.org"]
> Is there a option to have all user of a specific domain? For example do all users in @github.com can access the wiki while users with @example.org will not be able to do so.
> 
> Filipe

[https://github.com/arr2036/omnigollum/issues/39](Issue Link)

**Comment by dometto** [comment]
Sorry, no, we don't know much about how omnigollum works. You could try stackoverflow, or contacting someone who has documented the workings of authentication in the wiki.
