### ISSUE TITLE
underscores in page title are being replaced by spaces when creating it

### ISSUE THREAD

**Issue by SimJoSt** [gollum/gollum#1135]
In our gollum powered Wiki we regularly create pages in the scheme "YEAR_MONTH_DAY" (without the quotations marks). These pages always get renamed to "YEAR MONTH DAY" and if it's corrected in the first editor, where you can select the file format, the undescores will again be replaces by spaces after saving.
Only when you then rename the page properly, the underscores will stay.

**Comment by bartkamphorst** [comment]
This is default behavior. However, we are looking at ways to change this.

**Comment by dometto** [comment]
This will be changed in `5.x` (see https://github.com/gollum/gollum-lib/pull/249).
