### ISSUE TITLE
Limit [[_TOC_]] depth

### ISSUE THREAD

**Issue by sarnobat** [gollum/gollum#1137]
I don't see a way to limit the table of contents depth. Can this be added, if it isn't already supported? (if it is, could it be documented?)

**Comment by dometto** [comment]
See #650. This feature is actually already in gollum-lib, but still needs to be documented in the wiki. Sorry about that.

**Comment by sarnobat** [comment]
Thanks. In answer to my question, one needs:

[[_TOC_|levels = 3]]

**Comment by rroller** [comment]
Updated the wiki with this info.

**Comment by bartkamphorst** [comment]
Thanks! 👍
