### ISSUE TITLE
pandoc support

### ISSUE THREAD

**Issue by somenxavier** [gollum/gollum#1138]
can you add `pandoc` in https://github.com/github/markup/blob/master/lib/github/markup/markdown.rb options? Is [this](http://mwolf.net/2014/04/29/adding-pandoc-to-gollum/) still valid?

Thanks,

**Comment by dometto** [comment]
I don't think pandoc will likely be added to github-markup, but anyway you should ask there and not here. The instructions you link to look like they could still work though. Feel free to add an entry to the wiki citing that article (or contact its author about that).

**Comment by somenxavier** [comment]
Just this: http://mwolf.net/2014/04/29/adding-pandoc-to-gollum/
