### ISSUE TITLE
Allow "Compare changes" in no-edit mode

### ISSUE THREAD

**Issue by astorije** [gollum/gollum#1140]
When `no-edit` is set, accessing a `/compare/:page` returns:

> Error
> Forbidden. This wiki is set to no-edit mode.

I don't have a lot of context here, but I don't see why these are tied together.
In particular, my team is starting to use Gollum but we want to disable edit mode to use a peer-review process on changes (therefore adding/editing a page would be made on the git repo itself). We still want to be able to see the history though.

It would be great to have an option, such as `--disallow-compare`, that would control this independently.

I can look to open a PR if you are OK with this idea.

**Comment by bartkamphorst** [comment]
I don't think we need an additional flag for that. I would be fine with allowing history viewing in no-edit mode, as long as the revert functionality is disabled. @dometto ?

**Comment by astorije** [comment]
> I would be fine with allowing history viewing in no-edit mode, as long as the revert functionality is disabled.

I am as happy with this suggestion as I would with the one I made :-)
The only reason why I mentioned an addition flag for this is that I didn't know the context why disabling compare views in no-edit mode at the time it was added. I can't think of any use case where this would be desirable, but if it was done, then maybe there were some.
Thanks for the answer!

**Comment by astorije** [comment]
Actually, is it possible that it was not intentional to remove compare view in no-edit mode, [here](https://github.com/gollum/gollum/pull/990/files#diff-5e2ad4cc36d2afcb0239af3d22d65073L31)?

**Comment by bartkamphorst** [comment]
Seems plausible.

**Comment by dometto** [comment]
I'm pretty sure this is just a bug. I think we can just whitelist the compare page.

**Comment by bartkamphorst** [comment]
@astorije If you have time, feel free to take a stab at a fix; we'd be happy to merge a PR.

**Comment by astorije** [comment]
Hi @bartkamphorst, it looked like an easy fix so I gave it a go in #1143 and it worked locally. I'm hoping this PR won't be a can of worms because of limited free time... :-)

Thanks for your feedback, @bartkamphorst and @dometto!
