### ISSUE TITLE
 How to start gollum with config file?

### ISSUE THREAD

**Issue by yuzhangbit** [gollum/gollum#1142]
Couldn't find any config.rb example to start gollum.

**Comment by rroller** [comment]
I have an example startup script that launches gollum with a config file here: http://ronnieroller.com/Gollum#create-your-config-rb

**Comment by yuzhangbit** [comment]
@rroller  Thank you very much!  It works.  By the way, do you know  how to customize mathJax configuration file to recognize single $  as inline math symbol in gollum?
