### ISSUE TITLE
Issue with redcarpet rendering table

### ISSUE THREAD

**Issue by ganesshkumar** [gollum/gollum#1147]
I am creating a docker container to use gollum. 

As mentioned in the [docs](https://github.com/gollum/gollum/wiki/Gollum-via-Docker), under the section `Creating the Dockerfile`, I used redcarpet to render markdown. 

**Packages in the docker container**

* Gollum 4.0.1
* Redcarpet 3.3.4
* org-ruby 0.9.12

But the table is not rendered properly and raw text was getting displayed. I tried the table with one `-` and three `---` format as it was mentioned in one of the issues but it didn't help.  I switched to `github-markdown` and things are working fine.

Can we update the wiki to use github-markdown or is there any other fix for this?

**Comment by dometto** [comment]
I'm not sure if I fully understand your question. If things work fine
with github-markdown, please use it. :) Gollum is meant to be flexible
with regards to the markdown rendering gems it uses.

**Comment by ganesshkumar** [comment]
My question was can we update the [doc](https://github.com/gollum/gollum/wiki/Gollum-via-Docker) to use github-markdown? So that others need not try out with different gems.

**Comment by dometto** [comment]
Ah, I see! Yes, that would be great. Thanks for taking the effort.
(Maybe you could add a short note to explain that one can package any of
the rendering gems supported by gollum, as explained in
https://github.com/gollum/gollum/#markups)

**Comment by ganesshkumar** [comment]
I have edited the wiki accordingly. Included the list of supported gems in the list below. Thanks for your help
