### ISSUE TITLE
Question: there is some way to view the full concatenated wiki?

### ISSUE THREAD

**Issue by vizcay** [gollum/gollum#1151]
Hi, I love this project.. using it for my small business internal wiki.

There is some way to see a full concatenated view of all the pages (I guess alphabetical ordered) just for printing purposes? Or something like that..

Thanks!

**Comment by thespacedoctor** [comment]
how about this macro -- just tested it in my wiki and it seems to work:

```ruby
module Gollum
  class Macro
    class ListAllPages < Gollum::Macro
      def render()
        
        base_path = @wiki.base_path
        thisPage = @page
        baseResults = ""
        directoryResults = ""

        parent = ::File.dirname(thisPage.path)
        regex = "\/([^\/]*?)$"
        baseRegex = Regexp.new(regex, "i")

        if @wiki.pages.size > 0
          thesePages = Hash.new
          @wiki.pages.map {|p|
            if baseRegex.match(p.url_path)
              matches = baseRegex.match(p.url_path).captures
              g1 = matches[0]
              g1 = g1.gsub '-', ' '
              g1 = g1.gsub '_', ' '
              thesePages[g1]="<li><a href=\"#{base_path}/#{p.url_path}\">#{g1}</a></li>"
            end
    }
        end
        if thesePages and thesePages.length
          thesePages=thesePages.sort_by { |title, link| title.downcase }
          result = thesePages.map{|k,v| "#{v}" }.join()
          if result and result.length > 3
              "<BR><div><strong>All Pages</strong><ul class=\"no-bullet\">#{result}</ul></div>"
          end
        end
      end
    end
  end
end
```

**Comment by bartkamphorst** [comment]
@vizcay Does this macro fit your needs?

**Comment by vizcay** [comment]
@bartkamphorst I'm sorry for the late reply, I was on a trip.. this week I will test it and give feedback.

Thank you!

**Comment by vizcay** [comment]
@bartkamphorst it works, but

* it only lists the titles, not the actual content
* it sorts alphabetically by page title, and doesnt take into account the directory structure, for example

definition.md
process_xxx/
  a_title.md

here a_title will appear before definition.

**Comment by dometto** [comment]
I'm closing this since it should be clear in which way to further develop the Macro. Unfortunately we can't help with the development of Macros, but you can share your custom Macros [in the wiki](https://github.com/gollum/gollum/wiki/Custom-macros), and continue the discussion in a gist.
