### ISSUE TITLE
Serve up favicon.ico if it exists

### ISSUE THREAD

**Issue by stevearm** [gollum/gollum#1157]
It'd be handy if gollum handled `GET /favicon.ico` specially so that, if `favicon.ico` exists in the wiki root, it serves it up, otherwise returns a `404`.

To do the same thing, I need to add a handler using `config.rb` then run gollum pointed to that config.

**Comment by stevearm** [comment]
Closing this because it already works how I'm asking it to work.

**Comment by stevearm** [comment]
Reopening this, since it's back to the old behaviour. See #1158 for info

**Comment by stevearm** [comment]
Closing this again for good. Gollum doesn't serve up uncommitted files. So just put a `favicon.ico` in the root, then *add and commit it*, then it'll work without any custom configs.

**Comment by alastairdb** [comment]
But if you add a favicon image then currently search stops working - https://github.com/gollum/rugged_adapter/issues/24 - at least when using the rugged adapter to handle utf8
