### ISSUE TITLE
Load local config.rb by default

### ISSUE THREAD

**Issue by stevearm** [gollum/gollum#1159]
It'd be nice if, when `--config` is not specified, gollum loaded `config.rb` if it exists in the root of the wiki. Something like this (in `bin/gollum:247`):

    if options[:config]
      # Load in options[:config]
    else if File.file?('config.rb')
      # Load in config.rb
    else
      # Don't load anything (the usual)
    end

I've never written ruby and don't have a local dev setup, so an actual pull request would be blind edits.

**Comment by bartkamphorst** [comment]
I personally like the explicitness in the way it is handled now.

**Comment by dometto** [comment]
As do I: I'm afraid much confusion would be caused by config files that one forgets are there. And using the command line switch seems like little effort.
