### ISSUE TITLE
_TOC_ not rendering properly in _Sidebar

### ISSUE THREAD

**Issue by brandubh** [gollum/gollum#1161]
Is that me or using the [[_TOC_]] tag in _Sidebar renders the toc of the sidebar file itself and not the related page toc? Is this by design? immo a TOC in a sidebar/header/footer should render the page toc.

**Comment by dplanella** [comment]
Not just you :) I've had the same issue, where I'd expect `[[_TOC_]]` in my `_Sidebar.md` file to render a TOC of the files it sits next to, which it doesn't. Neither does the `<<AllPages()>>` macro work as expected when added to `_Sidebar.md`: it does not list any pages.

**Comment by bartkamphorst** [comment]
I suspect this will be fixed with https://github.com/gollum/gollum-lib/pull/215 in gollum-lib master.

**Comment by dplanella** [comment]
Thanks for the update! Is there any ETA for the gollum-lib release that fixes this issue?

**Comment by rubykat** [comment]
This week I ran into this problem, so I installed the gollum-lib (and gollum) master which had the fix mentioned above, and while the <<AllPages()>> macro did work in the _Sidebar (unlike in the official release), the [[_TOC_]] still didn't work. So this bug isn't fixed yet, alas.

**Comment by polyzen** [comment]
@dplanella, the fix was included in release 4.2.2 which was Nov 18th.
https://github.com/gollum/gollum-lib/releases/tag/v4.2.2

@rubykat, perhaps you could try the release, if you haven't?

Haven't tried subpages yet; in the progress of migrating from DokuWiki. :)

**Comment by bogado** [comment]
This still not working on the latest release. I made it work by setting the parent_page to the current page.

**Comment by bogado** [comment]
Just added a [pull request ](https://github.com/gollum/gollum-lib/pull/232) with the fix.

**Comment by blaasvaer** [comment]
Well, this does still not work AT ALL, yet.

If I leave the _Sidebar.md with a content of only:

```
[[_TOC_]]
```

the sidebar complete disappears.

I HAVE to have 'some' other stuff in there as well. I decided to give it a header, like:

```
####Some Title
[[_TOC_]]
```

And now, this is what I get:

![screen shot 2017-10-03 at 12 56 35](https://user-images.githubusercontent.com/1193257/31121930-583a5786-a83a-11e7-9eec-4d1059b40153.png)

Not to useful in my book.

The only thing I found useful (actually putting page links in the sidebar) is this:
```
<<GlobalTOC("Table of Contents")>>
```

**Comment by dometto** [comment]
Should be fixed by https://github.com/gollum/gollum-lib/pull/283

**Comment by dometto** [comment]
May be a while before the fix is released.
