### ISSUE TITLE
Emojis not being rendered

### ISSUE THREAD

**Issue by dplanella** [gollum/gollum#1163]
After having set `:emoji => true` in the `config.rb` file, I tried to simply write :heart: (`:heart:`) in one of the wiki pages.

I'd expected the emoji to be rendered once I'd saved the page, but it simply shows me the text (`:heart:`). Are emojis supposed to work out of the box? Or is there some extra configuration to do after having set `emoji` to `true` in the config file?

**Comment by bjoernalbers** [comment]
Did you install gollum from source or from RubyGems?
The latter does not support emoji (yet) because it hasn't been updated in a while - v4.0.1 was released over a year ago.

@gollum Could you please provide a new release on RubyGems? Thanks

**Comment by dometto** [comment]
I take it the problem is the old release, which I'll fix ASAP. Otherwise please reopen.

**Comment by dplanella** [comment]
Sorry for the late reply, I'd not noticed the comment. Thanks @bjoernalbers. I did install from the gems indeed, which I thought was the recommended way of installation, as otherwise is a bit of a pain to keep track of all dependencies if installing gollum from source. Is the Ruby gem then not being updated?

@dometto, have you had the chance to update the gem? Thanks!

**Comment by dplanella** [comment]
Actually, I can confirm that the gem has been updated and emojicons now work. Thank you!
