### ISSUE TITLE
Running the Dockerfile listed in the wiki gives Gollum::InvalidGitRepositoryError at /

### ISSUE THREAD

**Issue by zfrenchee** [gollum/gollum#1165]
Followed the instructions in the [wiki article about dockerizing gollum](https://github.com/gollum/gollum/wiki/Gollum-via-Docker) and got this error: 

Gollum::InvalidGitRepositoryError
file: git_layer_grit.rb 
location: rescue in initialize 
line: 289

**Comment by zfrenchee** [comment]
I also don't see any mention of a file called git_layer_grit.rb in this repo.

**Comment by zfrenchee** [comment]
initialized an empty git repository in the volume and it works.

**Comment by lmqwudi** [comment]
what dose it mean in the volume
