### ISSUE TITLE
How do I use GitHub Style and Arbitrary Anchors

### ISSUE THREAD

**Issue by ajstadlin** [gollum/gollum#1166]
I figured out how to do the Gollum style TOC anchors as follows:

```
[Level 1](#level-1)
[Level 2](#level-1_level-2)
[Level 3](#level-1_level-2_level-3)

# Level 1
## Level 2
### Level 3
```

Question 1:  Is there a way to make the anchors behave like they do in GitHub markdown?

```
[Level 1](#level-1)
[Level 2](#level-2)
[Level 3](#level-3)

# Level 1
## Level 2
### Level 3
```

Question 2:  Is there a way to use the markdown syntax to create an arbitrary anchor Without creating a TOC entry?  

For example, I would like to navigate to the beginning of a specific text paragraph in my page that does not have a TOC entry associated with it.

**Comment by dometto** [comment]
> Question 1: Is there a way to make the anchors behave like they do in GitHub markdown?

Unfortunately not, no. The current anchor implementation is the result of a number of bugs: using GitHub style anchors, there are potential conflicts if you have e.g. multiple "level 2" anchors with the same title (`# Foo ## Level 2 # Bar ## Level 2`).

> Question 2: Is there a way to use the markdown syntax to create an arbitrary anchor Without creating a TOC entry?

Not as far as I know, although some markdown flavors may support it. That depends on the implementation though.
