### ISSUE TITLE
Gollum can't find config.rb with bare repositiory

### ISSUE THREAD

**Issue by orodbhen** [gollum/gollum#1167]
When I run Gollum from a bare repository with 

    gollum --bare --config config.rb

I get:

`````
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /wiki/config.rb (LoadError)
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/bundle/gems/gollum-4.0.1/bin/gollum:242:in `<top (required)>'
        from /usr/local/bundle/bin/gollum:22:in `load'
        from /usr/local/bundle/bin/gollum:22:in `<main>'
`````

I'm running gollum inside a Docker container with the repository mounted to the container at `/wiki`.

**Comment by dometto** [comment]
That's expected behavior -- config.rb must be a file on the filesystem, not just in the repo. (This is, of course, because config.rb needs to be loaded before we can process the repository.)

**Comment by orodbhen** [comment]
But doesn't config.rb have to be committed to the repo? How does that work if it's bare?

In any event,  I was able to get it working by changing it to config.ru and running it as a Rack app. Then it doesn't need to be in the repo at all.
