### ISSUE TITLE
Gollum and https

### ISSUE THREAD

**Issue by alledm** [gollum/gollum#1168]
Hello,

I configured Gollum behind `oauth2_proxy` (which acts as ssl terminator)

While Gollum works through links and pages, some actions (i.e. "edit") look for the `http` endpoint rather than `https`.

How can I fix it?

**Comment by lopopolo** [comment]
Install the Rack::SSL middleware and use it in your config.ru

**Comment by dometto** [comment]
Thanks for the proposed fix @lopopolo. Please let us know if it doesn't solve your issue @alledm, then I'll reopen.

**Comment by zeigerpuppy** [comment]
I am also trying to get Gollum to work behind an SSL proxy (apache2).
My site works apart from, saving edits in live mode (as the throws a mixed-content warning).  
It would be great to have a little more information of how to use the Rack::SSL option with Gollum.

**Comment by zeigerpuppy** [comment]
I tried installing Rack:SSL and then adding a `config.ru` file in the base directory of my wiki:

```
#!/usr/bin/env ruby
require 'rubygems'
require 'sinatra'
require 'json'
require 'gollum/app'
require 'openssl'

class Application < Sinatra::Base
  use Rack::SSL

  get '/' do
    'SSL FTW!'
  end
end
```

my gollum instance is started with the command:
```
gollum --host 127.0.0.1 --port 4567 --base-path wiki --live-preview
```

It doesn't look like th enew options are live though, because chromium still throws a mixed content error.

```
/wiki/Applications/Gollum-Wiki/Gollum-Wiki:1 GET https://git.server.net/wiki/Applications/Gollum-Wiki/Gollum-Wiki 401 (Unauthorized)
?page=Gollum-Wiki&path=Applications%2FGollum-Wiki:1 XMLHttpRequest cannot load https://git.server.net/wiki/Applications/Gollum-Wiki/Gollum-Wiki. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 401.
```

**Comment by lopopolo** [comment]
A config.ru is a file that specifies how to stitch together rack-compatible apps and middleware, including the gollum application. The config.ru isn't automatically used; you have to instruct your rack webserver to use it.

1. Your config.ru file needs to load the gollum application
2. Don't use the built in gollum command line as it does not expose the ability to use a custom config.ru
3. Use a rack-compatible server like thin

I'd suggest you [RTFM](https://github.com/gollum/gollum/wiki/Gollum-via-Rack).

**Comment by zeigerpuppy** [comment]
Thanks for the pointers. 

I found an even simpler way to do this with the proxy, by setting the option:

```
RequestHeader set X-Forwarded-Proto "https" env=HTTPS
```

in the apache2 reverse proxy.  The all requests are processed as HTTPS, works well, no more errors in browsers.
