### ISSUE TITLE
Managing Gollum from a parent repo

### ISSUE THREAD

**Issue by hudsonbuddy** [gollum/gollum#1171]
Hi all,

I have a personal project that is managed by git, and have gollum working locally. Problem is when I make a commit on the personal project repo it does not manage gollum. Thus when I deploy it, the route where gollum is mounted is served but there is an internal server error based on the fact that there is no presence of git.

Any work arounds?

**Comment by dometto** [comment]
I'm not sure what you are exactly trying to accomplish. If the idea is to bundle gollum with a rails app (as I suspect), you should mount gollum as a rack app (see https://github.com/gollum/gollum/wiki/Gollum-via-Rack and the relevant rails docs).

**Comment by hudsonbuddy** [comment]
Gollum works fine locally mounted as a rack app because of the local .git file. When I go through the process of deploying to a remote server, since the entire repo (of which the gollum directory is nested in) is managed by git, I can't track that .git directory (which gollum is entirely dependent on for functionality) I looked into submodules but I don't think that solves the problem
