### ISSUE TITLE
Bad wiki link

### ISSUE THREAD

**Issue by vivace-io** [gollum/gollum#1172]
Quick fix thing I noticed! I was going over the wiki documentation, specifically the [bit on setting it up with CAS](https://github.com/gollum/gollum/wiki/Gollum-via-Rack-and-CAS-SSO). 

The link to Jasig returns 404, so all it needs is to be updated!

Thanks!

**Comment by dometto** [comment]
The wiki is publically editable, so please feel free! :)

**Comment by dometto** [comment]
I'll take care of it now though.
