### ISSUE TITLE
Page list will brake for paths that have special characters for regexp.

### ISSUE THREAD

**Issue by bogado** [gollum/gollum#1179]
The page list processing will use the "path" as a direct source in a regular expression, This means that pages that have special characters like "+" for instance will not work correctly.

This might be a security threat, carefully made directory names might introduce exponential work to the service, [see here](http://www.rexegg.com/regex-explosive-quantifiers.html) or worse if there's any way to execute code from inside the regex (perl allows this for instance).

**Comment by bartkamphorst** [comment]
Fixed in master. Thanks @bogado !
