### ISSUE TITLE
Improve log message when git command fails

### ISSUE THREAD

**Issue by stevearm** [gollum/gollum#1181]
I'm on macOS, and running `/usr/local/bin/gollum /Users/stevearm/wiki` would work fine, but running those same lines through launchctl would produce a server with no pages (loading it goes to `/create/Home`).

I tracked it down to different paths. My shell prepends `/usr/local/bin` before everything else. I assume this let gollum to use `/usr/local/bin/git` (brew installed) when run from my shell. When run from launchctl it would fall to `/usr/bin/git` which fails because I don't have XCode installed.

None of this shows up in the logs that I could see. This whole path issue is out of scope of gollum, but is there any way to surface an error so this is more obvious why it kept thinking the repo was empty? I was spinning my wheels thinking it was a path issue for a while.

**Comment by bartkamphorst** [comment]
`gollum` only uses the system git binary with the `grit` adapter, which is outdated and will be replaced with the `rugged` adapter (which can already be used). Once the transition has been made from grit to rugged as the default adapter, your issue should be resolved, and a solution as you describe will be unnecessary. Given the other priorities we have I'm closing this issue.
