### ISSUE TITLE
plantUML doesn't work when gollum is run as a rack app

### ISSUE THREAD

**Issue by TakahashiNZ** [gollum/gollum#1183]
I am running Gollum as a docker image and I can get plantUML to work using the following command:
<pre>
docker run -d -p 80:80 -p 443:443 --link plantUML:plato -v /storage/wiki/:/root/wiki --name wiki genebarker/gollum --hsts plato --config config.rb
</pre>
However, when I run it as a rack app like so:<pre>
docker run -d -p 80:80 -p 443:443 --link plantUML:plato -v /storage/wiki/:/root/wiki -e RACK_APP=config.ru --name wiki genebarker/gollum --hsts plato --config config.rb</pre>

Then I just get the "Sorry, unable to render PlantUML diagram at this time" message 

my config.ru is very simple, and it works as expected:
<pre>
#!/usr/bin/env ruby
#--------------------------------------------------------------------
# - example custom rack for the Gollum wiki engine
# - file should be placed in wiki root
# - RACK_APP environment variable should be set to the filename
# - entrypoint.sh script will run this app using:
#   $ rackup $RACK_APP -p 4567
#--------------------------------------------------------------------
require 'rubygems'
require 'gollum/app'

gollum_path = File.expand_path(File.dirname(__FILE__))
wiki_options = {
    :live_preview => false,
    :allow_editing => true,
    :allow_uploads => true,
    :universal_toc => false,
}

users = {'user1' => 'password1',
         'user2' => 'password2'}

use Rack::Auth::Basic, 'realm' do |username, password|
    users.key?(username) && users[username] == password
    Precious::App.set(:loggedInUser, username)
    if users.key?(username) && users[username] == password
        Precious::App.set(:loggedInUser, username)
    end
end

Precious::App.set(:gollum_path, gollum_path)
Precious::App.set(:default_markup, :markdown)
Precious::App.set(:wiki_options, wiki_options)
run Precious::App

#set author
class Precious::App
   before do
       session['gollum.author'] = {
           :name => "%s" % settings.loggedInUser,
           :email => "%s@example.com" % settings.loggedInUser,
       }
    end
end
</pre>

I'm fairly new at this so there is probably something obvious I am missing. I'm not sure if the problem is plantUML + running as a rack app, or if the problem is also related to the fact I'm running gollum in a docker image.

Thanks in advance for your time and considerations.

**Comment by bartkamphorst** [comment]
I'm sorry, but we do not have the capacity to answer these kinds of questions in the issue tracker. Please ask on stackoverflow instead. I hope you manage to resolve your issue!

**Comment by TakahashiNZ** [comment]
I found my problem, when running gollum as a rack app you can't use --config to specify the plantuml URL,  you need to include the config stub in the rack app config.

I have found a related problem though, Gollum does not work with plantUML when the plantUML webserver is set up for https only. I think the test Gollum uses to determine if the server is there fails when the server is https.

Is that an appropriate bug?

**Comment by dometto** [comment]
> Gollum does not work with plantUML when the plantUML webserver is set up for https only. ... Is that an appropriate bug?

Yes, but see https://github.com/gollum/gollum-lib/pull/213. I haven't looked at it for a while but don't quite see why my attempted fix there shouldn't work (as the feedback in the PR states). Any help appreciated.
