### ISSUE TITLE
Broken anchor link in the Known Limitations wiki page

### ISSUE THREAD

**Issue by grantwinney** [gollum/gollum#1184]
There's a broken anchor link in the [Known limitations](https://github.com/gollum/gollum/wiki/Known-limitations) wiki page.

I would've fixed it myself and created a PR, but I'm not sure if it should link to the "[Syntax highlighted code blocks](https://github.com/gollum/gollum/wiki#user-content-syntax-highlighted-code-blocks)" section or the "[Include tag](https://github.com/gollum/gollum/wiki#user-content-include-tag)" section of the main wiki page.

**Comment by dometto** [comment]
Thanks, fixed.
