### ISSUE TITLE
GitHub/Gollum common way to link to internal pages

### ISSUE THREAD

**Issue by mrev11** [gollum/gollum#1186]
I would like to turn my software repository into a wiki _both_ in GitHub and 
Gollum, but I cannot find a common acceptable solution to link internal pages.

The following code works in GitHub, but Gollum wants to download the raw md
file instead of bringing up the page. 

    [Some text](some_other_wiki_page.md) 

On the other side, this code (without file extension) works in Gollum, 
but fails in GitHub.

    [Some text](some_other_wiki_page) 

I have a poor solution: for each md file doing

    ln  -s  some_wiki_page.md  some_wiki_page.md.md 

Is there a better idea?

**Comment by dometto** [comment]
In the [gollum wiki](https://github.com/gollum/gollum/wiki), internal links seem to work without the `.md` extension. Perhaps look at the support pages for github wikis?

**Comment by mrev11** [comment]
Exactly:

Gollum waits link URLs of internal pages _without_ the `.md` extension.  
GutHub waits link URLs _with_ the `.md` extension.

So there is no simple common solution.

**Comment by dometto** [comment]
I meant: in the gollum wiki on github, which is what I linked to. Github wikis work without file extension, too.

**Comment by mrev11** [comment]
As I can see gollum wiki on github is another (third) incompatible version.

1. I think, github manages URLs corectly (first).

2. Local gollum do not support md exension. What do you do if you have a README _and_ a README.md file, and you want to refer to the simple README?

3. Hithub wiki gollum do not support directory struture.

**Comment by polyzen** [comment]
> As I can see Gollum wiki on GitHub is only another (third) incompatible version.
>
>   1. I think, GitHub manages URLs correctly.

I seem to have missed something here.

2. Sure it does. Why would you have 2 readme's?

3. See Gollum's `--collapse-tree` option.m

**Comment by dometto** [comment]
> How do you link to a "README" file if you have also a "README.md"?

This seems to be the source of the confusion. In Gollum, pages need to have one of the supported file extensions (e.g. `.md`), but since the wiki is agnostic about file formats, you *don't* use the file extension in links. This means you can only have one `README.ext` page (where `.ext` is a supported file extension).

I actually don't know what happens when you have both, say, a `README.md` and `README.mediawiki` -- I take it the latter will just be ignored. However, the scheme of linking to `README` *without* a file extension works on github, too. So as long as you do not have multiple `README` files, this should work.

Hope that helps!

**Comment by mrev11** [comment]
Thank you for the answer. I have tried and now I can use links both in  GitHub and Gollum. But the key is the compatibility. If there would be a common compatible syntax of links (and generally compatible syntax of markdown), then it would make the GitHub/Gollum pair  to be more useful.

I have a GitHub project with a number of md files, which are referenced by each other and are linked from the README.md. I find it to be useful that the documents can be browsed starting from the README.md.

I would like to edit the above md files, in my local Git repository, while I can see and verify them in my local Gollum and browser. When the documents are ready to publish, I would like to push the changes from my local repo to the GitHub. But I cannot do that because of the incompatibility of the syntax of links. The situation is the same with the GitHubs wiki.

As i had written earlier, there is a way to have the same links in local Gollum and GitHub by making a page.md.md symlink to each page.md.  But it is a topic of planning, so I do not want to push that.

**Comment by sabtechco** [comment]
I seem to have missed something here.
[ثبت شرکت](https://payeshsabt.com)
