### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by cerdiogenes** [gollum/gollum#1193]
I can't upgrade do Rails 5, getting the following after `bundle update`:

```bash
Resolving dependencies....
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.0.1, which depends on
      actionpack (= 5.0.0.1) was resolved to 5.0.0.1, which depends on
        rack (~> 2.0)

    gollum (~> 4.0) was resolved to 4.0.0, which depends on
      sinatra (>= 1.4.4, ~> 1.4) was resolved to 1.4.4, which depends on
        rack (~> 1.4)
```

Is there any work to make it compatible with `rack (~> 2.0)`?

**Comment by dometto** [comment]
This requires updating sinatra. It looks like they're in the process of releasing a `v2.0`: https://github.com/sinatra/sinatra/releases
See https://github.com/gollum/gollum/pull/1200 for an attempt to upgrade. We'll have to drop support for ruby `< 2.2.2` if we want sinatra `v2.x`.

**Comment by bartkamphorst** [comment]
I was thinking of doing that anyway for v.5.x, so that's okay with me.

**Comment by straight-shoota** [comment]
Any updates on this? Gollum seems to work with Sinatra 2.0 without issues, but the version is limited to `~> 1.4` in gemspec.

**Comment by bartkamphorst** [comment]
Sorry, no update as of yet. Development has slowed to a halt at the moment but we welcome help moving the 5.x branch forward. So if you've tested the basic functionality with Sinatra 2.0 and the test suite passes, please feel free to open a PR against the 5.x branch removing the 1.4 limitation in the gemspec.

**Comment by bartkamphorst** [comment]
@straight-shoota The `5.x` branch now uses Sinatra 2.0.
