### ISSUE TITLE
no-edit mode prevents comparing versions

### ISSUE THREAD

**Issue by christianrondeau** [gollum/gollum#1195]
I'm running Gollum 4.0.1 on Ubuntu 16.04.2 LTS with `--no-edit` mode.

When I select a page in the web browser, select `History`, choose two versions and select `Compare Revisions`, I get the message: 

    Error
    Forbidden. This wiki is set to no-edit mode.

I would either expect for comparing revisions to work in `--no-edit` mode, OR not to have the `Compare Revisions` option and checkboxes (I obviously prefer the former, but if there is good reasons not to allow it, then the option should not be available).

**Comment by bartkamphorst** [comment]
I recall seeing this issue before and having seen a resolution to it, but I'm not entirely sure. @dometto ?

**Comment by dometto** [comment]
Yes, this was fixed in https://github.com/gollum/gollum/commit/0675844d97a14a788d81a9b99efa373c339dbfec

@christianrondeau, I think the problem was just that this patch was not yet released. I've just released `v4.1.0`. That should fix this issue with `--no-edit` at least.

**Comment by christianrondeau** [comment]
Amazing! Thanks @dometto :)
