### ISSUE TITLE
1x1 pixel "delete" button in Files view in `no-edit` mode

### ISSUE THREAD

**Issue by christianrondeau** [gollum/gollum#1196]
I'm running Gollum 4.0.1 on Ubuntu 16.04.2 LTS with `--no-edit` mode.

When I select the `Files` view, there are one-pixels buttons that attempt to delete the page (which obviously won't work, since Gollum runs in `--no-edit` mode)

The HTML part that should not be rendered (or optionally hidden with a no-edit css):

    <form method="POST" action="/deleteFile/mypage" onsubmit="return confirm('Do you really want to delete the file mypage?');"><button type="submit" name="delete" value="true"></button></form>

**Comment by bartkamphorst** [comment]
I can confirm this behavior on `5.x`.

**Comment by bartkamphorst** [comment]
Unfortunately the HTML for this is generated in gollum-lib for some reason...

**Comment by bartkamphorst** [comment]
This has been fixed in the `5.x` branch; the delete action is omitted from the HTML when run with `--no-edit`.
