### ISSUE TITLE
Message line hardcoded to Markdown

### ISSUE THREAD

**Issue by ellipticview** [gollum/gollum#1203]
When creating an Asciidoc page, the status line says:
```
Created pagename (markdown)
```
The issue seems to be on line 82 of livepreview.js.

**Comment by bartkamphorst** [comment]
The easiest fix is for that status line to be agnostic with regard to the syntax of the created page. @ellipticview Would you be willing to submit a PR in that direction?

**Comment by bartkamphorst** [comment]
@ellipticview The live preview function only works for markdown. Without live preview, with the regular editor, the commit message for create works like it is supposed to:
![screen shot 2017-03-26 at 9 27 26 pm](https://cloud.githubusercontent.com/assets/571173/24334480/23979bb6-126b-11e7-8828-8ee2b11d424a.png)
