### ISSUE TITLE
Dependency Issues on Ubuntu 16.04

### ISSUE THREAD

**Issue by dev00** [gollum/gollum#1205]
I installed gollum like recommended here:
https://github.com/gollum/gollum/wiki/Installation#ubuntu-150415101604

since I'm using ubuntu 16.04 LTS.

Gollum will then fail when trying to start it and complain about a missing dependency.
```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- linguist (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/github-markup-1.4.6/lib/github/markups.rb:4:in `<module:Markup>'
	from /var/lib/gems/2.3.0/gems/github-markup-1.4.6/lib/github/markup.rb:94:in `instance_eval'
	from /var/lib/gems/2.3.0/gems/github-markup-1.4.6/lib/github/markup.rb:94:in `<module:Markup>'
	from /var/lib/gems/2.3.0/gems/github-markup-1.4.6/lib/github/markup.rb:18:in `<module:GitHub>'
	from /var/lib/gems/2.3.0/gems/github-markup-1.4.6/lib/github/markup.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/gollum-4.1.0/lib/gollum.rb:8:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/gollum-4.1.0/bin/gollum:7:in `<top (required)>'
	from /usr/local/bin/gollum:23:in `load'
	from /usr/local/bin/gollum:23:in `<main>'
```
Trying to install linguist manually will result in a fail since linguist requires ruby 2.4 Installing ruby 2.4 via RVM and installing gollum after that will result in other errors, which I unfortunately didn't write down.

Did I miss something?

**Comment by leonboxboat** [comment]
Just pure coincidence I just submitted a ticket for this too. Debian, Ubuntu and Docker instructions all fail:

https://github.com/gollum/gollum/issues/1206

**Comment by dummys** [comment]
same here under Arch linux ...

**Comment by dometto** [comment]
The linguist issue is also causing Travis tests to fail: https://travis-ci.org/gollum/gollum/jobs/212997919

May have to do with recent new releases of linguist. I'll investigate.

**Comment by dometto** [comment]
`github-markup` has been updated so that it doesn't depend on `linguist` anymore

**Comment by bartkamphorst** [comment]
👍

**Comment by dummys** [comment]
hi, keep getting this: gems/github-markup-1.6.0/lib/github/markup/implementation.rb:11:in `block in initialize': uninitialized constant Linguist::Language (NameError)
