### ISSUE TITLE
Pages with accents (e.g. "Employés") redirect to create  even though the file exists

### ISSUE THREAD

**Issue by christianrondeau** [gollum/gollum#1209]
After updating to Gollum 4.0.1 (I did not track dependencies not the original version I updated from, sorry about that), pages with accents in Git will not be seen as existing in Gollum.

To reproduce, create a page in Git called "Employés.md" and try to access it with `http://localhost/Employés`.

It will redirect you to `http://mcagit.domain.local/create/Employés` even though the page exists.

This was after a recent update, but unfortunately, I cannot say exactly from which update (and I won't be able to do a bisect myself, sorry)

Let me know if you have any questions!

**Comment by dometto** [comment]
This is also still present in `v4.1.0`. In fact, trying to create a page while a UTF-8 filename is present in the tree triggers an `Encoding::Compatibility` error. @bartkamphorst, do you know if this is an old issue or a regression?

**Comment by bartkamphorst** [comment]
This has been resolved in the `5.x` branch and will be available with the release of `5.x`.
