### ISSUE TITLE
gollum gem depends on cmake

### ISSUE THREAD

**Issue by matt-wallis** [gollum/gollum#1210]
On Ubuntu 16.04, following instructions at https://github.com/gollum/gollum/wiki/Installation#ubuntu-150415101604. Raising this issue to suggest a minor improvement to the documentation.
```
$ sudo gem install gollum
Building native extensions.  This could take a while...
ERROR:  Error installing gollum:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/rugged-0.25.1.1/ext/rugged
/usr/bin/ruby2.3 -r ./siteconf20170324-19072-7koek8.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... no
ERROR: CMake is required to build Rugged.
```
easily fixed:
```
sudo apt-get install cmake
```
This issue can be fixed by adding `cmake` to the list of things to install with `apt-get` prior to installing the gollum gem.

**Comment by dometto** [comment]
Thanks for pointing this out! The wiki is publically editable. Please feel
free to make the change and close the issue. :)

**Comment by matt-wallis** [comment]
@dometto said:
> The wiki is publically editable. Please feel free to make the change and close the issue. :)
Done!

**Comment by bartkamphorst** [comment]
Thanks! 👍

**Comment by lamegaton** [comment]
You may also need to run `sudo apt-get install pkg-config` after `sudo apt-get install cmake`
