### ISSUE TITLE
Sidebar display broken in versioned view

### ISSUE THREAD

**Issue by dsanader** [gollum/gollum#1226]
Hello,

When I browse pages coming from the "Latest Changes" menu, or when I append a /sha1 at the end of a page URL, it seems like `bar_side` is not set properly or to the default value, which breaks the CSS.

I've notice this difference between the two views.
```diff
-<div class=" has-sidebar has-bar">
+<div class=" has-sidebar has-rightbar">
```
Which in turn led to the [page.mustache](https://github.com/gollum/gollum/blob/master/lib/gollum/templates/page.mustache#L52) file and the `bar_side` variable.

This is happening with a 4.1.0 gollum.

Regards.

**Comment by dometto** [comment]
Thanks for the report, just fixed in `master`.
