### ISSUE TITLE
Dependencies problem with gemojione and gollum-lib

### ISSUE THREAD

**Issue by waltharius** [gollum/gollum#1227]
When trying to install gollum on Centos 7 I had errors:

` gem install gollum
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: gollum requires gemojione (~> 2); gollum-lib requires gemojione (~> 3.2)`

Don't know much about ruby, so can't solve this issue alone.

**Comment by dometto** [comment]
*sigh* somehow the `gemojione` dependencies for `gollum` and `gollum-lib` managed to diverge. Sorry, I'll cut a new release tomorrow which should fix this.

**Comment by fliiiix** [comment]
Cool just found that this also affects the FreeBSD port, but since you cut a new release today I will wait for this and then update the port for FreeBSD.

**Comment by fliiiix** [comment]
Is there any ETA?

**Comment by waltharius** [comment]
When can we expect this fix?

**Comment by fliiiix** [comment]
thanks for your work @dometto ❤️

**Comment by dometto** [comment]
Sorry for the wait, I'm waiting for the Travis build to pass and will release the new gem then.

**Comment by bartkamphorst** [comment]
Thanks @dometto !
