### ISSUE TITLE
Uniform layout

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1228]
Currently, the fileview has a completely different layout than other pages. In addition, the navigation buttons are only sporadically included on the page.

**Comment by dometto** [comment]
Would be great to fix this. Perhaps we can first move the fileview to gollum as recently proposed?

**Comment by bartkamphorst** [comment]
Yes, that would be preferable.

**Comment by dometto** [comment]
For anyone interested reading this: we would very much welcome help from someone proficient in CSS and styling. :)
