### ISSUE TITLE
gem install gollum gives me error bits/c++config.h not found in Mac OS Sierra

### ISSUE THREAD

**Issue by giper45** [gollum/gollum#1232]
Hi , maybe a simple issue, but I'm not able to understand how to resolve it, because I' m not practical about gem installations. When I try to give 
```
sudo gem install charlock_holmes -- --with-icu-dir=/opt/local/lib/icu --with-opt-include=/opt/local/include/ --with-opt-lib=/opt/local/lib/
``` 
or
```sudo gem install gollum ``` 
it gives me the  following error : 
```
compiling transliterator.cpp
In file included from transliterator.cpp:4:0:
/usr/local/include/c++/5.1.0/string:38:28: fatal error: bits/c++config.h: No such file or directory
compilation terminated.

``` 

Maybe some flag in order to set the link  to libraries  ? 
Mac OS Sierra version 10.12 , 
here  the gcc version (Xcode installed) : 
``` 
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Thanks in advance !

**Comment by bartkamphorst** [comment]
@giper45 I apologize, but we do not have the resources to troubleshoot installation issues that are clearly not specific to gollum. I recommend asking your question on StackOverfow instead.
