### ISSUE TITLE
Spaces don't work in anchor links in MediaWiki markup

### ISSUE THREAD

**Issue by DKroot** [gollum/gollum#1237]
In MediaWiki markup I can write anchor links like this: `[[#Recommended Tools]]`. This, however, does not work on GitHub even after including page name, e.g. `[[Database Tools|#Recommended Tools]]`.

The spaces have to be replaced by underscores: e.g. `[[Database Tools|#Recommended_Tools]]` as a workaround. See also issue #1236.

**Comment by dometto** [comment]
Whitespace in links will work in `v5.0`
