### ISSUE TITLE
Linking to audio and video files

### ISSUE THREAD

**Issue by atrost** [gollum/gollum#1239]
Is there a way to insert mp3/mp4 files with Gollum Wiki? Help documentation systems and also many wiki based systems often have the ability to let content authors to embed tutorial material as video. It seems as though it is not currently supported as an attempt to upload a mp4 file with Gollum simply generates a markup for the image tag and not video. If video is not currently supported, are there any plans to add such feature in the future?

**Comment by atrost** [comment]
Thanks! As a prove of concept, I was able to embed mp4 video onto a Gollum Wiki page using a Gollum Macro. I will plan to add this in a pull request.

**Comment by atrost** [comment]
Just opened a pull request. Thanks.

**Comment by bartkamphorst** [comment]
Thanks @atrost for the PR. I look forward to having this functionality in gollum. 👍

**Comment by dometto** [comment]
Looks like this was resolved in https://github.com/gollum/gollum-lib/pull/277/files, except we may also want an `Audio` Macro that is modeled on the exact same idea. @atrost? :)

**Comment by dometto** [comment]
@atrost sorry about that, and for the long wait. I've dealt with these issues on Travis CI (I think) by adding `unicode_utils` to the development dependencies in the `gollum-lib` gemspec. Probably in your case you had the gems installed, but they weren't part of the `bundle`. Try with the new (alpha) release of `gollum-lib 5.x`, or by `git pull`ing the updated version of `gollum-lib` and let me know if you can get the Travis tests to pass on the audio-macro now.

**Comment by dometto** [comment]
This will be implemented in `v5.x` thanks to @atrost in https://github.com/gollum/gollum-lib/pull/297
