### ISSUE TITLE
help, ubuntu 16.04 install gollum error

### ISSUE THREAD

**Issue by liangrengongzuoshi** [gollum/gollum#1240]
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': /var/lib/gems/2.3.0/gems/posix-spawn-0.3.13/lib/posix_spawn_ext.so: undefined symbol: rb_fix2int - /var/lib/gems/2.3.0/gems/posix-spawn-0.3.13/lib/posix_spawn_ext.so (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/posix-spawn-0.3.13/lib/posix/spawn.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/posix-spawn-0.3.13/lib/posix-spawn.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/gitlab-grit-2.8.1/lib/grit/git.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/gitlab-grit-2.8.1/lib/grit.rb:34:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter/git_layer_grit.rb:3:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/gollum-lib-4.2.5/lib/gollum-lib.rb:13:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/gollum-4.1.1/lib/gollum/app.rb:4:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/gollum-4.1.1/bin/gollum:242:in `<top (required)>'
        from /usr/local/bin/gollum:23:in `load'
        from /usr/local/bin/gollum:23:in `<main>'

**Comment by dometto** [comment]
Looks like the posix-spawn C-extensions failed to compile. Make sure `gem install posix-spawn` succeeds before attempting to run gollum. Possibly you haven't got the right build tools installed. Unfortunately, we cannot provide detailed installation help as it would cost too much time. If you can't get posix-spawn to install properly, ask around on stackoverflow, for example. If the list of required packages on the gollum Installation wiki page needs updating, please be so kind as to let us know (or better yet, update it yourself).

**Comment by liangrengongzuoshi** [comment]
yes，you are right，the posix-spawn has problem，thanks

Checking gems...

posix-spawn-0.3.13.gem has 5 problems
  ext/.RUBYARCHDIR.time:
    Extra file
  ext/Makefile:
    Extra file
  ext/posix-spawn.o:
    Extra file
  ext/posix_spawn_ext.so:
    Extra file
  lib/posix_spawn_ext.so:
    Extra file
