### ISSUE TITLE
Breadcrumbs (All pages) navigation doesn't work when Gollum runs inside a Rails app

### ISSUE THREAD

**Issue by atrost** [gollum/gollum#1241]
In the All Pages view, clicking on a directory that has a child directory should update the breadcrumbs trail control and take the user to the next location within a page's hierarchical structure, however, this doesn't work when Gollum is integrated into a Rails application. One of the incentives to integrating Gollum into a Rails application is that you can leverage a Rails' authentication OAuth2/Device/* and any additional custom authentication policies that an application might already have in place to also authenticate Gollum Wiki users (eliminates the need for omnigollum and so forth). Authentication and most of the Gollum's common functionally seems to be working fine except the breadcrumbs. Wandering if anyone hit the same issues before.

**Comment by atrost** [comment]
Details of the environment:
OS X 10.11.4
Rails version: 2.1.5
Ruby: 2.3.3
gollum (4.0.1)
gollum-grit_adapter (1.0.1)
gollum-lib (4.2.5)

**Comment by dometto** [comment]
Please try opening a new PR, as I explained in #1242.

**Comment by dometto** [comment]
@atrost is this still an issue?

**Comment by dometto** [comment]
I think this was an artifact of using the `extract_path` helper in the `/pages` route. In 5.x we've refactored, and the Pages view actually assumes there *isn't* a trailing slash, so I'm gonna close this. @atrost if you keep experiencing the problem with gollum 5.x please reopen this

**Comment by atrost** [comment]
@dometto Ok, that sound reasonable to me. We have been using Gollum from a forked version for a while with the fix I proposed originally and it has been working great for us so far. When we ready to update to v5 we will of course retest it.
