### ISSUE TITLE
Use GitHub's Primer.css

### ISSUE THREAD

**Issue by thomaskuntzz** [gollum/gollum#1243]
I'm surprised to see that gollum doesn't use [primer](http://primercss.io/), GitHub's own frontend framework. Why is it this way? Would it be ok to use Primer or is there a good reason not to do so?

I'd be interested in improving gollum's frontend, which doesn't look really pretty right now (out of the box at least)... And by the way that's surprising when we compare that to how neat and well integrated it is on github.com.

**Comment by bartkamphorst** [comment]
I don't think there is any reason why primer couldn't be used, and we would very much welcome your help to fix up gollum's default frontend!

**Comment by thomaskuntzz** [comment]
Great! I'd love to work on this a bit in my spare time.

Sadly, I don't know anything about ruby / sinatra and about how gollum works so I might have a really hard time figuring it all out by myself... How could I get some help without polluting any issue thread?

Thanks!

**Comment by dometto** [comment]
Thanks for your interest! Any help with the frontend is very welcome. We're currently working on a major new release (see the 5.x branch), so this could be part of that.

I think work on the frontend would have to start with #917, which is an attempt to convert gollum's css to SASS. I think most work there has already been done, and we're basically waiting to decide on as SASS preprocessor. But maybe that's a good place to start? You could start a new PR based on #917 since it's very old by now, and we could discuss things there. Or if you'd prefer to start somewhere else, open a fresh issue/PR and we'd be more than happy to talk you through the Ruby/Sinatra stuff!

**Comment by thomaskuntzz** [comment]
Okay, great!

I think it would be good if #1097 could be merged, so that we have a base with SASS and then we can iterate and improve on that more easily. Is that doable right now? :slightly_smiling_face:

**Comment by thomaskuntzz** [comment]
And I have one question: How can I work on the fontend without having to rebuild form source for every sigle change I make? :sweat_smile:

**Comment by thomaskuntzz** [comment]
Here is an idea of what the 'new page' page would look like: https://codepen.io/thomaskuntzz/project/full/XWNGMj/

**Comment by thomaskuntzz** [comment]
I could start making changes to the front-end but I would like to avoid making changes in CSS that I'd later have to convert in SASS. Should I start making changes on the [css-to-sass](https://github.com/gollum/gollum/tree/css-to-sass) branch or first wait for it to be merged?

Thanks in advance for your answer!

**Comment by thomaskuntzz** [comment]
@dometto ping

**Comment by bartkamphorst** [comment]
Ideally, we'd get SASS working on the 5.x. branch. The latest idea was to use the [SASS rack plugin](http://sass-lang.com/documentation/Sass/Plugin/Rack.html). Any experience?

**Comment by dometto** [comment]
@thomaskuntzz, perhaps you can weigh in on the best SASS processor in the relevant PR. The question is whether we need anything more than SASS (uglification, CoffeeScript, etc.), as the rack plugin only provides SASS.

**Comment by dometto** [comment]
One more thing: note that there has been a major change to part of the frontend in the 5.x branch, namely to the editor, which is now based on ACE (so we don't have to develop and maintain our own). That may have some impact on your efforts.

And the design preview for the new page page looks really nice! Thanks for chipping in.

**Comment by thomaskuntzz** [comment]
@bartkamphorst All the work that's been done on SASS is in the css-to-sass branch right now, isn't it? Then how can we work on SASS in 5.x without merging css-to-sass into it?

**Comment by dometto** [comment]
You're right, we have to merge it into `5.x`. I've changed the base branch for that PR. If we make a call on what asset preprocessor to use, I think it could be merged right away. @bartkamphorst, what are your thoughts on the need for minification? See #1097.

**Comment by thomaskuntzz** [comment]
I just saw that the SASS rack plug-in can output minified CSS with the appropriate option. So maybe we can get away with just using the rack plug-in, it's the simplest and I think we'll be just fine with it.

See http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

**Comment by bartkamphorst** [comment]
I think that `:compact` is a good compromise between speed and readability.

**Comment by bartkamphorst** [comment]
Merging the branch into `5.x` is probably better done by hand, but yes, I think that's the direction we should move in.

**Comment by thomaskuntzz** [comment]
Well, I think we don't care about the CSS output because the work is on the SASS files anyway and we generate CSS just because it has to be served to browsers, which need CSS. Unless you want someone to be able to read the code in their browser, but now they have features to make readable minified CSS code by automatically indenting it.

**Comment by thomaskuntzz** [comment]
@bartkamphorst What do you mean by "done by hand", and why would it be better this way?

**Comment by bartkamphorst** [comment]
> now they have features to make readable minified CSS code by automatically indenting it.

I wasn't aware of this. 👍 In that case, `:compressed` is fine as well.

**Comment by bartkamphorst** [comment]
> What do you mean by "done by hand", and why would it be better this way?

Because there's 27 commits in that branch, and there are a number of merge conflicts that prohibit automatic merging. I just think it would be cleaner (and probably faster) to reapply the changes manually.

**Comment by thomaskuntzz** [comment]
Okay, can you take care of this? 🙂

**Comment by bartkamphorst** [comment]
The buttons are conditionally set to `disabled` depending on the language definition (for example, markdown will have different markup buttons than asciidoc). Not sure about the `collapsibleInputs()` call.

**Comment by dometto** [comment]
I'm working on merging css-to-sass into 5.x. As @bartkamphorst suggested I may end up just reapplying the changes manually. For now I'm still trying to get the rack-sass plugin to cooperate. :)

**Comment by bartkamphorst** [comment]
👍

**Comment by thomaskuntzz** [comment]
It looks like the buttons aren't set to `disabled` anymore on the 5.x branch. Looks like a bug, don't know where it comes from... And by the way, half of the markup languages available are grayed out in the editor in the 5.x branch. Is it normal?

**Comment by bartkamphorst** [comment]
> It looks like the buttons aren't set to disabled anymore on the 5.x branch. Looks like a bug

I noticed that too. Yes, I think it's a bug.

> And by the way, half of the markup languages available are grayed out in the editor in the 5.x branch. Is it normal?

Yes, that signals that you haven't installed the right gems for those markup languages.

**Comment by thomaskuntzz** [comment]
Okay,  thanks! 👍

**Comment by thomaskuntzz** [comment]
Would it be any way to load the editor.css stylesheet only when the page viewed is the editor?

**Comment by dometto** [comment]
Stylesheets are loaded in the `layout` template. I guess we could remove `editor.css` from there and add it in the editor template. That would mean the stylesheet is loaded halfway through the page's HTML though. Not sure if that's a definite no-no, but it's not very pretty. What would be the main advantage?

**Comment by thomaskuntzz** [comment]
Okay, nevermind, I'll do without.

Are okay with using Flexbox? Just wanted to make sure...

**Comment by snewell92** [comment]
@thomaskuntzz Do eet, flexbox affords the stylings much more freedom. Maintainability++ and it's easier to reason about how the layout is, generally less wrapping divs.

It's really up to @dometto et. al. but I, for one, vote for flexbox!

**Comment by bartkamphorst** [comment]
Hadn't heard of flexbox to be honest, but it looks very useful. So, @thomaskuntzz , go for it!

**Comment by thomaskuntzz** [comment]
Okay, you can see what I've already done here: https://github.com/thomaskuntzz/gollum/tree/5.x
It's going on quite slowly because I don't have tons of free time to dedicate to it... I've worked only on the editor right now and the keyboard shortcuts don't work anymore and I don't know why...

**Comment by dometto** [comment]
Keep up the good work, @thomaskuntzz! We're also going a bit slower with the `5.x` development due to busy times at work. If you need help/feedback on the editor, @ProgramFan might be of service.

**Comment by ProgramFan** [comment]
We switch to the Ace editor in 5.x so the original keyboard shortcuts are abandoned. I added back `Ctrl+S` but other shortcuts are missing.

It would be nice if we add back all original keyboard shortcuts in the new editor, and it is pretty easy to do it, by adding something like  https://github.com/gollum/gollum/blob/5.x/lib/gollum/public/gollum/javascript/editor/gollum.editor.js#L79 in the same javascript file. Any help is welcome. 👍

**Comment by dometto** [comment]
@thomaskuntzz I've been away for a while and wasn't able to work on gollum. Can you update me on the current situation regarding the GUI?

**Comment by thomaskuntzz** [comment]
@dometto The same for me, so on my side nothing happened, and it will probably be so until at least September...

**Comment by bartkamphorst** [comment]
@thomaskuntzz I realize it's been over a year, but would you still be interested in working towards a PR for gollum that integrates Primer.css?

**Comment by bartkamphorst** [comment]
@thomaskuntzz All good! Good luck with your studies!

**Comment by thomaskuntzz** [comment]
Thanks! 😊

**Comment by dometto** [comment]
Anyone following this thread: [work on gollum `v5.0`](https://github.com/gollum/gollum/wiki/5.0-release-notes) is coming along nicely, and we'd really like to include a revamped and more maintainable user interface. Support for `sass` and asset helpers has been merged into the `5.x` branch, so the task should not be too difficult -- but @bartkamphorst and I lack the knowledge of CSS and a knack for interface design. Besides, we're busy working on improving other parts of gollum. If you know anyone who would be interested in contributing to this, (based on @thomaskuntzz's great start), please point them here! 

/cc @sunny: if you know anyone who could help out with this, please let us know :)

**Comment by sunny** [comment]
Sure thing! Can't think of anybody specific but I'll forward the message to people who might be interested.

**Comment by bartkamphorst** [comment]
Initial Primer.css support has been implemented in https://github.com/gollum/gollum/pull/1393. There is still plenty of room for improvement though, so I'll close this issue but open an improvement issue for continued work on improving the frontend.
