### ISSUE TITLE
Why is Gollum's frontend so different form what we can see on GitHub Wikis?

### ISSUE THREAD

**Issue by thomaskuntzz** [gollum/gollum#1244]
Hi, I'm just wondering why Gullum looks really neat when on Github, but quite ugly when taken alone.

Given that Gollulm is developed by GitHub, why aren't all the improvements/changes made on GitHub Wikis directly integrated in Gollum "core"? Does anyone know?

Because I'm actually trying to revamp Gollum's fronted (see #1243) and much of the work I'd have to do is redundant with what has already been done on GitHub Wikis...

**Comment by dometto** [comment]
There's an easy answer to that question: github's wikis are no longer
running on gollum (although there is probably an overlap in code). This
open source project is no longer maintained by GitHub, although we try to
mirror the functionality of the GitHub wikis.

**Comment by thomaskuntzz** [comment]
:open_mouth::scream::astonished::boom::fire::shit::-1::cry::sob:

What a pity! How come? Any docs on this?

**Comment by bartkamphorst** [comment]
See https://github.com/gollum/gollum/pull/794 .
