### ISSUE TITLE
Proposal: Production mode

### ISSUE THREAD

**Issue by lopopolo** [gollum/gollum#1250]
I saw in [another issue](https://github.com/gollum/gollum/pull/1247#issuecomment-305226225) talk of dynamically compiling scss on every request.

I'd love to be able to install gollum and then run a command when deploying which dumps all the compiled, minified, file names with cache-busting hashes, etc. static assets to a configurable location (in my document root) so i can serve them via nginx.

**Comment by dometto** [comment]
I think the use of SCSS and appropriate precompilers should take care of that. As you noticed, we're currently discussing that, and any help with #1247 is very welcome! I currently have some questions there that you may be able to help out with.I think the use of SCSS and appropriate precompilers should take care of that. As you noticed, we're currently discussing that, and any help with #1247 is very welcome! I currently have some questions there that you may be able to help out with.
