### ISSUE TITLE
Proposal: Add support for uploading pasted images

### ISSUE THREAD

**Issue by np422** [gollum/gollum#1251]
Hello,

I like to take many screenshots and attach to the documents I write. I think it would be great if it was possible to use Copy/Paste directly from the screenshot tool.

I was able to get it to work reasonably well by adding the content from jquery.inline-attachment.js 
from  https://github.com/Rovak/InlineAttachment to the custom.js file in wiki-repo and make some minor modifications on how the response is handled as gollum sends a redirect instead of a json-reply - so I still got  "[[ /uploads/{filename} ]]" inserted at the cursor position.

**Comment by np422** [comment]
(Gollum became my tool of choice for wikis after I first discovered it about a month ago).

Perhaps "a screenshot tool" instead of "the screenshot tool" would have been a better choice of words, as in whatever is used to capture pictures of the screen.

There is a standard for images as clipboard/paste data in javascript that is supposed to be browser and plattform independent, or that's what I've been told anyway.

I will make an attempt to include paste functionality in the 5.x branch and will get back with a PR. I will probably need some guidance and a couple of roundtrips before the PR is compliant with Gollums current coding and quality standards.

**Comment by dometto** [comment]
Would be glad to help out with a PR!
