### ISSUE TITLE
gem install charlock_holmes -v '0.7.3' failed

### ISSUE THREAD

**Issue by svolence** [gollum/gollum#1255]
Bundler::GemspecError: Could not read gem at /var/lib/gems/2.4.0/cache/charlock_holmes-0.7.3.gem. It may be corrupted.
An error occurred while installing charlock_holmes (0.7.3), and Bundler cannot continue.
Make sure that `gem install charlock_holmes -v '0.7.3'` succeeds before bundling.

In Gemfile:
  gollum was resolved to 4.1.2, which depends on
    gollum-lib was resolved to 4.2.7, which depends on
      gollum-grit_adapter was resolved to 1.0.1, which depends on
        gitlab-grit was resolved to 2.8.1, which depends on
          charlock_holmes

ubuntu 14.04
ruby 2.4

**Comment by dometto** [comment]
Please read the docs before posting here.
