### ISSUE TITLE
Internal links with relative sub dir in textile

### ISSUE THREAD

**Issue by vicnet** [gollum/gollum#1259]
I have a directory tree in git like this:
```
User_Manual
  | mainpage.textile
  |- conf
  |    `- my pages.textile
  `-  other subdirs
```
In mainpage, I want to refer to subpages in subdirs.

First, in redmine textile, internal links are like this [[link|text]].
In gollum, it seems that it should be: [[text|lnk]].
Don't know which is correct...

I try the following links in 'mainpage.textile':
```
["Test Espace":User_Manual/conf/Test-Espace]
[[Test Espace|User_Manual/conf/Test-Espace]]
[[Test Espace|Test-Espace]]
[[Test Espace]]

["Test Espace":conf/Test-Espace]
[[Test Espace|conf/Test-Espace]]
```
The 4 first lines are OK.

I expect to use the last line, with relative link to avoid extra information.
This displays in blue ! but link to http://mysite/cont/Test-Espace. Click create a new page of course.

With ["Test Espace":conf/Test-Espace], it is ok, but not in preview page...
And this form refers to external link

Gollum should search in local dir first then if not in main dir, no ?

**Comment by dometto** [comment]
I'm having some trouble understanding this issue because as far as I know, the use of the colon (`:`) as a separator in links is not allowed in `gollum`. Are you by any chance using the wiki system on github? That's no longer running on gollum.

**Comment by dometto** [comment]
On `5.x`, the gollum tag `[[Test|conf/Test]] simply works. The following Textile-style link also works:
```
"Test":conf/Test.textile
```

**Comment by bartkamphorst** [comment]
@dometto Maybe add the output of `--versions` to this ticket for future reference. 👍

**Comment by dometto** [comment]
```
Gollum 5.0.1b
Running on: x86_64-darwin17 with Ruby version 2.4.1
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
rugged 0.27.4
gollum-rugged_adapter 0.4.4
With the following renderers:
RedCloth 4.3.2
kramdown 1.9.0
```
