### ISSUE TITLE
Why Gollum use different syntax for PlantUML diagrams than Gitlab?

### ISSUE THREAD

**Issue by martinmares** [gollum/gollum#1260]
Why **Gollum** prefer this syntax?

<pre>
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
</pre>

When **Gitlab** (which prefers the gollum as a local viewer of the repository) used this syntax:

<pre>
```plantuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
```
</pre>

It would be great if Gollumn used the same syntax.

**Comment by dometto** [comment]
The three backticks are interpreted as a code block in gollum. Maybe not in gitlab if they don't use GitHub flavored markdown by default?

**Comment by martinmares** [comment]
## I talk about this scenario:

### (1) create test-repo with sample UML diagram
### (2) click on "Clone repo... icon"

![obrazek](https://user-images.githubusercontent.com/1379370/30077606-ab82f106-927c-11e7-82cf-6f981e1984a2.png)

### Which will show me the instructions how run it locally (3)

![obrazek](https://user-images.githubusercontent.com/1379370/30078318-2719e41e-927d-11e7-9de7-ce69ff26564b.png)

### But this example (4) not working on my localhost (after clone wiki repo to my local machine)

![obrazek](https://user-images.githubusercontent.com/1379370/30078354-36d08f66-927d-11e7-8f82-b2482d6e172d.png)

**Comment by dometto** [comment]
Not treating this as a bug. If anyone wants to come up with a PR for this, you're most welcome, but as I said the difficulty is that three-backtick-syntax is interpreted by gollum as a code block (that syntax is borrowed from github-flavored markdown). So the `@` syntax is actually clear and works well from gollum's point of view.

**Comment by jgsuess** [comment]
I also think this annoying. Prevents integrated local editing. Maybe the ticket should be on gitlab, though. But it is definitely a major draw on integration. I guess this a feature request on either party. Could you please reopen or put a feature request on gitlab wiki component?
