### ISSUE TITLE
Common anchors for gollum, github and static

### ISSUE THREAD

**Issue by sciurius** [gollum/gollum#1261]
I have a collection of markdown documents that I maintain mostly locally with gollum. They are also published on a GitHub wiki, and extracted into static pages for publication on a separate web site.
In general, this works okay. However, I now run into problems with anchors and links to anchors.

Given a document "Overview.md" with:

    # Overview
    ## Section
    ### Topic
    ...

Under gollum 4.1.1 the anchor for "Topic" is "#overview_section_topic". GitHub yields "#topic". This makes it impossible to create a link that will work on both.
Since GitHub is basically 'out of control', is there a way to make gollum play nice with GitHub?

**Comment by dometto** [comment]
I wouldn't be against a PR that implemented this. Anchors are generated in [this file](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/toc.rb). Happy to provide support if you'd be willing to give this a try.

**Comment by dometto** [comment]
Fixed in `5.x` (see [here](https://github.com/gollum/gollum/wiki/5.0-release-notes#anchors))
