### ISSUE TITLE
Anchors change when --h1-title is used

### ISSUE THREAD

**Issue by sciurius** [gollum/gollum#1262]
Command line option --h1-title is documented to "Use the first '&lt;h1>' as page title.".

It seems to have another side-effect: the "first '&lt;h1>' " is also removed from the anchor links.

Given a document

    # Overview
    # Section
    # Topic
    ...

The anchor links for "Topic" will be "#overview_section_topic". With --h1-title, this will become "#section-topic". This is highly frustrating when running the same documents under different instances of gollum.

**Comment by dometto** [comment]
I understand the frustration but am not sure whether it can be addressed. When using the `--h1-title` option, it would be very confusing if  the`#overview` prefix was still required for the other anchors. I think a choice should be made whether a particular repository is to be used with the `--h1-title` option or not by the users of a wiki. However, there are some other issues concerning anchor generation. If possible, we can try to omit the nesting of anchor titles, as suggested here: https://github.com/gollum/gollum-lib/issues/167
I'll close this issue in favor of that.

**Comment by dometto** [comment]
Also see the proposal in https://github.com/gollum/gollum/issues/1261
