### ISSUE TITLE
Logging the client IP address in commits

### ISSUE THREAD

**Issue by nspassov** [gollum/gollum#1263]
Hi,

I am trying to include the IP address with each commit and have it displayed in the history log. I am running gollum with a rack extension that allows each client to set their committer name (which is saved in a cookie).

Any pointers on how to include the IP address with that?

**Comment by dometto** [comment]
I'd start looking in [this file](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/wiki.rb) and override the `message` parameter in the relevant methods.
