### ISSUE TITLE
I installed github-markdown and github-markup. But,its not working.

### ISSUE THREAD

**Issue by AbelZhou** [gollum/gollum#1266]
*** LOCAL GEMS ***

github-markdown (0.6.9)
github-markup (1.6.1)

When i write some code with ``` tag. But its dosen't work.
Like this.
![Image](https://raw.githubusercontent.com/AbelZhou/img/master/64F88833-2B8D-4E04-852C-25A1991E4D5D.png)

**Comment by dometto** [comment]
Could you post the actual syntax you're using?

**Comment by AbelZhou** [comment]
I was wrong, I used the markdown editor is Ulysses. Automatically added a lot of unnecessary labels.
