### ISSUE TITLE
Error cloning a GitHub wiki on Windows due to invalid chars in file name

### ISSUE THREAD

**Issue by caioproiete** [gollum/gollum#1269]
When creating pages that contain `:` (colon) in their title, Gollum creates file names that also contain `:` in their names, which causes a `git clone` to fail on Windows, given that `:` is not a valid character for file names.

```
caioproiete@CAP MINGW64 /c/projects/dev
$ git clone https://github.com/caioproiete/docs.wiki.git
Cloning into 'docs.wiki'...
remote: Counting objects: 418, done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 418 (delta 52), reused 3 (delta 1), pack-reused 316
Receiving objects: 100% (418/418), 1.05 MiB | 879.00 KiB/s, done.
Resolving deltas: 100% (229/229), done.
error: unable to create file How-to:-Request-new-features-and-bug-fixes.md: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

ps: Apologies if this is not the right place to file this issue, let me know if this is the case and where should it go.

**Comment by bartkamphorst** [comment]
Can confirm this issue.

**Comment by adiroiban** [comment]
If you want to use it on Windows don't use colon in the title :) or any of the other characters which are not supported by Windows

This is a general issue with any cross OS repo, in Linux you can create files with + or | but then clone will fail on Win

I don't think that gollum should deal with it... is better to allow these char for people which are using the repo only on Linux (Unix)

**Comment by caioproiete** [comment]
> If you want to use it on Windows don't use colon in the title :) or any of the other characters which are not supported by Windows

I'm sorry @adi, but I don't agree. Git is supported on Windows and GitHub Wiki (Gollum) uses Git for source control. Therefore, any developer should be able to clone a GitHub Wiki repository on any operating system supported by Git (Windows being one of them), and it should "just work".

Also, remember that the people writing posts are not necessarily the same people cloning the repo. Just because *John* from the Marketing department decided to use a colon on a title, means that *Lisa* on the development team no longer can clone the repo on Windows. That doesn't make any sense to me.

Gollum should deal with this issue in some way, be it sanitizing the names of the files before saving to the file system, be it prohibiting characters such as colon to be used as titles, or something else. But it's a concern that Gollum should address IMO.

**Comment by dometto** [comment]
Actually, I think `gollum` should not restrict filenames any further than `git` itself does. And as committing files with names containing semicolons is clearly allowed by `git` (provided the filesystem supports this, so basically when on *nix), I don't see a reason to enforce stricter policies. Gollum wikis are simply *as* cross-OS portable as `git` repos.

> Git is supported on Windows and GitHub Wiki (Gollum) uses Git for source control. Therefore, any developer should be able to clone a GitHub Wiki repository on any operating system supported by Git (Windows being one of them), and it should "just work".

As I explain above, there is no more reason to expect repositories from GitHub to "just work" on Windows than there is to expect any odd git repo to do so. Also note that GitHub wikis are no longer running on gollum. The two projects, though historically intertwined, have separated.

That being said, supporting `gollum` on Windows is a goal, and we are pursuing that through developing https://github.com/repotag/gollum-lib_rjgit_adapter (allowing you to run `gollum` on `jruby`).

**Comment by caioproiete** [comment]
> And as committing files with names containing semicolons is clearly allowed by git (provided the filesystem supports this, so basically when on *nix)

I don't know the internals of `git`, but considering the error messages mentioned above, it looks like `git` itself doesn't really have rules to allow/disallow specific characters in filenames, but rather it defers to the OS which means that if you want cross-OS portability on your repository, you need to be conscious and follow stricter policies.

---

> note that GitHub wikis are no longer running on `gollum`. The two projects, though historically intertwined, have separated.

Good to know. Thanks! I'll contact GitHub directly then.

---

> That being said, supporting `gollum` on Windows is a goal, and we are pursuing that through developing https://github.com/repotag/gollum-lib_rjgit_adapter (allowing you to run gollum on jruby).

I'm not sure how allowing `gollum` to run on `jruby` would solve the issue I reported here. The problem is not the OS where `gollum` is running on, but the OS a `gollum` repo is being cloned to.

If the host runs `gollum` on *nix, it will write files with names not supported on Windows. A developer on a client machine running Windows now cannot clone the repository because of that.

There's already some level of sanitization of characters the file names, for example, [replacing spaces with dashes](https://github.com/gollum/gollum/issues/764#issuecomment-32599293)... I don't see why not improve upon that...

**Comment by dometto** [comment]
> it looks like git itself doesn't really have rules to allow/disallow specific characters in filenames, but rather it defers to the OS which means that if you want cross-OS portability on your repository, you need to be conscious and follow stricter policies.

Exactly, that's a choice you make as the owner/committer to a repository (and not as the software that utilizes git).

> I'm not sure how allowing gollum to run on jruby would solve the issue I reported here.

Sorry, I didn't mean to imply that it would. I only wanted to indicate that we're not opposed to Windows support (just not on the level of enforcing certain filenames). That does mean that I think there should be a sane error message when gollum attempts to commit something with an illegal name, btw.

> There's already some level of sanitization of characters the file names, for example, replacing whitespace with dashes.

That's actually a good reason for not implementing this: we've gotten rid of whitespace sanitization in the 5.x development branch. This was causing huge problems all around gollum (spaces getting re-substituted for various reasons, trouble with filenames containing hyphens, etc.), and making the codebase very complicated, precisely because it was trying to enforce something that git does not care about. Moreover, the only historical reason for having this substituting was that grit  (not git) used to be too dumb to handle spaces, as the spaces would be interpreted as a separate command line argument.
