### ISSUE TITLE
Question: Offline use with easy synchronization

### ISSUE THREAD

**Issue by dumblob** [gollum/gollum#1272]
Is it possible and a good idea to use gollum for the use case described on http://wiki.c2.com/?WikiSync ? If yes, then how?

**Comment by dometto** [comment]
Gollum is specifically designed to enable offline use. Simply clone the wiki and work on it locally. Then syncing is as simple as doing a git push to the remote wiki. But obviously this only works if gollum is used for the remote wiki, too
