### ISSUE TITLE
Branch 5x : Rename Results in ".md.md" File Extensions 

### ISSUE THREAD

**Issue by chris2fr** [gollum/gollum#1274]
To reproduce : 

1. Link a page explicitly referencing ".md" and click on that link.
2. Rename that page noticing that .md is already in the title and conserve it.

Observed Outcome :

The page name ends in .md.md.

Expected Outcome :

The page name ends in .md.

Notes: I think this may also be the case on creating new pages.

**Comment by bartkamphorst** [comment]
Issue confirmed. Thanks for reporting!

**Comment by bartkamphorst** [comment]
Issue is resolved in 5.x. branch.
