### ISSUE TITLE
Branch 5x : Dead Keys Add Keystrokes in Editor Pane

### ISSUE THREAD

**Issue by chris2fr** [gollum/gollum#1275]
To Reproduce:

1. Configure your keyboard to use international dead keys (I use Dvorak US on my Mac)
2. Type "L'état, c'est moi" while using option-e e for the "é"

Observed Result:

L'´état, c'est moi.  
Notice the extra ´ before the é

Desired Result:

L'état, c'est moi.

**Comment by dometto** [comment]
Thanks for this report. Might this be a bug in the ACE editor, rather than in gollum? Could you try reproducing this on, say, the demo editor on the ACE website?

**Comment by chris2fr** [comment]
It is not reproducible here in any case:
https://ace.c9.io/build/kitchen-sink.html
Should I look further?

**Comment by chris2fr** [comment]
Would there be a way to deactivate ACE in the 5x branch?

**Comment by chris2fr** [comment]
Hey @dometto, you were right! Simply replacing ACE-1.2.5 with ACE-1.2.9 in the source code fixed the problem!

**Comment by bartkamphorst** [comment]
@chris2fr Glad to hear you resolved this issue. Would you mind opening a PR against the 5.x branch in which ACE is updated to v.1.2.9? Would be much appreciated.

**Comment by chris2fr** [comment]
Sure, will do.

*Chris Mann* *+33 781 811 811* chris@ordiner.com
*Ordiner* Paris, Cultiver l'informatique  www.ordiner.com

**Comment by bartkamphorst** [comment]
@chris2fr Any luck?

**Comment by chris2fr** [comment]
Hey,

I didn't clone.

*Chris Mann* *+33 781 811 811* chris@ordiner.com
*Ordiner* Paris, Cultiver l'informatique  www.ordiner.com

**Comment by bartkamphorst** [comment]
@ProgramFan Would you mind upgrading ACE to the latest version in branch `5.x` to resolve this 'dead keys' issue?

**Comment by ProgramFan** [comment]
Sorry to respond late. Would someone check if the PR resolve this issue?

**Comment by bartkamphorst** [comment]
Thanks @ProgramFan ! @chris2fr Would you mind checking if your issue with dead keys is indeed resolved with [this PR](https://github.com/gollum/gollum/pull/1293)?

**Comment by bartkamphorst** [comment]
@chris2fr ACE has been updated to 1.3.1 in the `5.x` branch, which should resolve your issues with dead keys.
