### ISSUE TITLE
v4.1.2 : Pages with Hyphens in Names are Uneditable

### ISSUE THREAD

**Issue by chris2fr** [gollum/gollum#1276]
**To Reproduce:**

1. Create a page with a hyphen in the name (either with a space, a hyphen or an underscore)
2. Put text in the page.
3. Edit that same page.

**Observed Result**

Blank page

**Expected Result**

Edited page

**Comment by chris2fr** [comment]
I confirm that this behaviour is absent from version 4.1.1. 

**4.1.1**

I created a page as underscore_test where the name was modified to "underscore test" and page filename was modified to underscore-test.md and remains editable.

**4.1.2**

I created a page as underscore_test where the name was modified to "underscore test" and page filename was modified to underscore-test.md. Upon edit, the dash returned to the Wiki Page name and the edit function no longer works.

**Comment by chris2fr** [comment]
Would this have anything to do with the following issue? https://github.com/gollum/gollum-lib/issues/282

**Comment by chris2fr** [comment]
I think it is linked to my installation of the branch 5x from source, then the suppression of the branch 5x before installing the problem with 4.1.2. My reversion to v.4.1.1. probably fixed the problem. However, I did notice that when I uninstalled the branch 5x, I think gem thought it was uninstalling 4.1.1 (from my human memory).

**Comment by bartkamphorst** [comment]
Thanks for reporting this. I'm seeing the same behavior in the `5.x` branch.

**Comment by bartkamphorst** [comment]
This behavior no longer occurs on the `5.x` branch. As we will not backport the hyphenation fixes to 4.x I'm closing this issue.
