### ISSUE TITLE
Branch 5.x: Wrong value on version (4.1.1)

### ISSUE THREAD

**Issue by chris2fr** [gollum/gollum#1278]
https://github.com/gollum/gollum/blob/5.x/gollum.gemspec

In `./gollum.gemspec`

**Observed**

> s.version           = '4.1.1'

**Expected**

> s.version           = '5.x'

**Comment by chris2fr** [comment]
Changed value in `./lib/gollum.rb`

**Comment by bartkamphorst** [comment]
Fixed in #1287 .
