### ISSUE TITLE
Gollum - PlantUML integration seems not to work.

### ISSUE THREAD

**Issue by veponen** [gollum/gollum#1279]
What ever uml code I write, it gives "Wellcome to PlantUML" message. Which is an indication of an error. 
I have been trying to follow instructions related to modifying config.rb, adding the :plantuml_url there.  Also changed DEFAULT_URL at plantuml.rb to my local PlantUML server url. 

My local plantumlserver run in Jetty works fine, I have tested the uml code there and it does prepare image just fine. Same image is not visible when I copy that uml code to Gollum page. Only the "Wellcome..." message is shown. 

I have been debugging a bit the plantuml.rb and I know that the uml-code comes to  def render_plantuml(id, code)- function fine. And I can see that it returns the "Wellcome" message link. Maybe Plantuml-interface has changed somehow?
Best Regards...

**Comment by veponen** [comment]
I have a potential fix, how should I go forward with it?

**Comment by define-null** [comment]
@veponen I had the same issue, but haven't looked at the code yet. 
Maybe you could start with the pullrequest if you have a potential fix, so that others could try it?

**Comment by veponen** [comment]
@define-null I posted this issue to wrong place, it is an issue for gollum/gollum-lib. Should I open a new one there and this should then be closed?

**Comment by bartkamphorst** [comment]
This will be fixed in the `5.x` release. For a quick fix, change 
```ruby 
compressedData = Zlib::Deflate.deflate(text)
``` 

into 
```ruby 
compressedData = Zlib::Deflate.new(nil, -Zlib::MAX_WBITS).deflate(text, Zlib::FINISH)
``` 

in gollum-lib's ` lib/gollum-lib/filter/plantuml.rb`.
