### ISSUE TITLE
Alpine image is too big

### ISSUE THREAD

**Issue by n-sviridenko** [gollum/gollum#1288]
Hello,
The alpine setup requires many packages: https://github.com/gollum/gollum/wiki/Installation#alpine . Is it possible to specify only required? Also, `alpine-sdk` doesn't require `cmake` that's also required by gem.
Thanks.

**Comment by dometto** [comment]
The installation instructions in the wiki are user-maintained. Feel free to correct them (but please verify that your changes are correct).
