### ISSUE TITLE
Configure TOC panel per wiki

### ISSUE THREAD

**Issue by dns2utf8** [gollum/gollum#1292]
Hi all

I would like to configure the some of wikis (hosted inside Gitlab CE).
Is it possible to restrict the TOC side bar depht to one for one specific repo?

I tried to find information about a `./config.yml` or something similiar, but my search turned up nothing.

Greets

**Comment by dometto** [comment]
You mean including only `h1`-level divisions in the TOC, so no subsections? That's currently not possible: all header elements are treated as TOC elements. The relevant code is [here](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/toc.rb#L18). PRs welcome.
