### ISSUE TITLE
 [[image-url|frame]] does not place image in a iframe

### ISSUE THREAD

**Issue by CristianCantoro** [gollum/gollum#1295]
Per the [documentation](https://github.com/gollum/gollum/wiki): `[[image-url|frame]]` should "tell Gollum to place the image in an `<iframe>`".

Code:
```
[[/uploads/tree.html|frame]]
```

results is:
```
<p><span class="frame"><span><img src="/wiki/uploads/tree.html" /></span></span></p>
```

expected result is:
```
<p><iframe src="/wiki/uploads/tree.html" /></p>
```

Note that `/wiki/uploads/tree.html` is a full HTML page that I have uploaded to my wiki, and I was trying to use this workaround to get an `<iframe>` within another page (what is referenced in https://github.com/gollum/gollum/issues/482 does not work for me).

**Comment by dometto** [comment]
Hmm. According to the `gollum-lib` tests this is actually the expected behavior:
```
$ grep -r frame test/
test//test_markup.rb:  test "image with frame" do
test//test_markup.rb:    content = "a\n\n[[alpha.jpg|frame]]\n\nb"
test//test_markup.rb:    output  = "<p>a</p><p><span class=\"frame\"><span><img src=\"/greek/alpha.jpg\"/></span></span></p><p>b</p>"
test//test_markup.rb:  test "absolute image with frame" do
test//test_markup.rb:    content = "a\n\n[[http://example.com/bilbo.jpg|frame]]\n\nb"
test//test_markup.rb:    output  = "<p>a</p><p><span class=\"frame\"><span><img src=\"http://example.com/bilbo.jpg\"/></span></span></p><p>b</p>"
test//test_markup.rb:  test "image with frame and alt" do
test//test_markup.rb:    content = "a\n\n[[alpha.jpg|frame, alt=Alpha]]\n\nb"
test//test_markup.rb:    output  = "<p>a</p><p><span class=\"frame\"><span><img src=\"/greek/alpha.jpg\" alt=\"Alpha\"/><span>Alpha</span></span></span></p><p>b</p>"
```
So I'm a bit puzzled. As far as I know there is nothing in gollum that could take care of rendering the iframe here. I think we should just strip this from the docs tbh.

**Comment by dometto** [comment]
@bartkamphorst ok with removing mention of this functionality from the docs for `5.x`?

**Comment by bartkamphorst** [comment]
Let's wait and discuss first the desirability of the functionality.

**Comment by dometto** [comment]
I spoke too soon: the relevant functionality is implemented [here](https://github.com/gollum/gollum-lib/blob/gollum-lib-5.x/lib/gollum-lib/filter/tags.rb#L301-L307). It seems it may just be wrong to describe it as adding an `inframe`, though. What are the reasons for wanting to put an image in an `iframe` rather than a `span`, @CristianCantoro?

**Comment by CristianCantoro** [comment]
@dometto wrote:
> What are the reasons for wanting to put an image in an `iframe` rather than a `span`, @CristianCantoro?

Because in an `iframe` you can put anything you want, not just images, i.e. as in the case I was interested in another HTML page (which can also be dynamic, for example)

**Comment by dometto** [comment]
Thanks for the clarification. My suspicion, then, is that iframes weren't implemented for security reasons. On public wikis, alllowing iframes would pose obvious security risks.

The way to accomplish this on your personal install would be to try [customizing the sanitation settings](https://github.com/gollum/gollum/wiki/Security#page-sanitization) to allow iframes, and then just using `<iframe>` on your pages.

I have updated the docs to remove the mistaken reference to `iframes`.

**Comment by CristianCantoro** [comment]
@dometto wrote:
> The way to accomplish this on your personal install would be to try [customizing the sanitation settings](https://github.com/gollum/gollum/wiki/Security#page-sanitization) to allow iframes, and then just using `<iframe>` on your pages.

Thanks for the pointer! I have done that but I had to modify a line:
```ruby
sanitizer.attributes['a'].push 'target' # Attributes
```
returns an error:
```ruby
Traceback (most recent call last):
	7: from /home/cristian/.rvm/gems/ruby-2.6.0-preview2/bin/ruby_executable_hooks:24:in `<main>'
	6: from /home/cristian/.rvm/gems/ruby-2.6.0-preview2/bin/ruby_executable_hooks:24:in `eval'
	5: from /home/cristian/.rvm/gems/ruby-2.6.0-preview2/bin/gollum:23:in `<main>'
	4: from /home/cristian/.rvm/gems/ruby-2.6.0-preview2/bin/gollum:23:in `load'
	3: from /home/cristian/.rvm/gems/ruby-2.6.0-preview2/gems/gollum-4.1.3/bin/gollum:251:in `<top (required)>'
	2: from /home/cristian/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	1: from /home/cristian/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/path/wiki-config/config/config.rb:19:in `<top (required)>': undefined method `push' for nil:NilClass (NoMethodError)
```


 instead this works:
```ruby
sanitizer.attributes["iframe"] = ["src"] # Attributes
```
