### ISSUE TITLE
Installation fails on Centos 7.3

### ISSUE THREAD

**Issue by snhirsch** [gollum/gollum#1296]
FYI:

gem install gollum
ERROR:  Error installing gollum:
        nokogiri requires Ruby version >= 2.1.0

Centos repository has only:

ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

**Comment by snhirsch** [comment]
After a protracted battle, I was able to install a newer ruby using RVM and finally got Gollum working.  You need to review your installation instructions on a Centos 7.3 system.  They are not complete/correct and do not work (per original post).

**Comment by dometto** [comment]
The install guide in the wiki is user maintained. Please feel free to update it!
