### ISSUE TITLE
Issue with Links in SVG files

### ISSUE THREAD

**Issue by Riviera12345** [gollum/gollum#1297]
Hi 

I have hosted Gollum locally along with a PlantUML server.

I have changed my config.rb file to render PlantUML images to be rendered as svg images.

The issue begins with including hyperlinks in the svg image. The image is being rendered, however the link is not clickable. When the image is viewed in a seperate tab, it does allow the link to function. I have tried to search regarding the problem and have found the following links, not in Gollum but elsewhere [here](https://forum.joomla.org/viewtopic.php?t=845084
) and [here](https://github.com/jamesmartin/inline_svg/issues/18)

I am assuming the problem lies in the fact that the page being generated by gollum is using `<img> `tags

``<p><img src="http://10.10.10.1:8080/plantuml/svg/U9mLZhqEWa0GX7kUWXVOqAWaHwCX1XfZucai2CLwNkJ2iKkuFN_UtgEOOhvlYja7mKNYv3FLTOF8h8h2iq4_S12rsUxAekKF28Es4cT0Q9oqyG5QVjx2tOqERi7H2nhsFax01BKbEMieyuirJ8Gk12HZ-xxAb3P8bEPLdgdZT_Ri1CKnhVs4ZYGbwVnWZ0rXfJM_xRAYwu9c35Msj_HCX__AHK3g" /></p>``

against advised by this site [here](https://www.sitepoint.com/add-svg-to-web-page/) regaring the use of svg files in html pages.

What and where should I modify in gollum to render images as svg to preserve the ability of the image to interact. I am new to ruby, but I am inclined to tinker with the code. Kindly point me in the direction
to work it out.

Thank you.

**Comment by dometto** [comment]
Sorry for the slow reply. You should have a look at the PlantUML filter in `gollum-lib`: https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/plantuml.rb

It should be fairly easy to change the `img` tag to an `object` tag. If you manage to get it working with `svg`, I'd welcome a pull request!

**Comment by Riviera12345** [comment]
Thank you. I will give it a try

**Comment by Riviera12345** [comment]
In my understanding we need to replace

this line

"<img src=\"#{gen_url(code)}\" />"

with this

"object type="image/svg+xml" data=\"#{gen_url(code)}\"></object>"

however, this is resulting in  following errors

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require':
/var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/filter/plantuml.rb:108:
syntax error, unexpected tIDENTIFIER, expecting keyword_end (SyntaxError)
      "<object type="image/svg+xml" data=\"#{gen_url(co...
                          ^
/var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/filter/plantuml.rb:108:
syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
...  "<object type="image/svg+xml" data=\"#{gen_url(code)}\"></...


I am trying to work on them.  I have found another thread, which might be
of interest here

https://github.com/asciidoctor/asciidoctor/issues/1301

Thank you

**Comment by Riviera12345** [comment]
Okay, by escaping double quotes I am able to run the gollum server, by this line 

"<object type=\"image/svg+xml\" data=\"#{gen_url(code)}\"></object>"

But the entire code is removed when the page is rendered! Why? Is there any other piece of code which is stripping away this line??

**Comment by Riviera12345** [comment]
Alas, the answer lies in 

 https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/sanitize.rb
I have replaced these three lines 
      ```
doc = Nokogiri::HTML::DocumentFragment.parse(data)
      doc = @markup.sanitize.clean_node!(doc)
      doc.to_xml(@markup.to_xml_opts
```

with 

`data`
In short, i have ensured that the module is not sanitizing the html.  Which is evident that it is not the right way, but for the sake of trouble shooting the problem....

The svg is getting rendered now with `object` tags. Also, the hyperlinks are now working. 

Thank you for the help. However, the issue has not been resolved the way it is supposed to be. How should we deal with `nokogiri` which is used in the `sanitize.rb` filter

**Comment by dometto** [comment]
Thanks for working on this! We can change the sanitization settings to allow the `object` tag. See the `Sanitize` class in gollum. First we should determine whether allowing that tag generally has any security risks though -- I would guess not, but I'm personally not familiar with this tag.

**Comment by Riviera12345** [comment]
Thank you for the input. I have a found a long winding thread about the security issue with `object` tag [here](https://bugzilla.mozilla.org/show_bug.cgi?id=530308#c27)   . Some more [here] (https://www.w3.org/2014/06/05-svg-minutes.html#item01) and [hear](https://www.w3.org/wiki/SVG_Security) regarding SVG related security. Though there is no clear verdict, enabling these tags does need some additional thought. I am trying to understand the working of Sanitize gem. Will get back once I understand how to go about it. 

Thank you once again.

**Comment by bartkamphorst** [comment]
I'm not in favor of whitelisting `object` by default at this point. @Riviera12345 I'm therefore closing this issue, but if you've managed a workaround for your local instance of gollum, feel free to post it here or add it to the wiki so others may benefit.
