### ISSUE TITLE
Gollum ignore a page extension?

### ISSUE THREAD

**Issue by rygo6** [gollum/gollum#1300]
I am having a lot of difficulty figuring out how to get Gollum to ignore a file extension. I have a bunch of .mdj files in my Gollum repo, which are StarUML source files, I would like to commit them to the Gollum repo to have them saved there. But Gollum is interpreting the .mdj file extension as a page and it adds to the wiki. How can I configure it to not do this?

**Comment by bartkamphorst** [comment]
`.mdj` files are not registered by default as pages (see `markup.rb`). Is it possible gollum sees them as Files (which they are) instead of Pages?
