### ISSUE TITLE
open page when exact match in search 

### ISSUE THREAD

**Issue by deadc0de6** [gollum/gollum#1303]
Would it be possible that if a search term matches exactly an existing page in the wiki, gollum would open that page? Let's say for example there's a page named "test", a search with `test` should open the page `[[test]]`.

**Comment by dometto** [comment]
@deadc0de6 happy to merge this into gollum. Would you like to try your hand at a PR?

**Comment by acaporrini** [comment]
@dometto I made a PR for this:
#1352

**Comment by deadc0de6** [comment]
@acaporrini nice, thanks! Sorry but I'm not good at ruby :-s

**Comment by dometto** [comment]
We've decided not to include this feature, because the behavior is not always as intuitive as it might seem. See #1352.
