### ISSUE TITLE
page.raw_data returns strangely-misparsed macros?

### ISSUE THREAD

**Issue by roystgnr** [gollum/gollum#1304]
When I look at a typical raw_data string for a page with tags and macros in it, via render output from within different macro:

Gollum tags get parsed (or rather, not parsed) as expected: ```[[My Tag]]``` is still ```[[My Tag]]``` in the output.

Gollum macros get strangely transformed: e.g. ```<<Foo(Bar)>>``` becomes ```&lt;<foo>&gt;</foo>``` and ```<<Foo(Bar|Baz Qux)>>``` becomes something like ```&lt;<foo qux="">&gt;``` (with a closing tag much later in the text?!)

Is there any way to get *raw* raw_data?  I would like for one macro to be able to search a page for instances of itself or another macro.  text_data appears to have the same problems as raw_data, and using formatted_data makes it easy to lose data or end up in an infinite recursion.

**Comment by dometto** [comment]
My hunch would be that the html entities are getting put it in at the point where a page is saved. You could check this by seeing if they are indeed part of the blobs in the git repository. If they are, then at least `raw_data` *is* outputting the "*raw* raw data". The question is then how to stop the content from being transformed to html entities.

**Comment by roystgnr** [comment]
It looks like what tricked me here was "via render output".  Whatever is transforming macros is happening **after** my Gollum::Macro subclass render method returns; if I just use STDERR.puts (what I should have been using for "printf debugging" in the first place, but I'm new to Ruby) then I see that the macro text is stored correctly.

Sorry for the false positive issue (and for taking so long to get back to it); thank you very much for the quick response.
