### ISSUE TITLE
Image corruption with --alow-uploads

### ISSUE THREAD

**Issue by NHALX** [gollum/gollum#1306]
All images uploaded through the web interface are being corrupted. 

- Text files upload ok.
- Image display is ok for files uploaded and committed through other means (shell access).

Versions: 
Gollum 4.1.2, git 2.14.1, slackware 14.2, ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-linux]

**Comment by bartkamphorst** [comment]
Cannot reproduce this on `5.x` gollum.

**Comment by bartkamphorst** [comment]
@NHALX You mentioned your git version, but not the git adapter you were using. Did you use gollum's default grit adapter?

**Comment by NHALX** [comment]
It was most likely the default. It's been a while, but I don't recall doing any special configuration.

**Comment by bartkamphorst** [comment]
Actually, I've just now come across this in `5.x`.

**Comment by dometto** [comment]
Any difference between uploading via the button or drag-and-drop?

**Comment by dometto** [comment]
> Actually, I've just now come across this in 5.x.

With grit or rugged, though?

**Comment by bartkamphorst** [comment]
> With grit or rugged, though?

RJGit (on Windows).

**Comment by bartkamphorst** [comment]
Upload relies on `committer.add_to_index` to commit uploaded files to the repository, but this method attempts to normalize the files by calling the following `normalize` method:
```ruby
def normalize(data)
  data.gsub(/\r/, '')
end
```
This works fine for text files, but my hunch is that this code is eating up some bytes from the binary files that are uploaded. And the kicker is that any errors are suppressed (from `committer.rb`):
```ruby
rescue ArgumentError => err
  # Swallow errors that arise from data being binary
  raise err unless err.message.include?('invalid byte sequence')
end
```

**Comment by bartkamphorst** [comment]
The `ptools` gem uses this code to guess whether a file is a binary file or not:
```ruby
  def self.binary?(file, percentage = 0.30)
    return false if image?(file)
    bytes = File.stat(file).blksize
    bytes = 4096 if bytes > 4096
    s = (File.read(file, bytes) || "")
    s = s.encode('US-ASCII', :undef => :replace).split(//)
    ((s.size - s.grep(" ".."~").size) / s.size.to_f) > percentage
end
```
(where `image?(file)` just does a check based on file extension.)

@dometto Perhaps we can use the same heuristic for determining whether or not to pass `data` to `normalize`?

**Comment by dometto** [comment]
Nicely diagnosed. Git uses a similar heuristic for determining whether a file is binary. Perhaps we could use that?

**Comment by bartkamphorst** [comment]
> Git uses a similar heuristic for determining whether a file is binary. Perhaps we could use that?

Perhaps, but I'd have to check if we can access that heuristic.

In other news, I can confirm that the uploaded files make it to the server just fine, and that file corruption happens afterwards when committing the contents of the file to the repository.

**Comment by bartkamphorst** [comment]
This issue has been fix in `5.x` with PR https://github.com/gollum/gollum/pull/1353. Tested specifically on Windows and uploading images and PDFs works fine now. 👍
