### ISSUE TITLE
Markdown rendering: possible for a "newline" to render as "newline"?

### ISSUE THREAD

**Issue by chrisbeckstrom** [gollum/gollum#1308]
Out of the box, if I want gollum to make a new line using markdown, I have to end the line with two spaces. I much prefer the more intuitive "just hit return and that will be rendered as a new line"

I can't be the only one interested in this.

Is it possible? Thanks for your help!

**Comment by bartkamphorst** [comment]
If I do this on gollum from the `5.x` branch the double space at the end of a line doesn't render a newline, but a return does. Can you confirm that you also see this behavior on the 5.x branch?

**Comment by dometto** [comment]
I'm getting the behavior reported by @chrisbeckstrom on `5.x` (I'm using `kramdown v1.9.0` on MRI -- perhaps that makes for the difference between your setup, @bartkamphorst?). However, AFAIK this is standard behavior for Markdown: you need an empty line (or apparently two spaces at the end) to render a break (see e.g. [here](http://markdownlivepreview.com/)). I think it's github-flavored markdown that doesn't require the whitespace. You can configure which flavor of markdown to use by installing additional rendering gems (see [here](https://github.com/github/markup/blob/master/lib/github/markup/markdown.rb) for the markdown gems supported via `github-markup`), or by overriding [this](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/markups.rb#L5-L7) in `config.rb`.

**Comment by dometto** [comment]
@bartkamphorst we could default to github-flavored markdown in `5.x` if we so choose, by modifying [this line](https://github.com/gollum/gollum-lib/blob/gollum-lib-5.x/lib/gollum-lib/markups.rb#L59) and adding:
`:input => GFM`

Also see: https://kramdown.gettalong.org/parser/gfm.html

**Comment by bartkamphorst** [comment]
Would this break any tests?

**Comment by chrisbeckstrom** [comment]
Thanks @dometto !
