### ISSUE TITLE
Page creation behavior for Links with Umlauts is irritating

### ISSUE THREAD

**Issue by dingens** [gollum/gollum#1310]
When:
* Creating a link, say [[München]], it appears red. Fine so far.
* You click it, you get to the create page. When saving, the page is created as _Munchen_. That's okay, but:

Expected Behavior:
* the [[München]] link turns blue and you end up on that _Munchen_ page.

Actual Behavior:
* the link stays red, upon clicking it you get to the create page again. Only when saving, you get a duplicate file name error message.

**Comment by bartkamphorst** [comment]
Agreed. This should be fixed in the `5.x` release.

**Comment by bartkamphorst** [comment]
This has been resolved with https://github.com/gollum/gollum-lib/commit/f397fec9730cdcccc44404a02aa8b62f39fd9f0e (see `5.x` branch).

**Comment by TheSilvus** [comment]
This is still affecting me in the newest version (commit `e0a2b18`, `gollum --version` shows `5.0.1b`).

Also, using emojis (e.g. a markdown link `[Test](❤️)`) redirects to creating a page named `[?]`.
