### ISSUE TITLE
No such file or directory - /gollum/config

### ISSUE THREAD

**Issue by rsov** [gollum/gollum#1313]
Hello

Doing a clean install.

Ruby: `jruby-9.0.0.0 (2.5.0)`

- Created directory called 'gollum'
- ran `$gollum`
- went to `localhost:4567`
- clicked 'save' to create new page
- received error: "No such file or directory - /home/rsov/gollum/config"
- Creating a blank `config` file did not resolve the issue

No stack trace was given with the error

**Comment by bartkamphorst** [comment]
How did you actually install gollum? Did you clone it from Github? Or did you install it via rubygems?

**Comment by rsov** [comment]
@bartkamphorst Installed it from rubygems. I resolved this problem (somehow). Don't remember 100% what I did. I think pointing it to an initialized git repo resolved it

**Comment by bartkamphorst** [comment]
Okay, thanks for letting me know. Closing the issue as resolved.
