### ISSUE TITLE
Finishing RTL support

### ISSUE THREAD

**Issue by AvtechScientific** [gollum/gollum#1314]
Hello,

could you, please, finish RTL support, so it works perfectly, not just very good?...
For now Gollum (on @GitLab) seems to be the best solution for supporting RTL languages.

Gollum automatically recognizes RTL texts and renders wiki pages properly, aligning them to the right!
See example here:

https://gitlab.com/pninim.org/pninim/wikis/test.org

Update: It looks like Markdown renders correctly (right aligned), but RDoc and AsciiDoc - do not.

However when you start editing an RTL text (after pressing the "Edit" button) it get's aligned to the left. This can be solved in Firefox by pressing the "Ctrl-Shift-x", thus forcing RTL manually. Gollum is the only app that doesn't block it - thank you!

So in order to make the RTL support perfect, could you, please enable it also in the editor, by:
1. Automatically recognizing an RTL language, the way you do during rendering.
2. If an RTL language is detected, imitate the Firefox's "Ctrl-Shift-x" behavior.

Thank you!

**Comment by bartkamphorst** [comment]
Have you tried the editor's behavior in the `5.x` branch yet?

**Comment by AvtechScientific** [comment]
Not yet. Is there an online demo, to check it?

**Comment by bartkamphorst** [comment]
No, unfortunately there's no online demo. You would have to check out the branch yourself and run gollum locally.

**Comment by dometto** [comment]
Anyone watching this thread interested in RTL support, please have a look at https://github.com/gollum/gollum/pull/1350 and let us know whether the implementation there gives you what you need!

**Comment by dometto** [comment]
Implemented in 5.x. See [here](https://github.com/gollum/gollum/wiki/5.0-release-notes#support-for-right-to-left-direction-text) for description of the new behavior.
