### ISSUE TITLE
5.x: utf-8 error thrown in Overview page (rugged)

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1339]
Rugged adapter: when there are pages in the wiki with utf-8 filenames:

<img width="1438" alt="screen shot 2018-10-20 at 00 52 33" src="https://user-images.githubusercontent.com/147111/47247304-237a2d00-d403-11e8-9a28-d167edbc2b1a.png">

I do not really understand why this is happening, but the cause appears to be [here](https://github.com/gollum/gollum/commit/3b9af34e0dacf6980eccccb3d82da269a43c62cb#diff-c3330a4adf9600567f00ccb96269d088R60), in the recent changes to the pages/overview view.

**Comment by bartkamphorst** [comment]
I don't see this locally (RJGit). Does it happen with any utf-8 characters? Do you mind adding `--versions` info?

**Comment by dometto** [comment]
Sorry, should've mentioned that it's rugged-specific in the body, too

**Comment by dometto** [comment]
Resolved in https://github.com/gollum/gollum/pull/1346 and https://github.com/gollum/gollum-lib/pull/307
