### ISSUE TITLE
5.x: mathjax config not among protected files

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1340]
Just realized the mathjax js config file is not among the newly protected routes introduced by [this PR](https://github.com/gollum/gollum/pull/1324). However, at the time the protecting routes are being defined, we don't have access to the wiki options yet, so we can't fetch the location of the mathjax config file. My proposal is to do the same thing we're doing with JS and CSS: don't let the user determine the filename, but let it always be e.g. `mathjax.config.js` (?), and block that from being edited.

> However, at the time the protecting routes are being defined, we don't have access to the wiki options yet

For the same reason, we should clearly document that these routes are *always* blocked -- whether you're using `--css`, `--js`, or -`--mathjax-config`. Is that a reason to prefix the filenames, so that we get e.g. `gollum_custom.js`, etc.?

**Comment by dometto** [comment]
Also, have I forgotten any files that need to be protected? There is `config.rb`, but editing that won't have direct effects (only when the wiki is re-launched with the modified file as config file), so I don't think that should be one. Moreover, config.rb doesn't *have* to be committed to the repo.

**Comment by dometto** [comment]
>   For the same reason, we should clearly document that these routes are always blocked -- whether you're using --css, --js, or ---mathjax-config. Is that a reason to prefix the filenames, so that we get e.g. gollum_custom.js, etc.?

Or perhaps we could require the user to save the config files under a `/gollum` directory, since `/gollum` is already a reserved namespace?

**Comment by dometto** [comment]
> I would argue the opposite, even though a relaunch is required, since config.rb can contain (and will run) arbitrary ruby code.

Some flexibility would be lost though, if we forced users to use `./config.rb` as the config file. At present you could run e.g. `gollum --config /var/gollum/global.conf.rb`. It doesn't even have to be part of the repo. Not sure how best to proceed here.

**Comment by bartkamphorst** [comment]
Let's leave config.rb the way it is then, and only fix `mathjax.config.js`.

**Comment by bartkamphorst** [comment]
Closed by https://github.com/gollum/gollum/pull/1358.
