### ISSUE TITLE
Unable to start gollum with `--config config.ru`

### ISSUE THREAD

**Issue by zeigerpuppy** [gollum/gollum#1354]
I am attempting to use a `config.ru` file for starting Gollum with Multimarkdown support.  However, `gollum` seems to have difficulty finding the file.  I have tried everything but can't get it to start with the `--config <filename>` option.  Starting without the config option works properly.  

I feel like I'm missing something obvious!

Gollum version 4.1.4 (Debian 9), ruby 2.3.3p222;
`gollum`  installed via `sudo gem install gollum` 

start command:

```bash
/usr/local/bin/gollum         --host 127.0.0.1 --port 4567 \
                        --base-path wiki --live-preview \
                        --css --js \
                        --config /mnt/docs/config.ru
```

error received:

```bash
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /mnt/docs/config.ru (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/gollum-4.1.4/bin/gollum:251:in `<top (required)>'
	from /usr/local/bin/gollum:22:in `load'
	from /usr/local/bin/gollum:22:in `<main>'
```

my `config.ru` file:

```ruby
!/usr/bin/env ruby
require 'rubygems'
require 'sinatra'
require 'json'
require 'gollum/app'
require 'openssl'

#class Application < Sinatra::Base
#  use Rack::SSL
#  get '/' do
#    'SSL FTW!'
#  end
#end

# testing MultiMarkdown,
# see: https://github.com/gollum/gollum/wiki/Custom-rendering-gems#using-multimarkdown
require 'rmultimarkdown'
module Gollum
  class Markup
    mmd = proc { |content|
     MultiMarkdown.new(content).to_html
    }
    GitHub::Markup::Markdown::MARKDOWN_GEMS['rmultimarkdown'] = mmd
    GitHub::Markup::Markdown::MARKDOWN_GEMS.delete('kramdown') # You may want to disable support for kramdown to en$
  end
end
```

**Comment by bartkamphorst** [comment]
You appear to be confusing `config.ru` with `config.rb`. The former is for running gollum as a rack app through [rackup](https://github.com/rack/rack/wiki/(tutorial)-rackup-howto) while the latter is for customization of gollum. Looking at the contents of your file, I suspect you want the latter. If so, you should rename your file to `config.rb` and specify its path with the `--config` flag.

**Comment by zeigerpuppy** [comment]
thanks @bartkamphorst, that's got me one step closer.

After changing the filename to `*.rb`, I now get the error:

```
/mnt/docs/config.rb:1: warning: regex literal in condition
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': /mnt/docs/config.rb:1: unknown regexp option - b (SyntaxError)
/mnt/docs/config.rb:1: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/gollum-4.1.4/bin/gollum:251:in `<top (required)>'
	from /usr/local/bin/gollum:22:in `load'
	from /usr/local/bin/gollum:22:in `<main>'
/mnt/docs
```

I suspect that this is now an error in my `config.rb` file but at least it's calling it!

Is there a minimal example of `config.rb` available that I can work off?

**Comment by bartkamphorst** [comment]
The error is thrown because your shebang on the first line is incorrect. It should be `#!/usr/bin/env ruby` instead of `!/usr/bin/env ruby`, but I actually don't think you need a shebang in `config.rb` for it to work. Other than that, see https://github.com/gollum/gollum/blob/master/config.rb and have a look at gollum's [wiki](https://github.com/gollum/gollum/wiki/Formats-and-extensions) for more info.

**Comment by zeigerpuppy** [comment]
thanks again.
