### ISSUE TITLE
5.x: 'e' shortcut leads to wrong URL with --base-path

### ISSUE THREAD

**Issue by scolytus** [gollum/gollum#1355]
When pressing 'e' on a page, the same action as the edit button should be triggered. Instead, when using `--base-path`, a wrong URL is generated. At the moment I work around this by rewriting the URL on my reverse proxy.

Expected URL:
`https://example.com/gollum/gollum/edit/test/testPage1.md`

Actual generated URL:
`https://example.com/edit/gollum/test/testPage1.md`

Settings:
`--base-path gollum`

Versions:
```
Gollum 5.0.1b
Running on: x86_64-linux with Ruby version 2.5.3
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
With the following renderers:
kramdown 1.17.0
RedCloth 4.2.9
org-ruby 0.9.12
wikicloth 0.8.3
```

**Comment by bartkamphorst** [comment]
@dometto Perhaps you can include a fix for this with https://github.com/gollum/gollum/pull/1338?

**Comment by bartkamphorst** [comment]
@scolytus Thanks for reporting this. 👍

**Comment by dometto** [comment]
Fixed in https://github.com/gollum/gollum/pull/1338
