### ISSUE TITLE
Spaces escaping as %2B (producing + signs) when editing files

### ISSUE THREAD

**Issue by zverhope** [gollum/gollum#1367]
Everything had been humming along fine, but I seem to have come across a difficulty I can't solve when selecting a file to edit. The path of the file is encoded with %2B instead of %20 wherever a space should be, which then causes gollum to attempt to create a new file with + signs where the original file that I intend to edit has spaces. For instance if I attempt to edit "Here is a note.md" it attempt to create a new note titled "Here+is+a+note.md". This only happens when editing and wikilinks are working fine with spaces. I assume this might have something to do with the "escaped_url_path" variable? I've tried to troubleshoot this and not been able to come up with a solution. Any help would be most appreciated!

My versions output is as follows:

```
Gollum 5.0.1b
Running on: x86_64-darwin18 with Ruby version 2.6.0
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
With the following renderers:
kramdown 1.17.0
```

**Comment by zverhope** [comment]
Just as a follow-up to the above, I thought it might be helpful to provide my output, first when clicking a link to open a page and then when attempting to edit the page. You can see where the space-for-+ substitution/escape happens in the first output when attempting to edit.

```
# Clicking Link to View Note

IP.address - - [05/Feb/2019:11:39:24 CST] "GET /20190203174840%20A%20new%20note%20to%20test%20everything%20out.zk HTTP/1.1" 200 7166
http://wiki-url.com:4567/Home -> /20190203174840%20A%20new%20note%20to%20test%20everything%20out.zk
IP.address - - [05/Feb/2019:11:39:24 CST] "GET /css/template.css HTTP/1.1" 302 0
http://wiki-url.com:4567/20190203174840%20A%20new%20note%20to%20test%20everything%20out.zk -> /css/template.css
IP.address - - [05/Feb/2019:11:39:24 CST] "GET /gollum/create/css/template.css HTTP/1.1" 200 6904
http://wiki-url.com:4567/20190203174840%20A%20new%20note%20to%20test%20everything%20out.zk -> /gollum/create/css/template.css

# Editing Note 

IP.address - - [05/Feb/2019:11:39:27 CST] "GET /gollum/edit/20190203174840+A+new+note+to+test+everything+out.zk HTTP/1.1" 302 0
http://wiki-url.com:4567/20190203174840%20A%20new%20note%20to%20test%20everything%20out.zk -> /gollum/edit/20190203174840+A+new+note+to+test+everything+out.zk
IP.address - - [05/Feb/2019:11:39:27 CST] "GET /gollum/create/20190203174840%2BA%2Bnew%2Bnote%2Bto%2Btest%2Beverything%2Bout.zk HTTP/1.1" 200 7056
http://wiki-url.com:4567/20190203174840%20A%20new%20note%20to%20test%20everything%20out.zk -> /gollum/create/20190203174840%2BA%2Bnew%2Bnote%2Bto%2Btest%2Beverything%2Bout.zk
IP.address - - [05/Feb/2019:11:39:27 CST] "GET /css/template.css HTTP/1.1" 302 0
http://wiki-url.com:4567/gollum/create/20190203174840%2BA%2Bnew%2Bnote%2Bto%2Btest%2Beverything%2Bout.zk -> /css/template.css
IP.address - - [05/Feb/2019:11:39:27 CST] "GET /gollum/create/css/template.css HTTP/1.1" 200 6904
http://wiki-url.com:4567/gollum/create/20190203174840%2BA%2Bnew%2Bnote%2Bto%2Btest%2Beverything%2Bout.zk -> /gollum/create/css/template.css
IP.address - - [05/Feb/2019:11:39:27 CST] "GET /javascript/editor/langs/zk.js?_=1549388367498 HTTP/1.1" 302 0
http://wiki-url.com:4567/gollum/create/20190203174840%2BA%2Bnew%2Bnote%2Bto%2Btest%2Beverything%2Bout.zk -> /javascript/editor/langs/zk.js?_=1549388367498
IP.address - - [05/Feb/2019:11:39:27 CST] "GET /gollum/create/javascript/editor/langs/zk.js HTTP/1.1" 200 6916
http://wiki-url.com:4567/gollum/create/20190203174840%2BA%2Bnew%2Bnote%2Bto%2Btest%2Beverything%2Bout.zk -> /gollum/create/javascript/editor/langs/zk.js
```

**Comment by dometto** [comment]
Thanks for the report. IIRC correctly we switched to using a URL encode function provided by ERB. Perhaps that's too blame!

**Comment by dometto** [comment]
Note to self: we should add a test to prevent this.

**Comment by zverhope** [comment]
> Thanks for the report. IIRC correctly we switched to using a URL encode function provided by ERB. Perhaps that's to blame!

Thanks so much for looking in to it when you have the time. I can't seem to quite figure it out. I've been going through some of the architecture of the code to customize a few things in an attempt to familiarize myself with how the app is working--adding date tagging, automating yaml, etc--but am not very strong with ruby and haven't yet figured out the source of the encoding errors. 

Whereabouts might I look in the code to try to fix this behaviour if you were to guess where it might be located? If I can help at all, I'm willing.

**Comment by dometto** [comment]
Thanks for helping out! Off the top of my hat, I think the relevant lines are [here](https://github.com/gollum/gollum-lib/blob/gollum-lib-5.x/lib/gollum-lib/page.rb#L140) (encoding) and [here](https://github.com/gollum/gollum/blob/5.x/lib/gollum/app.rb#L285) (decoding). I see that encoding is done using `ERB`'s url encoding method, whereas decoding is happening using a method from the `CGI` library. That may be the problem (perhaps we need to use `ERB`'s decode method, too).

If you want to go about debugging, I recommend running `bundle exec irb` from the gollum project root, and:
```ruby
require 'erb'
require 'cgi'
```
...and play around with the output of the respective encoding and decoding methods. It would already be a great help if you could let us know about the results of that!

**Comment by dometto** [comment]
Scratch part of that: I just realized that given your description of the situation, it's already going wrong before we reach the `post '/edit'` route, which means the `CGI` decode method is not involved. I would guess it's indeed the `escaped_url_path`, then, which is ultimately being set [here](https://github.com/gollum/gollum-lib/blob/gollum-lib-5.x/lib/gollum-lib/page.rb#L140]

One further thing. I noticed this in your log:
```
IP.address - - [05/Feb/2019:11:39:24 CST] "GET /css/template.css HTTP/1.1" 302 0
http://wiki-url.com:4567/20190203174840%20A%20new%20note%20to%20test%20everything%20out.zk -> /css/template.css
IP.address - - [05/Feb/2019:11:39:24 CST] "GET /gollum/create/css/template.css HTTP/1.1" 200 6904
http://wiki-url.com:4567/20190203174840%20A%20new%20note%20to%20test%20everything%20out.zk -> /gollum/create/css/template.css
```
That seems like a problem, it's not finding `template.css`. Does this have anything to do with the customizations you mentioned, or is it broken in `5.x`?

**Comment by zverhope** [comment]
Perfect! You confirmed my suspicions about the `escaped_url_path` and redirected me to where I should have been looking all along. I was confining my troubleshooting to the gollum repo and neglected to see how gollum-lib fit into the architecture of the project. It looks as if the gem version of gollum-lib that installed as a dependency with gollum-5.x still used CGI rather than ERB, even though it lists as 5.0.a.4--perhaps a recent change? 

Anyway, installing the gollum-lib-5.x gem from source seems to have fixed this issue. All functions are now functioning as expected. I do still have one minor difficulty on an unrelated matter--an inability to change the default markdown extension due to being unable to delete the format before restoring it--but I'll open a separate issue for that if I can't figure it out. Thank you again for all of your help!
