### ISSUE TITLE
Table of contents in a sidebar

### ISSUE THREAD

**Issue by jb2cool** [gollum/gollum#1370]
I have started using Gollum as an internal mirror for a private GitHub repo and it's working well with the exception of the navigation. I see that Gollum can support a sidebar and i see there is a macro for GlobalTOC but i can't for the life of me work out how to put the two together. All i want is a list of all the pages in a clickable list at the side of the page. Do you have any pointers of how i can do this.

For info, I currently have a single directory of about 8 .md files.

Thanks
Jason

**Comment by bartkamphorst** [comment]
I think what you want is to create a `_Sidebar.md` file in your repository with the (literal) contents `<<GlobalTOC()>>`. Make sure you commit this `_Sidebar.md` file to your repository. See [here](https://github.com/gollum/gollum/wiki#subpages) and [here](https://github.com/gollum/gollum/wiki#default-macros) for more info on sidebars and macros.

**Comment by jb2cool** [comment]
That's exactly it, thanks Bart. I had tried that already but the important bit I missed was that I hadn't commited it to the repository.

**Comment by bartkamphorst** [comment]
I'm glad you got it to work! 👍
