### ISSUE TITLE
Improvement request: when uploading using the form, place link to uploaded file onto clipboard

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1401]
Currently, the upload form just returns the user to the previous screen (page or edit page). It would be nice if a link to the newly uploaded file was placed on the user's clipboard for easy insertion into the text if so desired. With drag-and-drop uploading the link is automatically inserted into the text.

**Comment by dometto** [comment]
Could just add a `clippy` octicon button to the dialog window so the user herself can copy the url if desired!

**Comment by bartkamphorst** [comment]
> Could just add a clippy octicon button to the dialog window so the user herself can copy the url if desired!

![Screen Shot 2019-09-02 at 14 08 01](https://user-images.githubusercontent.com/571173/64113652-2b2c9100-cd8b-11e9-8608-43485dd8ac39.png)
