### ISSUE TITLE
KaTeX for Mathematical Typesetting

### ISSUE THREAD

**Issue by jessebett** [gollum/gollum#1404]
Currently mathematical typsetting is provided by mathjax, which potentially has a small bug due to the discontinuation of the CDN #1390.

However, for a few reasons, mathjax is possibly less preferred than KaTeX for typesetting. In particular, the KaTeX project has more github stars and contributors than mathjax. Further, KaTeX demonstrates that they are faster than mathjax.

Currently gollum's mathematical typsetting is hardcoded to be provided by mathjax, e.g. with the flag `--mathjax`. 

Is it possible to have `5.x` also support KaTeX provided typesetting?

**Comment by bartkamphorst** [comment]
I could see how the `--mathjax` flag could potentially be turned into something like `--math [lib]` where `[lib]` could be mathjax or katex, and a different CDN would be loaded depending on the setting. @dometto Any thoughts? In any case I don't think this request can be prioritized before sorting out [all the todos](https://github.com/gollum/gollum/issues/1400) for the `5.x` release.

**Comment by dometto** [comment]
What would be the benefit of having both Mathjax and KaTeX? Is KaTeX not yet feature complete? Especially in 5.x: we're no longer using a CDN, but have bundled the mathjax JS with gollum. Doing that with KaTeX, too, would produce a double dependency load.

If the feeling is that Mathjax is generally being abandoned in favor of KaTeX, we could just decide to bundle KaTeX instead. Provided, that is, that there are no use cases which KaTeX doesn't cover. Could you tell us a bit more about that, @jessebett? Also cc @ProgramFan, who bundled Mathjax for us.

**Comment by dometto** [comment]
> Further, KaTeX demonstrates that they are faster than mathjax.

That certainly appears to be the case:

https://www.intmath.com/cg5/katex-mathjax-comparison.php

**Comment by bartkamphorst** [comment]
Wow, huge difference in rendering times!

**Comment by ProgramFan** [comment]
KaTeX is much simpler to bundle.

**Comment by dometto** [comment]
if someone can confirm that KaTeX's functionality is as complete as Mathjax's, I'm all for switching to KaTeX then. PRs welcome!

**Comment by ProgramFan** [comment]
I see arguments on the internet that KaTeX is not as complete as Mathjax at the moment. For example, the `equation` and `eqnarray` are not supported at the moment as listed in https://katex.org/docs/support_table.html.

**Comment by dometto** [comment]
Thanks @ProgramFan. Then let's wait until 5.1 and see if KaTeX is complete by then?

**Comment by bartkamphorst** [comment]
Makes sense to me. Let's keep mathjax for the first major 5.x release, and keep this issue open as an improvement request.

**Comment by ProgramFan** [comment]
Although some people concern the render speed, it is often indistinguishable for pages with a small number of latex equations, given the fact that we are bundling mathjax. But I would not object to the idea that we bundle both and let the user choose.

**Comment by bartkamphorst** [comment]
FYI: It seems that the `equation` environment has been implemented in KaTeX: https://github.com/KaTeX/KaTeX/pull/2369 .

**Comment by tasusu** [comment]
Current gollum uses Mathjax ver 2.x, whereas Mathjax 3.x is much faster. Is there any plan to include 3.x as well as KaTeX? 
https://www.intmath.com/cg5/katex-mathjax-comparison.php?processor=MathJax3

**Comment by bartkamphorst** [comment]
@ProgramFan Would you be willing to update Mathjax to version 3.x?

**Comment by ProgramFan** [comment]
I will try.

**Comment by ProgramFan** [comment]
The speed of mathjax 3 is impressive, at least on the demo page, and can be faster than katex sometimes. 👍

**Comment by ConstantinGahr** [comment]
Are there any new plans regarding including KaTex into Gollum?

I'm asking since I'm using Gollum to locally test my Gitlab wiki. Gitlab itself renders math formulas using KaTeX while Gollum doesn't. As such, locally, my formulas are rendered as pure tex code blocks and hard to debug.

Any news or ideas on how to circumvent this problem?

**Comment by bartkamphorst** [comment]
@ProgramFan Would you be willing to update MathJax to 3.x and bundle KaTeX as well?

**Comment by bartkamphorst** [comment]
@ProgramFan OK, thanks for letting us know. 👍

**Comment by dometto** [comment]
Would be very good to try and resolve this issue soon-ish. One thing that would be helpful, if we're going to add more JS assets, is to have a toolchain/workflow in place for JS dependency management. I'm not an expert on this, but believe `yarn` is still the most commonly used tool for this? Or just straightforward `npm`?

Given my lack of experience with this it would be great if someone could help out with coming up with a sane JS dependency workflow for gollum development!

**Comment by benjaminwil** [comment]
I have experience and am interested in setting up the JS dependency toolchain.

I wanted to do this anyway for mobile-editing related features I would like to RFC.

**Comment by dometto** [comment]
@jessebett see #1900 for a draft implementation of katex support in addition to mathjax. Any feedback about what would make the best user experience is welcome.

**Comment by dometto** [comment]
Katex support has been implemented in #1900. This will be released in the upcoming 6.0 version of gollum, and is already available in the latest gollum Docker image.

Please note that support for MathJax also remains. Only users who were previously using a custom `mathjax.config.js` should rename this file to `math.config.js`.

See [here](https://github.com/gollum/gollum/wiki/6.0-Release-Notes) for further documentation.
