### ISSUE TITLE
5.x: Rename dialog does not decode filename with spaces

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1432]
Something I just noticed is that the rename dialog does not handle spaces in the filename well. For example, if I try to rename the page `page with spaces.md`, I get the following dialog:

![Screen Shot 2019-10-05 at 09 09 02](https://user-images.githubusercontent.com/571173/66251383-d300fa00-e74f-11e9-8c93-ce2390154784.png)

Modifying the title to `page%20with%20spaces foo` subsequently leads to the page being renamed to literally `page%20with%20spaces foo.md`.

![Screen Shot 2019-10-05 at 09 11 23](https://user-images.githubusercontent.com/571173/66251409-21ae9400-e750-11e9-831a-212b43921e9d.png)

**Comment by bartkamphorst** [comment]
> I'm reluctant to change that from escaped_url_path to url_path. Perhaps the safest is to use decodeURI() to decode the page path and page name here?

Makes sense if that indeed causes the name to be shown properly in the dialog. 👍

**Comment by dometto** [comment]
Resolved in #1447
