### ISSUE TITLE
How can i install 5.x on Mac?

### ISSUE THREAD

**Issue by sunbjt** [gollum/gollum#1439]
I want to install 5.x on my mac, but  I can't find the way in wiki.
Please help. Thanks.

**Comment by dometto** [comment]
5.0 is not released yet. You can run it from source:

* git-clone gollum
* git-fetch and checkout the 5.x branch
* `bundle install`, `bundle exec gollum`

We're getting quite close to a release (we're [waiting](https://github.com/libgit2/rugged/issues/818) for a new release of https://github.com/libgit2/rugged), but still, running it from source in this way is unsupported, and things may break at a next update.
