### ISSUE TITLE
5.x: current code does not start in my docker

### ISSUE THREAD

**Issue by scolytus** [gollum/gollum#1440]
## Error

I get the following error when trying to start gollum:

```
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rugged_adapter (LoadError)
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/gollum-lib-5.0.a.4/lib/gollum-lib.rb:11:in `<top (required)>'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/gollum-5.0.1b/lib/gollum/app.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/gollum-5.0.1b/bin/gollum:263:in `<top (required)>'
	from /usr/local/bundle/bin/gollum:23:in `load'
	from /usr/local/bundle/bin/gollum:23:in `<main>'
```
## Build

I just created a fresh docker image and wanted to test the latest changes. I did not change anything in the way the docker image is built, it's always a clean built from source:

```
mkdir -p /gollum-src \
    && cd /gollum-src \
    && git clone https://github.com/gollum/gollum-lib.git \
    && git clone https://github.com/gollum/gollum \
    && cd /gollum-src/gollum-lib \
    && git checkout gollum-lib-5.x \
    && bundle install \
    && bundle exec rake install \
    && cd /gollum-src/gollum \
    && git checkout 5.x \
    && bundle install \
    && bundle exec rake install
```

## Docker Image

`docker pull scolytus/gollum:SNAPSHOT-5-26-20191018-182138`

### Gollum Version Info

```
Gollum 5.0.1b
Running on: x86_64-linux with Ruby version 2.6.5
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
With the following renderers:
kramdown 2.1.0
RedCloth 4.2.9
org-ruby 0.9.12
wikicloth 0.8.3
```

### Commit IDs

```
Gollum:     56e36df6
Gollum-Lib: 197162f
```

### Ruby Gem Version

```
3.0.3
```

**Comment by dometto** [comment]
I think the problem is you're attempting to bundle install gollum-lib first, but that doesn't properly specify the rugged_adapter dependency at the moment. Just try this:
```
mkdir -p /gollum-src \
    && cd /gollum-src \
    && git clone https://github.com/gollum/gollum \
    && cd /gollum-src/gollum \
    && git checkout 5.x \
    && bundle install \
    && bundle exec rake install
```

**Comment by dometto** [comment]
@scolytus let me know if this resolves your issue

**Comment by scolytus** [comment]
@dometto Just tried a few scenarios, but this seems to not install gollum-lib - so if I run `gollum` as my entrypoint I get the following error:

```
gollum_1  | /usr/local/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'gollum-lib' (~> 5.0.a) among 112 total gem(s) (Gem::MissingSpecError)
gollum_1  | Checked in 'GEM_PATH=/.gem/ruby/2.6.0:/usr/local/lib/ruby/gems/2.6.0:/usr/local/bundle', execute `gem env` for more information
gollum_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
gollum_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
gollum_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
gollum_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
gollum_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
gollum_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
gollum_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
gollum_1  | 	from /usr/local/bundle/bin/gollum:23:in `<main>'
```

So this only works if you:
* use `bundle exec gollum` as the entrypoint in the `/gollum-src/gollum` working dir
* put some extra effort in getting file permissions right or just run it with UID=0 in the container

The goal of my docker container is to have `gollum` installed "system wide" and don't have to use `bundle` - otherwise you lose the properties of a nice docker image.

**Comment by dometto** [comment]
> The goal of my docker container is to have gollum installed "system wide"

Fundamentally, the problem is that gollum and gollum-lib specify some of their dependencies (such as the rugged adapter) in the Gemspec, which does not allow specifying git branches in development as the source for a dependency. This would all be solved if we could release the new gem, but that's currently still blocked on [this](https://github.com/libgit2/rugged/issues/818).

I think I can solve you're original issue by adding the rugged_adapter development dependency to the gollum-lib Gemfile for now. But things may well break at a later point in development -- there is just no way of guaranteeing that all dependencies are met with bundle in the way you were attempting.

**Comment by dometto** [comment]
Wait, no, it looks like the rugged_adapter development branch is already specified in the gollum-lib Gemfile:
```
  gem 'gollum-rugged_adapter', :git => 'https://github.com/gollum/rugged_adapter'  # For development purposes
```

Sorry, that's not the issue then. The problem must lie with the attempt to package and install the gem locally. Have you had success with this with previous versions of 5.x, or just with 4.x?

**Comment by scolytus** [comment]
I've always used 5.x branches. I wanted to update to the latest commit this weekend, that's when I noticed that it doesn't work any more.

So my last working image was built 2019-09-15 using these commits:

* Gollum:     41d7cf75
* Gollum-Lib: ff8207c

The Dockerfile: https://github.com/scolytus/gollum-docker/blob/master/5.x/Dockerfile

I didn't write (and want to avoid) a biscet script for the image so I don't know which commit between 2019-09-15 and now broke the build.

**Comment by dometto** [comment]
@scolytus sorry but we're going to have to focus our efforts on releasing the 5.0 gem. On the bright side, when that's done, your problem would also be solved. :)
