### ISSUE TITLE
Documentation Error: Mac OSX Installation

### ISSUE THREAD

**Issue by jonesjp** [gollum/gollum#1442]
Please remove the \ characters from the install command for charlock_holmes:

Current:
--with-cxxflags=\'-Wno-reserved-user-defined-literal -std=c++11\'

Should be:
--with-cxxflags='-Wno-reserved-user-defined-literal -std=c++11'

**Comment by dometto** [comment]
I don't know exactly to what document you're referring, but if it's in the project wiki, you can edit it yourself! If not, let me know which file you're looking at.

**Comment by jonesjp** [comment]
Ah, thank you. Yes, it was on the wiki, but I didn't realize I could edit it. It's fixed now.
