### ISSUE TITLE
4.1.4 Firefox says the site is insecure because it tries to fetch the favicon over http, even behind an https reverse proxy.

### ISSUE THREAD

**Issue by DePingus** [gollum/gollum#1448]
Version 4.1.4 Security Issue (sort of)

I have Gollum behind an nginx reverse proxy and password protected with an .htaccess file. When visiting my Gollum wiki Firefox says "the Connection is Not Secure" right in the address bar. Firefox's console says:

`Loading mixed (insecure) display content “http://wiki.mywebsite.dev/create/favicon.ico” on a secure page`

Chrome's dev tools shows the same error, though the site is not labeled insecure in the address bar. Looks like the favicon is hardcoded to http?

**Comment by dometto** [comment]
Actually, it looks like favicon doesn't exist, and the browser is being redirected to the `create` route for that reason. So the problem perhaps occurs anyway when a redirect is triggered, e.g. when you try to load a non-existing page? In that case, you just need to tweak the rewrite rules for your reverse proxy.

Alternatively, you can solve your problem by committing a favicon.ico to your repository root. :)

@bartkamphorst: should we add a default favicon, or is this situation fine?

**Comment by dometto** [comment]
Discussion of favicon in #1466

**Comment by phuedx** [comment]
Sorry to revive a long-closed issue. I came across this issue a while ago when I encountered the same problem and wanted to add a few notes just incase others do the same.

> So the problem perhaps occurs anyway when a redirect is triggered, e.g. when you try to load a non-existing page?

During testing, whenever Gollum responded with an HTTP 302, the `Location` header was always an absolute URL.

> In that case, you just need to tweak the rewrite rules for your reverse proxy.

Alternatively, I added a line to my reverse proxy's configuration that signalled to Gollum (Rack, specifically) that that scheme being used to access it was HTTPS:

```
# /path/to/nginx/conf.d/default.conf

# ...

# Enabling any one of the following three lines fixed the issue described here.
# Per MDN [0], "the XFP header is a de-facto standard header for identifying the
# protocol that a client used to connect to your proxy or load balancer." Note
# that Rack gives the X-Forwarded-SSL header precedence.
#
# [0] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto
# [1] https://github.com/rack/rack/blob/324f0355568064f131fc0cf0a4843a67b37858fc/lib/rack/request.rb#L210
proxy_set_header X-Forwarded-Proto $scheme;

#proxy_set_header X-Forwarded-SSL on;
#proxy_set_header X-Forwarded-Scheme $scheme;
```

**Comment by bartkamphorst** [comment]
Much appreciated, @phuedx . Our wiki is also open to edit, should you be inclined to write up a short tutorial on how to set up gollum with SSL.
