### ISSUE TITLE
Improvement request: support ~strikethrough~

### ISSUE THREAD

**Issue by jstolarek** [gollum/gollum#1449]
I would love to have markdown support for ~strikethrough~ text. On GitHub this is achieved by wrapping text between tilde signs: `~foo~`. I just tested this on 5.x branch and it does not seem to work with the default markdown.

**Comment by dometto** [comment]
If it doesn't work with the default markdown, that's because kramdown doesn't support strikethrough. I'm guessing strikethrough support on github is provided by the `commonmarker` gem. If you `gem install commonmarker`, gollum should automatically use that to render markdown.
