### ISSUE TITLE
Feauture request: add support for favicon

### ISSUE THREAD

**Issue by jstolarek** [gollum/gollum#1466]
I'd like to able to put `favicon.ico` file in the root of my repo and have it displayed as a favicon in the browser.

**Comment by dometto** [comment]
This actually already works. You just need to make sure `favicon.ico` is committed to the repository root. It's not the cheapest way of loading a favicon, but since the browser will cache it anyway I'm inclined to leave it like this. Or did you have another idea, @jstolarek?

**Comment by bartkamphorst** [comment]
> This actually already works (on 5.x at least). You just need to make sure favicon.ico is committed to the repository root.

Ah, nice. 👍

**Comment by dometto** [comment]
The only thing we could do is add a special route for `favicon.ico`, which throws a 404 (rather than a redirect) when it doesn't exist.

**Comment by bartkamphorst** [comment]
Are there established best practices in this regard?

**Comment by dometto** [comment]
I think our use case is a little bit unique, in that we're letting the users determine the app's favicon. But I think it's sane not to treat favicon.ico as just another page, so don't redirect to 'create' if it doesn't exist?

**Comment by jstolarek** [comment]
> This actually already works (on 5.x at least). You just need to make sure favicon.ico is committed to the repository root.

I just tested on the 5.x branch and it doesn't work for me. I cleared the browser cache but still nothing. Anything else that needs to be configured aside from having a `favicon.ico` committed in the root of the repository?

**Comment by dometto** [comment]
Nope, that does the trick for me. Browser caching can be quite stubborn -- have you tried a different browser? To debug, have a look at your browser's development view. In Firefox, under 'Network', you can search for favicon and see whether the request succeeded (and if not, what the response was).

**Comment by bartkamphorst** [comment]
I just tried this, and Firefox keeps using the cached response to the `/create/favicon.ico` route, but Safari shows the favicon.ico that I committed to the root of my repo.

**Comment by jstolarek** [comment]
> have you tried a different browser

Indeed, works in Chrome with gollum 4.

> In Firefox, under 'Network', you can search for favicon and see whether the request succeeded (and if not, what the response was).

Nope, no request for a favicon.

Anyway, whatever the problem is on my side it clearly is already implemented in gollum. Closing.

**Comment by jstolarek** [comment]
Fun fact: if I access gollum via `127.0.0.1:4567` rather than `localhost:4567` then favicon loads correctly.
