### ISSUE TITLE
Emojis Broken on 5.x 

### ISSUE THREAD

**Issue by TheCedarPrince** [gollum/gollum#1472]
Hi all,

Really enjoying Gollum! Just a small problem however and that is certain emojis are not rendering. I am not sure the rhyme or reason to it, but the problem persists in 5.x.

Here is what the error looks like:

![image](https://user-images.githubusercontent.com/29561456/76471059-0f541880-63c8-11ea-92be-a4744af1f0c8.png)

Here is my output file from `bundle exec gollum --versions`

```
Gollum 5.0.1b
Running on: x86_64-linux with Ruby version 2.6.5
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
rugged 0.99.0
gollum-rugged_adapter 0.4.4
Markdown rendering gem: pandoc-ruby
Other renderering gems:
none
```

Any thoughts on what I should do to fix this? Thank you.

**Comment by bartkamphorst** [comment]
@TheCedarPrince Can you post the String that causes the incorrectly rendered html?

**Comment by flowerysong** [comment]
https://github.com/flowerysong/gollum/commit/3df61c5a059edd73baae75f1738bfdeb2a5c9ad0 fixes the problem I ran into, but I didn't investigate whether it was fully correct.

**Comment by dometto** [comment]
That looks like a plausible enough fix. If it does solve the issue, we would be happy to accept that change as a PR.

**Comment by TheCedarPrince** [comment]
Hey @flowerysong and @dometto - I opened a pull request here #1474 

It should be good to go. Thanks @flowerysong and @dometto for the help! 

Feel free to close this when the pull is approved.

**Comment by bartkamphorst** [comment]
@flowerysong Can you explain why (you think) this works?

**Comment by flowerysong** [comment]
It's in the commit message. Without this change the link to the asset was based on the uppercase Unicode codepoint returned by the API (e.g. `1F680.png`), but the correct filename for the asset is `1f680.png`: https://github.com/bonusly/gemojione/blob/master/assets/png/1f680.png

I'm (now) fairly confident that this is a reasonable change, having peeked into the gemoji source code: https://github.com/bonusly/gemojione/blob/master/lib/gemojione.rb#L68-L69

**Comment by bartkamphorst** [comment]
Sorry for missing the commit message; thanks @flowerysong for explaining anyway! I asked because I was wondering whether the issue could perhaps be a gemojione bug that we were working around in gollum, but now I agree that your fix in gollum is appropriate. Thanks again.
