### ISSUE TITLE
Feature request: Support for mermaid

### ISSUE THREAD

**Issue by liuzhenqi77** [gollum/gollum#1473]
[Mermaid](https://github.com/mermaid-js/mermaid) can be used to create diagram and flowchart with Markdown-like snippets. 

There was an attempt to support mermaid (#1118, #1119 ) 4 years ago. Now mermaid has more features, support many new diagrams, and is integrated in [many places](https://github.com/mermaid-js/mermaid/blob/develop/docs/integrations.md) including [other wikis](https://github.com/mermaid-js/mermaid/blob/develop/docs/integrations.md#wikis). It's also requested a lot to be supported officially for GitHub [here](https://github.com/github/markup/issues/533) as an important part of modern markdown.

It will be great if gollum could support mermaid!

Thanks,

**Comment by dometto** [comment]
Would be happy to accept and help out with PRs for this to the `5.x` branch. It shouldn't be too hard to include the mermaid JS in the gollum assets, and optionally require it in `layout.mustache`.

**Comment by forivall** [comment]
Also, [gitlab supports mermaid](https://docs.gitlab.com/ee/user/markdown.html#mermaid), and gitlab recommends gollum for editing wikis locally ([for example](https://gitlab.com/forivall/dark-gitlab/-/wikis/git_access)).

**Comment by dometto** [comment]
Gitlab uses

```
```mermaid
```

to start a mermaid block.

It would be cool to support this, but that would mean we have to either:

* scan for codeblocks twice (in the `Code` filter, and in the new `Mermaid` filter), which is inefficient
* scan for mermaid blocks as part of the `Code` filter, which complicates the logic in that filter

For context, for anyone who would like to work on this: gollum needs to *extract* mermaid blocks, *then* render the document, *then* put the mermaid block back in place. This is to prevent the markup renderer from accidentally attempting to render mermaid syntax. We already do this for various kinds of blocks, e.g. code blocks, plantuml blocks, etc. See for example the [code filter](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/code.rb).

**Comment by dometto** [comment]
Using the work in progress in https://github.com/gollum/gollum-lib/pull/410 and adding the following to `custom.js`, I have succeeded in implementing basic support for mermaid. Anyone interested in Mermaid support in Gollum, please feel free to provide feedback!

JS:

```js
var mermaid = document.createElement('script');  
mermaid.setAttribute('src','https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js');
document.head.appendChild(mermaid);

mermaid.initialize({
  // mermaid core options
  mermaid: {
    startOnLoad: true,
  },
  // mermaidAPI options
  flowchart: {
    useMaxWidth: true,
    htmlLabels: true,
  },
  secure: ['secure', 'securityLevel', 'startOnLoad', 'maxTextSize', 'htmlLabels'],
  securityLevel: 'strict',
});
```

Obviously,  the settings would need to be tweaked, and mermaid should probably be bundled with gollum to enable offline use. It's also worth thinking more about security: it looks like GitLab renders mermaid diagrams [in an iframe](https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/assets/javascripts/behaviors/markdown/render_mermaid.js) for added security.

Result:

<img width="1290" alt="Screenshot 2022-01-14 at 15 06 09" src="https://user-images.githubusercontent.com/147111/149530215-3d963ec8-10df-4766-bbd0-6546acb96581.png">

Source (part):

~~~
```mermaid
  sequenceDiagram
  Alice->>John: Hello John, how are you?
  John-->>Alice: Great!
  Alice-)John: See you later!
```
~~~

This should provide compatibility with GitLab.

**Comment by bartkamphorst** [comment]
I'd be in favor of further developing this functionality. I would also prefer to set the `language_handler` proc in gollum.

**Comment by dometto** [comment]
Support for mermaid will be released in `gollum v.6.0`. Those keen to try it out now can give the latest `master` a spin -- don't forget to use the `--mermaid` command line flag! Please let us know about any issues you encounter.

**Comment by dometto** [comment]
Also, documentation for this feature will of course be added before the 6.0 release. Any help with this would also be appreciated.
