### ISSUE TITLE
The --h1-title Flag Not Working as Expected in 5.x

### ISSUE THREAD

**Issue by TheCedarPrince** [gollum/gollum#1480]
# Problem:

I am attempting to us the `--h1-title` flag in gollum 5.x and it is not working as expected. What I am expecting to see happen is gollum scan my markdown for the first instance of a h1 header (denoted as `# title`) and make that the title of the page.

As of now, that is not happening and I am still left with the title of the page being the name of the file. 

# Information for Replication:

## Markdown File

Here is an example of my markdown that I am writing so you can see if I am breaking something (NOTE: if I put the h1 header immediately after the YAML, there is no error):

```mkd

---
bibliography: zettel.bib
csl: ieee.csl
nocite: |

---

> **Date:** Tue 10 Mar 2020 05:16:37 AM UTC
> 
> **Summary:** Gives an overview of the 2020 SARS-CoV-2 (COVID19) pandemic and what the disease is. 
> 
> **Keywords:** ##summary ##health #covid19 #publichealth #pandemic #globalhealth #health #healthcare 

## **Note Linked From:**

### [Coronavirus Definition](03102020054429-coronavirus-definition)
- **Summary:** Note on what coronavirus is.

### [Risk of Dying from COVID19](03102020052237-covid19-dying)
- **Summary:** Note on the current fatality when acquiring COVID19.

### [CDC Respiratory Disease Prevention](03102020053006-cdc-respiratory-preventions)
- **Summary:** Note on generic methods on preventing respiratory infection approved by the CDC.

## **Note Linked To:**

---

# SARS-CoV-2

```

With this markdown, I expect to see **SARS-CoV-2** as the title but it is not showing up.

## Gollum --versions

Here is my `gollum --versions` output:

```
Gollum 5.0.1b
Running on: x86_64-linux with Ruby version 2.6.5
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
rugged 0.99.0
gollum-rugged_adapter 0.4.4
Markdown rendering gem: pandoc-ruby
Other renderering gems:
none
```

# Conclusion:

I do not know what is happening but I am willing to tackle this issue a bit more if you can point me in the right direction.

Even if this is not necessarily a bug, it feels constricting with formatting. Maybe there could be another flag like `--h1-title-global` that does my expected behavior if `--h1-title` isn't supposed to behave the way I think it should. We could also update documentation as well should the need arise.

**Comment by dometto** [comment]
Hi @TheCedarPrince! I'm afraid this is just the way the --h1-title feature functions: it *extracts* the first header from a document, if it's an h1, and turns it into a title. This means an easy way to achieve what you want is to keep the document you provide, but just add an addititional h1 with the title you want immediately after the YAML. That will become the page's title, and you can still have an h1 with the same title lower in the document. I hope this addresses your need! Feel free to reopen if it doesn't.

**Comment by TheCedarPrince** [comment]
That makes sense @dometto  - would you be opposed to me clarifying that in the documentation? I could make a pull sometime this week.

**Comment by dometto** [comment]
No, any additional clarification is most welcome! The wiki is freely editable, but the Readme and command line help in `bin/gollum` would need a pull request. Thanks for chipping in!
