### ISSUE TITLE
5.x: Footer styling issue if sidebar is positioned on the left

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1488]
![Screen Shot 2020-03-16 at 17 11 41](https://user-images.githubusercontent.com/571173/76778000-63387600-67a9-11ea-896d-e4d29b3b0021.png)

**Comment by bartkamphorst** [comment]
Suggestions for styling welcome. The real issue here is that the sidebar length is larger than the wiki-content. The footer info in this picture is thus at the bottom of the wiki-content. Perhaps the H1 and the breadcrumbs should also move to the right when the sidebar is to the left?

**Comment by bartkamphorst** [comment]
Thoughts, @dometto ?

**Comment by dometto** [comment]
And/or the "When was this page last modified?" and Delete Page link should be directly below the sidebar?

**Comment by bartkamphorst** [comment]
Fixed in #1498.
