### ISSUE TITLE
5.x: Mapping absolute-url part of link to local folder itself.

### ISSUE THREAD

**Issue by fullstackly** [gollum/gollum#1495]
I have lots of absolute-path links to files sort of:
`[file](https://github.engine.sourcefire.com/files/docs/wiki/FILES-main-page)` & I would like to map/redirect all appropriate requests to `https://github.engine.sourcefire.com/files/docs/wiki/`-part back to `/` of wiki.git folder. Is there any option to do that? I googled all around but never found any.

**Comment by bartkamphorst** [comment]
In 5.x, you should be able to achieve this using the `.redirects` file. See [here](https://github.com/gollum/gollum/wiki#redirects).

**Comment by fullstackly** [comment]
I've tried to create `.redirect.gollum` in /gollum and put
`'https://inner.git.repos.com/project/docs/wiki/': /` in there. But still it follows original urls. Am I doing something wrong?

**Comment by bartkamphorst** [comment]
First, make sure the file is called `.redirects.gollum` and not `.redirect.gollum`. Second, make sure this file not only exists in the root of your gollum git repository, but is also committed (`git add .redirects.gollum; git commit -m "Adding redirects."`). Finally, gollum only understands relative paths to its pages, for example `sub/dir/pagename.md: Home.md` (so no fully specified URIs). Hope this helps!

**Comment by fullstackly** [comment]
Absolutely, thanks a lot.

**Comment by bartkamphorst** [comment]
Great to hear! Closing this issue then.
