### ISSUE TITLE
5.x Editor - links are highlighted inconsistently

### ISSUE THREAD

**Issue by petrkalina** [gollum/gollum#1506]
i.e.:

<img width="918" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77761925-0f475000-7039-11ea-8995-a05193e512cc.png">

.. you can see that some links are highlighted, and some are not..

**Comment by dometto** [comment]
It's not working only for links in an ordered or unordered list. This is an unwanted consequence of the fact we don't want to highlight links in, e.g., code blocks and UML blocks. Not sure how to fix. I would at least not consider this a critical bug, we can release 5.0 and fix this later.

**Comment by dometto** [comment]
Found a fix in in https://github.com/gollum/gollum/pull/1510/files
