### ISSUE TITLE
custom.css from repository root

### ISSUE THREAD

**Issue by heavywatal** [gollum/gollum#1507]
I don't know if it is a bug or feature, but there is an inconsistency between the documentation and behavior. README says `--css` "Uses custom.css from repository root" ("gollum's root" in Wiki; I feel it is a little ambiguous), but actually gollum reads the one in `--page-file-dir`, which is set to the repository root by default.

I hope the documentation is correct and the program gets fixed because I like the idea of separating page sources from the other files with `--page-file-dir`.

My gollum is `HEAD -> 5.x`. Thank you.

**Comment by dometto** [comment]
Thanks for pointing out the ambiguity in the documentation. However, I'm afraid we do intend for it to be read out of the `page_file_dir`, as URI paths (`http://127.0.01/path/to/resource`) are relative to the page_file_dir. While we understand it might in principle be nice to separate those config files from the rest of the docs, this would unfortunately be non-trivial to implement, and the added code complexity would not be worth the potential benefit -- not to mention that some people might want to have alle the files in the `page-file-dir`, and this would become impossible. Apologies!

**Comment by heavywatal** [comment]
I see. Thank you for the quick response!
