### ISSUE TITLE
5.x - Github Compatibility - images without suffix

### ISSUE THREAD

**Issue by petrkalina** [gollum/gollum#1509]
a very minor issue:

image 1 (no suffix)

`![ImageTest](https://www.iconfinder.com/icons/183416/download/png/64)` -  ![ImageTest](https://www.iconfinder.com/icons/183416/download/png/64)

image 2 (with suffix)

- `![Image Test 2](https://github.com/dcm4che/dcm4chee-arc-light/raw/master/dcm4chee-arc-ui2/src/assets/img/delete_color.png)` - ![Image Test 2](https://github.com/dcm4che/dcm4chee-arc-light/raw/master/dcm4chee-arc-ui2/src/assets/img/delete_color.png)

.. as you can see, both work in github, while in gollum, it looks like

<img width="921" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77769779-951cc880-7044-11ea-8be5-e907145867d4.png">

.. feel free to close as irrelevant - just wanted to continu feeding back testing results..

**Comment by bartkamphorst** [comment]
> just wanted to continu feeding back testing results..

Excellent, thanks!

**Comment by petrkalina** [comment]
<img width="1675" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77770625-db265c00-7045-11ea-9bcc-7999a5eb725f.png">

.. I'm not sure why it is forbidden - better test with some other image as well

**Comment by petrkalina** [comment]
in fact .. the image only works from github somehow - I cannot display it in the browser as well..

<img width="832" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77770855-32c4c780-7046-11ea-96b6-134a1964deb0.png">

**Comment by dometto** [comment]
I'm getting a 404 for that link:

https://www.iconfinder.com/icons/183416/png/64

**Comment by dometto** [comment]
This is very odd. It didn't work for me in gollum a second ago, but it does now:

`![ImageTest](https://www.iconfinder.com/icons/183416/download/png/64)`

Results in:

<img width="412" alt="Screenshot 2020-03-27 at 16 20 58" src="https://user-images.githubusercontent.com/147111/77771449-fa71b900-7046-11ea-92bb-168c48510f43.png">

**Comment by petrkalina** [comment]
.. let's close this.. this is how it looks on github:
<img width="844" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77771456-fd6ca980-7046-11ea-9bad-4d28f951ef81.png">

**Comment by dometto** [comment]
One of life's little mysteries :)

**Comment by dometto** [comment]
Note that if you happen to be looking for icons to use in the wiki, you can use Octicons! https://github.com/gollum/gollum/wiki/Standard-Macros#octicon-macro
