### ISSUE TITLE
[5.x, CSS] H2 and H3 headings have the same size (1.5em)

### ISSUE THREAD

**Issue by anordal** [gollum/gollum#1515]
H2 and H3 looks indistinguishable to an unfamiliar reader. Try this, for a comparison:

```
# H1
## H2
### H3
#### H4
##### H5
###### H6
```

In Firefox's debug view, I can see that H2 and H3 are indeed the same size – 1.5em.

I think the faint underline on H2 is good as extra styling, but not sufficient as the only difference:

* What you expect is a size difference. What the unfamiliar reader sees, when looking at a H2, is a H3 with a `<hr>` underneath.
* You can't see the difference from 3m away.
* The faint underline is not preserved after pasting into Word (yes, my teammate had enough of markdown).

**Comment by dometto** [comment]
@bartkamphorst do we want to incorporate this change in 5.0? The release was delayed because of https://github.com/gollum/gollum/pull/1517 so if you think it's easy to fix, we might as well wait a bit longer. :) Same goes for #1516

**Comment by bartkamphorst** [comment]
I'll likely have a fix for this in the afternoon.
