### ISSUE TITLE
[5.x] print.css fails to remove buttons and .breadcrumb

### ISSUE THREAD

**Issue by anordal** [gollum/gollum#1516]
`print.css` looks like this (at least after saving the page in Firefox, I haven't found the corresponding source file, at least any that made any difference):

```
ul.actions{display:none}#delete-link{display:none}div#footer{display:none}
```

Let's insert newlines to see the diff of what I had to change to make it print as just the document:

```diff
-ul.actions{display:none}
+nav.actions{display:none}
+.breadcrumb{display:none}
 #delete-link{display:none}
 div#footer{display:none}
```

**Comment by dometto** [comment]
Thanks @anordal!
