### ISSUE TITLE
5.x: <hr /> not rendered

### ISSUE THREAD

**Issue by jstolarek** [gollum/gollum#1518]
Consider a following markdown file:

```
foo

---

bar
```

This produces the following HTML:

```html
<p>foo</p>
<hr />
<p>bar</p>
```
But the `<hr />` - which I would expect to be a line - is not rendered in any way:

![gollum4](https://user-images.githubusercontent.com/1597921/77884281-ab04d600-725c-11ea-9875-8b103a9d9eb6.jpg)

Probably a matter of CSS styling?

**Comment by bartkamphorst** [comment]
> Probably a matter of CSS styling?

Correct. Fixed in master with https://github.com/gollum/gollum/pull/1522 .

**Comment by jstolarek** [comment]
Hm. I'm not seeing any difference. I'm on commit 40215c3d and using `commonmarker` gem for rendering things still look the same. I've played a bit in FF inspector: `hr` only becomes visisble if I uncheck `border: 0 none;` in `.markdown-body hr` (and it looks horrible then).

**Comment by bartkamphorst** [comment]
Here's what it looks like for me:

![Screen Shot 2020-03-30 at 12 04 59](https://user-images.githubusercontent.com/571173/77900717-be289d80-727e-11ea-8370-6ea7bf5ecd2c.png)

For comparison, here's what it looks like on Github's wiki:
![Screen Shot 2020-03-30 at 12 06 27](https://user-images.githubusercontent.com/571173/77900863-f3cd8680-727e-11ea-86db-c3acc0f16c34.png)

**Comment by dometto** [comment]
I'm getting the same result as @bartkamphorst

**Comment by dometto** [comment]
@jstolarek that commit is not HEAD (although it's only one down). Give it a try with another `git pull`, and make sure to try a different browser to rule out a caching issue.

**Comment by jstolarek** [comment]
Ok, worked after a pull. Thanks! (40215c3 was HEAD when I was writing my comment.)
