### ISSUE TITLE
Octicons for heading anchors (:pencil and :link) get too small

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1519]
![Screen Shot 2020-03-30 at 09 43 52](https://user-images.githubusercontent.com/571173/77887749-6d5b7980-726b-11ea-84b8-7eb538344d4e.png)

On Github wikis, the octicons just stay 16x16. @dometto Any idea on how to fix this?

**Comment by dometto** [comment]
The relevant lines are:
https://github.com/gollum/gollum/blob/5.x/lib/gollum/public/gollum/stylesheets/template.scss.erb#L97
https://github.com/gollum/gollum/blob/5.x/lib/gollum/public/gollum/stylesheets/template.scss.erb#L116 (and the `height` attribute one line above).

The "fix" would be to make the height attribute an absolute number, not a function of `em`. But I wonder if that would really look better, I think it looks a bit weird on github to have a really small header with a larger icon:

<img width="233" alt="Screenshot 2020-03-30 at 10 44 10" src="https://user-images.githubusercontent.com/147111/77892767-6d5f7780-7273-11ea-91ed-5a9a8ae8d278.png">

(That's an h6)

But I don't feel really confident about my styling opinions, so your call!

**Comment by bartkamphorst** [comment]
I'm fine with the current behavior. If anyone else disagrees, feel free to comment here to discuss.
