### ISSUE TITLE
Image upload by drag&drop fails if there is space in the file name

### ISSUE THREAD

**Issue by petrkalina** [gollum/gollum#1526]
Example:

1. upload the image
2. the link is created i.e. <img width="268" alt="Screenshot 2093" src="https://user-images.githubusercontent.com/1150350/77914481-49615d80-7296-11ea-9e1f-fd2a164c92b5.png" />
3. "image not found" is displayed <img width="271" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77914575-6c8c0d00-7296-11ea-96bc-2c77da0f2321.png" />
4. on the disk, the image looks like this
```
root@gollum1:/wiki/uploads# ls -l | grep 2092
-rw-r--r-- 1 root root  12924 Mar 30 14:51 Screenshot 2092.png
```

the configuration is:
```
--config config.rb --lenient-tag-lookup
```
and
```
Precious::App.settings.wiki_options[:css] = true
Precious::App.settings.wiki_options[:allow_uploads] = "page"
```

I'm not sure if and how the "allow_uploads = page" is interpreted in v.5 .. from this case it also seems that this one does not work any more..

**Comment by dometto** [comment]
Just FYI: there is an upload button outside of the editor view (on the page view).

**Comment by dometto** [comment]
> I'm not sure if and how the "allow_uploads = page" is interpreted in v.5 .. from this case it also seems that this one does not work any more..

You're just not setting the per-page upload option correctly. You can use `--allow-uploads page`, or set:

```
Precious::App.settings.wiki_options[:allow_uploads] = true
Precious::App.settings.wiki_options[:per_page_uploads] = true
```

You can see that's how to do it by peaking at the `bin/gollum` script [here](https://github.com/gollum/gollum/blob/master/bin/gollum#L121). In general, please have a look at https://github.com/gollum/gollum/blob/master/bin/gollum if you're in doubt about how to set options in `config.rb`.

**Comment by dometto** [comment]
I can't reproduce the problem when running gollum with `gollum /tmp/lotr/ --allow-uploads page --lenient-tag-lookup`. I'm assuming the problem is with the way you're setting the upload options. If not, feel free to reopen.
