### ISSUE TITLE
5.x: http link with not displayed as link in the wiki

### ISSUE THREAD

**Issue by petrkalina** [gollum/gollum#1527]
Example source:

```
Otherwise, all options are described here - see: https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server
```

result:

<img width="649" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77919750-deb42000-729d-11ea-9dc3-b311c3595af5.png">

using this code

```
Otherwise, all options are described here - see: [[https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server]]
```

it works as expected:

<img width="633" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77920154-64d06680-729e-11ea-8ac4-8b9ba5b06dfe.png">

Maybe this is a feature that I was not aware until now - in that case sorry for raising alarm!

**Comment by dometto** [comment]
Yes, you need to use Gollum-style tags if you want something to be parsed as an external link, too: `[[http://github.com]]`. Without the tags, the link won't be parsed as a link at all -- gollum performs no autolinking, although some rendering gems might do that themselves. The way I see it, that's up to the rendering gem. But of course, someone could implement an `Autolink` Filter for gollum-lib's filter chain if desired.

(Of course, you can also use markup-specific ways of defining external links `[]()` on markdown)

**Comment by heavywatal** [comment]
Using `<http://github.com>` style will be more portable because it is defined in CommonMark:
https://spec.commonmark.org/0.29/#autolinks

That said, I like the idea of having an autolink option. Does it have to be implemented as a new gollum-lib's filter? Is it possible to pass some options to the upstream markdown parser? e.g.,
https://github.com/github/markup/blob/cd01f9ec87c86ce5a7c70188a74ef40fc4669c5b/lib/github/markup/markdown.rb#L9

**Comment by dometto** [comment]
> Using <http://github.com> style will be more portable because it is defined in CommonMark

thanks @heavywatal, I didn't know about that syntax! Good news: turns out it already works on gollum. 😄  I've tested it (successfully) using the kramdown, commonmarker, and pandoc-ruby gems.

Leaving autolinking up to the individual rendering gems thus seems like the right approach. 👍
