### ISSUE TITLE
Image upload from mac OS screenshot fails

### ISSUE THREAD

**Issue by petrkalina** [gollum/gollum#1528]
On github, it is possible to upload directly from mac OS screenshot. It looks like this:

make the screenshot - it appears in the bottom right corner:

<img width="1261" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77920512-d9a3a080-729e-11ea-88cd-87dd072b9318.png">

then drag it over the edit wiki area.. I did it now for the below image

<img width="200" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77920599-f9d35f80-729e-11ea-9c80-fa1c5d4cfbda.png">

.. then it is displayed. In gollum it does not. I have no idea what really happens on the upload when using a captured image like this - I only know that for mac users, this would be the preferred way how to add screenshots - otherwise you ahve to wait till the screenshot is saved, find it on the disk, rename it to not to have spaces (to avoid #1526) and drag-and-drop it.

**Comment by dometto** [comment]
PRs welcome

**Comment by dometto** [comment]
@petrkalina I'm not able to drag and drop in that way on github, either, using Firefox. What browser are you using?

**Comment by petrkalina** [comment]
safari

**Comment by petrkalina** [comment]
testing with firefox .. yes, it is not possible. Probably is is via some proprietary extension present only in safari!

**Comment by petrkalina** [comment]
testing with chrome: also does not work!

**Comment by petrkalina** [comment]
.. ok, I guess this is another example of "not going to fix" as it is too small and specific bug..

**Comment by petrkalina** [comment]
In overall, the experience with images seems not to be very smooth. I'm overloaded, otherwise I'd love to get involved and fix these small issues adding user comfort..

**Comment by dometto** [comment]
@petrkalina thanks for the reports, it's good to be aware of this anyway! It would be great to have a smoother user experience for image uploading, but it also doesn't have to happen right now -- we've just released 5.0 anyway. If you have a bit more time in the future, I'd be happy to give advise on PRs if you are looking to chip in!
