### ISSUE TITLE
the gemspec file is missing an rdoc dependancy

### ISSUE THREAD

**Issue by greyltc** [gollum/gollum#1532]
[Bundling](https://bundler.io/) gollum doesn't work unless the rdoc dep is explicitly is included.

Here's the error when trying to run the bundle:
```
$ BUNDLE_GEMFILE=/opt/gollum/Gemfile bundle exec ruby /opt/gollum/bin/gollum
Traceback (most recent call last):
	11: from /opt/gollum/bin/gollum:7:in `<main>'
	10: from /opt/gollum/bin/gollum:7:in `require'
	 9: from /opt/gollum/lib/gollum.rb:8:in `<top (required)>'
	 8: from /opt/gollum/lib/gollum.rb:8:in `require'
	 7: from /opt/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup.rb:10:in `<top (required)>'
	 6: from /opt/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup.rb:25:in `<module:GitHub>'
	 5: from /opt/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup.rb:101:in `<module:Markup>'
	 4: from /opt/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup.rb:101:in `instance_eval'
	 3: from /opt/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markups.rb:2:in `<module:Markup>'
	 2: from /opt/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markups.rb:2:in `require'
	 1: from /opt/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup/rdoc.rb:2:in `<top (required)>'
/opt/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup/rdoc.rb:2:in `require': cannot load such file -- rdoc (LoadError)
```

**Comment by dometto** [comment]
Isn't rdoc standardly available on a ruby installation?

**Comment by greyltc** [comment]
fixed by https://github.com/gollum/gollum/pull/1533

**Comment by greyltc** [comment]
> Isn't rdoc standardly available on a ruby installation?

I don't know.  

I do know that I needed to add this dependancy or else rdoc could not be found after I [bundled](https://bundler.io/) gollum.

**Comment by dometto** [comment]
I cannot reproduce this error as `rdoc` seems to be integral to my ruby install: if I try to `gem uninstall` it, it just stays present. But it looks like you have a ruby environment where rdoc is somehow not present. If anything, `rdoc` should be added as a dependency to https://github.com/github/markup/, which is the gem that is actually requiring. it. You could open an issue and PR there.

As a workaround on your Docker image (I presume you're still trying to run from Docker), you could try just running `gem install rdoc` before installing gollum. Also note: it looks like you're still trying to run gollum from source, but now that 5.0 has been released, the preferred way of running gollum is without bundler: just `gollum` on the command line ought to work. (Of course, this may not be what you want, depending on your usecase.)

**Comment by greyltc** [comment]
> I presume you're still trying to run from Docker

Not docker anymore. Bundle seems to be much more elegant.

Here are the steps you can take to recreate this issue (you might need `cmake` for this to work, and of course [bundle](https://bundler.io/) and ruby, but those should be the _only_ deps for this to work on any linux):
```bash
wget https://github.com/gollum/gollum/archive/v5.0.0.tar.gz
tar -xvf v5.0.0.tar.gz
cd gollum-5.0.0
bundle config set --local path vendor/bundle
bundle config set --local without development test
bundle install
cp -ra . /tmp/gollum
# now we have a complete standalone gollum "installation" in /tmp/gollum

# so then let's run it:
BUNDLE_GEMFILE=/tmp/gollum/Gemfile bundle exec ruby /tmp/gollum/bin/gollum /path/to/git/wiki
```
You should see the missing rdoc error there.

**Comment by dometto** [comment]
@greyltc I would advise opening an issue and your PR at https://github.com/github/markup/ -- since that is the gem that's requiring `rdoc`. We ought to fix dependency issues at the source, and not downstream. As a work around, I think you should still be able to just `gem install rdoc`. Thanks for chipping in and let us know if we can help further!
