### ISSUE TITLE
Changing the desktop-page-layout

### ISSUE THREAD

**Issue by DanSman** [gollum/gollum#1541]
Hi

I'm trying to change the size of the layout. 

Before v5 it was only - gollum.css:
```
#wiki-wrapper {
  margin: 0 auto;
  overflow: visible;
  width: auto;
}

@media all and (min-width: 940px) {
  #wiki-wrapper {
    width: 1120px;
    padding-left:20px;
    padding-right:20px;
  }
}
```

I've tried a few things already, but so far I haven't had any luck. So I thought it'd be faster if I just asked you ;)

Thanks
Dan

**Comment by bartkamphorst** [comment]
> Before v5 it was only - gollum.css

You mean `custom.css`, not `gollum.css`. 

> I've tried a few things already, but so far I haven't had any luck. So I thought it'd be faster if I just asked you

We have a wiki for a reason. We have limited time, so please do us the courtesy to read the documentation: there's an example there that changes the width of the wiki (on 5.x).

https://github.com/gollum/gollum/wiki/Custom-Styling-and-Views

Be sure to commit `custom.css` to your repository for the changes to take effect.
