### ISSUE TITLE
Absolute paths do not work as advertised

### ISSUE THREAD

**Issue by svenssonaxel** [gollum/gollum#1544]
The 5.0 release notes states:

`If you want to link to page Bilbo in the repository root from a subdirectory, specify an absolute path: [[/Bilbo]]`

It appears that this markup, in Markdown, produces a link relative to the domain root, not repository root. When `--base-path` is set, these are different.

**Comment by dometto** [comment]
With `--base-path wiki`:

`[[/Samwise]]`  generates (correctly) `<a class="internal present" href="/wiki/Samwise.md">Samwise</a>`

Without `--base-path`:

`[[/Samwise]]`  generates (correctly)  `<a class="internal present" href="/Samwise.md">Samwise</a>`

So I can't reproduce this. Are you on gollum 5.x? Please feel free to reopen if I've missed something.
