### ISSUE TITLE
ReStructuredText requires Python 2 while Python 2 is EOL

### ISSUE THREAD

**Issue by aidecoe** [gollum/gollum#1548]
**Describe the bug**

ReStructuredText markup requires Python 2, but Python 2 is EOL and may be removed in next releases of popular Linux distros.

From README.md:
> (the python2 command must be available on your command line) 

I see it's using github-markup for RST processing: https://github.com/github/markup/blob/master/lib/github/commands/rest2html

**To Reproduce**
1. Install python3 and docutils for python3 only.
2. Create new page.
3. Choose "reStructuredText" as markup.
4. Click "Preview". 
4. See error.
    > Failed to render page: Traceback (most recent call last): File "/home/wiki/.gem/ruby/2.5.0/gems/github-markup-3.0.4/lib/github/commands/rest2html", line 50, in from docutils import nodes ImportError: No module named docutils

**Expected behavior**
Renders just fine with python3 docutils instead of python2 docutils.

Always include the output of the `gollum --versions` command (NB: `versions` in plural).

```
Gollum 5.0.1
Running on: arm-linux-gnueabihf with Ruby version 2.5.5
Using:
rugged 0.99.0
gollum-rugged_adapter 0.99.4
gollum-lib 5.0.3
Markdown rendering gem: kramdown
Other renderering gems:
none
```

rst2html itself is compatible with python3:

```
$ head $(which rst2html)
#!/usr/bin/python3

# $Id: rst2html.py 4564 2006-05-21 20:44:42Z wiemann $
# Author: David Goodger <goodger@python.org>
# Copyright: This module has been placed in the public domain.

"""
A minimal front end to the Docutils Publisher, producing HTML.
"""

```

**Comment by bartkamphorst** [comment]
> See error.

Could you report the error itself please?

Also, is `rest2html` compatible with python3?

**Comment by dometto** [comment]
I think [github-markup](github.com/github/markup/) may take care of ReST rendering. The problem may be just that we're being too strict in activating rest support, [here](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/markups.rb#L84). We should maybe just change that to `python3`?

**Comment by bartkamphorst** [comment]
Ah, see, that's why I wanted to see the actual error message. 

> We should maybe just change that to python3

Yes, and if missing, potentially check the output of `python -V`?

**Comment by dometto** [comment]
> Yes, and if missing, potentially check the output of python -V?

That would break on JRuby I think, but we can work around that!

**Comment by bartkamphorst** [comment]
How so?
```sh
jruby-head :010 > require 'open3'
 => true 
jruby-head :011 > stdout, stderr, status = Open3.capture3("/usr/bin/env python -V")
 => ["", "Python 2.7.10\n", #<Process::Status: pid 36972 exit 0>] 
jruby-head :012 > stderr
 => "Python 2.7.10\n" 
```

**Comment by dometto** [comment]
Hmm, I thought there was a problem with system calls under JRuby!

**Comment by bartkamphorst** [comment]
Forking processes, yes.

**Comment by aidecoe** [comment]
@bartkamphorst updated description with error message rendered on the page on preview.

**Comment by bartkamphorst** [comment]
@aidecoe Thanks.

> import nodes ImportError: No module named docutils

Try running `pip install docutils`.

**Comment by bartkamphorst** [comment]
Also, `github/markups` still calls `python2` [here](https://github.com/github/markup/blob/master/lib/github/markups.rb#L52).

**Comment by aidecoe** [comment]
@bartkamphorst it works with docutils installed for python2. It doesn't work when docutils is installed for python3 only.

**Comment by dometto** [comment]
@aidecoe perhaps you could open an issue/PR at `github-markup` asking them to update to `python3`?

**Comment by dometto** [comment]
See https://github.com/github/markup/pull/1319

**Comment by dometto** [comment]
Looks like this was fixed in the most recent version of `github-markup`: https://github.com/github/markup/commit/0ed8aff7af08b58013fe0465d623e71d95fe42a7

We need to make sure to require the latest version (`4.0`) as the `github-markup` update was a breaking change.

**Comment by renich** [comment]
Ping?

**Comment by renich** [comment]
and ping again

**Comment by dometto** [comment]
@renich just updated `gollum-lib` to use the new `github-markup`. I don't have time to test the new behavior with RST this weekend, but if you want to give it a spin and let me know the results, let me know how it goes and I can bump the gem!

**Comment by renich** [comment]
It seems to work great! Thanks a lot!

**Comment by renich** [comment]
For the sake of clarity, here's how I enabled it:

Went to my gollum configuration, pointing to a long-standing repo and added this to `Gemfile`

```
gem 'gollum-lib', git: 'https://github.com/gollum/gollum-lib'
```

Then, I deleted `vendor`: `rm -fr vendor` and updated and installed: `bundler update`.

That was it. It worked fine.

**Comment by dometto** [comment]
Updated `gollum-lib`, `gem update` or `bundle update` should suffice now!
