### ISSUE TITLE
mathjax-config no longer an option?

### ISSUE THREAD

**Issue by travisallison** [gollum/gollum#1556]
I have Gollum 5.0.1.  It doesn't seeem that mathjax-config is an option, despite what the wiki says here: https://github.com/gollum/gollum/wiki#mathematics

When I enter 'gollum -h' the --mathjax option appears, but not the --mathjax-config option.  

When I enter:
gollum --mathjax --mathjax-config "mathjax-config.js"

I get the error:
gollum: invalid option: --mathjax-config

How do I change the mathjax options?

**Comment by dometto** [comment]
You no longer need to enable `--mathjax-config` manually in 5.x. Just commit a `mathjax.config.js` to the root of the repository and it will automagically be used. I think this has not been documented in the [wiki](https://github.com/gollum/gollum/wiki) yet -- much appreciated if you have a moment to update it!
