### ISSUE TITLE
Feature Request: Provide official container image

### ISSUE THREAD

**Issue by scolytus** [gollum/gollum#1560]
Now that version 5 is released it would be nice if there was an official container image of gollum.

This can then replace the rather long and verbose tutorial at https://github.com/gollum/gollum/wiki/Gollum-via-Docker

I have an example image published on docker hub: https://hub.docker.com/r/scolytus/gollum
The source code can be found here: https://github.com/scolytus/gollum-docker

**Comment by dometto** [comment]
@scolytus we have little experience with Docker, but I recognize it's become a standard deployment method by now, and it would be good to have an 'official' gollum image. If your image is not too tailor-made for specific purposes, we would be happy to host it under the gollum org, if you'd like to maintain it?

**Comment by scolytus** [comment]
@dometto I could to that, or at least I'm willing to take care of it and learn how to properly care for it with GitHub + Dockerhub.

I haven't used the integrated tooling yet, instead I did some manual stuff on my machine. I would want to avoid that if I would take over the 'official' image. I would go for an open and transparent build with GitHub and Dockerhub.

It looks like the user [`gollum`](https://hub.docker.com/u/gollum/) is already taken on Dockerhub, so we'd need to find another one. How can we coordinate this?

**Comment by dometto** [comment]
Sorry for the extremely slow response @scolytus. I still think it would be great if you could maintain such a default image.

>  I would go for an open and transparent build with GitHub and Dockerhub.

Sounds like a great idea!

> It looks like the user gollum is already taken on Dockerhub, so we'd need to find another one. How can we coordinate this?

That's annoying. You could set up an account named `gollum-org`, `gollum-official`, or something like that? @bartkamphorst, any suggestions?

I assume you'll need read access to the gollum repo on your github account to set up the link between DockerHub and this Github repo? And/or would you need there to be a `/gollum/docker` repository under our github org?

**Comment by bartkamphorst** [comment]
> You could set up an account named gollum-org

Sounds good to me. 👍

**Comment by scolytus** [comment]
@dometto @bartkamphorst 

* I have created the Docker Hub organization `gollumorg` - https://hub.docker.com/u/gollumorg
  * This is an organization on a free plan - I can add 2 more Docker Hub users for contingency
* I have created a repository `gollum` - https://hub.docker.com/r/gollumorg/gollum
  * No content yet, still figuring out best way to build the images
* I have created a GitHub Machine account `gollum-bot` - https://github.com/gollum-bot
  * This one is under my control
  * Can you please add it to gollum github organization?
  * It only needs *read* access, should be fine as the repositories are public.

**Comment by scolytus** [comment]
@dometto @bartkamphorst 

I would create a dedicated repo for dokcker at first. Once the image and the process is stable we could think about moving it to the main repository.

**Comment by dometto** [comment]
> I would create a dedicated repo for dokcker at first. Once the image and the process is stable we could think about moving it to the main repository.

Will do! I'll also add the bot :)

**Comment by dometto** [comment]
I've invited the bot :)

**Comment by riddla** [comment]
@scolytus Can you give me a heads up how to use https://github.com/gollum/docker directly? Would love to test the image ..

**Comment by pReya** [comment]
@riddla Clone the repo, navigate into the main folder and run `docker build . --file Dockerfile`.

**Comment by pReya** [comment]
Can anyone explain to me why `therubyracer` is needed in the dockerfile?

**Comment by scolytus** [comment]
@pReya I wanted to check in a later step if the installed gems are OK for common use cases. I created the Dockerfile some time ago and back then it was on some list of recommended packages.
Once we have a stable build and upload process to dockerhub feel free to open an issue in the gollum/docker repo.

**Comment by scolytus** [comment]
@dometto @bartkamphorst I've just sent you an E-Mail regarding next steps.

**Comment by fanhongtao** [comment]
Some suggestions:
1. Imge base from `ruby:2.7` will make docker file too large.  Try use `ruby:2.7.1-alpine3.12`, which is based on `Alpine`.  The result is `1.12GB` vs `356MB`.
2. Create a new user in `Dockerfile`, and use it use command `USER`. This will makes the wiki page created by `docker` belongs to the user who starts `docker`, not to `root`.

Here's my [Dockfile](https://github.com/fanhongtao/utils/blob/master/docker/gollum/Dockerfile).

**Comment by dometto** [comment]
Hi @scolytus! I see there is a docker image in the 'docker' repo now. Is this fully functioning now, or does it still need some tweaking (for instance, based on @fanhongtao's suggestions)?

**Comment by scolytus** [comment]
@dometto Sorry for the long delay, last weeks were rather busy. I'll get to it this week and I'll have an update for you by the end of the week.

**Comment by scolytus** [comment]
@dometto Sorry, this took longer than expected, but I uploaded the first image using GitHub actions today.
I also opened some issues in https://github.com/gollum/docker to manage further development.

**Comment by rgov** [comment]
I tested the `gollumorg/docker` image and it is working well.

**Comment by darless1** [comment]
I created PR #1732  because I think the Dockerfile should live in this repository and not elsewhere. This is standard practice, from my point of view. This allows for CI integration for testing the latest changes within the repo and building the latest docker image using it.

Latest dockerhub image that was built from this PR branch: [dockerhub image](https://hub.docker.com/layers/darless1/gollum/dfda2b1b5a6b554f8c93e83059e0bed7b77e2694/images/sha256-c0f88691ce335e326f0e97bf2b7942e8657d9c507c4275b074bd4aa4a48cb5a6?context=explore) is 465.86 MB
 and it uses ruby 2.7.  The original size is 1.16 GB but could be made lighter. Look in that PR for more information and differences to the one in gollum/docker.

**Comment by darless1** [comment]
@dometto can this be closed since docker support is now within the repo?
