### ISSUE TITLE
Docker on Windows installation instructions

### ISSUE THREAD

**Issue by zbetzen** [gollum/gollum#1562]
Hello,

We've ran into a few issues while trying to install Gollum through Docker on Windows using your instructions.

When you run the docker container it doesn't see pwd, we had to reference my-gollum-wiki
docker run -v c:/my-gollum-wiki:/wiki -p 4567:80 gollum

You may want to update the windows instructions to let people know docker run needs to know where my-gollum-wiki is.

thanks,

**Comment by zbetzen** [comment]
Also we had to give docker permissions to mount host directories. This is the tutorial I used https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c

**Comment by dometto** [comment]
Hi @zbetzen! Thanks for letting us know. I'm assuming you're referring to [this](https://github.com/gollum/gollum/wiki/Gollum-via-Docker). That documentation is actually user-contributed, so feel free to update it!
