### ISSUE TITLE
[question]: is there a way to change the default Home.md?

### ISSUE THREAD

**Issue by ahmadnassri** [gollum/gollum#1569]
looking for a way to tell gollum to use `README.md` as the default index page for root and folders ... mimicking GitHub's behavior

**Comment by dometto** [comment]
There's no dedicated configuration option for this, although it's not a bad idea. We can add it to a later version of gollum. For now, I think you can accomplish what you want by using a [redirect](https://github.com/gollum/gollum/wiki#redirects)

**Comment by dometto** [comment]
Actually, it seems you can already achieve this. Use a [config file](https://github.com/gollum/gollum#config-file) and then add the following to it:

```ruby
Precious::App.set(:wiki_options, { :index_page => 'README' })
```

@ahmadnassri if this works to your satisfaction, would you mind adding a pointer about this option to the project [wiki](https://github.com/gollum/gollum/wiki)?

**Comment by ahmadnassri** [comment]
indeed, this does address it! thank you!

doesn't seem one can make PRs directly to a wiki in GitHub ... I've gone ahead and cloned the wiki to a [separate repo](https://github.com/ahmadnassri/gollum-wiki), and made the [update](https://github.com/ahmadnassri/gollum-wiki/commit/7ce5c8c0832586afb9a6f546997d553ab6d3f7fc) there ...

you pull the change from that repo and push it to the wiki here from a user with write access.

thanks.
