### ISSUE TITLE
Overview links are broken for subdirectories with spaces

### ISSUE THREAD

**Issue by Fastidious** [gollum/gollum#1572]
**Describe the bug**
Pages can be created under a subdirectory with spaces, but the subdirectory link itself is broken.

**To Reproduce**
1. Edit a page, add ```[[test directory/testpage]]```.
2. Click on link, create page.
3. Go to Overview, and see the `test directory`. 
4. Only the `test` portion will be clickable.

**Expected behavior**
Spaces converted to `%20` or other, subdirectories in working state.

**Environment Info**
```
madhatter:~ fastidious$ gollum --version
Gollum 5.0.1
```

**Comment by bartkamphorst** [comment]
@dometto I think I have a fix by encoding the `folder_path` variable [here](https://github.com/gollum/gollum/blob/master/lib/gollum/views/overview.rb#L52) like so:
```ruby
folder_url  = "#{overview_path}/#{ERB::Util.url_encode(folder_path)}/"
```
I just wonder if there isn't already a more elegant way to do this?
