### ISSUE TITLE
Hiding buttons

### ISSUE THREAD

**Issue by Fastidious** [gollum/gollum#1573]
Is there a way to hide buttons (Overview, Last Changes, Page History)? If so, how? Thanks!

**Comment by bartkamphorst** [comment]
The most straightforward way I think would be give each button an `id` and then use jQuery to select the buttons you want to hide (e.g., `$('nav_overview').hide()`). The first part would require a PR to gollum to add the `id`s, the hiding part could be done in `custom.js`.

**Comment by dometto** [comment]
What about using custom templates?

**Comment by bartkamphorst** [comment]
> What about using custom templates?

Certainly another possibility. It's just that I think it wouldn't be unreasonable to give buttons `id`s.

**Comment by bartkamphorst** [comment]
I added `id`s to the buttons that didn't have them before in https://github.com/gollum/gollum/pull/1577. This means that you can now hide buttons through `custom.js` like so:

```javascript
$( document ).ready(function() {
    $('#minibutton-overview').hide();
    $('#minibutton-history').hide();
    $('#minibutton-latest-changes').hide();
});
```
Just make sure to commit `custom.js` to the root of your repository. Hope this helps @Fastidious !
