### ISSUE TITLE
[Feature Request] How to set default markup for new pages?

### ISSUE THREAD

**Issue by bkanuka** [gollum/gollum#1574]
Hi there,  not sure if this is possible with a custom config, or if this is a feature request.

Is it possible to set the default markup for new pages?  Currently my repo has everything in acsiidoc, but creating a new page in Gollum defaults to Markdown.

**Comment by bartkamphorst** [comment]
> creating a new page in Gollum defaults to Markdown.

@bkanuka You may be aware of this already, but if you specify a known extension explicitly in the New Dialog (e.g., 'new file.asciidoc') the editor will recognize the page formatting and switch to Asciidoc. 

Insofar as your question pertains to forcing gollum to use Asciidoc as the default for new pages where no extension was specified, I don't have the answer yet.

**Comment by bartkamphorst** [comment]
Actually, [this line here](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L76) sets `markdown` as the `default_markup`, so it should be possible to change this from `config.rb`.

**Comment by bartkamphorst** [comment]
@bkanuka Adding the following line to your `config.rb` should do it.
```ruby
Precious::App.set(:default_markup, :asciidoc)
```
