### ISSUE TITLE
Most [[tags]] do not work in asciidoc documents.

### ISSUE THREAD

**Issue by plujon** [gollum/gollum#1575]
Perhaps this is a documentation issue.

Gollum tags do not work in asciidoc documents.  For example, `[[_TOC_]]` does not render a table of contents, but :toc: does.  Similarly, double-bracketed urls such as `[[https://github.com/gollum/gollum/wiki]]` do not become hyperlinks. 

Are Gollum tags supposed to work in asciidoc pages?

**Comment by bartkamphorst** [comment]
Yes, they are supposed to work. We will investigate.

**Comment by dometto** [comment]
See [here](https://github.com/gollum/gollum/wiki/Formats-and-extensions#example-enabling-gollum-tag-filters-for-asciidoc) for enabling the Tag filter on asciiidoc pages. Let us know if it doesn't work as expected!

**Comment by plujon** [comment]
Org-mode also uses a syntax that conflicts with Gollum's, but it seems to be handled fine (double-brackets are *the* way to link in org-mode).  Could something similar could be done for asciidoc?

For example, [[_TOC_]] and [[abc|something]] are pretty clearly gollum tags and not asciidoc anchors.
