### ISSUE TITLE
Failed to load YAML frontmater: Tried to load unspecified class: Time

### ISSUE THREAD

**Issue by tevino** [gollum/gollum#1579]
**Describe the bug**
Meta data containing specific format of date and/or time causes error.

![image](https://user-images.githubusercontent.com/1027300/84367933-7f607d80-ac07-11ea-89d5-050204afaf1a.png)

**To Reproduce**
1. Create a page with a meta data `Date: 2020-06-11 11:11:11`
2. Click on 'Save'
3. See error as showed in the above image

**Expected behavior**
Meta data display without error.

![image](https://user-images.githubusercontent.com/1027300/84368240-e3834180-ac07-11ea-8f21-b46f39dcdf30.png)

Here's the full content of the page to reproduce:

```yaml
---
Date: 2020-06-11 11:11:11
---
```

**Environment Info**

```shell
> gollum --versions
Gollum 5.0.1
Running on: universal.x86_64-darwin19 with Ruby version 2.6.3
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.4
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by dometto** [comment]
This is an issue in the underlying YAML render/loader, [Psych](https://github.com/ruby/psych/issues/262). Apparently it is not considered safe to let YAML generate Date classes. Maybe a workaround could be quoting your date:

```yaml
Date: '2020-06-11 11:11:11'
```

I hope that's useful. Anyway, we can't do much about this on gollum's side I'm afraid -- I'm reluctant to mess with the default classes that are considered safe.

**Comment by dometto** [comment]
@tevino I dropped a note at https://github.com/ruby/psych/issues/262#issuecomment-642539725 -- let's hope there's some activity there.
