### ISSUE TITLE
Spellchecking not working on editor

### ISSUE THREAD

**Issue by gamaralf** [gollum/gollum#1583]
The editor does not perform spellcheck. Even the context menu (accessed through the right mouse button) shows a regular menu, not the menu expected on a text area.

**To Reproduce**
1. Access a wiki page and click "Edit" button
2. Write misspelled words, they are not highlighted
3. Access the context menu of the editor, it is the same as a regular part of a web page, should be an editable text area menu.

**Expected behavior**
Misspelled words should be highlighted and the context menu of the editor should be like one from a text area.

**Environment Info**
Tested on Firefox 77.0.1 and Google Chrome 80.0.3987.149.

Output of `gollum --versions`:
```
Gollum 5.0.1
Running on: x86_64-linux with Ruby version 2.6.3
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.4
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by bartkamphorst** [comment]
Thanks for the report. This is a known issue, though, one of the oldest open ones, see [here](https://github.com/gollum/gollum/issues/979). If you know of any way forward, please don't hesitate to open a PR.
