### ISSUE TITLE
ISE on /search

### ISSUE THREAD

**Issue by plujon** [gollum/gollum#1586]
Using Gollum 5.0.1, visit /search with no q parameter.  I get an ISE.

  NoMethodError - undefined method `empty?' for nil:NilClass:
  .../vendor/bundle/ruby/2.5.0/gems/gollum-5.0.1/lib/gollum/app.rb:502:in `block (2 levels) in <class:App>'

I only noticed this because a bot requested that resource, resulting in spew in the server's error log.

**Comment by heavywatal** [comment]
Good catch! I have submitted a quick fix for this.

**Comment by dometto** [comment]
Just merged @heavywatal's fix. Many thanks for the report and the fix! It'll be contained in the next gollum release.
