### ISSUE TITLE
Mathjax not working with Org-mode markup

### ISSUE THREAD

**Issue by karthink** [gollum/gollum#1588]
**Describe the bug**
Mathjax output is not being rendered inside the `\(`,`\)` and `\[`,`\]` delimiters in org-mode markup.

As per the wiki instructions, I've created `mathjax.config.js` in the root of my wiki containing:
```
window.MathJax = {
  tex2jax: {
    inlineMath: [['$', '$'], ['\(', '\)']],
    displayMath: [['$$', '$$'], ['\[', '\]']],
    processEscapes: true
  },
  TeX: {extensions: ['autoload-all.js']}
};
```

And I tried it with this source in the file `Home.org`:
```
A quick test of some maths: This is inline: \( A A^{\dagger} = A^{\dagger} A \implies A \) is normal. Also inline: $\alpha, \beta, \frac{\Gamma}{\int_0^\infty f(x) \mathrm{d} x}$

This is display math:

#+BEGIN_HTML
\[
\dot{x} = A(t) x(t)
\]
#+END_HTML
```
Here is the output:
![2020-06-28-032947_779x203_scrot](https://user-images.githubusercontent.com/8607532/85945015-b913d280-b8ef-11ea-9522-84542a120e17.png)

Math inside the `$`s is being rendered correctly, but the brackets are not. Other aspects of Org markup (headings, tables) are being respected, although none are included in the example above. When I saved the same file as `Home.md` (without the `#+BEGIN...` statements) it renders as markdown correctly, including the `\(` and `\[` blocks.

**Environment Info**
```
Gollum 5.0.1
Running on: x86_64-linux-gnu with Ruby version 2.5.5
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.4
Markdown rendering gem: kramdown
Other renderering gems:
org-ruby 0.9.12
```

My `config.rb`:
```
Gollum::Page.send :remove_const, :FORMAT_NAMES if defined? Gollum::Page::FORMAT_NAMES

# Specify the path to the Wiki.
gollum_path = '/var/www/gollum/wiki'
Precious::App.set(:gollum_path, gollum_path)

# Specify the wiki options.
wiki_options = {
  :live_preview => false,
  :allow_uploads => false,
  :allow_editing => false
}
Precious::App.set(:wiki_options, wiki_options)
Precious::App.set(:default_markup, :org)

# Set as Sinatra environment as production (no stack traces)
Precious::App.set(:environment, :production)
```

Gollum is started as:
`/usr/local/bin/gollum --mathjax --config "/etc/gollum/config.rb"`

**Comment by dometto** [comment]
Thanks for the report. Haven't looked at the problem in detail, but I have a hunch this may be related to https://github.com/gollum/gollum/issues/1559 ?

**Comment by karthink** [comment]
I don't think it's related to that issue since everything works as expected
when rendering markdown documents. This problem seems limited to Org markup.

>

**Comment by heavywatal** [comment]
Please read the thread #1559 again to clarify your problem. We have to consider three layers: markdown/org source (you write), HTML code (gollum generates), and visual result (MathJax renders). MathJax tries to find `\( \)` and `\[ \]` in HTML, and never care what is written in org or markdown.

What is the expected and observed HTML code generated from your `Home.org`? Where can I find the spec of org-to-html translation like [CommonMark Spec](https://spec.commonmark.org/current/)?

**Comment by karthink** [comment]
Here is the HTML generated from Home.org:

```html
<p>A quick test of some maths: This is inline: \( A A<sup>†</sup> = A<sup>†</sup> A \implies A \) is normal. Also inline: $α, β, \frac{Γ}{∫_0^∞ f(x) \mathrm{d} x}$</p>

<p>This is display math:</p>
\[
\dot{x} = A(t) x(t)
\]
```
This is the expected output. The `\( \)` and `\[ \]` are showing up as expected in the HTML, but MathJax is not rendering them.

I'm not sure there is a spec for org-mode, just a [manual](https://orgmode.org/manual/index.html) and the [source](https://github.com/wallyqs/org-ruby) for the gem implementation. However, as we can see here the problem appears to be MathJax, not Org.

**Comment by heavywatal** [comment]
Thank you for the clarification. Perhaps you need double backslashes in your `mathjax.config.js` like `['\\(', '\\)']`.

https://docs.mathjax.org/en/latest/web/configuration.html#web-configuration

**Comment by karthink** [comment]
After some experimentation, I've traced the issue down to a problem with org export to html.

> Perhaps you need double backslashes in your `mathjax.config.js` like `['\\(', '\\)']`
1. After I read the mathjax documentation and did this, the code works as expected on most things. However, certain equations still don't render correctly:

![2020-06-30-234237_252x79_scrot](https://user-images.githubusercontent.com/8607532/86211535-64f53200-bb2b-11ea-8473-0b95c561acdc.png)

The problem is apparent from looking at the html generated from Org:
```html
<p>This is display math:</p>
<p>\[
  sin<sup>2 + α</sup>(x) + cos<sup>2 + β</sup>(x) ≈ 1
  \]</p>
```

The LaTex superscript `^{...}` is being exported as a `<sup></sup>` tag from Org. This happens in both display and inline math environments, and irrespective of any `#+BEGIN_HTML...#+END_HTML`  Org blocks around the math. 

So now MathJax is working correctly but Org export to html is not.

**Comment by heavywatal** [comment]
> The LaTex superscript `^{...}` is being exported as a `<sup></sup>` tag from Org.

I guess this translation is the expected behavior of org-to-html. You will need to protect, escape, or whatever to see `^{...}` in HTML.

https://orgmode.org/manual/Subscripts-and-Superscripts.html#Subscripts-and-Superscripts

**Comment by karthink** [comment]
@heavywatal 
This is not the expected behavior of org-to-html. The manual page you linked simply talks about a setting to control whether the curly braces around the sub/superscripted text are required. Moreover, I can export documents from Org-mode in Emacs with no problems rendering the `^` found in math environments as-is.

That said, it looks like this is a problem with `org-ruby` and not Gollum, so I will raise the issue over there.
