### ISSUE TITLE
Examples needed in Security.md

### ISSUE THREAD

**Issue by fanhongtao** [gollum/gollum#1596]
While in Gollum 4.x , the [Security](https://github.com/gollum/gollum/wiki/Security) page has some examples on how to add extra tags/ attributes to the whitelist. This is helpful for someone like me, who has no background on Ruby. So I can easily write my  `config.rb` :

```Ruby
sanitizer = Gollum::Sanitization.new

sanitizer.elements.concat ['link']
sanitizer.attributes[:all].push 'href'

sanitizer.elements.concat ['script']
sanitizer.attributes[:all].push 'src'

sanitizer.attributes[:all].push 'style'

Precious::App.set(:wiki_options, {sanitization: sanitizer})
```

In Gollum 5.x, the `Security` page only provides a link to [Loofah](https://github.com/flavorjones/loofah).  

I think there is a little gap between Loofah and Gollum. Even if I write some code like

```Ruby
my_scrubber = Loofah::Scrubber.new do |node|
  if node.name == "link"
    Loofah::Scrubber::STOP
  end
end
```

How can I make this Scrubber work in Gollum?

Could you please add some examples in [Security](https://github.com/gollum/gollum/wiki/Security)?

**Comment by dometto** [comment]
Added examples to the relevant wiki page
