### ISSUE TITLE
Gollum 5.0.1 can't open the right directory, if it's name has space

### ISSUE THREAD

**Issue by fanhongtao** [gollum/gollum#1597]
**Describe the bug**
If a directory's name has space, Gollum can't open the  it in 'Overview' mode.

**To Reproduce**
1. Create a new page, with name '/maths/chapter1 abc/section1 number'.
![new-page](https://user-images.githubusercontent.com/402665/87783701-98dc9100-c867-11ea-863f-8c3d7f73e467.png)

2. Visit page '/gollum/overview/maths/' ( Click 'Overview' button, and then click link 'maths' )
![maths](https://user-images.githubusercontent.com/402665/87783904-f244c000-c867-11ea-9b37-cc0ae77a2f31.png)

3. Click link 'chapter1 abc'.
![not-found](https://user-images.githubusercontent.com/402665/87783922-f83aa100-c867-11ea-9535-213b05e7bd4d.png)

**Expected behavior**
When click 'chapter1 abc', gollum should open directory 'chapter1 abc' , and list page(s) in it.

**Environment Info**

> gollum --version
Gollum 5.0.1

**Comment by bartkamphorst** [comment]
Looks like a duplicate of https://github.com/gollum/gollum/issues/1572, which I recall should be fixed on `master`. @fanhongtao Can you double check that this issue goes away if you use the latest version from `master`?

**Comment by fanhongtao** [comment]
Yes,  it goes away. Thanks.

**Comment by dometto** [comment]
Fix released in 5.1
