### ISSUE TITLE
Bibliography and citations fail to render

### ISSUE THREAD

**Issue by zverhope** [gollum/gollum#1598]
I’m unable to render either my bib file or citations from bib files in my markdown files. I have all of the necessary dependencies installed (pandoc, pandoc-citeproc, bibtex-ruby, citeproc-ruby, pandoc-ruby, and csl) and the bib file, markdown file, and csl are all committed to the repo. 

I've triple-checked the formatting of the bib file with BibDesk, and have also tried a single-citation file and note:

The `test.md` file is

```
---
title: Test bib
bibliography: test.bib
---

This is a test document [@Harris1992].
```

and the corresponding `test.bib`

```
@article{Harris1992,
	Abstract = {Abstract This article reviews interpretations of the history of British society during the Second World War. Traditionally the Second World War has been viewed as a period of outstanding national unity and social solidarity, and the social arrangements of wartime have been seen as a unique catalyst of administrative 'collectivism'and the growth of the 'welfare state'. More recent historiography has presented a more diffuse picture, emphasising the elements of.},
	Author = {Harris, Jose},
	Journal = {Contemporary European History},
	Keywords = {zvh:project:books_bombs},
	Title = {War and Social History: Britain and the Home Front During the Second World War},
	Year = {1992}}
```

Screenshots of what is rendered (or not rendered) are below. I'm sure I must be missing something quite simple, but I've attempted a bunch of possible solutions and no luck so far. Any help anyone can provide would be so appreciated.

Great work on 5.0 btw!
![Screenshot 2020-07-21 13 46 06](https://user-images.githubusercontent.com/27869239/88094127-abe9ac80-cb58-11ea-9fae-5ee59547364b.jpg)
![Screenshot 2020-07-21 13 46 31](https://user-images.githubusercontent.com/27869239/88094131-adb37000-cb58-11ea-9c85-d52d11fa3f0d.jpg)

**Comment by dometto** [comment]
Sorry for the slow reply @zverhope! Could you post the output of `gollum --versions` please?

I think the problem might be that `pandoc-ruby` is being overridden as the rendering engine in case the `commonmarker` gem (and perhaps also others) is present. At least, I was able to reproduce the problem by installing commonmarker. A quick fix for your problem could thus be to:

`gem uninstall commonmarker`

(Or uninstall whatever markdown renderer is being used by default -- the `--versions` switch will tell you)

Nevertheless, this shouldn't be happening. I'll try to come up with a more permanent fix.

**Comment by dometto** [comment]
See https://github.com/gollum/gollum-lib/pull/384

**Comment by dometto** [comment]
Solved in the latest gollum-lib bugfix release.
