### ISSUE TITLE
[Discussion] Show SVG images with external CSS

### ISSUE THREAD

**Issue by fanhongtao** [gollum/gollum#1601]
# 1 Background

When I write code like:

```markdown
[[ /uploads/s001-qu-xian-002.svg ]]
```
Gollum will turns it into :

```html
<img src="/uploads/s001-qu-xian-002.svg" />
```
If the SVG file has all the code, not include an external file, that works well. 

BUT there are a lot of SVG files in my wiki, and the SVG files have a common external css file `default-style.css`. So there is a problem. The `<img>` just read & draw the SVG file, not the included CSS.

After some test, I find that `<embed>` can do what I want. Here's what I do.

# 2 Write a Gollum Macro

At first, I try to write a gollum macro.  After read [MACROS](https://github.com/gollum/gollum/wiki#macros), I write the fellowing code in `config.rb` :

```ruby
module Gollum
  class Macro
    class SVG < Gollum::Macro
      def render (fname)
        "<embed src=\"#{fname}\" \" type=\"image/svg+xml\" />"
      end
    end
  end
end
```

Now, change code in markdown from  `[[ /uploads/s001-qu-xian-002.svg ]]`  to `<< SVG( /uploads/s001-qu-xian-002.svg) >>`. 

It works.  EXCEPT the modification of makrdown after drag & drop a SVG file.

# 3 Use JQuery to change HTML in client (browser)

With JQuery, we can change HTML dynamically. So I end up the code in `custom.js` ( start gollum with `-js` arg) 

```js
$(document).ready(function() {
  formatSVG();
});

function formatSVG() {
  $("img[src$='.svg']").each(function (imgindex, imgitem) {
    var ele = $("<embed src=\"" + imgitem.src + "\" type=\"image/svg+xml\" />");
    $(imgitem).replaceWith(ele);
  });
}
```

In this way, we don't need to change the markdown code created by drag & drop.

# 4 My Question

Does gollum need to treat SVG as a special image type? Or just let gollum user to play some tricks?

---
[svg-test.tar.gz](https://github.com/gollum/gollum/files/5001826/svg-test.tar.gz)

**Comment by dometto** [comment]
Hi @fanhongtao! Sorry for the late reply to this. I'm not 100% sure what your remaining question is: it seems like you've got it working nicely! iIs there something that still doesn't work for you?

Or is your question whether it's possible to include some of these changes in gollum by default? I'm not sure that's possible, because it's the markdown rendering gems that are responsible for turning e.g. `[[ /uploads/s001-qu-xian-002.svg ]]` into HTML.

**Comment by fanhongtao** [comment]
When I found issue, it cost me a few days to work around, so I post this question. What I mean is: it's possible to include some of these changes in gollum by default.

Since this is just a minor issue, and can be solved with a little work. Now I think, there is no need to change gollum. Thanks anyway.

**Comment by dometto** [comment]
Understood! I think your SVG Macro may be of interest to other people -- if you like, you could share it by linking to a gist on [this wiki page](https://github.com/gollum/gollum/wiki/Custom-macros)!
