### ISSUE TITLE
Is it possible to use variables in _Template?

### ISSUE THREAD

**Issue by tevino** [gollum/gollum#1603]
For example:

`_Template.md`

```markdown
Date: {{YYYY-MM-DD}}

# {{page_name}}

Body

...
```

**Comment by dometto** [comment]
Hi! No, this is not possible at the moment. But you could perhaps [define a Macro](https://github.com/gollum/gollum/wiki#custom-macros) to achieve both ends:

* a `Date()` macro that outputs the current date using ruby's built in date functions
* a `CurrentPage()` macro that uses Gollum's `Macro` class [new `active_page` method](https://github.com/gollum/gollum-lib/pull/380/files#diff-00e41296bb0175ab8f262d99316b357eR28)

If you end up implementing these Macro's, please open a PR at gollum-lib -- we would be very interested!

**Comment by tevino** [comment]
@dometto Thanks for the info, I don't know ruby, but I'll give it a try.

**Comment by tevino** [comment]
It seems that [Macro](https://github.com/gollum/gollum/wiki#custom-macros) is expanded at rendering time, in that case, a `Date()` macro outputs the current date is not very useful.

What I wanted is a macro expanded in edit mode, so that what's written in the result markdown files is the expanded content instead of the macro markup. Is there anything like that? @dometto
