### ISSUE TITLE
Can't add <script> to whitelist

### ISSUE THREAD

**Issue by fanhongtao** [gollum/gollum#1606]
After read [Security](https://github.com/gollum/gollum/wiki/Security), I add fellowing code to `config.rb`

```ruby
::Loofah::HTML5::SafeList::ALLOWED_ELEMENTS_WITH_LIBXML2.add('link')
::Loofah::HTML5::SafeList::ALLOWED_ELEMENTS_WITH_LIBXML2.add('script')
```

One of my wiki page, has code:

```html
<link rel="stylesheet" type="text/css" href="http://apps.bdimg.com/libs/fontawesome/4.2.0/css/font-awesome.min.css">
```

Another page has:

```html
<script type="text/javascript" src="calc-interval.js"></script>
```

Test result:

* Page with `<link>` works well.
* Page with `<script>`, can't see `<script>` in the HTML.

Do I need some extra config code to add `script` to the whitelist ?

Gollum version: 5.1

**Comment by dometto** [comment]
Yes, gollum explicitly scrubs script tags in the body of a wiki page. But you can use the `--js` switch to include custom Javascript (don't forget to commit your `custom.js` to the repository).
