### ISSUE TITLE
Support for folders (directories)

### ISSUE THREAD

**Issue by ParadoxV5** [gollum/gollum#1607]
Hello,

I’m in a scenario where I’d like to organize my local pages in a folder (directory)-oriented structure and push them to GitHub Wiki.
I was expecting to see the online page names displaying their full paths (separated by `/` at each level) relative to the root folder on GitHub Wiki (for example, `Building/Android`); instead, GitHub wiki only displays the files’ names without mentioning their residing subfolder.

I would like to know if this is a feature request for Gollum or rather GitHub’s oversight.
If it’s the latter, can you kindly mention how to contact GitHub for issues specific to GitHub Wiki?

**Comment by dometto** [comment]
Sorry, Gollum is not in any way part of or affiliated with GitHub.
