### ISSUE TITLE
Pages with some non alpha numeric characters are not edited

### ISSUE THREAD

**Issue by Se6** [gollum/gollum#1615]
**Describe the bug**
If you create a page name with non alpha numeric characters, you can not edit it afterwards. 

**To Reproduce**
1. Create a new page named  C++
2. Edit it afterwards, it will have no effect. You will only get the original page you created as if no edit happened.

**Environment Info**
Gollum 5.1.1
That used to be fine prior version 5.

**Comment by bartkamphorst** [comment]
Good find; thanks for reporting @Se6 . I can confirm the behavior: the page `C++.md` is created on disk, but the resulting page url is encoded as `C%2B%2B.md`, which seems to cause the subsequent behavior.
