### ISSUE TITLE
YAML front matter doesn't work in editing preview

### ISSUE THREAD

**Issue by CrustyAuklet** [gollum/gollum#1617]
**Describe the bug**
When using the YAML front matter, the page preview shows a YAML parsing error.

**To Reproduce**
1. Create a new page or edit an existing page
2. Use YAML front matter (for example to set the page title)
3. Click the preview tab in the gollum editor
4. YAML parsing error is shown at the top of the preview
5. If changes are saved, the page is rendered as expected

**Expected behavior**
Page preview should look like the final rendering of the page, with YAML front matter taken into account.

**Screenshots**
**Editing the page:**
![image](https://user-images.githubusercontent.com/9755578/93683044-ad095e00-fa63-11ea-92c6-67e9b2b5a9ff.png)

**Preview of page while editing:**
![image](https://user-images.githubusercontent.com/9755578/93683208-babee380-fa63-11ea-8a51-347f24c9feda.png)

**View of page once saved:**
![image](https://user-images.githubusercontent.com/9755578/93683360-c7dbd280-fa63-11ea-879d-a82506b61a66.png)

**Environment Info**
```sh
gollum@red-markdown2:~$ gollum --versions
Gollum 5.0.1
Running on: x86_64-linux-gnu with Ruby version 2.7.0
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.4
Markdown rendering gem: kramdown
Other renderering gems:
org-ruby 0.9.12
```

**Comment by bartkamphorst** [comment]
Can confirm the behavior as well as the typo in the error message 😅 (frontmater).

**Comment by bartkamphorst** [comment]
Here's the difference:
```
# Normal render:
"---\nkey: value\nfoo: bar\nex: ample\n"

# Preview render:
"---\r\nkey: value\r\nfoo: bar\r\nex: ample\r\n"
```

**Comment by dometto** [comment]
Strange! Should we just replace all `\r` with `\n` in the preview route?

**Comment by bartkamphorst** [comment]
Fixed on gollum-lib master with this [PR](https://github.com/gollum/gollum-lib/pull/386).

**Comment by CrustyAuklet** [comment]
thanks! that was really quick :)
