### ISSUE TITLE
Query: Does gollum support backlinks?

### ISSUE THREAD

**Issue by anthrolisp** [gollum/gollum#1622]
Does gollum support backlinks? Thanks in advance!

**Comment by dometto** [comment]
Sorry @anthrolisp, not sure what you mean by backlinks in this context! Of course, other websites can link to your gollum instance, provided that it is hosted publicly on the internet. I'll close this for now, but please feel free to expand!

**Comment by raghuveerdotnet** [comment]
Backlinks in the wiki/note-taking tool context are reverse links, meaning if I have an `A.md` file that references a ` B.md` file, the `B.md` file should list all the links to it in the entire wiki.

For ex: Let's say there is a file called `Foo.md`

```
# Foo Heading

foo content that references [[Bar.md]]
```

Now when I go to `Bar.md`, it should show:

```
# Bar Heading

bar content, bla blu bleh

# Backlinks
---
Foo.md
Doo.md
Moo.md
```

**Comment by dometto** [comment]
Thanks for the explanation @raghuveerdotnet! This is currently unsupported. It would be possible to [write a Macro](https://github.com/gollum/gollum/wiki#custom-macros) that does this, that would crawl through the wiki looking for matching links. However, in a large wiki, that would not perform very well: the entire wiki would be crawled every time the page is rendered.

A better performing solution would be to write a (ruby or shell) script that crawls the wiki and generates backlinks. That script could be run periodically in cron, or be ran as a git-hook upon a commit. We do not have plans to work on such a solution ourselves, but would be happy to coach and help anyone out who wants to work on it. It would make for a great addition to our `contrib` directory.
