### ISSUE TITLE
Add support to extract user's name and email from HTTP headers (injected by authenticating reverse proxy)

### ISSUE THREAD

**Issue by pdinc-oss** [gollum/gollum#1624]
This feature request will allow F5, Apache HTTPD, etc reverse proxies to inject authoritative HTTP headers on every request to inform Gollum as to the identity of the remote user.

--enable-authentication [MODE]

Where mode HTTP_HEADER is expected

The headers will follow the convention described in https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

- GIT_AUTHOR_NAME is the human-readable name in the “author” field.
- GIT_AUTHOR_EMAIL is the email for the “author” field.
- GIT_COMMITTER_NAME sets the human name for the “committer” field.
- GIT_COMMITTER_EMAIL is the email address for the “committer” field.

Later the names can become configurable.

Please assign to us, patch will be forthcoming.

**Comment by pdinc-oss** [comment]
- there really should be a header name override config option.
- it currently ignores the committer headers

**Comment by pdinc-oss** [comment]
We deployed this to our production system, will provide feedback after a week of usage.

**Comment by dometto** [comment]
hi @pdinc-oss, wondering if you've had any success with this. :)

**Comment by pdinc-oss** [comment]
> hi @pdinc-oss, wondering if you've had any success with this. :)

yes, it is working quite well - no bugs in 16 days. Looking for feedback on it at this point.

**Comment by bartkamphorst** [comment]
> Looking for feedback on it at this point.

Interesting approach! Looking forward to learning more about this.

**Comment by pdinc-oss** [comment]
> > Looking for feedback on it at this point.
> 
> Interesting approach! Looking forward to learning more about this.

What can we help explain?

**Comment by bartkamphorst** [comment]
Sorry, I meant to say that I'm awaiting your pull request. 😄

**Comment by pdinc-oss** [comment]
> Sorry, I meant to say that I'm awaiting your pull request. 😄

https://github.com/gollum/gollum/pull/1636

**Comment by dometto** [comment]
Closing in favor of discussion in #1636. @pdinc-oss it still seems to me like using omnigollum might be the best fit for your use case, but if there's something I'm missing feel free to let us know.

**Comment by pdinc-oss** [comment]
We had to fork it, as we are only using gollum - no additional software.
