### ISSUE TITLE
Encoding::CompatibilityError on page creation with template

### ISSUE THREAD

**Issue by treiher** [gollum/gollum#1626]
**Describe the bug**
An encoding error is shown when a new page is created, which contains a non-ASCII character in its name, and a template is present, which also contains a non-ASCII character.

**To Reproduce**
The issue only occurs, if `--template-page` is enabled.

1. Click on `New`
1. Enter `_Template.md` as page name
1. Click on `OK`
1. Enter non-ASCII character (e.g., Ü) as content
1. Click on `Save`
1. Click on `New`
1. Enter page name with non-ASCII character (`e.g., `Ü`)
1. Click on `OK`
1. The following error is shown:

```
Encoding::CompatibilityError at /gollum/create/%C3%9C
incompatible character encodings: UTF-8 and ASCII-8BIT
file: template.rb location: render line: 39
BACKTRACE
(expand)

JUMP TO: GET POST COOKIES ENV
/home/gollum/.gem/ruby/2.5.0/gems/mustache-0.99.8/lib/mustache/template.rb in render
      # can skip the compilation stage.
/home/gollum/.gem/ruby/2.5.0/gems/mustache-0.99.8/lib/mustache/template.rb in render
      render(context)
/home/gollum/.gem/ruby/2.5.0/gems/mustache-0.99.8/lib/mustache.rb in render
      tpl.render(context)
/home/gollum/.gem/ruby/2.5.0/gems/mustache-0.99.8/lib/mustache/context.rb in partial
      mustache.render(part, self)
/home/gollum/.gem/ruby/2.5.0/gems/mustache-0.99.8/lib/mustache/template.rb in render
      # can skip the compilation stage.
/home/gollum/.gem/ruby/2.5.0/gems/mustache-0.99.8/lib/mustache.rb in render
    return tpl.render(context) if ctx == {}
/home/gollum/.gem/ruby/2.5.0/gems/mustache-0.99.8/lib/mustache/sinatra.rb in mustache
        rendered = instance.render(instance.template, locals)
/home/gollum/.gem/ruby/2.5.0/gems/gollum-5.1.1/lib/gollum/app.rb in block (2 levels) in <class:App>
          mustache :create
/home/gollum/.gem/ruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb in call
        status, headers, body = @app.call(env)
/home/gollum/.gem/ruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb in call
        app.call env
/home/gollum/.gem/ruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb in call
        status, headers, body = app.call(env)
/home/gollum/.gem/ruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb in call
        result or app.call(env)
/home/gollum/.gem/ruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb in call
        result or app.call(env)
/home/gollum/.gem/ruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb in call
        status, headers, body        = @app.call(env)
/home/gollum/.gem/ruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb in call
      @app.call(env)
/home/gollum/.gem/ruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb in call
      status, headers, body = @app.call(env)
/home/gollum/.gem/ruby/2.5.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb in service
        status, headers, body = @app.call(env)
/usr/lib/ruby/2.5.0/webrick/httpserver.rb in service
      si.service(req, res)
/usr/lib/ruby/2.5.0/webrick/httpserver.rb in run
          server.service(req, res)
/usr/lib/ruby/2.5.0/webrick/server.rb in block in start_thread
```

**Expected behavior**
The `Create New Page` page should be shown.

**Environment Info**

```
Gollum 5.1.1
Running on: x86_64-linux-gnu with Ruby version 2.5.5
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: redcarpet
Other renderering gems:
none
```

**Comment by dometto** [comment]
@treiher just for debugging purposes, have you checked whether this bug persists when you use a different markdown rendering gem (e.g. the default kramdown -- you can achieve this by doing a `gem uninstall redcarpet`)?

**Comment by MArpogaus** [comment]
I am having the save issue with v5.2.1 regardless of the renderer I use.

    Gollum 5.2.1
    Running on: x86_64-linux-musl with Ruby version 3.0.0
    Using:
    rugged 0.99.0
    gollum-rugged_adapter 1.0
    gollum-lib 5.1
    Markdown rendering gem: pandoc-ruby
    Other renderering gems:
    org-ruby 0.9.12

This is the error trace:

    2021-03-05 08:40:01 - Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT:
	    /usr/local/bundle/gems/mustache-0.99.8/lib/mustache/template.rb:39:in `render'
	    /usr/local/bundle/gems/mustache-0.99.8/lib/mustache/template.rb:43:in `render'
	    /usr/local/bundle/gems/mustache-0.99.8/lib/mustache.rb:121:in `render'
	    /usr/local/bundle/gems/mustache-0.99.8/lib/mustache/sinatra.rb:113:in `mustache'
	    /usr/local/bundle/gems/gollum-5.2.1/lib/gollum/app.rb:371:in `block (2 levels) in <class:App>'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	    /usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'
	    /usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
	    /usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/builder.rb:63:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	    /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	    /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	    /usr/local/bundle/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	    /usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/show_exceptions.rb:22:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/configuration.rb:248:in `call'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/request.rb:76:in `block in handle_request'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/thread_pool.rb:337:in `with_force_shutdown'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/request.rb:75:in `handle_request'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/server.rb:431:in `process_client'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
    2021-03-05 08:40:02 - Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT:
	    /usr/local/bundle/gems/mustache-0.99.8/lib/mustache/template.rb:39:in `render'
	    /usr/local/bundle/gems/mustache-0.99.8/lib/mustache.rb:121:in `render'
	    /usr/local/bundle/gems/mustache-0.99.8/lib/mustache/sinatra.rb:113:in `mustache'
	    /usr/local/bundle/gems/gollum-5.2.1/lib/gollum/app.rb:371:in `block (2 levels) in <class:App>'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	    /usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'
	    /usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
	    /usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/builder.rb:63:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	    /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	    /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	    /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	    /usr/local/bundle/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	    /usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/show_exceptions.rb:22:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	    /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/configuration.rb:248:in `call'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/request.rb:76:in `block in handle_request'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/thread_pool.rb:337:in `with_force_shutdown'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/request.rb:75:in `handle_request'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/server.rb:431:in `process_client'
	    /usr/local/bundle/gems/puma-5.2.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'

**Comment by dometto** [comment]
@treiher @MArpogaus could you perhaps check if applying this small patch (to the `bin/gollum` file) fixes the issue for you?

```patch
diff --git a/bin/gollum b/bin/gollum
index 4acedd5a..b6106c3e 100755
--- a/bin/gollum
+++ b/bin/gollum
@@ -1,4 +1,4 @@
-#!/usr/bin/env ruby
+#!/usr/bin/env -S ruby -Eutf-8
 
 $:.unshift File.join(File.dirname(__FILE__), *%w[.. lib])
```

**Comment by dometto** [comment]
Just reproduced this. It's not dependent on the rendering gem.

**Comment by dometto** [comment]
Sorry for the long wait on this issue. https://github.com/gollum/gollum/pull/1758 should resolve it. I'll drop a message here when it is merged and the fix is released (soon).
