### ISSUE TITLE
Unable to put bibliography or csl into global metadata of config.rb file

### ISSUE THREAD

**Issue by zverhope** [gollum/gollum#1627]
Hi there,

Wonderful progress on the project and it's a pleasure to use and to tinker with. Many thanks to everyone involved!

A minor issue I've had is with inputting the `bibliography` and `csl` fields of the yaml metadata for my pages into the global metadata. I have a single bib file and want to format everything using the same style. It's not a huge issue to put these two fields into the yaml block at the top of each page, but would be much more inconvenient if I could enter it as global metadata in my config.rb file. This seems to work with other basic metadata, like `title`, but doesn't work with either the `bibliography` or `csl` metadata (although both reliably work when placed in the page metadata). The relevant snippet from my config.rb file is as follows:

```
wiki_options = {
  :h1_title => false,
  :live_preview => true,
  :allow_uploads => true,
  :per_page_uploads => true,
  :allow_editing => true,
  :metadata => {'csl' => 'modern-language-association.csl',
    'bibliography' => 'Library.bib'},
  :css => true,
  :js => false,
  :mathjax => false,
  # :sidebar => :left,
  :emoji => true,
  :show_all => true,
  :display_metadata => false,
}
```

Again, with a test line like ` :metadata => {'title' => 'Test title'},` this works without issue, and both of those bibliographic metadata fields work perfectly in the metadata for the specific page. They just don't seem to function as global metadata. 

Any help would be appreciated. But again, not a huge issue. My thanks in advance!

**Comment by zverhope** [comment]
Hi all,
Problem solved: I temporarily modified my page.rb file to have it print page metadata as string to see how the data was being formatted internally. By changing the key-pair values to single quotes and eliminating spaces, my bibliographic metadata can now be specified globally with the following code in my config.rb:

```
  :metadata => {"csl"=>"modern-language-association.csl",
    "bibliography"=> "Library.bib"},
```

I actually do have another minor issue to raise regarding BibTeX files not formatting correctly, but I'll do that separately and close this issue with thanks!

**Comment by zverhope** [comment]
Ok, my apologies, but never mind my last post - while the global metadata I've entered above does now show in the metadata for the individual page - in `@page.metadata` - it still doesn't render the citations for that page.

**Comment by dometto** [comment]
@zverhope we've confirmed this and are working on a fix for the issue in https://github.com/gollum/gollum-lib/pull/387
