### ISSUE TITLE
Quesiton: can I change gollum/ path?

### ISSUE THREAD

**Issue by ViChyavIn** [gollum/gollum#1628]
When you edit pages, you get redirected to `http://example.com/gollum/page`. Is it possible to change this `gollum/` path to something else?

**Comment by dometto** [comment]
There is no option for this, sorry.

If you're willing to hack the code to achieve this, you can change it to you're liking [here](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L140) and [here](https://github.com/gollum/gollum/blob/master/lib/gollum/views/helpers.rb#L16). Perhaps there are other places where `'gollum'` is hardcoded, I'm not sure. If you want to try this: no warranty and no support I'm afraid :)

Hope gollum is still useful to you without this option!
