### ISSUE TITLE
How do I serve static files for a wiki?

### ISSUE THREAD

**Issue by ViChyavIn** [gollum/gollum#1630]
I have added `<link rel="stylesheet" type="text/css" href="main.css">` to my layout.mustache template and set `:static_assets_path` option to point to a directory where the main.css (I'm running via Rack) is located but it doesn't work! It seems that it even breaks the app.js file, which doesn't get loaded either. What do I do? Is putting all my stylesheets into the mustache itself the only way?

**Comment by dometto** [comment]
Gollum provides the --css option for including custom css, see the --help or the Readme. If you really want to hack the app and replace the standard CSS, I'm sure that's possible, but I'm adraid we can't offer support on that. But yeah, the app expects all assets to be in the static assets path, so it's to be expected that this breaks app.js!

**Comment by ViChyavIn** [comment]
Thank you for your response!

**Comment by ViChyavIn** [comment]
Oh, forgot to ask. What does this static option exist if it breaks the app.js? Maybe I can put the file into the directory along with the main.css?
