### ISSUE TITLE
Is it possible do add my own emojis to a wiki?

### ISSUE THREAD

**Issue by ViChyavIn** [gollum/gollum#1631]

**Comment by bartkamphorst** [comment]
Gollum uses [gemojione](https://github.com/bonusly/gemojione) for emojis. If that gem supports custom emojis, then that should work on gollum too. Your other option would be to use something like [CSS emojis](https://emoji-css.afeld.me/) through `custom.css` and a Macro to insert the `<i>` elements. Hope this helps.
