### ISSUE TITLE
Feature Request: Split View

### ISSUE THREAD

**Issue by FlyingRatBull** [gollum/gollum#1632]
It would be very helpful to have a split view (i.e. Editor + Preview) when editing pages. Especially when using plugins like _plantuml_ I find myself regularly switching between both views which costs a lot of time. If I were to see the preview of the content while typing it, it would increase my efficiency a lot.

**Comment by bartkamphorst** [comment]
We have moved away from live preview / split view, and I don't see it coming back any time soon. You can toggle between the Editor and the Preview pane with `Ctrl-Shift-P` though if that helps.
