### ISSUE TITLE
Bibliography does not render (Ubuntu 20.04)

### ISSUE THREAD

**Issue by julianbarg** [gollum/gollum#1633]
I am still very excited about the newly added support for BibTeX. I saw that the steps for enabling bibtex support are written for mac os (brew). I am glad to report that citations on a regular entry work as expected, and a bibliography is rendered. However, the bibliography file itself does not render correctly. The YAML entries for using a bibliography are printed at the top of pages in a table, is that expected behavior?

**Error message**

```Could not render the bibliography because no valid CSL or locale file was found in the wiki or in the CSL directory. Please commited a valid file, or install the csl-styles gem. The message from the parser was: failed to extract CSL data from "en-US": No such file or directory @ rb_sysopen - en-US.```

**To Reproduce**
1. Installed all required packages from the documentation (using apt instead of brew).
2. Added and commited bibliography.bib file to repository.
3. Added apa.csl to /usr/local/share/csl/ --this allowed for citations to work on all pages.
4. For good measure, after testing, also added and commited apa.csl to the repository.
5. For good measure, after testing, also added YAML to bibliography file (first tried just csl, then also with bib path).

**Expected behavior**
Rendered bibliography appears when visiting localhost:4567/bibliography 

**Screenshots**
![image](https://user-images.githubusercontent.com/40502144/100519651-560cbd00-3167-11eb-9836-623b37a8cb41.png)

**Environment Info**
```Gollum 5.1.1
Running on: x86_64-linux-gnu with Ruby version 2.7.0
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.5
Markdown rendering gem: pandoc-ruby
Other renderering gems:
none```

**Comment by dometto** [comment]
Hi @julianbarg! Just a quick follow up question: could you make sure the `csl-styles` gem is installed via `gem list csl-styles`? If it isn't, I think that's your problem: just `gem install csl-styles` manually!

**Comment by julianbarg** [comment]
Thanks, that did the trick!
