### ISSUE TITLE
apt install ruby-gollum-lib does not create any binary ?

### ISSUE THREAD

**Issue by DrakaSAN** [gollum/gollum#1635]
When trying to install gollum, I came across the wiki, and saw that one of the recommended installation method for Debian was by using apt.

One `apt install ruby-gollum-lib` later, I cannot find anything related to gollum that is launchable from the command line.

I presume that it either wasn't intending to provide the binary itself (as it is a `lib` package), or that the bin get put in the wrong place, I am however unable to verify this by myself.

**Comment by bartkamphorst** [comment]
We do not maintain the ruby-gollum-lib apt package. Please contact [the maintainers](https://ubuntu.pkgs.org/18.04/ubuntu-universe-i386/ruby-gollum-lib_4.2.7-1_all.deb.html) of that package.
