### ISSUE TITLE
Page deletion in Overview doesn't work if base-path option is given

### ISSUE THREAD

**Issue by ViChyavIn** [gollum/gollum#1638]
**Describe the bug**
Page deletion doesn't work if you attempt this action in Overview and gollum is run with base-path option. It doesn't return any error but the deletion commit ends up empty.

**To Reproduce**
Run gollum with base-path option: `gollum --base-path wiki`

**Expected behavior**
Deletion should work

**Environment Info**
```bash
$ gollum --versions
Gollum 5.1.2
Running on: x86_64-linux-gnu with Ruby version 2.7.0
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: kramdown
Other renderering gems:
none

```

**Comment by dometto** [comment]
Possibly related to https://github.com/gollum/gollum/issues/1620

**Comment by ViChyavIn** [comment]
Worth to mention that the same bug occurs if I don't specify the base-path but use an auth middleware I've wrote: https://github.com/ViChyavIn/gollum-firebase-auth

**Comment by dometto** [comment]
Thanks! That means it's almost definitely the same issue as #1620.

**Comment by dometto** [comment]
The patch in https://github.com/gollum/gollum/pull/1639 fixes the issue with base path. @ViChyavIn could you perhaps check whether it also solves the problem without base path, but with the auth middleware?

**Comment by ViChyavIn** [comment]
Yes, it fixes both cases! But still breaks if I specify template-dir :/

**Comment by ViChyavIn** [comment]
Nevermind, the problem is probably on my side: I replaced the templates with the default versions, leaving templates-dir option and deletion worked. Thank you!

**Comment by ViChyavIn** [comment]
Ah, you changed overview.mustache but I still had the old version. Replaced it with the new one and everything worked.

**Comment by dometto** [comment]
Yeah, sorry! My initial fix broke the links to the pages in the Overview. Glad you got it working, and thanks for the feedback!
