### ISSUE TITLE
_Template in different directories does not work as documented 

### ISSUE THREAD

**Issue by alzeih** [gollum/gollum#1640]
**Describe the bug**

The gollum wiki [https://github.com/gollum/gollum/wiki](https://github.com/gollum/gollum/wiki) says that

> Using the --template-page option, you can also use _Template file that will be used as the template for creating new pages. You can have different _Template files in different directories.

However, only the /_Template file in the root directory is checked when using `--template-page` 

https://github.com/gollum/gollum/blob/123518b94066044de11f5b9231399cda6a394497/lib/gollum/app.rb#L354-L356 

**To Reproduce**
1. Create file Foo/_Template and commit to git
2. Run gollum with --template-page
3. Make a new page under Foo/

**Expected behavior**
The content of Foo/_Template should be the raw content of a new page under Foo/
This template should be able to exist and be different from other directories.

**Environment Info**
Gollum 5.1.2
Running on: x86_64-linux with Ruby version 2.7.2
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: kramdown
Other renderering gems:
none

**Comment by alzeih** [comment]
Okay, I discovered two things:

1. The template in the root directory must be named `/_Template.ext`, e.g.: `/_Template.md`, not just `/_Template`. The wiki documentation didn't make this clear. However, this doesn't solve templates in different directories, so `Foo/_Template.md` is not sufficient.

2. The following diff allows for templates in different directories.

```diff
diff --git a/lib/gollum/app.rb b/lib/gollum/app.rb
index 8f2131db..05842d99 100644
--- a/lib/gollum/app.rb
+++ b/lib/gollum/app.rb
@@ -351,10 +351,6 @@ module Precious
 
       get '/create/*' do
         forbid unless @allow_editing
-        if settings.wiki_options[:template_page] then
-          temppage = wiki_page('/_Template')
-          @template_page = (temppage.page != nil) ? temppage.page.raw_data : 'Template page option is set, but no /_Template page is present or committed.'
-        end
         wikip = wiki_page(params[:splat].first)
         @name = wikip.name
         @ext  = wikip.ext
@@ -362,6 +358,11 @@ module Precious
         @allow_uploads = wikip.wiki.allow_uploads
         @upload_dest   = find_upload_dest(wikip.fullpath)
 
+        if settings.wiki_options[:template_page] then
+          temppage = wiki_page(::File.join(@path, '/_Template'))
+          @template_page = (temppage.page != nil) ? temppage.page.raw_data : 'Template page option is set, but no /_Template page is present or committed.'
+        end
+
         page = wikip.page
         if page
           redirect to("/#{clean_url(page.escaped_url_path)}")
```

The key change is `wiki_page(::File.join(@path, '/_Template'))` and moving the block below the assignment of `@path`.

I note that https://github.com/gollum/gollum/pull/1612 is currently working in the same space, so I'll hold off submitting a PR yet, but feel free to use the above diff if you like.

The error message could either be updated to refer to `::File.join(@path, '/_Template')`, or removed entirely - I'm not sure it makes sense to include this on any new page in a folder without a _Template , it may not make sense to have a _Template in every folder.

The help text here will also need to be changed here https://github.com/gollum/gollum/blob/676811206d8d4442ec0c891b3c8be619b1dcae9c/bin/gollum#L155-L157
and here
https://github.com/gollum/gollum/blob/master/README.md

**Comment by bartkamphorst** [comment]
@alzeih I've incorporated your suggestion in https://github.com/gollum/gollum/pull/1612. Anything to add to that PR or is it good to go as far as you're concerned?

**Comment by alzeih** [comment]
@bartkamphorst LGTM!

**Comment by bartkamphorst** [comment]
Excellent, thanks @alzeih . Issue resolved in `master` by https://github.com/gollum/gollum/pull/1612.
