### ISSUE TITLE
Missing css definition breaks a header numbering (proposed fix)

### ISSUE THREAD

**Issue by ruomserg** [gollum/gollum#1642]
When using a header counting feature (header_enum: decimal) a weird behavior is observed.

* Multiple h2 headers have the same number assigned (e.g. "1.1. header2a", "1.1. header2b", etc)
* Level 3 headers are numbered incorrectly ("1.0.1 header3a","1.0.2 header3b" - note the zero digit in the middle).

Confirmed on firefox 83.0 (64 bit) on Linux.

I tracked this down to app-b205e593a30f1cc0054e2e9ed9fc8af3658d8ef4a62b9708c20f204560deefb7.css, which misses the definition of "h1{counter-reset:h2}.header-enum" (accodring to css definitions - body resets h1, h2 resets h3, h3 resets h4 and so on - but nothing resets the h2 counter).

After patching my local css-file with the missing definition, header numbering works as expected.

Could you please verify the problem and fix a css-file permanently ?

**Comment by dometto** [comment]
Thanks @ruomserg. Bug confirmed, fix confirmed! See https://github.com/gollum/gollum/pull/1643

However, I just noticed that with header numbering enbled, the 'link' icon to the left of the header is in the wrong position:

<img width="258" alt="Screenshot 2020-12-15 at 11 36 03" src="https://user-images.githubusercontent.com/147111/102204194-d6525280-3ec9-11eb-9dcb-4cd3a3b2e153.png">

If anyone has any suggestions on how to fix this, that'd be very helpful!

**Comment by ruomserg** [comment]
Thanks @dommetto for fixing the iusse! I got some time to investigate the link icon positioning. So far I've found the following:

* This link symbol is a background for an anchor defined in .markdown-body .anchor stylesheet.
* Symbol position is calculated using the header text position (empty anchor text in fact), and header numbers are introduced via another css trick and are not counted as a "text" here.
* Using sufficiently large negative margin-left it is possible to disconnect the link symbol from the numbers and move it to the left. When header numbering is not used - this would probably look ugly.

So far, I don't see any css-related trick (but it is not my field of expertise, so - please, double-check! :-) ) that could reliably offset the link symbol whenver header numbering is on or off. Thinking about the HTML generation, I see three possibilities:

* Remove the chain-link symbol from the background and put it in a body of <a...></a> as inline image/symbol. This would eliminate the black magic with background/offsets (but probably would also put the symbol in place permanently, no matter if mouse is hovering over it or not)
* Reposition it just after the header text (like the "edit" anchor). This is (probably) a little counter-intuitive (the link would point to the beginning of the text section, not at the header itself) - but not a big deal.
* Get rid of the visual  anchor link here. It just points on itself, and I can't see any use for it (other then maybe copying the link address). The (hidden) link itself would still be useful for TOC generation and cross-page links.
