### ISSUE TITLE
Bibtext citations do not render in preview

### ISSUE THREAD

**Issue by julianbarg** [gollum/gollum#1654]
The addition of support for bibtex is a huge improvement for gollum, but it seems so far it only works for saved pages. In the preview, the references are still displayed as (**???**) due to an error with YAML. The YAML error is ```Failed to load YAML frontmater: (<unknown>): mapping values are not allowed in this context at line 2 column 13```.

## Code
![image](https://user-images.githubusercontent.com/40502144/104095693-54eea580-5266-11eb-8a77-1f4b59ae6660.png)

## Preview
![image](https://user-images.githubusercontent.com/40502144/104095713-6f288380-5266-11eb-8b08-e3c1e4626c5f.png)

## Rendered page
![image](https://user-images.githubusercontent.com/40502144/104095755-b0b92e80-5266-11eb-8912-c68963385e1c.png)

**Comment by dometto** [comment]
I can't reproduce this error. Can you please let us know the output of `gollum --versions`, like the Issue Template asked? A sample repository would be of help, too.

**Comment by julianbarg** [comment]
Alright. ```gollum --versions``` output:
```
Gollum 5.1.1
Running on: x86_64-linux-gnu with Ruby version 2.7.0
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.5
Markdown rendering gem: pandoc-ruby
Other renderering gems:
none
```
Repository:
https://github.com/julianbarg/gollum_cite_prev

**Comment by dometto** [comment]
Can't reproduce on that repo either. My versions:

```
Gollum 5.1.2
Running on: x86_64-darwin18 with Ruby version 2.6.3
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: pandoc-ruby
Other renderering gems:
none
```

Try `gem update gollum gollum-lib` and see if that resolves your problem?

**Comment by julianbarg** [comment]
Alright, that resolved the issue.
