### ISSUE TITLE
Changing ace-editor colourscheme (theme) in gollum 5.1.2

### ISSUE THREAD

**Issue by zeigerpuppy** [gollum/gollum#1656]
I note that the editor div has a selector in the class for the colorscheme of the editor, in my case it's `ace-tomorrow`.

```html
<div position="absolute" style="height: 508px; width: 1138px;" id="gollum-editor-body-ace" class="form-control ace_editor ace_hidpi ace-tomorrow">
```

Is it possible to change the chosen theme, I'd like to replace it with one of the other themes (see [source here](https://github.com/ajaxorg/ace-builds/tree/master/src-noconflict) and some examples of other themes [here](https://tmtheme-editor.herokuapp.com/#!/editor/theme/Monokai).

Is there a way to select a different .js/.css for the ace-editor on startup of gollum?

**Comment by bartkamphorst** [comment]
Have you tried changing the div's class (e.g., `$('#gollum-editor-body-ace').removeClass('ace-tomorrow').addClass('ace-monokai')` through `custom.js`? Assuming the other ace themes are bundled, I would assume you can swap out themes like that. Of course you can also use `custom.css` to add your own style.

**Comment by dometto** [comment]
@zeigerpuppy have you given the proposed solution via `custom.js` a shot? If it works, it may be nice to add this to the wiki, e.g. [here](https://github.com/gollum/gollum/wiki/Custom-Styling-and-Views).

**Comment by bartkamphorst** [comment]
Ping @zeigerpuppy .

**Comment by dometto** [comment]
The following would be the correct JS:

```js
$(document).ready(function () {
window.ace_editor.setTheme('ace/theme/solarized_dark')
})
```

However, at present this only works when manually adding the theme in question to the assets, as we are only adding the default theme [here](https://github.com/gollum/gollum/blob/master/lib/gollum/public/gollum/javascript/editor.js#L9). The question is: do we want to package more ace themes with gollum? Presumably not all of them..

**Comment by bartkamphorst** [comment]
> do we want to package more ace themes with gollum?

Is there a straightforward way to load a theme from a url?

**Comment by dometto** [comment]
This seems to work, although the result is not great yet -- not sure if it needs more tweaking or the theme just doesn't look very well :):

```js
ace.config.setModuleUrl(
    "ace/theme/clouds", 
    "http://ajaxorg.github.io/ace-builds/src-noconflict/theme-clouds.js"
)
ace_editor.setTheme("ace/theme/clouds")
```

**Comment by bartkamphorst** [comment]
I think a theme is a pair of `.js` and `.css` files; and since you're only including a `.js`, maybe that's why it doesn't look great?

**Comment by dometto** [comment]
Actually, it works fine. It was just that the theme I selected had a much more visible print margin (the vertical line in the editor)! Here's what I put in `custom.js` -- don't forget to commit that file, and run gollum with `--js`:

```js
$(document).ready(function () {
window.ace.config.setModuleUrl(
    "ace/theme/clouds", 
    "http://ajaxorg.github.io/ace-builds/src-noconflict/theme-clouds.js"
)
window.ace_editor.setTheme('ace/theme/clouds')
window.ace_editor.setOption("showPrintMargin", false)
})
```

Updated the wiki [here](https://github.com/gollum/gollum/wiki/Custom-Styling-and-Views#using-customjs-and-the---js-flag).

**Comment by niels-borne** [comment]
I tried this with clouds > solarized_dark,
this has for effect of changing the color of the cursor but not the background, which remains white.
So unless I miss something obvious I wouldn't say this is working fine.
Is some custom.css missing as was suggested above ?
