### ISSUE TITLE
Installation in Windows not possible due to libssh2 not found

### ISSUE THREAD

**Issue by ffuentese** [gollum/gollum#1657]
**Describe the bug**
When I try to install gollum I get an error because the package can't be found.

Temporarily enhancing PATH for MSYS/MINGW...
Installing required msys2 packages: mingw-w64-x86_64-libssh2
error: no se pudo obtener el archivo «mingw-w64-x86_64-libssh2-1.8.0-1-any.pkg.tar.xz» desde repo.msys2.org: The requested URL returned error: 404

I'm using Windows 10 Pro.

EDIT: Also I found this bug in another project which is not solved either and points to an issue with libssh2 on Windows https://github.com/libgit2/rugged/issues/558

**To Reproduce**
1. Install gem install gollum on a Windows 10 machine

**Expected behavior**

Gollum is installed

**Screenshots**

**Environment Info**
Windows 10 PRO 
Command Prompt with Ruby

Always include the output of the `gollum --versions` command (NB: `versions` in plural).

**Comment by bartkamphorst** [comment]
What Ruby are you using? As noted in the README, "On Windows, Gollum runs only on JRuby". Are you on JRuby?

**Comment by dometto** [comment]
Closing for lack of information. Feel free to reopen @ffuentese.
