### ISSUE TITLE
MSIE support

### ISSUE THREAD

**Issue by plujon** [gollum/gollum#1664]
Under MSIE 11, a javascript exception occurs on page load because Array.prototype.includes() is used.

The exception can be avoided with the following polyfill, inserted at the top of layout.mustache, or by avoiding calls to [].includes

    if (!Array.prototype.includes) {Array.prototype.includes = function (x) { return 0 <= this.indexOf(x) }}

If Gollum is not supposed to support MSIE, perhaps that could be documented somewhere.

**Comment by dometto** [comment]
@plujon thanks for the suggested fix! Care to open a PR?

**Comment by bartkamphorst** [comment]
Thanks @garetethan for the PR. @plujon Let us know if you find anything else on MSIE that needs attention.
