### ISSUE TITLE
--js tag does not seem to work

### ISSUE THREAD

**Issue by julianbarg** [gollum/gollum#1666]
I am trying to use the --js tag to load the google analytics gtag. Cannot seem to get it to work, I tried relative path, absolute path, all kinds of different permissions.

**To Reproduce**
1. clone https://github.com/julianbarg/wiki
2. run with ```gollum . -js gtag.js```
3. Gtag should show up somewhere when you open the local instance of the wiki in the browser and use the inspect tools

**Expected behavior**
My instance of wiki runs at wiki.jbarg.net . gtag isn't there, google analytics is also not receiving anything.

**Environment Info**
```Gollum 5.1.2
Running on: x86_64-linux-gnu with Ruby version 2.7.0
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: pandoc-ruby
Other renderering gems:
none```

**Comment by bartkamphorst** [comment]
@julianbarg You've misread how the `--js` flag works (see the output of `gollum --help`).  It doesn't take an argument, but instead simply looks for a specific file to load called `custom.js` in your wiki's root. Note that you must commit `custom.js` to your repository for this to work. Hope this helps.

**Comment by julianbarg** [comment]
This helps plenty, thanks!
