### ISSUE TITLE
[RFC] Dynamic branch/ref

### ISSUE THREAD

**Issue by ivojonker** [gollum/gollum#1668]
I would love for a feature to be able to "work/serve" multiple branches at the same time, instead of only the configured -ref. 

I guess this could be done via the context-root. e.g. http://gollum/master/home.md vs http://gollum/feature-branch/home.md. This limits the use of branch-names with (back)slashes though, but i'm sure this can be overcome by introducing aliases.

Context: Our team works feature-oriented (each branch = a to-be-released-feature), but currently there's a disconnect between the technical documentation (in-branch/git) and the functional documentation (in confluence). The straight-forward solution would be to have our functional desginers document in the git-feature-branches as well, but unfortunately our designers & analysts cannot install software on their pc, as they are using strictly managed corporate machines. Gollum would fit this gap.

**Comment by bartkamphorst** [comment]
@ivojonker Part of the attraction of gollum is that it doesn't expose the underlying git structure to its users, so I don't see this being part of gollum anytime soon. My recommendation would be to fork and implement this yourself. Any further thoughts about this, @dometto ?

**Comment by ivojonker** [comment]
@bartkamphorst thanks for evaluating my request, very sound reply. While I'm no Ruby developer, your code is easy to follow and I'm pretty sure I can do the fork and implement this.
