### ISSUE TITLE
Extra space between text and carriage in editor

### ISSUE THREAD

**Issue by vvrein** [gollum/gollum#1669]
**Describe the bug**
In freshly installed Gollum app strange thing goes in text editor: carriage goes far behind after text end,  
or before text end. Behavior differs depending on char width, I suppose.

**To Reproduce**
1. Open editor
2. Start typing long line
3. Watch as carriage goes far behind text

**Expected behavior**
Carriage right at the end of the text.

**Screenshots**
[video](https://user-images.githubusercontent.com/17022100/107852388-1d50bb80-6e19-11eb-82f7-53b08291a61b.mp4)
![output](https://user-images.githubusercontent.com/17022100/107852516-bda6e000-6e19-11eb-8a64-c25860426313.gif)

**Environment Info**

| /home/vrein/.local/share/gem/ruby/2.7.0/bin/gollum --versions
```
Gollum 5.1.2
Running on: x86_64-linux with Ruby version 2.7.2
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by dometto** [comment]
Thanks for the report! Strange issue. I cannot reproduce it on Firefox and Chrome. What browser are you on? And could you verify that you don't have the same issue with the editor on https://ace.c9.io/ ? If you do, it's a bug/browser support issue in [ACE](https://github.com/ajaxorg/ace).

**Comment by vvrein** [comment]
Yup, reproducible here https://ace.c9.io/ 
Thanks!
I'm on Firefox 85.0.1

**Comment by vvrein** [comment]
Hehe, seems very old-aged issue https://github.com/ajaxorg/ace/issues/3036
Here is another similar issue https://github.com/arangodb/arangodb/issues/13117

**Comment by vvrein** [comment]
Fixed for myself: https://github.com/ajaxorg/ace/issues/3036#issuecomment-778647000
