### ISSUE TITLE
Minor styling issue: footer and sidebar touching on (nearly) empty page

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1674]
Absolutely love the improvements to the styling you've made, @benjaminwil! When giving gollum a test drive before cutting a new gem release, I just noticed a minor styling issue.

Previously, this is what an almost empty page with sidebar and footer would look like:

<img width="1058" alt="Screenshot 2021-02-20 at 11 23 33" src="https://user-images.githubusercontent.com/147111/108592518-7e731480-736e-11eb-83c4-989f40fa78c9.png">

So the existing situation is arguably already not super neat. But after recent changes, the footer's width has been extended, so we now get the slightly weirder (or maybe it's just weird in a different way:)) looking following result:

<img width="1107" alt="Screenshot 2021-02-20 at 11 23 54" src="https://user-images.githubusercontent.com/147111/108592542-964a9880-736e-11eb-9cba-433c4b7cb315.png">

It's a very minor issue as it literally only happens when the page is entirely empty or only has a single line on it. But perhaps we should put some padding between the footer and sidebar? If that's somehow complicated because the way our CSS is currently structured, I'm also happy to keep things as they are for the next gem release!

**Comment by benjaminwil** [comment]
I've submitted a PR for this. Thanks for finding this issue.
