### ISSUE TITLE
Gollum missing web server dependency required to run

### ISSUE THREAD

**Issue by elcfd** [gollum/gollum#1688]
**Describe the bug**

I would like to preface this bug report by saying that I am not a Ruby developer and therefore I am not familiar with how dependencies are pulled into a Ruby project.

I use gollum as a frontend to my private VimWiki and I run gollum in a docker container. I based my docker image from the [following instructions](https://github.com/gollum/gollum/wiki/Gollum-via-Docker#creating-the-dockerfile).

Each new gollum release I update my docker image and the recent change to gollum 5.2.x something "broke". Gollum would not start (see error message below).

**Screenshots**

```
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1755:in `detect_rack_handler': Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)
        from /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1493:in `run!'
        from /usr/local/bundle/gems/gollum-5.2.1/bin/gollum:286:in `<top (required)>'
        from /usr/local/bundle/bin/gollum:23:in `load'
        from /usr/local/bundle/bin/gollum:23:in `<main>'
```

**Solution**

From a quick search on the internet I found if I added `gem install thin` to my [Dockerfile](https://github.com/elcfd/gollum-docker/blob/master/Dockerfile) then this solved the issue.

As far as I can see the general [installation](https://github.com/gollum/gollum/wiki/Installation) instructions and the the [docker](https://github.com/gollum/gollum/wiki/Gollum-via-Docker#creating-the-dockerfile) installation instructions suggest that `gem install gollum` is good enough to get gollum up and running however the issue I am seeing is that this is not the case. Its seems that as of version 5.2.x gollum requires a web server to be installed alongside it.

My question is - shouldn't gollum specify a compatible web server package in its project's dependencies file so it is automatically pulled in at installation time?

Or should the installation instructions be updated to explicitly state that alongside gollum a web server is required to be installed?

**Environment Info**

```
Gollum 5.2.1
Running on: x86_64-linux with Ruby version 3.0.0
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.1
Markdown rendering gem: kramdown
Other renderering gems:
org-ruby 0.9.12
```

**Comment by dometto** [comment]
@elcfd this is an issue with `ruby v3.0` rather than gollum. Until version 3.0, the WEBrick webserver was part of the ruby standard library. Apparently, [not anymore](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/). You could use an older ruby, or manually `gem install webrick` (or `thin`) for now. We'll figure out how best to support ruby 3.0 elsewhere.
