### ISSUE TITLE
Support Ruby 3.0

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1689]
- [X] Make gollum pass on Travis with Ruby 3.0
- [x] Make gollum-lib pass on Travis with Ruby 3.0
- [x] WEBrick is no longer part of the standard library: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
- [x] Bugs: 
  - [x] #1655

**Comment by dometto** [comment]
Gollum tests pass on travis with ruby 3.0. Webrick is being installed there even though we don't require it explicitly. Maybe this has something to do with the travis environment.

One [test failure](https://travis-ci.org/github/gollum/gollum-lib/jobs/760786784) for gollum-lib, which seems related to #1655.

**Comment by dometto** [comment]
I better understand what's going on with `webrick` now. `rake` happens to depend on (an old version of) `webrick`, so when running gollum via `bundle exec`, it happens to be there even on ruby 3.0. When installing gollum via `gem install`, development dependencies (i.e. `rake`) are not installed, and so webrick is not available.

Shall we simply fix this by adding `webrick` as an explicit dependency? Folks who want to use another server can always do that using a `config.rb`. See here for the sinatra [howto](https://stackoverflow.com/questions/15755085/how-do-you-choose-your-http-server-in-sinatra). (Since nobody has ever complained about this, I don't think gollum needs to have its own command line switch for this?)

**Comment by bartkamphorst** [comment]
Adding webrick as a dependency seems fine. 👍

**Comment by dometto** [comment]
Ruby 3.0 support now available by running `gem update gollum-rugged_adapter` (`v1.1` of that gem or higher required).
