### ISSUE TITLE
[Feature Request] Set default editor keybinding

### ISSUE THREAD

**Issue by joroec** [gollum/gollum#1691]
First of all, thanks for the **great** open-source software! I really appreciate my local wikis a lot!
I recently found out that the editor even supports vim bindings which makes Gollum *almost* perfect for my use case!

However, I did not find an option to change the default keybindings to vim so that one does not switch from "default" editor mode to "vim" editor mode everytime a new page is opened.

Did I miss the feature? If not, do you think such a feature might be useful for multiple users and not just me?
I might be even able to look into it if someone can tell me which files to touch roughly. Obviously, I cannot promise anything.

Looking forward to your feedback!

Greetings,
Jonas

**Comment by fuzzylemma** [comment]
I have a local hack working that forces vim to be the default. I'm working on a making it configurable and will share once functioning

**Comment by darless1** [comment]
I personally use VIM on a daily basis, and would have no issue with this change, however, isn't this really a per-user configuration? 
- Is there any concept of users? I didn't think I saw anything there. If there was, then it could be done as a user preference.
- Otherwise, this could be saved in the browser storage and the JS modified to go off of that if its available.

**Comment by townsen** [comment]
Implementing this would be a great idea for VIM users - you have my vote! @fuzzylemma - I just hope your real name isn't [Pierre de Fermat](https://en.wikipedia.org/wiki/Fermat%27s_Last_Theorem) ;-)

**Comment by fuzzylemma** [comment]
> isn't this really a per-user configuration?
Yea, my solution is a server side config. I imagine this will benefit those hosting their own for personal use cases (like myself), rather than multi-user use cases. Although, multi-user cases will probably be fine with default keybind settings.

**Comment by fuzzylemma** [comment]
PR submitted: https://github.com/gollum/gollum/pull/1756
