### ISSUE TITLE
Navbar button highlighting issues

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1692]
**Describe the bug**

* The navbar buttons and search bar light up on focus. However, for the search bar and the buttons on the far left and far right, this highlighting is clipped. Have a look at the screenshots to see what I mean. 

* The search bar's height is different from the buttons. This is easily fixed by adding the class `input-sm` to the search bar. (Note that the clipping of the Home button highlight becomes worse without any padding from the (currently) larger input element.)

* The Rename button is the only button that does not show the highlighting on focus. It's unclear to me why.

**To Reproduce**

1. Go to the landing page
2. Click on the search bar
3. Observe the  clipped highlighting

**Expected behavior**

I would expect the search bar to have the same height as the buttons. I would expect highlighting to be visible all around the buttons and search bar.

**Screenshots**

![Screenshot 2021-03-02 at 21 26 03](https://user-images.githubusercontent.com/571173/109710710-4c4b8900-7b9e-11eb-98d6-98f1ba19714b.png)
![Screenshot 2021-03-02 at 21 26 14](https://user-images.githubusercontent.com/571173/109710712-4ce41f80-7b9e-11eb-8aa6-d478863db5da.png)

![Screenshot 2021-03-02 at 21 31 24](https://user-images.githubusercontent.com/571173/109711088-c24ff000-7b9e-11eb-9999-872444dd11a8.png)
![Screenshot 2021-03-02 at 21 44 02](https://user-images.githubusercontent.com/571173/109712570-7a31cd00-7ba0-11eb-9021-b1a0d5317ed2.png)

**Environment Info**

```
Gollum 5.2.1
Running on: java with Ruby version 2.6.5
Using:
rjgit 5.7.0.2
gollum-rjgit_adapter 0.6
gollum-lib 5.1
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by benjaminwil** [comment]
Thanks. I believe I know what's going on here.
