### ISSUE TITLE
[Discussion] Style Tables with rounded corners?

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1693]
Just looking at a simple table, it occurred to me that we might want to style these similarly to our search bar, buttons, Footer and Sidebar, namely with rounded corners. Any thoughts @benjaminwil @dometto ?

![Screenshot 2021-03-02 at 22 09 46](https://user-images.githubusercontent.com/571173/109715703-448ee300-7ba4-11eb-88e9-8761c56fd75b.png)

**Comment by benjaminwil** [comment]
I think this would be a reasonable change.

While I am in there, I will also maybe look into making wide tables easier to view on mobile devices. I think a common strategy for this to use `overflow-x` styles.

**Comment by bartkamphorst** [comment]
Sounds good! 👍

**Comment by benjaminwil** [comment]
A small update for you.

This is actually somewhat complicated, because the borders belong to the child border elements (`<td>`, `<th>`, and so on), and not necessarily the `<table>`.

There are also many optional `<table>` children to take into account, like `<caption>`, `<tfooter><th>`s, and more.

I will look around to see if others have already implemented something similar that we could borrow from. Otherwise, it may be a lot of work for not-too-much benefit.

**Comment by benjaminwil** [comment]
As an example, I found [this demo on Codepen](https://codepen.io/mlms13/pen/CGgLF).

It looks good, but if you replace the demo table with this one:

```
<table>
  <caption>This is a table caption</caption>
  <thead>
    <tr>
      <th>Table Header 1</th><th>Table Header 2</th><th>Table Header 3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Division 1</td><td>Division 2</td><td>Division 3</td>
    </tr>
    <tr class="even">
      <td>Division 1</td><td>Division 2</td><td>Division 3</td>
    </tr>
    <tr>
      <td>Division 1</td><td>Division 2</td><td>Division 3</td>
    </tr>
    <tr>
      <td colspan="3">A row with a cell spanning all 3 columns</td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <th>Table Footer 1</th><th>Table Footer 2</th><th>Table Footer 3</th>
    </tr>
  </tfoot>
</table>
```

The `<tfoot>` elements are kind of broken. I spent a few minutes attempting to make more specific CSS changes to handle those elements but wasn't getting anywhere. I will likely try again once more later. Just thought I would post this all here in case someone else wanted to try it out.
