### ISSUE TITLE
Tabnav in the editing view is no longer styled correctly

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1694]
**Describe the bug**

The Tab nav in the editing view is no longer styled correctly. At least, I'm pretty sure it was working properly before the upgrade to the new Primer version.

**To Reproduce**
1. Go to landing page
2. Click on 'Edit'
3. Observe the Tab navigation Edit / Preview

**Expected behavior**

Only the selected tab is shown.

**Screenshots**

* Current behavior

![Screenshot 2021-03-02 at 22 15 47](https://user-images.githubusercontent.com/571173/109716382-1bbb1d80-7ba5-11eb-954d-ec454c2dd05f.png)

* Expected behavior 

![Screenshot 2021-03-02 at 22 16 04](https://user-images.githubusercontent.com/571173/109716384-1c53b400-7ba5-11eb-8ba0-11df2ff94674.png)

**Environment Info**

```
Gollum 5.2.1
Running on: java with Ruby version 2.6.5
Using:
rjgit 5.7.0.2
gollum-rjgit_adapter 0.6
gollum-lib 5.1
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by benjaminwil** [comment]
Interesting. I will take a look into this soon.

**Comment by dometto** [comment]
Thanks for the fix @benjaminwil!
