### ISSUE TITLE
[Question] Using Gollum with remote repo?

### ISSUE THREAD

**Issue by TilCreator** [gollum/gollum#1698]
I would like to use Gollum in combination with a local Gittea server.
The goal is to be able to push to the repo on the Gittea server and see the change in Gollum and also the other way around: Editing something on Gollum and having that change in the repo on Gittea.
This would allow to have all the data on Gittea and using issues and similar features easily.

Is something like this possible?
Something like setting `stateDir` to `git://git@gittea-instance.example:user/wiki.git`.
A workaround would also be to use the webhooks of gittea or a cronjob to pull/push, but that isn't pretty at all.

**Comment by dometto** [comment]
Gollum uses git as a backend, and git isn't meant for networking operations like this.* Note that gollum itself has support for hooks. I think it should be possible to set up a relatively neat sync via hooks.

*I'm not saying it's impossible. The way to go would be to implement a [git adapter](https://github.com/gollum/gollum/wiki/Git-adapters) for gollum that uses the Gitea api to effectively mimic calls to git. But we won't be implementing that ourselves. :)

**Comment by TilCreator** [comment]
thx
Implementing that for one specific git server api doesn't sound like a good use of time for sure.

Can you give me a hint at how to work with the hooks and is there some documentation / list of them?

**Comment by dometto** [comment]
There's some here: https://github.com/gollum/gollum/wiki/Hooks

Hope it's clear enough!

**Comment by TilCreator** [comment]
thx
