### ISSUE TITLE
ArgumentError - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by antage** [gollum/gollum#17]
```
$ /opt/ruby-1.9.2/bin/ruby -v
ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-linux]
$ /opt/ruby-1.9.2/bin/gem -v
1.3.7
$ echo $LANG
ru_RU.utf8

$ cd workspace/wiki && /opt/ruby-1.9.2/bin/gollum
== Sinatra/1.0 has taken the stage on 4567 for development with backup from Thin
>> Thin web server (v1.2.7 codename No Hup)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:4567, CTRL+C to stop
```

After hit http://localhost:4567/ I got error:
    ArgumentError - invalid byte sequence in UTF-8:
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/ruby1.9.rb:3:in `ord'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/ruby1.9.rb:3:in`getord'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby/internal/loose.rb:130:in `legacy_loose_object?'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby/internal/loose.rb:43:in`get_raw_object'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby/internal/loose.rb:32:in `[]'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby/repository.rb:84:in`block in get_raw_object_by_sha1'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby/repository.rb:83:in `each'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby/repository.rb:83:in`get_raw_object_by_sha1'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby/repository.rb:334:in `walk_log'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby/repository.rb:287:in`log'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby/repository.rb:306:in `rev_list'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby.rb:68:in`block in rev_list'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby.rb:224:in `block in try_run'
     /opt/ruby-1.9.2/lib/ruby/1.9.1/timeout.rb:57:in`timeout'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby.rb:223:in `try_run'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/git-ruby.rb:68:in`rev_list'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/commit.rb:94:in `find_all'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.1.0/lib/grit/repo.rb:261:in`commit'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/gollum-1.0.1/lib/gollum/page.rb:254:in `find'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/gollum-1.0.1/lib/gollum/wiki.rb:74:in`page'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/gollum-1.0.1/lib/gollum/frontend/app.rb:132:in `show_page_or_file'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/gollum-1.0.1/lib/gollum/frontend/app.rb:38:in`block in class:App'
     /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:865:in `call'
     ....

**Comment by mmeroberts** [comment]
Newbie question- running on windows but seeing this - what do I have to do to fix this?
