### ISSUE TITLE
Question: Best Practice for Gollum to Jekyll

### ISSUE THREAD

**Issue by white-gecko** [gollum/gollum#1703]
I would like to convert a Gollum Wiki to a static site with Jekyll.

* I found https://github.com/dreverri/gollum-site which does not as nice as jekyll and last commit 2014
* There is https://github.com/rubyunworks/jekyll-gollum (last commit 2016) which suggests to use https://github.com/rubyunworks/jekyll-transform
* https://github.com/rubyunworks/jekyll-transform (last commit 2016)

Is this still the best choice to use jekyll-transform or what are people using theses days?

This is related to #22 and #712.

**Comment by dometto** [comment]
I'll close this as it's not really a bug report or feature request. I think you'd be better off asking on StackExchange (also among `jekyll` users). If any concrete features or bugs connected to `jekyll` interop emerge, feel free to open a ticket here though!

**Comment by white-gecko** [comment]
Thank you.
https://stackoverflow.com/questions/66819481/best-practice-to-convert-a-gollum-wiki-to-a-jekyll-site
