### ISSUE TITLE
Add support for Obsidian.md files (feature request)

### ISSUE THREAD

**Issue by viaahmed** [gollum/gollum#1705]
Obsidian.md is kind of offline wiki builder. It is completely based on markdown and other markup languages. It would be nice if Gollum would support Obsidian.md syntax and import-export

**Comment by viaahmed** [comment]
[website](obsidian.md)

**Comment by dometto** [comment]
hi @viaahmed! Thanks for your suggestion. Could you be a bit more specific about what gollum could do to improve interoperability with Obsidian? If I understand well, Obsidian files are plain markdown files, so gollum should already be able to render them. Is there for example a difference in how Obsidian and gollum currently handle links to other pages?

**Comment by viaahmed** [comment]
> hi @viaahmed! Thanks for your suggestion. Could you be a bit more specific about what gollum could do to improve interoperability with Obsidian? If I understand well, Obsidian files are plain markdown files, so gollum should already be able to render them. Is there for example a difference in how Obsidian and gollum currently handle links to other pages?

Thanks for your quick response.
Does Gollum allows those **[[]]** wikilinks feature? And also the Obsidian dev team have implemented some non-standard their style syntax for extending markdown so, if Gollum could also allow that.
These include:
- Block referencing
- Comments
- ~~Some custom  codefences (eg the embed search query)~~

**Comment by bartkamphorst** [comment]
The basics should work. In the past, I've copied a gollum wiki to an Obsidean vault and that worked just fine (Obsidean rendered the network view and all). The other way around I have not yet tried, but it should work. Custom CSS is supported through `custom.css`.

**Comment by vcavallo** [comment]
The issue is with links.

Given a file structure like this:

```
index.md
notes/media-and-communication.md
```

and an index page that has these contents:

```
# index
- [[media-and-communication]]
```

Obsidian will render that link correctly and it will link to the proper file in `notes/`. Gollum renders that link as `http://localhost:4567/media-and-communication` which is not correct (the correct link would be `http://localhost:4567/notes/media-and-communication`)

**Comment by vcavallo** [comment]
Sorry - I've confirmed that `--lenient-tag-lookup` resolves my issue!
