### ISSUE TITLE
Empty HTML page title

### ISSUE THREAD

**Issue by jqdg** [gollum/gollum#1709]
The HTML page title is empty for all pages in the wiki. The page source has:
```html
<title></title>
```
I have tried different combinations of setting the title metadata, running with `--h1-title`, etc., but the title is always empty.

**Environment Info**

```
Gollum 5.2.2
Running on: x86_64-darwin18 with Ruby version 2.7.2
Using:
rugged 1.1.0
gollum-rugged_adapter 1.1
gollum-lib 5.1
Markdown rendering gem: kramdown
Other renderering gems:
asciidoctor 2.0.12
```

**Comment by bartkamphorst** [comment]
Confirmed.

**Comment by benjaminwil** [comment]
I am happy to look into this.
