### ISSUE TITLE
`cloned_testpath` expects some user git configuration to remain unset

### ISSUE THREAD

**Issue by benjaminwil** [gollum/gollum#1711]
**Describe the bug**

If the user's system `git` has configuration for `init.defaultBranch` or `init.templateDir` set, the `#cloned_testpath` helper method, which is used to set up many tests, does not work as expected. It causes many test suites to break when being run locally.

This is because it uses `%x{}` to reach out to the system's `git` binary and `git clone` with it. But it expects the user to be using default git settings, which is not always the case.

**To Reproduce**

The simplest way to reproduce this bug is to ensure you're on `git` 2.28 or newer and set the new `init.defaultBranch` configuration setting. I, however, ran into the issue using the `init.templateDir` setting, which is available on older versions of git.

1.  Run `git config --local init.defaultBranch "non-standard-value"`
   You could also reproduce using the `--global` flag, but this could be disruptive if you forget to change the value back after reproduction.
2. Run tests (`bundle exec rake test`)
3. See the failures. (One is pasted below.)
4. Don't forget to unset your `init.defaultBranch` setting, or set it back to a value that will work with `gollum`: `git config --locale init.defaultBranch "master"`

You'll see failures like this:

```
Rugged::RepositoryError: could not find repository from '/private/var/folders/pj/_b1vhm850wl5y9f7fjd
58nbc0000gn/T/4_x____5_x_tag_migrator20210404-8539-1e1m630'
/Users/bw/Projects/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-rugged_adapter-1.1/lib/rugged_adapter/git_layer_rugged.rb:567:in `new'
/Users/bw/Projects/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-rugged_adapter-1.1/lib/rugged_adapter/git_layer_rugged.rb:567:in `initialize'
/Users/bw/Projects/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-lib-5.1/lib/gollum-lib/git_access.rb:16:in `new'
/Users/bw/Projects/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-lib-5.1/lib/gollum-lib/git_access.rb:16:in `initialize'
/Users/bw/Projects/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-lib-5.1/lib/gollum-lib/wiki.rb:127:in `new'
/Users/bw/Projects/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-lib-5.1/lib/gollum-lib/wiki.rb:127:in `initialize'
/Users/bw/Projects/gollum/bin/gollum-migrate-tags:235:in `new'
/Users/bw/Projects/gollum/bin/gollum-migrate-tags:235:in `<top (required)>'
/Users/bw/Projects/gollum/test/test_migrate.rb:43:in `load'
/Users/bw/Projects/gollum/test/test_migrate.rb:43:in `block in load_script'
/Users/bw/Projects/gollum/test/test_migrate.rb:42:in `chdir'
/Users/bw/Projects/gollum/test/test_migrate.rb:42:in `load_script'
/Users/bw/Projects/gollum/test/test_migrate.rb:64:in `block (2 levels) in <top (required)>'
============================================================================================
/Users/bw/Projects/gollum/test/test_migrate.rb:37: warning: already initialized constant HYPHENATE
/Users/bw/Projects/gollum/test/test_migrate.rb:37: warning: previous definition of HYPHENATE was here
/Users/bw/Projects/gollum/test/test_migrate.rb:37: warning: already initialized constant PAGE_FILE_DIR
/Users/bw/Projects/gollum/test/test_migrate.rb:37: warning: previous definition of PAGE_FILE_DIR was here
/Users/bw/Projects/gollum/bin/gollum-migrate-tags:91: warning: already initialized constant REPO
/Users/bw/Projects/gollum/bin/gollum-migrate-tags:91: warning: previous definition of REPO was here
```

**Expected behavior**

Tests should pass.

**Environment Info**

```
⅋ bundle exec gollum --versions
Gollum 5.2.2
Running on: x86_64-darwin19 with Ruby version 2.7.1
Using:
rugged 1.1.0
gollum-rugged_adapter 1.1
gollum-lib 5.1
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by benjaminwil** [comment]
I haven't found the best way to get around this error yet. Locally, I am just removing my global system git configuration so I can run tests.

I think that the ideal solution is to make the system call out to `git clone` in the `#cloned_testpath` method more explicit, so it does not break if the user has global settings that conflict with `gollum`.

That said, this bug will probably only effect the tiniest amount of users, and it's not at all critical.

**Comment by dometto** [comment]
Maybe calling `git -c` and explicitly (un)set these parameters is the best we can do? This would be annoying if other config parameters also break the setup, but if it's just these two I see no problem with it. :)

**Comment by dometto** [comment]
I can't reproduce this anymore on `git` v2.37.3. I think `git clone` is now falling back to `master` regardless of `init.defaultBranch` for now (although this is likely to change to `main` in the near future, in which case we'll need to update our test repositories). Will close for now!
