### ISSUE TITLE
Feature Request: Fountain markup support

### ISSUE THREAD

**Issue by julianandrews** [gollum/gollum#1715]
It would be great to add support for [Fountain](https://fountain.io/) markup. Fountain is the leading markup language for screenplay writing.

**Comment by julianandrews** [comment]
I poked around a little in the source code, and may have a go at implementing this myself. If I did that would there be interest in merging in the changes?

**Comment by dometto** [comment]
Thanks for the suggestion @julianandrews! Can you tell us a bit more about your implementation? Does it utilize a ruby rendering gem, or JavaScript, for example? Based on that we can think about the best way to make this public -- either merging it into gollum, or a recipe in the wiki or in the `contrib` folder.

**Comment by bartkamphorst** [comment]
Shouldn't this ideally go through `github/markup`?

**Comment by julianandrews** [comment]
I hadn't settled on an implementation yet. If I were just implementing it for myself the lowest effort approach would be to just shell out to one of several pre-existing tools that convert fountain to html. This would make it easiest to swap out implementations if I found my first choice had any unexpected limitations, and would require the least change in gollum itself.

That said, if I'm going to the trouble, I'd like to find a way to share the change (which was a large part of my motivation for opening this issue). So what would be the easiest/best way to make this public?

There's a workable implementation in Ruby [here](https://github.com/olivertaylor/Textplay) (with what looks like a standard 3-clause BSD license). I'm guessing it wouldn't be much work to make a gem out of that. There's also a javascript library [here](https://github.com/mattdaly/Fountain.js) (MIT license) though unless there's some reason to prefer it, I wouldn't lean towards a server-side javascript implementation.

Alternatively, the fountain format is intentionally designed to be very simple to parse so I might just implement a gem from scratch. Fountain.js is less than 300 lines of code, and most of the ~1200 lines of code in Textplay is for handling various options, plus a big block of css and templates.

As another note - fountain markup is designed to map naturally to xml. The implementation could be as simple as a (very short) fountain -> xml conversion gem along with an appropriate style-sheet (and client-side JS for the editor).

I'm pretty flexible on approach. I'm hoping for some guidance on what will work best for distribution before I get going!

**Comment by dometto** [comment]
> Shouldn't this ideally go through github/markup?

Yes, ideally, but not sure they would accept it unless there is a standard/well-maintained ruby gem that handles rendering. However, one way to implement a gem might be to extend/monkeypatch `github-markup`:

* Register an implementation for fountain [here](https://github.com/github/markup/blob/master/lib/github/markup.rb#L12)
* Add a new subclass of the `GemImplementation` or `CommandImplementation` classes for rendering Fountain (see [here](https://github.com/github/markup/tree/master/lib/github/markup))
  * with `CommandImplementation` it would be pretty simple to shell out to fountain rendering gems. Downside is it might well not work on JRuby/Windows.
 
Apps like gollum could then just `require` the extension and rendering would happen automagically via `github-markup`.

There's a question here about how well `github-markup` is maintained (there is some recent activity fortunately) and how easy it is to customize. I don't know if switching to an alternative (like `gitlab-markdown`) makes sense at some point. But for now that might be overkill.

**Comment by dometto** [comment]
By the way, I and @bartkamphorst have been assuming Fountain is a format for complete *documents*, so on the same level as Markdown, `.rst`, `.org`, etc. Is that correct, or is Fountain syntax rather something that would embedded *in*, e.g., a markdown document?

**Comment by julianandrews** [comment]
Yup, fountain is a format for complete documents, and that's definitely what I was thinking to implement.

There are plugins that render fountain embeded in MediaWiki or Wordpress blogs, and I could see something similar being useful for some writers (to add snippets to an outline or notes), but it's definitely not what I was imagining.

**Comment by bartkamphorst** [comment]
Another option could perhaps be to implement fountain support in `pandoc`, since gollum already supports pandoc. See [here](https://github.com/jgm/pandoc/issues/4228) for the feature request.

**Comment by julianandrews** [comment]
Pandoc support probably does make the most sense here.

That said, I don't expect to see that issue resolved any time soon, and my Haskell is a little too limited to be comfortable jumping into a big codebase like Pandoc with confidence, so I'm probably going to try to put something together for myself for gollum.

@dometto - you mentioned wiki recipes. Could you point me at examples of those? If I come up with an approach that works with that, I could share it.

**Comment by dometto** [comment]
@julianandrews sorry for the slow reply. Did you ever come up with a solution that works for your? I imagine it would require monkeypatching `github-markup` in the way I [describe](https://github.com/gollum/gollum/issues/1715#issuecomment-821987445), which could be done in `config.rb`. If that works, we could share the recipe in the `contrib` folder, or in the [project wiki](https://github.com/gollum/gollum/wiki).

**Comment by bartkamphorst** [comment]
Update: Check out John MacFarlane's Fountain reader for pandoc [here](https://github.com/jgm/pandoc/issues/4228).

**Comment by dometto** [comment]
Excellent! @julianandrews if you're keen to try it, you could try adding support for Fountain using `pandoc-fountain`. The approach would be:

1. register `.fountain` (or whatever the relevant extension is) file extensions [here](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/markups.rb#L70-L95)
2. register a `GitHub::Markup` renderer for `fountain`, analogous to [this](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/markups.rb#L60)
  * The block should do something like `PandocRuby.convert(content, :from => 'fountain.lua', :to => :html)`
3. Both "registrations" should occur only conditional on the availability of `pandoc-fountain`. I am not sure if the current helper `#executable_exists?` will do the trick, since I don't know if `founain.lua` is supposed to be an executable on the user's `PATH`.

**Comment by julianandrews** [comment]
@dometto - I doubt I'll have time to get to this any time soon. I'll be watching the issue in case someone gets around to it, and may even do it some day, but I have no idea when!

**Comment by dometto** [comment]
It looks like `fountain.lua` can be anywhere on the user's system. That is: the usage is `pandoc -f /path/to/fountain.lua`. This may make it difficult to implement straightforwardly in `gollum-lib`, since there is no "normal" or default place to check for the existence of `fountain.lua`.

The alternative is to provide a recipe for implementing fountain support via `config.rb`, which would allow the user to specify the path t `fountain.lua`.

A mixed approach is also possible: check for a config variable specifying the path to `fountain.lua`, and enabling support for it in case it's found. But that sounds like it may be more complicated than it's worth?

**Comment by dometto** [comment]
When 6.0 is released, users will be able to use Fountain by doing the following:

1. Install `pandoc` on their system
1. `gem install pandoc`
1. Installing the [Fountain lua filter](https://github.com/jgm/pandoc/issues/4228) for `pandoc`
1. Adding the following to `config.rb` (and running Gollum with `--config`):

```ruby
fountain_lua = '/path/to/.pandoc/filters/fountain.lua'
require 'pandoc-ruby'
Gollum::Markup.register(
    :fountain, "Fountain", :extensions => ['fountain'],
    :enabled => Gollum::MarkupRegisterUtils::gem_exists?('pandoc-ruby'),
    :render => proc {|content| ::PandocRuby.convert(content, f: fountain_lua, to: :html) }
)
```

Given the lack of a proper rendering gem for Ruby, this is I think the best we can do. @julianandrews hope this is acceptable, let me know if you see ways to improve support.

Keeping this open as a reminder to document this.

**Comment by bartkamphorst** [comment]
@julianandrews And of course, if you ever do get around to implementing a gem for parsing fountain files yourself, let us know!

**Comment by dometto** [comment]
Documented here: https://github.com/gollum/gollum/wiki/Formats-and-extensions#example-enabling-support-for-fountain

If anyone has ideas about how we can better support Fountain, please feel free to reopen or comment.
