### ISSUE TITLE
README says `gollum <dir>` when you should run `git init <dir>` first.

### ISSUE THREAD

**Issue by basking2** [gollum/gollum#1720]
**Describe the bug**
The README says to run `gollum /my/dir` when it should say run `git init /my/dir` first and _then _ `gollum /my/dir`.

**To Reproduce**
1. Follow the readme and Gollum blows up because an empty directory is not an initialized Git directory.

**Comment by dometto** [comment]
I would find adding `git init` equally confusing, since of course you can also run gollum with an already existing git repository. Maybe the best thing is to add an explicit notice "where `wiki` is an initalized git repository" or something, e.g. in an `*` item below. PR welcome!

**Comment by basking2** [comment]
@dometto - PR 1722 submitted.

**Comment by dometto** [comment]
Thanks @basking2
