### ISSUE TITLE
Migrate from travis-ci.org before the end of May 2021

### ISSUE THREAD

**Issue by benjaminwil** [gollum/gollum#1723]
From travis-ci.org:

> Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com.

It would probably be little-to-no effort to migrate to travis-ci.com. Open source projects still run free on travis-ci.com. I haven't looked at how much configuration changes might be needed, or how much lede time might be required to make this change.

If we are unhappy with Travis CI generally, I would be happy to create configuration for GitHub Actions if we have interest in trying that. I would not be able to do that before June 2021, however.

**Comment by darless1** [comment]
It looks like they pushed back the date to June 15th. This is the message when looking at build results. 

Hi! It seems there are still plenty of builds running. We're pushing back the shutdown date to June 15th. Please consider migrating to travis-ci.com.

**Comment by benjaminwil** [comment]
Amazing, thanks! I haven't had time to think about this stuff.

**Comment by darless1** [comment]
I created PR #1729 which switches to GitHub actions instead of Travis CI. Looking at Travis COM, their free tier is limited. GitHub actions are integrated. In the PR I'm only testing 2.4.0, 2.6.0, and 3.0.0 ruby (not jruby due to a bug with that specific version).
