### ISSUE TITLE
config file documentation

### ISSUE THREAD

**Issue by mralusw** [gollum/gollum#1726]
In case there is documentation for the config file, I'm having trouble finding it (especially given that there's another, unrelated, yet web-present gollum project out there).

My original problem was that I cloned a gitlab project wiki,  followed their instructions, and had http://localhost:4567/ *insist* on creating a new (capital-H) Home page (even though `home.md` exists -- guessing the URL fixes it). If the homepage is configurable via CLI options / config file (it doesn't appear to be), then there is no need for another issue.

**Comment by dometto** [comment]
There isn't a single wiki page listing all the things one can do with `config.rb` unfortunately. In general, however, you can do everything you can do with command-line switches, as documented here:

https://github.com/gollum/gollum/wiki/Gollum-via-Rack

Pages in the wiki starting with `Custom...` or `Changing...` usually document options in `config.rb` (or `config.ru`). If you think it would be useful, feel free to add an overview page to the wiki gathering these, @mralusw! The wiki is publically editable. Please let me know if you have any further questions.
