### ISSUE TITLE
Unicode characters in path shows as escape characters

### ISSUE THREAD

**Issue by egigoka** [gollum/gollum#1728]
**Describe the bug**
Unicode characters in path shows as escape characters.

**To Reproduce**
1. Сlick "New" to create new page
2. Enter "/тест1/тест2" as Page Name
3. Click "OK"

**Expected behavior**
Path under Page Name will be shown in Unicode.

**Screenshots**
Page view:
![image](https://user-images.githubusercontent.com/23525323/121296832-bb0d5080-c90a-11eb-9ee2-f0f7c9ef13a7.png)
Overview:
![image](https://user-images.githubusercontent.com/23525323/121296999-0c1d4480-c90b-11eb-8fb5-5c71a32a5396.png)
in Overview in list folder name is alright:
![image](https://user-images.githubusercontent.com/23525323/121296905-dbd5a600-c90a-11eb-9d04-868effc66fdb.png)

**Environment Info**
latest official docker image

Gollum 5.1.2
Running on: x86_64-linux with Ruby version 2.7.2
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: kramdown
Other renderering gems:
none

**P.S.**
English is not my mothers tongue, sorry if not all is clear.

**Comment by benjaminwil** [comment]
@dometto I don't have access to the Gollum organization on Docker Hub, but I imagine that we just need to push a new release to Docker Hub somehow?

When I pull the Docker image and create a new container, I indeed get `gollum v5.1.2`, not `gollum v5.2.3`.

**Comment by bartkamphorst** [comment]
@scolytus Can you update the gollum version in the docker image or check why the 'latest' image is not up-to-date?

**Comment by darless1** [comment]
With #1732 the docker is generated and tested on each push. Using the docker from the latest build I followed the procedures mentioned here and I am not seeing the issue present.

Docker image used: [Latest](https://hub.docker.com/layers/darless1/gollum/dfda2b1b5a6b554f8c93e83059e0bed7b77e2694/images/sha256-c0f88691ce335e326f0e97bf2b7942e8657d9c507c4275b074bd4aa4a48cb5a6?context=explore)

![test2](https://user-images.githubusercontent.com/3382617/122060225-01ebc200-cdb3-11eb-8dc3-8f45a7c9d3f9.png)

**Comment by dometto** [comment]
Will close this since the real issue is that the docker image is out of date.
