### ISSUE TITLE
Register a channel on Libera.Chat

### ISSUE THREAD

**Issue by benjaminwil** [gollum/gollum#1733]
I would like to consider registering a Gollum community channel on [Libera.Chat](https://libera.chat), an IRC network focused on FOSS projects. I can take ownership of the channel.

After I have formally registered I can promote the channel in the README and any relevant wiki pages.

@dometto @bartkamphorst I hope I would have your blessing. If you'd prefer I do not do this – I will oblige.

**Comment by darless1** [comment]
@benjaminwil - I see there is already a room in gitter but it has not been used for some time. What is the history there?

gitter channel: https://gitter.im/gollum/gollum
README could be updated with a gitter badge for people to know about.

**Comment by benjaminwil** [comment]
The Gitter room seems to be from before my time. Looks like it was only used a couple of times. 

I am not opposed to figuring out how to use Gitter and promoting the Gitter room on the README.

**Comment by dometto** [comment]
I'm happy with the Libera.Chat channel if you prefer that platform to gitter, @benjaminwil! Feel free to promote it to the Readme!

**Comment by dometto** [comment]
Looks like the channel now exists! Maybe we should advertise it in the README and then close this? We could also put a notice in the issue template, asking people to post questions (as opposed to bug reports/feature requests) there rather than filing issues?

**Comment by benjaminwil** [comment]
I haven’t actually registered the channel with Libera.Chat yet, but yes. I can get on this. 

My only hesitation around asking people to post questions there first would be that there is no organic community there, and I am unsure whether Gollum users are also IRC users. 😅

Out of curiosity, does the Gollum org have access to the GitHub discussions feature?

**Comment by dometto** [comment]
Turns out we do! https://github.com/gollum/gollum/discussions

Also looks like a good option to keep the issue tracker a bit cleaner. You're right there might be less people around on Libera, at least at first. Doesn't have to be mutually exclusive of course.

**Comment by bartkamphorst** [comment]
@benjaminwil Can I close this now that we have enabled GitHub discussions? Or would we still like to have an IRC channel?

**Comment by benjaminwil** [comment]
Let’s just close it. I will idle in the channel but it doesn’t seem to be a good option for discussions.
