### ISSUE TITLE
Rugged::HTTPError - remote authentication required but no callback set

### ISSUE THREAD

**Issue by kimpenhaus** [gollum/gollum#1736]
Hi all,

this is more a question for help than an issue - and I am sorry if this is kind of dumb question as I am not an ruby guy. Also I am not sure if it's better to put it here, at rugged-adapter or maybe libgirt2/rugged...

I have setup gollum via docker to run in my local network (for documentation purposes). I want it to be linked to a gitea instance which is also hosted in the same network and I wanted it to auto-push on any changed. I've read in the wiki about the [hooks](https://github.com/gollum/gollum/wiki/Hooks) and have setup it up accoring with an `config.rb` adding also the gollum::hook:

```ruby
  Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
    committer.wiki.repo.git.pull('origin', committer.wiki.ref)
    committer.wiki.repo.git.push('origin', committer.wiki.ref)
  end
```

As far as I can tell that this is working the way, that the hook is fired and tries to pull/push.

My main problem - I have to add the credentials to pull/push to my gitea instance - and I have no clue how to do that :) I've found an [issue/documentation](https://github.com/libgit2/rugged/issues/743) at libgit2/rugged but that is ssh specific and I am running against an http/https endpoint.

The error from the docker logs is:

```
Rugged::HTTPError - remote authentication required but no callback set:
	/usr/local/bundle/gems/rugged-0.99.0/lib/rugged/repository.rb:272:in `push'
	/usr/local/bundle/gems/rugged-0.99.0/lib/rugged/repository.rb:272:in `push'
	/usr/local/bundle/gems/gollum-rugged_adapter-1.0/lib/rugged_adapter/git_layer_rugged.rb:313:in `push'
```

Anyone that can help me on that?

Thanks in adanvce!

**Comment by yy0931** [comment]
rugged is a binding to libgit2, and according to https://libgit2.org/docs/guides/authentication/ , You can set username/password pair in the url.
It says you can also use `git_remote_callbacks`, but I don't know how to use it.

```shell
git remote rm origin
git remote add origin https://username:password@github.com/foo/bar
```

**Comment by kimpenhaus** [comment]
Hey @yy0931,

thanks for your response - I wanted to have my configuration with username and password together in one place and not spread over multiple locations.

After fiddling a little bit around I found a working solution - and pass the credentials as an options parameter.

Maybe not the best ruby style 😁

```ruby
  Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
    credentials = Rugged::Credentials::UserPassword.new(username: 'my-username', password: 'my-password')
    committer.wiki.repo.git.pull('origin', committer.wiki.ref, credentials: credentials)
    committer.wiki.repo.git.push('origin', committer.wiki.ref, credentials: credentials)
  end
```

So maybe this can be optimized further?

**Comment by bartkamphorst** [comment]
@kimpenhaus Great! If this works, then you could also retrieve your password from your ENV if you don't want to hardcode it into your `config.rb`.

**Comment by kimpenhaus** [comment]
@bartkamphorst that's a great idea - especially when running inside a docker container I can provide it through that env parameter - thanks for the suggestion.

closing this as I reached what I wanted to.
