### ISSUE TITLE
Set gollum.author based on http headers, not using rack

### ISSUE THREAD

**Issue by harleypig** [gollum/gollum#1743]
I looked for a discussion channel for gollum. The only place I found was libera#gollum and there was only one person there.

I'm using Authelia for my authentication front-end. Authelia sets the REMOTE-{USER,NAME,EMAIL,GROUP} HTTP headers.

I found #1636 that has a way of doing that for GIT_* headers but it doesn't seem to have gone anywhere.

I am not familiar with ruby, but I can hack existing code well enough if I know where to put it. Is there a way I can write a module in config.rb that will do the same or similar?

**Comment by benjaminwil** [comment]
In your `config.rb`, you could override any main application logic (in the class `Precious::App` defined in `lib/gollum/app.rb`) by prepending a module and overriding any existing methods. 

I am not sure the following example does exactly what you'd want, but it should steer you in the direct direction:

```
# path/to/your/config.rb

module MyOverrideModule
  def commit_message
    name = request.fetch_header("MY_NAME")
    email = request.fetch_header("MY_EMAIL")
    
    msg = (params[:message].nil? or params[:message].empty?) ? "[no message]" : params[:message]
    
    message = { 
      message: msg,
      "gollum.author": { name: name, email: email }
    }
    
    message
  end
  
  Precious::App.prepend self
end
```

**Comment by harleypig** [comment]
Thank you. I'll experiment and see what I can figure out.

**Comment by harleypig** [comment]
This is what I came up with. Thank you for pointer, it worked almost straight out of the comment box.

```ruby
module OverrideMyPrecious
  def commit_message
    name = request.env['HTTP_REMOTE_NAME']
    email = request.env['HTTP_REMOTE_EMAIL']

    msg = (params[:message].nil? or params[:message].empty?) ? "[no message]" : params[:message]

    commit_message = {
      message: msg,
      name: name,
      email: email
    }

    commit_message
  end

  Precious::App.prepend self
end
```

**Comment by dometto** [comment]
good to hear you got it working @harleypig! If you have a moment it may be worth adding this recipe to the wiki. :) Would be much appreciated! The same if you manage to get your system file working (e.g. [here](https://github.com/gollum/gollum/wiki/Gollum-as-a-service)).

**Comment by weaversam8** [comment]
@dometto just had to find this again after searching for a few hours. I'd like to add it to the wiki- what's the best page to add this to?

**Comment by dometto** [comment]
@weaversam8 thanks for helping out with that. I think it would be best to have a fresh page for that! We should probably have a section with links to all the different recipe pages in the wiki on the main page, but no worries if you don't have time for that.

**Comment by davispuh** [comment]
It took me while to find this out how to setup this.
Overriding `commit_message` doesn't work anymore but I found it's documented at https://github.com/gollum/gollum/wiki/Gollum-via-Rack#setting-author-info-and-commit-notes-using-middleware
and also https://stackoverflow.com/a/40696797/314339

I'm using Docker image so there's no `config.ru` so instead I used `--config=config.rb` option and then set there
```ruby
class Precious::App
    before do
        session['gollum.author'] = {
            :name => request.env['HTTP_REMOTE_NAME'],
            :email => request.env['HTTP_REMOTE_EMAIL']
        }
    end
end
```

This works great now :)
