### ISSUE TITLE
Copy-button for code blocks

### ISSUE THREAD

**Issue by ghost** [gollum/gollum#1754]
I've just added a massive code in one code block and I realised that it would be a hassle to copy that one again :) So a button to copy the code would be helpful here :)

**Comment by PeterMarkuson** [comment]
I have found a solution copied together from snippets on the internet. I am not a professional developer and know not too much about JS and CSS. Also this solution seems not to be the securest nor elegant, but until there is something better this works for me on my private server. Maybe somebody can develop it further.

Three steps are required to make it work on Gollum 5.x:

1. Make gollum use the `--template-dir` option and edit the `layout.mustache` file to load JS and CSS into the body. Loading it into the head section and use the official `custom.js` and `custom.css` does **not** work for me.
2. Create a file `body.js` to load the script that will provide the copy button
3. Create a file `body.css` to load the styles for that button

### Prepare template
Create a folder for your own template, e.g. `mkdir -p /etc/gollum/templates` and copy the layout template to it. For my system this was `cp /var/lib/gems/2.7.0/gems/gollum-5.3.0/lib/gollum/templates/layout.mustache /etc/gollum/templates/`.

Then edit the template and include the following code below the `<body>` tag:
~~~
{{#css}}<link rel="stylesheet" type="text/css" href="/body.css" media="all">{{/css}}
{{#js}}<script type="text/javascript" src="/body.js"></script>{{/js}}
~~~

### Create body.js

In the root of your wiki create a file `body.js` with the following content:
~~~
const svgCopy =
  '<svg aria-hidden="true" height="12" viewBox="1 -2 12 18" version="1.1" width="18" data-view-component="true"><path fill-rule="evenodd" d="M0 6.75C0 5.784.784 5 1.75 5h1.5a.75.75 0 010 1.5h-1.5a.25.25 0 00-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 00.25-.25v-1.5a.75.75 0 011.5 0v1.5A1.75 1.75 0 019.25 16h-7.5A1.75 1.75 0 010 14.25v-7.5z"></path><path fill-rule="evenodd" d="M5 1.75C5 .784 5.784 0 6.75 0h7.5C15.216 0 16 .784 16 1.75v7.5A1.75 1.75 0 0114.25 11h-7.5A1.75 1.75 0 015 9.25v-7.5zm1.75-.25a.25.25 0 00-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 00.25-.25v-7.5a.25.25 0 00-.25-.25h-7.5z"></path></svg>';
const svgCheck =
  '<svg aria-hidden="true" height="12" viewBox="1 -2 12 18" version="1.1" width="18" data-view-component="true"><path fill-rule="evenodd" fill="rgb(63, 185, 80)" d="M13.78 4.22a.75.75 0 010 1.06l-7.25 7.25a.75.75 0 01-1.06 0L2.22 9.28a.75.75 0 011.06-1.06L6 10.94l6.72-6.72a.75.75 0 011.06 0z"></path></svg>';

document.querySelectorAll('pre > code').forEach(function (codeBlock) {
    var button = document.createElement('button');
    button.className = 'copy-code-button';
    button.type = 'button';
    button.innerHTML = svgCopy;

    var pre = codeBlock.parentNode;
    if (pre.parentNode.classList.contains('highlight')) {
        var highlight = pre.parentNode;
        highlight.parentNode.insertBefore(button, highlight);
    } else {
        pre.parentNode.insertBefore(button, pre);
    }
});

function addCopyButtons(clipboard) {
    document.querySelectorAll('pre > code').forEach(function (codeBlock) {
        var button = document.createElement('button');
        button.className = 'copy-code-button';
        button.type = 'button';
        button.innerHTML = svgCopy;

        button.addEventListener('click', function () {
            clipboard.writeText(codeBlock.innerText).then(function () {
                button.blur();
                button.innerHTML = svgCheck;
                setTimeout(function () {
                    button.innerHTML = svgCopy;
                }, 2000);
            }, function (error) {
                button.innerText = 'Error';
            });
        });

        var pre = codeBlock.parentNode;
        if (pre.parentNode.classList.contains('highlight')) {
            var highlight = pre.parentNode;
            highlight.parentNode.insertBefore(button, highlight);
        } else {
            pre.parentNode.insertBefore(button, pre);
        }
    });
}

if (navigator && navigator.clipboard) {
    addCopyButtons(navigator.clipboard);
} else {
    var script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/clipboard-polyfill/2.7.0/clipboard-polyfill.promise.js';
    script.integrity = 'sha256-waClS2re9NUbXRsryKoof+F9qc1gjjIhc2eT7ZbIv94=';
    script.crossOrigin = 'anonymous';
    script.onload = function() {
        addCopyButtons(clipboard);
    };

    document.body.appendChild(script);
}
~~~

### Create body.css

In the root of your wiki create a file `body.css` with the following content:

~~~
.copy-code-button {
    color: #272822;
    background-color: #FFF;
    border: 1px dashed #ccc;
    border-radius: 3px;

    display: block;
    margin-left: auto;
    margin-right: 0;

    margin-bottom: -15px;
    margin-top: -10px;
    padding: none;
    font-size: 0.5em;
}

.copy-code-button:hover {
    cursor: pointer;
    background-color: #F2F2F2;
}

.copy-code-button:focus {
    background-color: #E6E6E6;
    outline: 0;
}

.copy-code-button:active {
    background-color: #D9D9D9;
}

.highlight pre {
    margin: 0;
}
~~~

### Result

Start gollum including the `--template-dir` option pointing to your template folder.

The template loads the `body.js` code, which searches for code-blocks which are inside a `<pre>` tag. Then adds a button to the top right corner (to avoid overlay of code). Clicking that button will copy the content of the code block (indicated by a green checkmark). The button is styled by the `body.css` file to be as less disturbing as possible.

**Warning:** The button uses the clipboard API in modern browsers or loads a script from an external source that does the copy-to-clipboard stuff. That beeing said: I have not verified or reviewed the loaded source, but I found it was used in other scripts as well.

**Comment by aleee-idk** [comment]
The solution provided by @PeterMarkuson works!

The reason why that solution don't work in custom.js is because the file is inyected in the header of the page, so it's executed before the codeblocks are rendered. If you move all the logic to a function and pass to `window.onload` it should work.

Here is my solution based on @PeterMarkuson 's:

### custom.js
```js
// CONSTANTS
const COPY_TEXT = "Copy";
const COPIED_TEXT = "Copied!";

// Helper functions
const qs = (query) => document.querySelector(query);
const qsa = (query) => document.querySelectorAll(query);
const randomId = () => Math.random().toString(36).replace(/[^a-z]+/g, '').substr(2, 10);
const wait = async (seconds) => new Promise(resolve => setTimeout(resolve, seconds * 1000));
const copy = async (text) => navigator.clipboard.writeText(text);

const copyToClipboard = async ({ target }) => {
	const codeBlock = qs(`#${target.dataset.codeblock} code`);
  await copy(codeBlock.textContent);

	target.textContent = COPIED_TEXT;
	await wait(3);
	target.textContent = COPY_TEXT;
};

const addButtonToCodeblocks = () => {
  const codeBlocks = qsa("pre");

  codeBlocks.forEach((item) => {
		const id = randomId();

    const button = document.createElement("button");

    button.textContent = COPY_TEXT;
    button.classList.add("cust-btn-copy");
		button.dataset.codeblock = id;
		item.id = id;

    button.onclick = copyToClipboard;

    item.appendChild(button);
  });
};

const onLoad = () => {
	addButtonToCodeblocks();
};

window.onload = onLoad;
```

### custom.css

```css
:root {
	--teal: #94e2d5;
	--lavender: #b4befe;
	--text: #1e1e2e;

	--primary: var(--teal);
	--primary-text: var(--text);
	--accent: var(--lavender);
	--accent-text: var(--text);
}

pre {
  position: relative;

	/* so the button doesn't overflow */
	min-height: 3rem;
}

.cust-btn-copy {
  position: absolute;
  top: max(1%, 0.5rem);
  right: 1%;

	background-color: var(--primary);
	color: var(--primary-text);

  padding: 0.25rem 1.5rem;

	border: 0;
	border-radius: 10px;

	box-shadow: 2px 2px 5px 1px rgba(0,0,0,0.3);

	transition: all 100ms ease-in;
}

.cust-btn-copy:hover {
	cursor: pointer;

	transform: translate(-2.5%, -5%);

	background-color: var(--accent);
	color: var(--accent-text);
}
```

### Result

![image](https://user-images.githubusercontent.com/57039432/188246950-1337b7f0-23de-49da-9a1a-1bc32c8ae067.png)

### Note

Clipboard capabilities only work on pages with HTTPS enabled

**Comment by dometto** [comment]
I think with a little tweaking this could be integrated into gollum:

* For one thing, it would be nice to use an [octicon](https://primer.style/octicons/) for the copy button. We have access to octicons in the gollum JS templates through the `rocticon` helper method as illustrated [here](https://github.com/gollum/gollum/blob/master/lib/gollum/public/gollum/javascript/gollum.js.erb#L6).
* We would need to make sure this works both with http (for users runnning gollum locally) and https
* Applying the button to all `pre` blocks might be a little too much -- we should investigate, but I think `pre.code` may be more precise.

@aleee-idk would you be interested in working on a PR along these lines?

**Comment by aleee-idk** [comment]
Sure, if I have to modify only javascript I could do it, because I never worked in ruby before.

As for making it work in HTTP, It's depends of each browser, personally I change all my services (gollum included) because Firefox required a HTTPS connection to use the clipboard API. This is for security reasons so malicious websites don't copy a fork bomb or read the clipboard that often have password or other stuff, more details [here](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard).

So I thinks is a little beyond our control aside from checking if the clipboard API is available or not. Other ideas are welcome though.

I don't have much spare time these days though so I don't know when I could have this done, so if someone else want to take this feature good, if not I have no problem aside from that.

**Comment by dometto** [comment]
I don't think this would require work outside of the JS. Specifically, I think the new logic should be called from inside [this](https://github.com/gollum/gollum/blob/master/lib/gollum/public/gollum/javascript/gollum.js.erb#L636) if-block. Any work towards this would be greatly appreciated!

**Comment by aleee-idk** [comment]
I have almost everything working, the only thing left is improve the button feedback.

I made this little animation, but I would like to change the octicon color so it have better contrast in the green background. Is this possible?

If not I could just change only the icon for the feedback, but it wouldn't be so flashy.

I'm open to suggestion for other animations to provide feedback.

![Kooha-2022-10-09-14-51-54](https://user-images.githubusercontent.com/57039432/194772185-1768eca4-ba9d-4eab-a4cf-065415a36f4d.gif)

**Comment by dometto** [comment]
@aleee-idk this looks very nice! @bartkamphorst and @benjaminwil have more experience with Primer/Octicons, so maybe they can help out with your question. But anyway, please feel free to open a Pull Request with the progress you've made so far!

**Comment by bartkamphorst** [comment]
There's [this issue](https://github.com/primer/octicons/issues/240) about a `fill` option?

**Comment by dometto** [comment]
Ping @aleee-idk -- please feel free to open a PR! Would love to have this feauture in version 6.0.

**Comment by aleee-idk** [comment]
Sorry for the late response!

I created the [pull request](https://github.com/gollum/gollum/pull/1876).

For the time being I only leave the change in the icon when the user press the button, as I researched a little more there is no way to change the color.

![Kooha-2022-11-13-22-46-42](https://user-images.githubusercontent.com/57039432/201558450-5af7a98b-7078-474d-9a93-ea14941a6d54.gif)

I think [this](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/macro/octicon.rb) is the relevant part for what it's use to create the octicon icon, and it only accept  width and height. Moreover it seems the [library](https://primer.style/octicons/packages/ruby) doesn't support the change of color.

**Comment by bartkamphorst** [comment]
For reference, see [this PR](https://github.com/gollum/gollum/pull/1876) for discussion.
