### ISSUE TITLE
Question: getting the IP address of the Client which performed the change on the page in the Hook

### ISSUE THREAD

**Issue by makefu** [gollum/gollum#1766]
**Describe the bug**
We would like to use the gollum hook functionality to update the "Creator" and "Editor" of an article with the respective internal ip address or hostname. However i was unable to retrieve the Information from the context where the Hook is running.
Is there any chance to get the information?

**To Reproduce**
1. configure:
```
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
     # some magic which retrieves the ip address of the user which created 
end
```
2. Create a new article
3. The article is created with the user account "<hostname>"

**Expected behavior**
The ip address of the creator / editor should be available for the hook

**Screenshots**

**Environment Info**
```
# gollum --version
Gollum 5.2.1
```

**Comment by dometto** [comment]
Good question. It's not possible out of the box, because it requires some changes to the route logic. But I was able to get the basics of this working with a minimal change to `app.rb`:

```patch
diff --git a/lib/gollum/app.rb b/lib/gollum/app.rb
index d18582bf..ca29f050 100644
--- a/lib/gollum/app.rb
+++ b/lib/gollum/app.rb
@@ -390,8 +390,8 @@ module Precious
         path.gsub!(/^\//, '')
 
         begin
-          wiki.write_page(::File.join(path, name), format, params[:content], commit_message)
-
+          commit = wiki.write_page(::File.join(path, name), format, params[:content], commit_message)
+          Gollum::Hook.execute(:post_create_hook, commit, @env)
           redirect to("/#{clean_url(::File.join(encodeURIComponent(path), encodeURIComponent(wiki.page_file_name(name, format))))}")
         rescue Gollum::DuplicatePageError, Gollum::IllegalDirectoryPath => e
           @message = e.message
```

And in `config.rb`:

```ruby
Gollum::Hook.register(:post_create_hook, :hook_id) do |committer, env|
  puts env.inspect
end
```

When creating a new page, the `env` variable is printed on the console. `env[REMOTE_ADDRESS]` will contain the IP you're looking for.

So: you could implement this by monkeypatching `app.rb` and defining your hook in `config.rb`.

@bartkamphorst @benjaminwil do we want to add a Hook like this out of the box somehow?

**Comment by benjaminwil** [comment]
We’ve seen a few issues raised from users who have an internal or intranet wiki set up. It may be interesting to provide a hook like this if it would be helpful to many wiki administrators.

**Comment by dometto** [comment]
@makefu: if you're able to [run Gollum via Rack](https://github.com/gollum/gollum/wiki/Gollum-via-Rack), you could use the following `config.ru` and set the author details to what you want:

```ruby
#!/usr/bin/env ruby
require 'gollum/app'

class Authenticator
    def initialize(app)
      @app = app
    end
  
    def call(env)
      puts env['rack.session'].inspect
      env['rack.session'] = {} unless env['rack.session']
      env['rack.session']['gollum.author'] = {:name => 'Foo', :email => 'Bar'}
      @app.call(env)
    end
  end
  
use Authenticator

gollum_path = File.expand_path('/tmp/lotr') # CHANGE THIS TO POINT TO YOUR OWN WIKI REPO
wiki_options = {:universal_toc => false}
Precious::App.set(:gollum_path, gollum_path)
Precious::App.set(:default_markup, :markdown) # set your favorite markup language
Precious::App.set(:wiki_options, wiki_options)
run Precious::App
```

Although I've played around with passing the environment to the Hook context in https://github.com/gollum/gollum-lib/pull/431, I am not sure how great a solution that is. Changing the author of the page programatically based on the environment would require doing a commit from *inside* the `:post_commit` Hook, which is called from inside `Committer#commit`. I am not sure how clean/stable that would be.

If the `config.ru` solution works for you, I think it may be better to go with that and close this issue.

**Comment by dometto** [comment]
To be clear, the idea is that in the above example, you would be able to dynamically set the `gollum.author` set to any value, depending on the request context. E.g.:

```ruby
    def call(env)
      puts env['rack.session'].inspect
      env['rack.session'] = {} unless env['rack.session']
      ip_addr = env[‘REMOTE_ADDR’]
      env['rack.session']['gollum.author'] = {:name => ip_addr, :email => 'Bar'}
      @app.call(env)
    end
```

I think this would a better way to achieve what @makefu requests.

Nevertheless, there is still a question whether it makes sense to provide some context to the post commit hook as per https://github.com/gollum/gollum-lib/pull/431. @benjaminwil you mentioned in this thread you thought such functionality would be useful? What information specifically should we pass along to the `Committer` object in that case? Or should we make this user-definable?

**Comment by benjaminwil** [comment]
I don't remember why I had thought this. Haha.

Now I think I would need more information about the utility this logging provides and if it would be acceptable for the many kinds of wikis Gollum users have. (So: probably ignore my previous comment for now.)
