### ISSUE TITLE
Improving documentation regarding custom styling

### ISSUE THREAD

**Issue by ye-yng** [gollum/gollum#1770]
In the [custom stylings](https://github.com/gollum/gollum/wiki/Custom-Styling-and-Views) wiki page there's an example to increase the width of the page with the following configuration:

```
.container-lg {
  max-width: 90%;
}
```
However since the text div also uses the `.container-lg` class, the text would change its relative width with the parent div. We can add an extra configuration which sets the text div to use up all the space instead of changing with the parent div:

```
.main-content.clearfix.container-lg {
    max-width: 100%;
}
```

**Comment by benjaminwil** [comment]
Thanks for raising this issue.

I believe we could simplify this to:

```
.main-content {
  max-width: 100%;
}
```

I will update the wiki now. Let me know if I've misinterpreted at all.
