### ISSUE TITLE
Files are uploaded to the wrong path with HTTPS reverse proxy

### ISSUE THREAD

**Issue by rgov** [gollum/gollum#1771]
I have essentially the same issue as #1557 but the reporter closed it.

When I upload a file by dragging it onto the edit area, the following snippet gets inserted:

    [[/uploads/path/to/page/attachment.png]]

However this is not where the file ended up, and so it renders as `<img alt="Image not found" />`.

If I browse the "Overview" structure I find that it has uploaded to `uploads/https:/servername/path/to/page/attachment.png` or in one instance `uploads/https:/servername/gollum/edit/path/to/page/attachment.png`. These seem pretty clearly wrong?

Perhaps it is related to this logic here:

https://github.com/gollum/gollum/blob/75173890727255940d260847edcf7b9cf793f961/lib/gollum/app.rb#L242-L251

```
Gollum 5.1.2
Running on: x86_64-linux with Ruby version 2.7.2
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by dometto** [comment]
Thanks! Looks like a fix could be to do something like:

```ruby
dir = request.referer.match(/^https?:\/\/#{request.host_with_port}\/(.*)/)[1]
```

If we're using regex anyway, we can potentially refactor some (or all) of the other `.sub` steps as well.

**Comment by dometto** [comment]
Note sure why #1787 didn't auto-close this issue.
