### ISSUE TITLE
Dead link in the help panel to EmojiOne demo

### ISSUE THREAD

**Issue by julianbarg** [gollum/gollum#1775]
**Describe the bug**
There is a dead link in the Help panel--the link to the EmojiOne demo does not work anymore: http://emojione.com/demo/

**To Reproduce**
1. Go to edit mode
2. Click on the "?" to open the help panel
3. Click on "Miscellaneous" on the left
4. Click on Emoji
5. Click on the link to the EmojiOne demo

**Comment by benjaminwil** [comment]
Will be live in the next version of Gollum.
