### ISSUE TITLE
JRuby: headers and anchors not displayed properly

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1779]
[Two tests are failing on JRuby](https://github.com/gollum/gollum/runs/4125783787?check_suite_focus=true). After some research, I figured out that the culprit is the latest `nokogiri` version for JRuby. Long story short, it appears to be outputting some invalid XHTML in the [toc filter](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/toc.rb#L127), when adding anchors to header elements. This appears to be a bug in nokogiri, which I've reported [here](https://github.com/sparklemotion/nokogiri/issues/2355).

As a workaround, affected users can revert back to `nokogiri` ~`v1.11.7`~ `v.1.12.4` or earlier.

**Comment by flavorjones** [comment]
Please note that this change in behavior was introduced in Nokogiri v1.12.5, so reverting to v1.12.4 or earlier should be sufficient to work around it for now.

**Comment by dometto** [comment]
This should be fixed in the next release of nokogiri. Will leave this open for now in case users look for it.

**Comment by dometto** [comment]
Thanks to @flavorjones by the way!

**Comment by daniol** [comment]
Downgrading just nokogiri is not enough. After downgrading with:

```
gem uninstall nokogiri
gem install nokogiri -v 1.12.4
```

I ran in the following errors when starting gollum:

```
LoadError: no such file to load -- nokogiri
  require at org/jruby/RubyKernel.java:1017
  require at C:/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:160
   <main> at C:/jruby/lib/ruby/gems/shared/gems/loofah-2.12.0/lib/loofah.rb:4
  require at org/jruby/RubyKernel.java:1017
  require at C:/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
   <main> at C:/jruby/lib/ruby/gems/shared/gems/gollum-lib-5.1.3-java/lib/gollum-lib.rb:18
  require at org/jruby/RubyKernel.java:1017
  require at C:/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
   <main> at C:/jruby/lib/ruby/gems/shared/gems/gollum-5.2.3/lib/gollum/app.rb:5
  require at org/jruby/RubyKernel.java:1017
  require at C:/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
   <main> at C:/jruby/lib/ruby/gems/shared/gems/gollum-5.2.3/bin/gollum:270
     load at org/jruby/RubyKernel.java:1052
   <main> at c:\jruby\bin\gollum:25
```

HTML representation is currently completely broken.

**Comment by flavorjones** [comment]
@daniol It looks like there's an issue with your system and how nokogiri is installed which seems unrelated to this gollum issue.

Without more information, it's hard to know how to help; but if you could [open an issue](https://github.com/sparklemotion/nokogiri/issues/new?assignees=&labels=topic%2Finstallation&template=1-installation-difficulties.md&title=%5Binstall%5D) and take care to fill out the template, I will try to help.

**Comment by daniol** [comment]
I figured it out by myself. The correct way to downgrade is:
```
gem install nokogiri -v 1.12.4
gem uninstall nokogiri -v 1.12.5
```
After that, gollum was usable again.

**Comment by benjaminwil** [comment]
Just a short update on the status of this: we're still just waiting for a new version of Nokogiri to ship with a fix.

---

As an aside: I spent a bit of time trying to get our GitHub Actions workflows to use Nokogiri v1.12.4 so that our CI runs would pass until a new version of Nokogiri is released. But it seems like our runs don't actually respect what's in the committed `Gemfile`: I don't see `warbler` or my locked `nokogiri` versions being used.

Right now, if the JRuby failures happen first, it causes the Ruby 2.4.x and 2.6.x CI runs to fail early. (We could also turn `fast-fail` off to stop this from happening.)

**Comment by flavorjones** [comment]
FYI: ETA on a new Nokogiri release is "sometime in the next few days"

**Comment by benjaminwil** [comment]
@flavorjones Amazing! Thanks for the update.

**Comment by flavorjones** [comment]
Just leaving a note: Nokogiri v1.13.0 shipped earlier this week with this fix: https://github.com/sparklemotion/nokogiri/pull/2356
