### ISSUE TITLE
No way to add non-http links (markdown)

### ISSUE THREAD

**Issue by vissermc** [gollum/gollum#1780]
**Describe the bug**

When trying to add an external link that starts with another protocol, like file:// or slack://, it gets filtered out.

**To Reproduce**
Create a markdown page and add:

[test](file:///c/tmp/test.txt)

or

<a href="file://...>test</a>

**Version**
v5.2.3

**Comment by dometto** [comment]
Try adding:

```
Loofah::HTML5::WhiteList::ALLOWED_PROTOCOLS.add('file')
```

to your `config.rb` (use the `--config` switch) and let me know if that fixes it?

**Comment by vissermc** [comment]
When I run gollum with the --config option pointing to a directory containing a copy of the config.rb and config.ru:

 bundle exec bin/gollum ../wiki/gollum.git --bare --mathjax --config <my path....>

It says this:
bundler: failed to load command: bin/gollum (bin/gollum)
bin/gollum:279:in `require': cannot load such file -- /home/projects/gollum (LoadError)
        from bin/gollum:279:in `<top (required)>'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli.rb:474:in `exec'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:49:in `block in <top (required)>'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        from /home/projects/ruby/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
        from /home/projects/ruby/ruby-3.0.2/bin/bundle:23:in `load'
        from /home/projects/ruby/ruby-3.0.2/bin/bundle:23:in `<main>'

**Comment by dometto** [comment]
You have to specify the path to your config file, so `bundle exec bin/gollum ../wiki/gollum.git --bare --mathjax --config  /path/to/config.rb`
