### ISSUE TITLE
Drop Ruby 2.4 support

### ISSUE THREAD

**Issue by benjaminwil** [gollum/gollum#1795]
Ruby 2.4.x [has reached end of life](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/).

I would like to propose we stop supporting it and drop it from our CI matrix.

I am curious if there is a specific reason we still support it? After a search, I didn't find any specific rationale.

**Comment by dometto** [comment]
All good to drop it! No specific reason why we are still testing it, other than a vague idea that some backward compatibility is a good thing. :) But 2.4 is very old now.

**Comment by benjaminwil** [comment]
I've dropped Ruby 2.4 from our GitHub Actions workflow version matrix.

There's no explicit mention of supported Ruby versions in the README, nor mentions of Ruby versions anywhere else. So I think we can just close this issue now. :+1:
