### ISSUE TITLE
Hide extensions in internal links

### ISSUE THREAD

**Issue by NicosKaralis** [gollum/gollum#1808]
Is there a way to not show the extension of the file server by gollum?

In the browser I can access the page either via ``localhost:8080/Home`` and ``localhost:8080/Home.md``, this I can remove the extension with caddy or nginx, but I also want to hide the extensions in the link inside the body of the page

When I create a link using ``[[Home]]`` it replaces with a link to ``Home.md``, is there a way to remove the extension for all internal links?

**Comment by dometto** [comment]
I think @benjaminwil's suggestion is a good enough work around, so I'll close this. Let me know if there are any important us cases that this does not cover.
