### ISSUE TITLE
Dependency rdoc missing for installation of gollum gem

### ISSUE THREAD

**Issue by salexan2001** [gollum/gollum#1809]
**Describe the bug**
- I installed gollum using "gem install gollum".
- Afterwards I started gollum and received the following error message:
```
$ gollum
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rdoc (LoadError)
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

Installing rdoc using: "gem install rdoc" fixed the problem and let gollum start without errors.

**To Reproduce**
Already described in bug description.

**Expected behavior**
I expected "gem install gollum" to fetch all dependencies, including rdoc. I checked the issue tracker and README.md for a note on manual installation of rdoc, but it seems like the dependency is just missing.

**Environment Info**
```
$ gollum --versions
Gollum 5.2.3
Running on: x86_64-linux with Ruby version 3.0.3
Using:
rugged 1.1.1
gollum-rugged_adapter 1.1.2
gollum-lib 5.1.3
Markdown rendering gem: kramdown
Other renderering gems:
none
```

I am running an up-to-date archlinux as OS.

**Comment by dometto** [comment]
Problems with `rdoc` on arch have been reported before: https://github.com/gollum/gollum/issues/1342

My hunch is arch just does not require the `ruby-rdoc` package as part of a standard ruby installation, whereas most on most other environments `rdoc` is at least de facto treated and installed as part of the ruby standard lib. I wonder if it hurts just adding `rdoc` to the `Gemfile`.

**Comment by benjaminwil** [comment]
Ah I see. No, that would not hurt. Perhaps I will add it in the gemspec along with a comment about why we're explicitly adding it as a dependency.

**Comment by benjaminwil** [comment]
This issue will be resolved in the next releases version of the gem.
