### ISSUE TITLE
Only first line of commit message should be in RSS feed item title, the rest should go to description

### ISSUE THREAD

**Issue by retifrav** [gollum/gollum#1815]
**Describe the bug**

Perhaps, not a bug but a feature request. The RSS feed seems to get an entire commit message, and it is put into RSS item `<title>` tag, while the `<description>` tag only gets meta information such as `Commited by`, `Commit ID` and `Affected files`.

This works okay while editing via web-interface, because the changes description input field only has one line, but if one works with Gollum repository on his local machine, there he can compose multiline commit messages, sometimes very long and detailed ones, and all that content will go to the `<title>`, messing up the looks of the feed in one's RSS client.

**To reproduce**

1. Commit some changes with a multiline commit message, for example:
```
Some changes

- one thing
- another thing
```
2. Push it to remote (*or wherever Gollum serves the repository contents from*).

**Expected behavior**

RSS feed item gets only first line (*perhaps with an empty line as separator*) of the commit message to its `<title>` tag, while the rest goes to `<description>` tag.

**Environment Info**

```
$ gollum --version
Gollum 5.2.3

$ git --version
git version 2.25.1

$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

**Comment by benjaminwil** [comment]
Thanks for reporting. I don’t think this should take a lot of effort to resolve, and I am personally invested in putting More Good RSS feeds into the world.

**Comment by benjaminwil** [comment]
I mentioned this issue in a commit message and, apparently, this is causing GitHub to spam this issue every time I rebase the pull request. Sorry if this is causing anyone to get emails. :sweat_smile: 

I have nearly resolved this issue, but I am second-guessing whether a long commit body belongs in the `<description>` versus in some other field. After skimming through the RSS 2.0 specification, it seems like the `<description>` is also meant to be a short sentence or two, and we may already be misusing it by putting a `<ul>` with a list of files in it.

**Comment by benjaminwil** [comment]
Never mind! It sounds like `<description>` is the right place if we're generating feed `<item>`s:

> A channel may contain any number of <item>s. An item may represent a "story" -- much like a story in a newspaper or magazine; if so its description is a synopsis of the story, and the link points to the full story. An item may also be complete in itself, if so, the description contains the text (entity-encoded HTML is allowed; see [examples](https://www.rssboard.org/rss-encoding-examples)), and the link and title may be omitted. All elements of an item are optional, however at least one of title or description must be present.

Source: https://www.rssboard.org/rss-specification#hrelementsOfLtitemgt

So with that resolved, I just need to resolve a couple minor implementation issues according to the CI failures I am seeing. (Looks like newer Rubies don't like how I initialized a `Time` object in my tests, etc.)

**Comment by benjaminwil** [comment]
I've resolved all the issues. Unless someone takes issue with the pull request, I would expect this to be merged and included in the next release.
