### ISSUE TITLE
Can't reproduce CAS setup

### ISSUE THREAD

**Issue by undertherain** [gollum/gollum#1835]
Hi!
gollum looks like one of the best solutions for the git-based self-hosted wiki, and in a single-user mode I could run it without any problems.

But I was hoping to be able to use it within a small team - and for that we need user authentication. README file  points to a page which says that "with a little tweaking" it should be possible to use something called CAS for user authentication - but overall that manual seems very partial. I could not reproduce the example - well, it doesn't even say how to run it! I'm not a Ruby user, have zero knowledge about it in fact. Rubycas-server example does not run because of some incompatible versions, with setting up "proper" CAS I also had very little success. 

Would be fantastic if developers of somebody from the side could contribute complete manual of how to set up user authentication, or even provide a ready-to-use Dockerfile. 

Thanks a lot.

**Comment by dometto** [comment]
You might want to give [omnigollum](https://github.com/gollum/gollum/wiki#authentication) a try. I think there exist ready-made Docker images using omnigollum. If you find any good ones, please do report back here, or feel free to add them to the wiki!
