### ISSUE TITLE
Deprecate gollumorg/gollum docker repository

### ISSUE THREAD

**Issue by alexander-zimmermann** [gollum/gollum#1837]
Hey folks,

do you own the gollumorg/gollum docker repository on docker hub? If yes, could you deprecated it? I believe a lot of people (like me) pull it instead of gollumwiki/gollum.

BR
Alex

**Comment by benjaminwil** [comment]
I recall a thread about the `gollumorg` Docker organization but I'm having trouble locating it.

@dometto Do you know what has happened with that organization?

**Comment by dometto** [comment]
@scolytus owns that org on DockerHub and hasn't responded to our requests to delete it in the past :-( I've archived the https://github.com/gollum/docker repository (which @scolytus started originally), I could at least delete it if that helped clear up some confusion. I don't know how much chance we'd have of getting DockerHub to remove the image.

**Comment by dometto** [comment]
I've now requested recognition of `gollumwiki` as the official org, so that it would show up as a verified open source project on Dockerhub. Hopefully that will at least stop people from pulling the wrong image.

**Comment by alexander-zimmermann** [comment]
@dometto Thanks a lot! Fine by me to close the issue ;-)
