### ISSUE TITLE
Using a config file resp. set the default ref to main 

### ISSUE THREAD

**Issue by white-gecko** [gollum/gollum#1841]
Unfortunately the discussion was closed quite fast:

> For future reference, what you need to set in your config file is:
> 
> ```ruby
> wiki_options = {
>   ref: 'main'
> }
> ```

_Originally posted by @dometto in https://github.com/gollum/gollum/discussions/1833#discussioncomment-3355720_

Actually, it is:

`config.rb`:

```ruby
wiki_options = {
  ref: 'main'
}
Precious::App.set(:wiki_options, wiki_options)
```

and it needs to be called with: `gollum --config config.rb`

Maybe some more information about the config file should be added to the documentation/README.

**Comment by benjaminwil** [comment]
Since you've resolved your immediate issue, do you mind if I co-opt this issue to track the creation of that documentation/example file?

**Comment by white-gecko** [comment]
Sure.
Actually there is a sample config.rb. It should be linked in the README as it is hard to finde, since it is hidden behinde "Show 10 more pages ..."

The page is: https://github.com/gollum/gollum/wiki/Sample-config.rb

**Comment by benjaminwil** [comment]
Great! I will audit it and ensure it's more visible.

**Comment by dometto** [comment]
I've added a link to the sample config file at the top of the wiki's home page, and made the `Sample-config.rb` page a bit more verbose. I propose that we add a link to the sample config in the wiki in the README and in the `config.rb` file in the repository root, and then close this issue.

**Comment by benjaminwil** [comment]
Sorry for dropping this. That sounds like a plan to me. :+1:
