### ISSUE TITLE
`--no-static` broken after moving to yarn

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1847]
When investigating JS precompilation issues in the context of #1119, I noticed that when building a gem from the current `master` and running `gollum --no-static`, this results in the following error:

```
Sprockets::FileNotFound - couldn't find file 'mousetrap/mousetrap.min' with type 'application/javascript'
Checked in these paths: 
  /Users/dawa/.rvm/gems/ruby-3.0.0/gems/gollum-5.3.0/node_modules
  /Users/dawa/.rvm/gems/ruby-3.0.0/gems/gollum-5.3.0/lib/gollum/public/gollum/javascript
  /Users/dawa/.rvm/gems/ruby-3.0.0/gems/gollum-5.3.0/lib/gollum/public/gollum/stylesheets
  /Users/dawa/.rvm/gems/ruby-3.0.0/gems/gollum-5.3.0/lib/gollum/public/gollum/images
  /Users/dawa/.rvm/gems/ruby-3.0.0/gems/gollum-5.3.0/lib/gollum/public/gollum/fonts:
```

It looks like this is a result of #1824. Of course, when starting the app by running `bundle exec gollum`, there's no problem, as the `node_modules` directory will be found.

I think this is not a bug per se, but we should probably clarify that `--no-static` is only intended for usage with `bundle exec`, i.e. for testing or development. Should we maybe remove it from the `--help` listing altogether?

**Comment by benjaminwil** [comment]
That all makes sense. Maybe we could also change the flag name to `--development-assets` or something like that.

**Comment by dometto** [comment]
That sounds like a good solution!

**Comment by dometto** [comment]
Just realized that this would mean the next release would be breaking. We could also leave `--static` and `--no-static` in and print a deprecation message for now?

**Comment by dometto** [comment]
I think the best thing to do would be a major release that also includes the necessary changes to the default branch logic (#1813 and #1814), otherwise that'll end up being a separate breaking change. If we can think of anything else that should go in `v6.0`, it would be good to plan that in a separate discussion! cc @bartkamphorst
