### ISSUE TITLE
Double URL escape in "last modified" link

### ISSUE THREAD

**Issue by rgov** [gollum/gollum#1851]
1. Create a page with a space in the name, e.g., `foo bar.md`
2. View the page and click the "When was this page last modified?" link.

It makes a request to

```
http://localhost:4567/gollum/last_commit_info?path=foo%2520bar.md
                                                      ^^^^^ double escaped
```

The API does not return the expected response because it tries to access a file `foo%20bar.md` instead of `foo bar.md`.

Gollum 5.3.0, Ruby 2.7.2.

**Comment by dometto** [comment]
Thanks for the report!
