### ISSUE TITLE
Consolidate command line options

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1857]
As I mentioned in #1848, here are some options for consolidating the command line options:

*    `--local-time` should be a minor option at most (perhaps only configurable through config.rb)?
*   `--lenient-tag-lookup` could be removed in 6.x, of course saving the actual compatibility feature and documenting how to enable it through config.rb.
*    `--default-keybinding` could potentially be removed and again made into config.rb option (but needn't be)

**Comment by bartkamphorst** [comment]
If we [enable mermaid.js](https://github.com/gollum/gollum/issues/1888) by default, we can also remove the `--mermaid` option.

**Comment by bartkamphorst** [comment]
For `--lenient-tag-lookup` we could add a deprecation notice. I suspect quite a few users are still using the legacy way of linking, so it would be good to give them a heads up for the potential removal of this command-line option in `7.x`.

**Comment by bartkamphorst** [comment]
I don't have a strong preference about `--local-time` and `--default-keybinding`.

**Comment by benjaminwil** [comment]
I would argue that  `--default-keybinding`, and maybe `--local-time` are both features that could be handled in JavaScript and don't really need application configuration. But it's possible there is some nuance I'm missing.

**Comment by benjaminwil** [comment]
I would personally vote to just remove them in 6.0. But I don’t have a good understanding of how disruptive that may be.
