### ISSUE TITLE
Try enabling sandbox mode  for mermaid

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1888]
I opened https://github.com/mermaid-js/mermaid/issues/3153 to track a bug with Mermaid's sandbox safety feature. According to a poster in that thread the issue should be resolved in a newer version of mermaid. We should test this and enable sandbox by default if possible.

**Comment by dometto** [comment]
Sandbox mode has improved a little bit but there's still a bug for invalid diagrams, see [here](https://github.com/mermaid-js/mermaid/issues/3153#issuecomment-1329745239). @benjaminwil @bartkamphorst is this acceptable for gollum, or should we just keep the current more relaxed security setting? This also relates to the question whether we want to enable support for mermaid by default (without having to use `--mermaid`).

**Comment by benjaminwil** [comment]
Am I understanding that Mermaid is working properly with the stricter security setting _unless_ the the diagram is invalid?

If that's the case, maybe this is acceptable for Gollum.

It would be nice if there was a path towards providing a better error message for users... but that might be a larger issue for Mermaid if I'm understanding the issue correctly.

**Comment by dometto** [comment]
> Am I understanding that Mermaid is working properly with the stricter security setting unless the the diagram is invalid? If that's the case, maybe this is acceptable for Gollum.

That's right!

> It would be nice if there was a path towards providing a better error message for users... but that might be a larger issue for Mermaid if I'm understanding the issue correctly.

Yes, although the bug's open and recognised, and development on mermaid seems quite active So there's hope :)

**Comment by bartkamphorst** [comment]
I think we should enable mermaid by default and remove the `--mermaid` flag. I would favor enabling it in sandbox mode, and hope that the mermaid devs will fix the issue with invalid diagrams relatively soon.
