### ISSUE TITLE
Feature request: Download raw Markdown source for a page

### ISSUE THREAD

**Issue by rgov** [gollum/gollum#1906]
I would like an API for grabbing the raw, unrendered Markdown source for a page, like the "Raw" button on GitHub:

https://raw.githubusercontent.com/gollum/gollum/master/CONTRIBUTING.md

I understand I can access the underlying file on disk, or use the Edit button and copy the contents of the page.

This would make it easy to access a page from a script, or to export it to make a plain text attachment on an email, etc.

**Comment by rgov** [comment]
That might introduce a conflict if someone has a directory called `raw` no? Maybe that's not a big problem but alternatively `?raw=true` would be sufficient.

**Comment by benjaminwil** [comment]
🤦 Yeah, that seems a lot less error prone. Thank you!

**Comment by dometto** [comment]
I'm fine with `?raw=true` but also with `/gollum/raw/`. There's already e.g. `/gollum/assets/` so it's impossible to completely avoid clashes with file and directory names anyway.
