### ISSUE TITLE
Move uglifier to development dependency for faster package build

### ISSUE THREAD

**Issue by fliiiix** [gollum/gollum#1909]
**Describe the bug**
I think uglifier should be a development dependency and not a runtime dependency as it is right now.
As far as I can tell it is not required to run gollum, the only use is here -> https://github.com/gollum/gollum/blob/869292ed1e5018102729db1b1d46815807761e34/Rakefile#L251

- https://github.com/gollum/gollum/blob/master/gollum.gemspec#L35
- https://apidock.com/ruby/Gem/Specification/add_dependency

Why does this matter right now the FreeBSD ports requires that which then in requires 
nodejs to be built which is a big port which takes long.
`gollum -> uglifier -> execjs -> nodejs` dependency tree 
(Quickly checked on arch linux and its the same there i suspect it is packaged like this in most places)

**Expected behavior**
If it is move out of the runtime dependency the gollum package could be built faster (less dependencies to run).

**Comment by dometto** [comment]
A very reasonable request! We can move the dependency now and the change will make it into the upcoming 6.0 release.
