### ISSUE TITLE
Unsupported markups no longer shown as disabled (gray)

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1927]
![Screenshot 2022-12-27 at 11 41 03](https://user-images.githubusercontent.com/571173/209654692-8e89f76d-e39c-4bda-a502-ba025bc872a7.png)

It used to be the case that markups that were not installed and thus not supported by a gollum instance would be shown in gray in the `select` element. This apparently no longer works (on master, so not related to #1915).

**Comment by bartkamphorst** [comment]
Apparently, dropdown menus cannot (or are no longer consistently) styled with CSS. It would seem that the only option (no pun intended) is to actually add the disabled attribute to the option fields that aren't available. 
![Screenshot 2023-08-01 at 23 17 06](https://github.com/gollum/gollum/assets/571173/741fceb6-ee08-46e0-a048-925aaa67414e)
However, this would change gollum's behavior, since it would no longer be possible to actually select one of the unavailable formats and create a page (e.g. in BiBTeX) that gollum would not be able to render. @dometto @benjaminwil Would we be okay with this change in behavior?

**Comment by benjaminwil** [comment]
I think this change makes sense 👍 Any of these created pages would also not be previewable or viewable after save? If that's true: I think it makes for a better user experience to add the `disabled` attribute and ensure that users don't create unviewable pages.

**Comment by dometto** [comment]
> I think it makes for a better user experience to add the disabled attribute and ensure that users don't create unviewable pages.

Agreed!

**Comment by bartkamphorst** [comment]
> Any of these created pages would also not be previewable or viewable after save?
![Screenshot 2023-08-02 at 10 43 12](https://github.com/gollum/gollum/assets/571173/a78ab7ff-5a83-4fef-b46c-e6be439e2b72)

or for another format:

![Screenshot 2023-08-02 at 11 24 32](https://github.com/gollum/gollum/assets/571173/f86247a3-3690-48a7-b59d-10b7ff1837cc)

None of the content of the page is shown, only the error message (current behavior).

One issue I just ran into with setting the option fields to `disabled` is that these fields, if selected anyway, are not sent with the form. Why is this a problem? Because a user can use the create modal to create a file with a format that isn't enabled, say `example.org`. In the editor, the format selector is then set to (the disabled) `org-mode`, but when the file is saved, we run into an error:

![Screenshot 2023-08-02 at 10 46 32](https://github.com/gollum/gollum/assets/571173/74d2b78e-915f-4fcf-ac5c-8e70406aaa8a)

**Comment by bartkamphorst** [comment]
Ideally, the format would be specified in the create modal. Something like this:
![Screenshot 2023-08-02 at 19 15 58](https://github.com/gollum/gollum/assets/571173/fa707ea4-86e4-4261-aea6-b659b20930e6)
![Screenshot 2023-08-02 at 19 17 23](https://github.com/gollum/gollum/assets/571173/69ca4e78-3d7f-488a-99fc-7994c6b76a51)

That way, we would have the benefit of showing users which formats _could_ be supported by gollum (but aren't enabled), and hide those unused formats in the editor format dropdown. Thoughts?

**Comment by benjaminwil** [comment]
I like it.

**Comment by dometto** [comment]
I like it too! However, at present you can also navigate to a nonexisting page and be redirected to the Create page. In that scenario, you wouldn't see the Create New Page dialog at all. So maybe we need to implement some sanity checking after all? Either by verifying that a valid format is selected before saving a new page, or by gracefully handling the error you posted in the backend.

**Comment by bartkamphorst** [comment]
What we really need is Primer ViewComponents, so that we can use the [select panel](https://primer.style/css/storybook/?path=/docs/deprecated-selectmenu--docs#disabled).
