### ISSUE TITLE
Copy to clipboard button styling is unresponsive

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1942]
I noticed that if you zoom out a lot in your browser, the copy to clipboard button doesn't really scale/position well. This is a rather niche issue so I'm happy to close this as a wontfix, unless it's necessary to fix this for a good mobile experience. But I'm assuming the button won't even show up on mobile?

<img width="787" alt="Screenshot 2023-01-16 at 20 14 16" src="https://user-images.githubusercontent.com/147111/212751852-bad39ae5-e2f2-4c3d-8c37-4d7481bef854.png">

**Comment by benjaminwil** [comment]
I'm currently dealing with other issues related to this button, so I might as well think about this issue while I'm in there.

Other issues include:

- Making this button keyboard accessible.
- Making this button aware of browser clipboard API permissions.

**Comment by dometto** [comment]
Amazing, thanks!

**Comment by bartkamphorst** [comment]
@benjaminwil This issue was resolved, yes?

**Comment by benjaminwil** [comment]
I will have to double-check, as I can't really remember exactly how complete my work related to this button ended up being. I will close once I've verified.

**Comment by benjaminwil** [comment]
Yes, this was resolved!
