### ISSUE TITLE
Gollum markdown editor uses wrong image tags / links

### ISSUE THREAD

**Issue by good-unit** [gollum/gollum#1949]
In the inline markdown editor... when you click on "add image tag" gollum's editor uses the wrong ones.

The correct tag type:
[[ | ]]

The editor uses this type:
![]()

**Comment by bartkamphorst** [comment]
As far as I know the correct [image syntax](https://www.markdownguide.org/basic-syntax/#images-1) still is `![alt text](image.jpg)`.

**Comment by good-unit** [comment]
No, it's not -- according to the wiki:
https://github.com/gollum/gollum/wiki#tags
(scroll down)

**Comment by dometto** [comment]
Gollum has its specific tag syntax and markdown and other supported formats have their own image syntax. Both will be rendered correctly. At the moment, the editor inserts the markdown syntax, for both images and normal links. A case could be made for making the editor use gollum's own syntax, but the present behavior also seems reasonable to me, especially for users who want to produce documents that can be read by other apps.
