### ISSUE TITLE
Markdown: A line with just 2 spaces isn't a newline?!

### ISSUE THREAD

**Issue by good-unit** [gollum/gollum#1950]
Gollum Markdown question: 
* Why doesn't an "empty newline" with just 2 spaces at the end of line count as a newline in the generated HTML?
* Why do you have to add an ugly HTML tag \<br>?

**Comment by good-unit** [comment]
Thanks for the quick response.

>And I'm not sure what you mean by an "empty newline", since a blank line before another line should already cause that next line to be rendered as a new paragraph?

Exactly! But... if you put 2 or more empty lines it's just treated the same as if you had put only 1 empty line.
Why?
Sometimes I want 2 lines between the paragraphs. Why do I have to put ugly \<br> tags?
Why can't the newline be a newline -- why is it ignored?!

For e.g below (I put 1 empty line between a-b, and 2 empty lines between b-c... but they are spaced the same way).
This is silly (in my view):

a

b


c

**Comment by dometto** [comment]
As you can indeed see the same behavior occurs on github.com, or indeed any other app or site that uses markdown. It's simply part of the way markdown works! You can use other markup languages if you don't like markdown (and gollum supports a few) :)

**Comment by good-unit** [comment]
> As you can indeed see the same behavior occurs on github.com, or indeed any other app or site that uses markdown. It's simply part of the way markdown works! You can use other markup languages if you don't like markdown (and gollum supports a few) :)

Yes, but after working with it even further -- the more I dislike it.
If there is a bullet-list and say a title... and you want to leave 2 spaces in between them... it seems you can't.
You have to leave a new line after the last bullet list item... but if you also put a \<br> after that -- the generated HTML leaves 3 lines! in between the two sections. You can only leave 1 or 3 lines in between. I think we should make a request to change the Markdown rules. What do you think? Why can't a newline be a newline?

Anyway, I tried your suggestion of using asciidocs instead... 
The editor and HTML generator doesn't seem to support a huge majority of asciidocs.
Just one e.g: "Literal paragraphs" (indented lines -- which should be "pre-formatted") are treated as code blocks by gollum.

I started going through a: asciidoc cheat sheet -- to see what's supported and it seems not much... e.g the "Notes" (warnings/alerts) feature isn't supported, tables are a bit wonky, etc, etc, etc.
