### ISSUE TITLE
Markdown-style page links work inconsistently

### ISSUE THREAD

**Issue by claman** [gollum/gollum#1951]
**Describe the bug**
Markdown-style links to pages (such as those generated automatically by vimwiki) are correctly linked when rendering the index page, but are not linked on any other pages. It's possible that this is something related to the markdown renderer I'm using, but the inconsistency is confusing.

**Environment Info**

```
Gollum 5.3.0
Running on: x86_64-darwin20 with Ruby version 2.7.2
Using:
rugged 1.1.1
gollum-rugged_adapter 1.1.2
gollum-lib 5.2.2
Markdown rendering gem: commonmarker
Other renderering gems:
none
```

**Comment by bartkamphorst** [comment]
@claman Could you please provide reproducible examples so we can better understand what might be going on?

**Comment by claman** [comment]
Yes, absolutely. What's the best way to do that? Post example files themselves here, or put them into their own repository?

**Comment by benjaminwil** [comment]
@claman Even just a list of clear, easy-to-reproduce steps would suffice. Here's a silly example:

1. Create a new page with a link: `[some](/link)`.
2. View the new page.
3. Click on the link and note the new browser URL: `https://my-website.com/not-the-correct-link`.

**Comment by claman** [comment]
sorry for the quiet; should be able to take a look at this over the weekend

**Comment by claman** [comment]
Alright, I've successfully reproduced this. The steps are as follows:

1. initialize git repo in empty folder, start gollum and make a Home page
2. create a new page, "test", and link to it from Home using [test](test) -- link works
3. create another new page, "another test page", and link to it from "test" using [test2](another test page) -- link does not work from here or Home

The spaces are the problem; I can get the link to work by using "another%20test%20page" in the link instead.

I'm trying to make this inter-operable with vimwiki, which can handle spaces in filenames, but this seems less like a bug and more like my own issue to figure out. Sorry for the bother!

**Comment by benjaminwil** [comment]
No bother at all. Thanks for the update. Very interesting problem! Best of luck to you, and I’d be curious to hear how you end up resolving the interoperability issues.

**Comment by claman** [comment]
Filenames with spaces in them do work between double square brackets, however. So from the above comment: `[[another test page]]` would link correctly

**Comment by claman** [comment]
It looks like I may be running into a problem with the kramdown parser?
