### ISSUE TITLE
matrix and magnet links won't work with AsciiDoc

### ISSUE THREAD

**Issue by tastytea** [gollum/gollum#1959]
[Matrix specifies an URI scheme](https://github.com/matrix-org/matrix-spec-proposals/blob/old_master/proposals/2312-matrix-uri.md). A link to a user account looks like this, for example: `matrix:u/foo:example.org`.

**Describe the bug**
Matrix links work with asciidoctor like this: `link:matrix:u/foo:example.org[foo]`. However, they don't work with asciidoctor in gollum. There is no hyperlink generated at all. asciidoctor versions are the same.

The same problem exists with magnet links, like `link:magnet:?xt=urn:sha1:YNCKHTQCWBTRNJIV4WNAE52SJUQCZO5C[bar]`.

**To Reproduce**
1. Create asciidoc wiki page with `link:matrix:u/foo:example.org[foo]`
2. look at it in the browser

**Expected behavior**
`<a href="matrix:u/foo:example.org">foo</a>` in the generated HTML.

**Environment Info**
```
Gollum 5.3.1
Running on: x86_64-linux with Ruby version 2.7.7
Using:
rugged 1.6.2
gollum-rugged_adapter 2.1.0
gollum-lib 5.2.3
Markdown rendering gem: kramdown
Other renderering gems:
asciidoctor 2.0.18
```

**Comment by benjaminwil** [comment]
Hey there, thanks for reporting this issue.

I was able to reproduce your issue:

- Gollum does not render Magnet and and Matrix prefixed URLs.
- Using `Asciidoctor#convert` directly _does_ render those links.

I was able to determine that `gollum-lib` uses the gem `loofah` to sanitize URLs added to wiki pages. `loofah` includes a list of acceptable protocols: `::Loofah::HTML5::SafeList::ACCEPTABLE_PROTOCOLS`. [Link to current source](https://github.com/flavorjones/loofah/blob/5f7efdb02ed092f4dd73a88c451c66cdd12baaca/lib/loofah/html5/safelist.rb#L980-L1009). It seems to me that `loofah` is missing a lot of modern and weirdo protocols: not only `magnet:` and `matrix:`, but also `gemini:` and others.

I haven't done any research yet into what `loofah` chooses which protocols are "acceptable" versus "not acceptable," so I am unsure whether submitting a patch upstream to `loofah` would be fruitful or not. But it may be worth learning whether that's an option or not.

Alternatively, we could stop using `loofah`'s safelist for wiki content. In my opinion, this would be a reasonable thing to do. We're still sanitizing the entire wiki page contents for malicious code anyway, so what does `loofah`'s accepted protocols really give us? For unstructured content like a wiki page, I don't think that protocol filtering is very valuable, and, indeed, makes it difficult to support up-and-coming link formats like `gemini:`, for example.

**Comment by bartkamphorst** [comment]
Have a look at https://github.com/gollum/gollum/wiki/Security. Rather than disabling `loofah`, I would suggest explicitly allowing certain protocols in `config.rb`:
```ruby
Loofah::HTML5::WhiteList::ALLOWED_PROTOCOLS.add('magnet')
```

**Comment by dometto** [comment]
We have already added some protocols to the default allow list for `loofah` in the past, here: https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/sanitization.rb#L1

So I am happy in principle to more protocols to that list. The question @benjaminwil raises is what the point of imposing any kind of limit to link protocols is -- if we feel fine about having added `apt` in the past, and would consider adding `matrix` etc. now, why not just allow them all? However, doing so would depend on whethr `loofah` allows disabling sanitization of protocols (without disabling other sanitization).

**Comment by bartkamphorst** [comment]
I think there are sound reasons for not allowing all protocols. For examples, see [this thread](https://news.ycombinator.com/item?id=13044991). The fact that the Loofah allowlist can be extended easily through `config.rb` is enough for me.
