### ISSUE TITLE
`--h1-title` removes first h1 formatting

### ISSUE THREAD

**Issue by landonjx** [gollum/gollum#1960]
When using the `--h1-title` option, the selected h1 is shown without formatting (links, bold, etc. are all stripped for display).

Not sure which version this is. I'm running a docker image, first retrieved Jan. 2023. The web server adds `Server: WEBrick/1.7.0 (Ruby/3.1.3/2022-11-24)` to the response headers.

**Comment by landonjx** [comment]
Possibly related to #1480

**Comment by bartkamphorst** [comment]
Just to add to this: as far as styling is concerned, you could use `custom.css` to change the look of the H1.

**Comment by landonjx** [comment]
> Just to add to this: as far as styling is concerned, you could use `custom.css` to change the look of the H1.

Sure but there are limitations. No links and you'd need to style the whole thing as one, so no footnote indicators (`<sup>1</sup>`), for example

**Comment by landonjx** [comment]
Alright, I figured as much but thought I'd ask. I'll turn off `--h1-title` and use the custom css to hide the default title.

**Comment by bartkamphorst** [comment]
@landonjx Sorry, I didn't mean to dismiss your question/suggestion; just to point you to a workable solution. We can still discuss the desired behavior.

@dometto There at least a discrepancy in how `h1_title` is documented in the code in gollum-lib. The official docs say that `--h1-title` "sets page title to value of first h1" whereas `wiki.rb` states "Concatenate all h1's on a page to form the page title."

**Comment by landonjx** [comment]
@bartkamphorst I did/do appreciate your suggestion, regardless of its caveats. I went into this suspecting this issue was likely a non-starter. As well, sanitization was mentioned earlier. I hadn't considered that the title might need to be used elsewhere.
