### ISSUE TITLE
Changelog for version 5.3.1 is spooky

### ISSUE THREAD

**Issue by ceedriic** [gollum/gollum#1964]
**Describe the bug**

See title: In https://github.com/gollum/gollum/blob/v5.3.1/HISTORY.md, we have
1. Parallel universes (same version at different date)
2. A year with 20 months in it.

**Comment by dometto** [comment]
Thanks for the report! Looks like there was some user error here (i.e. on my part), but I'm not sure how I managed that given that the Rakefile should be guarding against this:

1. Double versions should be ruled out: https://github.com/gollum/gollum/blob/master/Rakefile#L209
2. The date is automatically added in the Rakefile, in `"%Y-%m-%d"` format: https://github.com/gollum/gollum/blob/master/Rakefile#L231

Will have to investigate!

**Comment by dometto** [comment]
Because `5.3.1` was a backport release, our release tooling wasn't functioning correctly and I ended up having to do things manually. #1971 will fix this.
