### ISSUE TITLE
a page move does not delete the worktree file with the old name

### ISSUE THREAD

**Issue by guillaume-d** [gollum/gollum#1976]
When moving a page, if using a non-bare repo, the file with the old name does not get deleted and just lies around.
IMHO the old file may go, we have version-control for it anyway.

"Thanks" to https://github.com/gollum/gollum/issues/1975 not being fixed yet, it does not (yet) prevent creating new pages under the old names! :wink:

**Comment by bartkamphorst** [comment]
I haven't been able to reproduce this behavior. Could you list the output of `gollum --versions` on your system and give us the exact steps to reproduce the issue? Here's what I'm seeing:

1. Create `bar.md` through the web interface;
2. Rename `bar.md` through the web interface to `foo.md`;
3. In the Overview, `foo.md` is found but `bar.md` is not;
4. In the working directory, `foo.md` is found, but `bar.md` is not.

Seems to me like it's working as intended.
