### ISSUE TITLE
Include tag not working with absolute paths

### ISSUE THREAD

**Issue by aaakbar** [gollum/gollum#1978]
Include tag works fine with relative paths, but when it comes to absolute paths it treats them as relative when the page is saved.

**NOTE**: When using Preview tab, the absolute paths seems to be rendered as expected. The problem only seems to be appearing when saving the doc.

**To Reproduce**
1. create a doc `/some/prefix/doc.md` and add some content
2. create another doc `/other/prefix/otherdoc.md` and try including the first doc in it using abs path to the first doc: `[[include:/some/prefix/doc.md]]`. Save the page.
3. in place where content of included page (= `doc.md`) should appear you get a message: Cannot include **/other/prefix/some/prefix/doc.md** - does not exist yet.

**Expected behavior**
Include tag with an absolute path to document should render the included document's content.

**Possible source of problem**
I investigated the `gollum-lib` repo and might have found the culprit - [Function `process_include_tag`](https://github.com/gollum/gollum-lib/blob/4a970f2d57806faf658ec32b593fa7e05e1a7c23/lib/gollum-lib/filter/tags.rb#L120). I'm not a Ruby dev myself so I might be wrong here. Nevertheless...`process_include_tag` contains the following line which seems to explain the source of the problem.
```ruby
resolved_page_name = ::File.join(@markup.dir, page_name)
```
When processing/rendering the include tag, current document's directory is used as prefix regardless of whether the path is abs. or rel. as there seems to be no specific handling of absolute paths (those with a `/` prefix). The included doc's abs. path seems to be appended to the directory of the including doc. In case of a leading slash the include paths should prob. not be concatenated with including docs path but shoud prob. simply be used as is. Sth. like:
```ruby
resolved_page_name = page_name
```
Prob. just a matter of adding an `if...else`.

**Environment Info**
```
Gollum 5.3.2
Running on: x86_64-linux with Ruby version 3.2.2
Using:
rugged 1.6.3
gollum-rugged_adapter 2.1.0
gollum-lib 5.2.4
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by dometto** [comment]
Fixed in https://github.com/gollum/gollum-lib/pull/452 (this will be included in the next bugfix release of `gollum-lib`).
