### ISSUE TITLE
Docker image does not include an ssh client.

### ISSUE THREAD

**Issue by jagerkin** [gollum/gollum#1981]
The docker image lacks an ssh client and so can't sync to ssh connected git repos.

**To Reproduce**
1. Create a docker container for a repo cloned from an ssh:// repo.
2. Register a post commit hook in the config.rb:
```
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
  `(cd /wiki && git pull && git push)`
end
```
4. Update a page
5. Error: Change is not pushed to upstream repo.
6. Open a terminal to the container: `docker exec -it CONTAINER_ID /bin/sh`
7. cd /wiki
8. git pull
9. Error:
```
/wiki # git pull
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

**Expected behavior**
Expected the git repo to sync and then push changes upstream.

**Environment Info**
```
/wiki $ gollum --versions
Gollum 5.3.0
Running on: x86_64-linux-musl with Ruby version 3.1.4
Using:
rugged 1.6.3
gollum-rugged_adapter 2.1.0
gollum-lib 5.2.4
Markdown rendering gem: kramdown
Other rendering gems:
RedCloth 4.3.2
org-ruby 0.9.12
creole 0.5.0
asciidoctor 2.0.20
wikicloth 0.8.3
```

**Comment by benjaminwil** [comment]
Thank you!

**Comment by bartkamphorst** [comment]
Thanks @jagerkin for the PR!
