### ISSUE TITLE
How to fast forward when possible?

### ISSUE THREAD

**Issue by kuon** [gollum/gollum#2005]
I integrate with git the following way:

```ruby
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
   committer.wiki.repo.git.pull('origin', committer.wiki.ref, credentials: creds)
   committer.wiki.repo.git.push('origin', committer.wiki.ref, credentials: creds)
end
```

But it creates a merge commit every-time.

I'd like to fast forward when possible to avoid the merge commit.

For now, I use the following workaround:

```ruby
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
  `cd /srv/gollum/diuriflux/internal-docs && git pull --ff`
  `cd /srv/gollum/diuriflux/internal-docs && git push`
end
```

But I'd like better support for conflict. Basically, when the origin has change and fast forward is not possible, force checkout the origin and apply changes on that.

**Comment by dometto** [comment]
The git classes that you are interacting with are defined [here](https://github.com/gollum/rugged_adapter/blob/master/lib/rugged_adapter/git_layer_rugged.rb). You can have a look if the support the methods you want -- in many cases, the methods (`pull`) just pass on their options to the underlying [rugged](https://github.com/libgit2/rugged) objects, so having a look at their docs might help you achieve what you want.

Let me know if that's enough to get you started at least!
