### ISSUE TITLE
Setting the gollum author environment variables doesn't make the Git commit use them.

### ISSUE THREAD

**Issue by andrewducker** [gollum/gollum#2012]
**Describe the bug**
Setting the gollum author environment variables doesn't make the Git commit use them.

**To Reproduce**
Set the Environment variables:
GOLLUM_AUTHOR_EMAIL            bob.smith@mycompany.com
GOLLUM_AUTHOR_USERNAME         Bob.Smith

Edit a page.

**Expected behavior**
The generated commit would use those variables in the commit.

**Actual behaviour**
The commits are from "anonymous".

**Environment Info**

Gollum 5.3.2
Running on: java with Ruby version 3.1.4
Using:
rjgit 5.7.0.2
gollum-rjgit_adapter 0.6.1
gollum-lib 5.2.4
Markdown rendering gem: kramdown
Other renderering gems:
none

**Comment by bartkamphorst** [comment]
Thanks for the report @andrewducker . The environment variables you mention only have a function in the context of the gollum docker image. For local use of gollum, you should just be able to set your `user.name` and `user.email` through git:
```bash
git config user.name " Bob.Smith"
git config user.email "bob.smith@mycompany.com"
```
(Or use the `--global` flag to apply these settings to all your git repositories.)

Please report back if this doesn't solve your issue.
