### ISSUE TITLE
Failed to run `java gollum.war` resulting in thread error

### ISSUE THREAD

**Issue by RayyanNafees** [gollum/gollum#2018]
**Please read the [CONTRIBUTION GUIDELINES](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md) before submitting!**

If your have problems using or installing the software which stem from bugs in the software or a lack of documentation, we are always happy to help out! However, **for ordinary usage questions, please consider asking elsewhere**, for instance on [StackOverflow](http://stackoverflow.com/questions/tagged/gollum-wiki).

**Describe the bug**
downloaded the `gollum.war` file to run using `java -jar gollum.war -S gollum`

**To Reproduce**
1. Install [scoop](https://scoop.sh) and install `git` if not installed: `scoop install git`
2. Install Microsoft JDK 17 : 
    ```bash
    scoop bucket add java
    scoop install microsoft17-jdk
    ```
4. Download the `gollum.war` from the [latest release](https://github.com/gollum/gollum/releases/tag/v5.3.2)
5.  Run in your terminal `java -jar gollum.war -S gollum`

**Expected behavior**
The gollum server should've ran
**Screenshots**
![image](https://github.com/gollum/gollum/assets/59685062/f16903e0-dd8b-43a3-849b-39f5295b9278)

**Environment Info**
|Edition	|  Windows 11 Home Insider Preview Single Language |
|---|---|
|Version	| 22H2 |
| Installed on	| ‎02/‎12/‎2023 |
| OS build	| 23595.1001 |
| Experience	| Windows Feature Experience Pack 1000.23595.1001.0 |

Always include the output of the `gollum --versions` command (NB: `versions` in plural).

[v5.3.2](https://github.com/gollum/gollum/releases/tag/v5.3.2)

**Comment by dometto** [comment]
Thanks for the report! I'm currently unable to try and reproduce this, but could you try with `java -jar gollum.war -S bin/gollum` (instead of `-S gollum`)? Also make sure the directory you're running the command from is a valid git repository (or provide gollum the path to one).

**Comment by RayyanNafees** [comment]
Thank you
Sorry for being irresponsive, the Issue was resolved on windows by your recommended command:
```bash
git init .
java -jar gollum.war bin/gollum
```
