### ISSUE TITLE
git creates 'main' as default branch

### ISSUE THREAD

**Issue by 0-wiz-0** [gollum/gollum#2025]
Please consider changing the default for `--ref` from `master` to `main`.

Reason:
I installed gollum for the first time today, pointed it at a freshly initialized git repository and tried adding files to it in the file system - but they were never visible on the web.
It took me some time to find out that gollum's web commits were to 'master' while mine were on 'main'.
Because the default branch for a new git repository is now 'main' (it was 'master' in the past).

I'm now running `gollum --ref main path` and it works, but this cost me some time to find out.

**Comment by dometto** [comment]
Hi @0-wiz-0! This should be fixed on the current `master` version of Gollum. If you want you can try this out by pulling the Docker image, but basically the new gem release (6.0) is long overdue, and this is another reason to release it soon.
