### ISSUE TITLE
Move from RACK_ENV to APP_ENV

### ISSUE THREAD

**Issue by svoop** [gollum/gollum#2029]
Gollum is using `RACK_ENV` to set the environment (production, development) similar to `RAILS_ENV`. While this is quite a common pattern, `RACK_ENV` was [never intended for this](https://github.com/rack/rack/issues/1546).

Given other frameworks move towards `APP_ENV` instead (even Rails 7 honors this), how about making the change on Gollum as well?

A quick grep shows only two places where this is used:

* [x] [bin/gollum](https://github.com/gollum/gollum/blob/db4adc231c26d58bb7e42da45ffcd768990ba239/bin/gollum#L285C3-L285C33) –> read `APP_ENV`, fall back to `RACK_ENV` (with deprecation warning), fall back to `:production`
* [x] [test/helper.rb](https://github.com/gollum/gollum/blob/db4adc231c26d58bb7e42da45ffcd768990ba239/test/helper.rb#L31) -> given the above just use `APP_ENV` instead
* [x] Maybe also document `APP_ENV` in the README.

What do you think about this? Am I missing something and if not, would you consider such a PR for merge?

**Comment by benjaminwil** [comment]
I think this change would make sense. I don't see anything stopping us from deprecating using `RACK_ENV` and removing it in the next major version or something like that.

Thanks for pointing out how we could make Gollum more conventional.

**Comment by dometto** [comment]
I agree this would be a good idea. Let's add a deprecation notice!

**Comment by dometto** [comment]
If I see correctly all the todos in the issues are completed now. Thanks again @svoop!
