### ISSUE TITLE
Move from master to main as default branch

### ISSUE THREAD

**Issue by svoop** [gollum/gollum#2030]
Here's another migration the time appears to be right IMO:

Up to now, the default branch (ref) for the wiki is "master". While this works fine for existing wikis, it bombs when creating a new one since git, GitHub, GitLab etc bootstrap new repos with "main" as the default branch for quite some time already.

I'd suggest:

* A patchlevel bump now which adds a deprecation warning to explicitly add `ref: 'master'` to your config.
* A major bump later which changes the default fron "master" to "main".

What do you think?

**Comment by benjaminwil** [comment]
This is related to #1813, which is resolved in 6.0.

So, this won't be an issue in 6.0. We should be gracefully handling both `main` and `master` branches as default branches for ever.

Let me know if I have misunderstood, but I think we can close this.

**Comment by svoop** [comment]
@benjaminwil You're totally right, thanks for the hint, I should have searched more carefully beforehand.

**Comment by dometto** [comment]
I think there is still a sense in which `master` is default, in that (in 6.0) it's the backup option if gollum-lib doesn't detect the existence of either branch. @svoop's comment is maybe a good reminder that we can switch that around now!

**Comment by benjaminwil** [comment]
Ah, right. I hadn't thought about it that way.

I also see there are some docs calling out `master`. Maybe those should be revisited also.
