### ISSUE TITLE
No API  in  `A simple, Git-powered wiki with a sweet API and local frontend. `

### ISSUE THREAD

**Issue by micheleAlberto** [gollum/gollum#2033]
**Describe the bug**
the repository description says : `A simple, Git-powered wiki with a sweet API and local frontend. `

Correct me if I am wrong but there are no APIs. If you want to get the contents of the wiki you can only access the presentation layer but there si no programmatic access like an endpoint providing the markdown or the metadata associated with any content of the wiki.

**To Reproduce**
1. Go to https://github.com/gollum/gollum
2. read the description on the right sidebar
4. write `API` in the search bar on the top right
6. verify there is no API

**Expected behavior**
Documented rest APIs, possibly with some openAPI specification.

**Comment by benjaminwil** [comment]
I think the API being referred to is [`gollum-lib`](https://github.com/gollum/gollum-lib). I can see how the "sweet API" description is misleading.

If the other maintainers agree, I would be good with shortening the description to simply read, "A Git-powered wiki" 😃

**Comment by dometto** [comment]
I would be happy with that! :)

But also: is there a usecase for having an actual api in gollum?

**Comment by micheleAlberto** [comment]
Obviously yes!
I am running a roleplaying game with my friends and we use a Gollum wiki to organize the lore of our adventures set in northern Italy around the year 3020. I use Gen AI to add more content and my current workflow involves opening each page of the wiki, click edit, copy the markdown then pasting it into a chatbot.

I wish I could automate this or at least the data extraction.

**Comment by dometto** [comment]
I'm also wondering if for most operations it might not be more desirable to clone the repository and make scripted changes to it, then push back the changes (so basically going behind gollum's back). https://github.com/grackorg/grack is a simple rack server that serves up git repos (you can push/pull to it) that once worked on and that *should* still be functional, if you wanted to stay in the rubysphere. :-) Also note the `/data/` route in gollum which may be useful for your purposes.

In any case, let's change the description on the repo and in the Readme for now and close this issue. @micheleAlberto for any desires for concrete verbs/behavior that could be provided by an API in gollum itself, feel free to open a request and we can discuss further there..

**Comment by dometto** [comment]
Changed the description to `A simple, Git-powered wiki with a local frontend and support for many kinds of markup and content` -- if anyone has a better suggestion, let me know!
