### ISSUE TITLE
Edit button does not lead to editable content

### ISSUE THREAD

**Issue by timrdf** [gollum/gollum#2051]
**I have read the [CONTRIBUTION GUIDELINES](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md) before submitting!**

If you**r** [sic] have problems using or installing the software which stem from bugs in the software or a lack of documentation, we are always happy to help out! ~~However, **for ordinary usage questions, please consider asking elsewhere**, for instance on [StackOverflow](http://stackoverflow.com/questions/tagged/gollum-wiki)~~.

**Describe the bug**
Unable to edit a page.

**To Reproduce**
1. Install gollum 5.3.3 using ruby gem
2. Invoke using `gollum --config home.gollum.rb --ref main` with `home.gollum.rb` containing `Precious::App.set(:wiki_options, { :index_page => 'home.md' })`.
3. Load a page http://localhost:4567/this/is/mypage.md
4. Observe some content rendered, e.g. "This is some content on a page that I put here on command line."
5. Click the Edit button.
6. On page http://localhost:4567/gollum/edit/this/is/mypage.md see an empty content page with one empty line. Wonder where the content to edit is.
7. Observe that the Preview tab shows the content of the page that we'd expect to be editing.
8. Click Save button anyway.
9. Land on page http://localhost:4567/gollum/edit/mypage.md (note** absence of path `/this/is/`) with content of some random guid e.g. 782d2bd32e3bd351450f8c1246ce177e5b8f64e4
10. Revisit http://localhost:4567/this/is/mypage.md
11. Observe some content rendered, e.g. "This is some content on a page that I put here on command line."

\*\*The same behavior occurs when trying to edit http://localhost:4567/home.md, so the extra path is not the only culprit.

**Expected behavior**
After clicking the Edit button on a page, the page enters an edit mode that shows the source code of the page and permits that source code to be modified and saved. 

The following screen shot illustrates what is expected:

<img width="1268" alt="Screenshot 2024-05-21 at 10 22 57 PM" src="https://github.com/gollum/gollum/assets/341956/cda5da11-9933-43db-a8d4-b994ed2458ab">

**Screenshots**
I added screenshots to help explain my problem.

<img width="1424" alt="2-click-edit-button" src="https://github.com/gollum/gollum/assets/341956/d9a6bd7b-7829-4b5a-9254-d3637f736cb5">

<img width="1421" alt="3-editing-none-of-the-content" src="https://github.com/gollum/gollum/assets/341956/2233361e-0f7a-4357-9b1e-62819cc9b6bc">

**Environment Info**

The undesirable behavior was done on an iMac with:

```
$ gollum --versions
Gollum 5.3.3
Running on: universal.x86_64-darwin23 with Ruby version 2.6.10
Using:
rugged 1.7.2
gollum-rugged_adapter 2.1.0
gollum-lib 5.2.4
Markdown rendering gem: kramdown
Other renderering gems:
none
```

The expected behavior was successfully accomplished on a MacBook:

```
% gollum --versions
Gollum 5.3.3
Running on: universal.x86_64-darwin22 with Ruby version 2.6.10
Using:
rugged 1.7.2
gollum-rugged_adapter 2.1.0
gollum-lib 5.2.4
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by benjaminwil** [comment]
Thanks for the detailed report 👍 I appreciate it.

I have one question for you:

> Observe some content rendered, e.g. "This is some content on a page that I put here on command line."

When you say you put the content on that page via the command line, how did you do this? Gollum does not care about the local filesystem--it only cares about Git tracked files. So I just want to confirm whether your file that reads **"This is some content on a page that I put here on command line."** was already in a git commit or not.

**Comment by timrdf** [comment]
Sure thing!

Yes, after I created the page on the command line, I did commit it. That commit is actually my most recent and thus my current HEAD, as I show below.

I have noticed that gollum does not render the page unless it is actually committed into a very specific branch within the git repository, and I can verify that it is there by seeing my command line edits rendered on the page before I click its Edit button.

```
% git log this/is/mypage.md 
commit ae99ae87656fb2cbf5bd6cc8468b6edacabd3d7f (origin/main)
Date:   Tue May 21 21:39:37 2024 -0400

% git log | tail
commit f773d09e68a6615a47089f5edbbe1ad9c1ed6871
Date:   Tue May 21 21:18:09 2024 -0400
```

**Comment by timrdf** [comment]
All of the above was using Firefox 126.0 (64-bit) with a pile of extensions.
Turning off all of the extensions did not avoid the problem.

Using Safari 17.5 avoids the problem and enables me to edit the way that I expected it to.

**Comment by timrdf** [comment]
Doing a bit of uninstalling / resetting / etc. of Firefox, gollum is able to edit as expected.
I won't be able to replicate the issue any more, so will close the issue.

**Comment by benjaminwil** [comment]
Huh, weird. Thanks for following up.
