### ISSUE TITLE
Unraid template available

### ISSUE THREAD

**Issue by nwithan8** [gollum/gollum#2054]
Hey there, just found this project looking for a wiki, and it seems to be perfect for my needs. I went ahead and made an Unraid template so that Unraid users can easily download and install this Docker container from the Community Apps store. Should be live in a few hours: https://unraid.net/community/apps?q=gollum#r

**Comment by dometto** [comment]
Thanks, that's appreciated! Would you like to add a page to the documentation (in this repo's wiki) to describe how to use gollum on unraid?

**Comment by nwithan8** [comment]
Done, thanks: https://github.com/gollum/gollum/wiki/Gollum-via-Docker#unraid
