### ISSUE TITLE
.war-launched gollum is not rendering existing wiki pages

### ISSUE THREAD

**Issue by timrdf** [gollum/gollum#2057]
I have read the [CONTRIBUTION GUIDELINES](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md) before submitting.

**Problems using** or installing the software which stem from bugs in the software (?) or a **lack of documentation**. For ordinary usage questions, have considered asking elsewhere, for instance on [StackOverflow](http://stackoverflow.com/questions/tagged/gollum-wiki).

**Describe the bug**

Existing file `wiki.local/home.md` is not rendered at `http://localhost:5678/home.md` but instead re-directs to `http://localhost:5678/gollum/create/home.md`.

**To Reproduce**

1. Cite the last time this person submitted [an issue](https://github.com/gollum/gollum/issues/2051).
2. Observe README.md’s [instructions for how to run the .war](https://github.com/gollum/gollum/blob/master/README.md#as-a-web-application-resource-java): `java -jar gollum.war -S gollum <your-gollum-arguments-here>`
3. Observe [documentation](https://github.com/gollum/gollum?tab=readme-ov-file#configuration) for what you can place at `<your-gollum-arguments-here>` 
4. Verify that `$war` is set to a locally-accessible copy of `gollum.war` (either [6.0.0](https://github.com/gollum/gollum/releases/download/v6.0.0/gollum.war) or [5.3.2](https://github.com/gollum/gollum/releases/download/v5.3.2/gollum.war) will produce same behavior)
5. Observe the usage information provided when running `java -jar $war -S gollum —help` (specifically, the occurrence of `[git-repo]` in `gollum [options] [git-repo]`, and "Path to the git repository being served. If not specified, current working directory is used.”)
6. Verify that `$config` is set to a locally-accessible file containing the string `Precious::App.set(:wiki_options, { :index_page => 'home.md' })`
7. Verify that `wiki.local` is a git working copy checked out to the branch `main`.
8. Verify that `wiki.local/home.md` exists and is under version control and committed into `main`.
9. Run command `java -jar $war -S gollum --host 127.0.0.1 --port 5678 --config $config --ref main wiki.local`
10. Load the URL `http://localhost:5678/home.md` in a Web browser.

**Expected behavior**

The Web browser should render the contents of `./wiki.local/home.md` instead of immediately re-directing to `http://localhost:5678/gollum/create/home.md` and offering to make a file that already exists but cannot be found.

**Screenshots**

Hopefully the create page and how it differs from a rendering of an existing page is an understood thing, so I’ll omit screenshots.

**Environment Info**

The output of the `gollum --versions` command (NB: `versions` in plural):

```
% java —version
java 11.0.23 2024-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.23+7-LTS-222)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.23+7-LTS-222, mixed mode)

% java -jar gollum.war -S gollum —versions

Gollum 5.3.2
Running on: java with Ruby version 3.1.4
Using:
rjgit 5.7.0.2
gollum-rjgit_adapter 0.6.1
gollum-lib 5.2.4
Markdown rendering gem: kramdown
Other renderering gems:
none
ERROR: org.jruby.exceptions.SystemExit: (SystemExit) exit
```

**Comment by dometto** [comment]
I can reproduce this. The issue seems to be with passing relative paths, both for `--config` and for the path to the wiki. Using @timrdf's reproduction steps but using absolute paths everything works:

```
java -jar gollum.war -S gollum --config /path/to/config.rb --ref main /path/to/wiki.local
```

My hunch was that this means that relative paths are being interpreted as relative to the WAR or the Java execution environment. I was able to verify this by following @timrdf's reproduction steps, and then trying to save a new page. That throws an internal server error which includes the following output:

```
Java::JavaIo::IOException - No such file or directory - /var/folders/wh/vvkf0yhx5rbfynxqvjz6645c0000gn/T/jruby12503261663615534050extract/wiki.local/.git/config:
```

**Comment by dometto** [comment]
@timrdf for now you can work around the issue by using absolute paths. If anyone has experience debugging WAR's and relative paths in particular, help is much appreciated!

**Comment by timrdf** [comment]
Using absolute paths for the arguments into the .war does enable the server to find the existing pages. Thanks!
