### ISSUE TITLE
Rack::Server error when using `--config config.rb`

### ISSUE THREAD

**Issue by orel1** [gollum/gollum#2059]
**Describe the bug**
If I try to run `gollum` with the `--config config.rb` option, I get the following error

    $ gollum --config config.rb wikidata/
    /home/vagrant/.local/share/gem/ruby/3.1.0/gems/gollum-6.0.0/bin/gollum:299:in `<top (required)>': uninitialized constant Rack::Server (NameError)

        Rack::Server.new(:app => Precious::MapGollum.new(base_path), :Port => options[:port], :Host => options[:bind]).start
            ^^^^^^^^
    Did you mean?  TCPServer
            from /home/vagrant/.local/share/gem/ruby/3.1.0/bin/gollum:25:in `load'
            from /home/vagrant/.local/share/gem/ruby/3.1.0/bin/gollum:25:in `<main>'

**To Reproduce**
1. Installing gollum in a test VM (debian 12)

        sudo apt install ruby-rubygems git ruby-dev build-essential cmake pkgconf libssl-dev
        gem install --user-install gollum

2. Creating the git repository

        mkdir -vp my-gollum-wiki/wikidata
        cd my-gollum-wiki/wikidata/
        git init
        touch Home.md
        git add Home.md && git commit -m "initial commit"

3. Creating a config file with a minimal content

        $ cat config.rb
        wiki_options = {
        base_path: "/wiki"
        }
        Precious::App.set(:wiki_options, wiki_options)

   See "Description" above ↑

**Expected behavior**

if I understand the <https://github.com/gollum/gollum/wiki/Sample-config.rb> page correctly, if we define the configuration in `config.rb` and not in `config.ru`, we don't need to have a rack server.

Did I miss something ?

**Environment Info**

    $ gollum --versions
    Gollum 6.0.0
    Running on: x86_64-linux-gnu with Ruby version 3.1.2
    Using:
    rugged 1.7.2
    gollum-rugged_adapter 3.0
    gollum-lib 6.0
    Markdown rendering gem: kramdown
    Other rendering gems:
    none

    $ lsb_release -d
    No LSB modules are available.
    Description:    Debian GNU/Linux 12 (bookworm)

**Comment by dometto** [comment]
Thanks for the report!

The error is coming from part of the code that gollum uses for the `base_path` functionalitz, which indeed requires `Rack:: Server `. I think rack is part of most core ruby installations so we haven't encountered the error in CI for instance, but we should make sure the dependency is explicitly declared in the project's Gemfile and .gemspec!
