### ISSUE TITLE
Mermaid with regular gem installation on version Gollum 5.3.3

### ISSUE THREAD

**Issue by nkreevo** [gollum/gollum#2061]
i use gollum on version 5.3.3, installed via gem on a regular linux box and run by a systemd unit. I´ve looked into the wiki https://github.com/gollum/gollum/wiki#diagrams where it says that i can enable mermaid support. However the flag does not work for me, i get this error:

```bash
wiki@wiki:~$ /usr/local/bin/gollum --config "/usr/local/etc/gollum/config.rb" --mermaid ...

gollum: invalid option: --mermaid
gollum: try 'gollum --help' for more information
```

any way to fix that? do I just need to enable something?

**Comment by dometto** [comment]
Hi @nkreevo! Mermaid support was added in version 6.0, so `gem update` should fix your problem. Let us know if you run into more problems.

**Comment by nkreevo** [comment]
Ahh, thanks for your advise.

Unfortunately i cannot update right now, since the update would break dependencies on my omniauth/omnigollum setup.
