### ISSUE TITLE
Static generation

### ISSUE THREAD

**Issue by Vanuan** [gollum/gollum#22]
What about static generation? It would be nice if I could generate HTML (and also to customize it with templates).

I was really excited about [jekyll](http://jekyllrb.com). And it would be great if gollum also had such functionality.

I know, gollum is positioned as a wiki, but what if one could use it for personal weblogs or general purpose websites? Hah, we're moving back to old days of static web (with JS though).

My proposal is to add a command line parameter --static destination.

**Comment by marek22k** [comment]
https://github.com/dreverri/gollum-site does not work with Ruby 3. Is there an alternative in the meantime?
