### ISSUE TITLE
Allow apt: URIs in sanitization.rb

### ISSUE THREAD

**Issue by fpoirotte** [gollum/gollum#233]
In https://github.com/github/gollum/blob/master/lib/gollum/sanitization.rb, there's a whitelist of URI schemes. I'd like the "apt:" scheme be added to that list.
My use case is simple, I have a project which depends on external libraries. I'd like to provide a wiki page for that project which contains "apt:" links (such as apt:gettext) to make it easier for Debian/Ubuntu users to install those librairies.

Currently, links are correctly generated, except that they do not contain an href attribute (because the sanitization process stripped it while checking whether the scheme is part of the whitelist).

Best regards,
François

**Comment by netcazean** [comment]
#1656
