### ISSUE TITLE
Add syntax highlighting for asciidoc

### ISSUE THREAD

**Issue by mojavelinux** [gollum/gollum#280]
Add syntax highlighting to [source] blocks using the pygments syntax highlighting engine.

In order to support this, the [source] blocks need to be honored. Currently, this markup breaks the rendering:

```
[source,python]
----
''' A multi-line
    comment.'''
def sub_word(mo):
    ''' Single line comment.'''
    word = mo.group('word')   # Inline comment
    if word in keywords[language]:
        return quote + word + quote
    else:
        return word
----
```

**Comment by dometto** [comment]
Now implemented as part of gollum-lib `master`: https://github.com/gollum/gollum-lib/pull/128

**Comment by craibuc** [comment]
Is this an accurate statement?

 * The [Python implementation of AsciiDoc](http://asciidoc.org/) supports [Highlight](http://www.andre-simon.de/doku/highlight/en/highlight.html), [Pygments](http://pygments.org/), and [GNU Source Highlight ](http://www.gnu.org/software/src-highlite/) (default).

* The Ruby implementation of AsciiDoc, called [AsciiDoctor](http://asciidoctor.org/) supports [CodeRay](https://github.com/rubychan/coderay), [Highlightjs](https://highlightjs.org/), [Prettify](https://code.google.com/p/google-code-prettify/), and [Pygments](http://pygments.org/).

* The open-source version of Gollum (via gollum-lib) supports [Rouge](https://github.com/jneen/rouge) (default) and [Pygments](http://pygments.org/).

This might be a source of confusion to some people.

If so, it might make sense to add this to gollum-lib's documentation (I'm happy to help with that).

**Comment by dometto** [comment]
That would appear to be accurate. :) Gollum does its own syntax highlighting (through Rouge or Pygments), superceding the behavior of the underlying markup renderer. So asciidoc syntax blocks will still be rendered by Rouge by default, courtesy of gollum-lib. That also means you can use github-style codeblocks no matter what markup/renderer you are using.

If that's unclear in the readme or wiki, please point it out to us (or open a pull request/edit it yourself)!
