### ISSUE TITLE
Re-activating MathJax support as an option on github wikis

### ISSUE THREAD

**Issue by pkra** [gollum/gollum#288]
I know that MathJax used to be available but I couldn't quite figure out why it was removed. I've only found [this comment](https://github.com/github/gollum/issues/210#issuecomment-3164493).

Speaking as part of the MathJax team, we would gladly help out sorting out any problems you may have had in the past (I couldn't find any issue report at [github.com/MathJax ](http://www.github.com/MathJax) or any comment on our mailing lists).

On the one hand, our MathJax CDN could be an option both remotely and locally. On the other hand, we could assist in fixing whatever problems there were locally.

**Comment by mmitkevich** [comment]
+1

**Comment by npalmer** [comment]
+1 would *love* to see MathJax support in github.com wikis.

**Comment by dometto** [comment]
> Github has recently offered more information about their plans concerning the github wiki's, see: #794

> This issue tracker will be specific to open source gollum (the gem release) from now on. Please direct queries and requests about github's wiki's to GitHub's support team.
