### ISSUE TITLE
OrgMode wiki preview has different link behaviour than real

### ISSUE THREAD

**Issue by zhensydow** [gollum/gollum#295]
I you add in the wiki with OrgMode a link like `[[Tutorial][Tutorial]]`, in preview this link points to:

    https://github.com/SkemaPlatform/skemaplatform.github.com/wiki/Tutorial

But when you save, the real link points to:

    https://github.com/SkemaPlatform/skemaplatform.github.com/Tutorial

The parser forgot to ass wiki part, i think.

**Comment by dometto** [comment]
Can't produce this on latest versions of gollum and gollum-lib, so likely this was a .com specific issue. Closing but feel free to reopen if you can reproduce this with open source gollum. (Note that gollum and github wiki's have diverged (#794) , so this is no longer the place to report github bugs).
