### ISSUE TITLE
nested wikis (submodules) possible?

### ISSUE THREAD

**Issue by jdlx** [gollum/gollum#299]
Hi, is there a way to host multiple independent wikis within a single gollum instance (running localy @ OSX)?

I tried a setup like this: a root master wiki which holds nothing but a Home page with links to other wikis which are nested in subdirs as submodules of the master wiki.. but i fail so far.. can't access any of the submoduled wikis.

Therefore: is this possible at all?

thx&cheers,
Jan

**Comment by guillaume-d** [comment]
For posterity's sake (and future personal reference :wink:) it seems there are ways to run wikis side-by-side (not _nested_ though), see #44.
