### ISSUE TITLE
Gollum crashes with empty repo

### ISSUE THREAD

**Issue by milaniliev** [gollum/gollum#32]
When initializing a new repo, Gollum 1.0.1 crashes if there are no commits in the repository.

It would be awesome if Gollum had a init command that created a repo and initialized it with at least one commit.

**Comment by ajstadlin** [comment]
Yes, still broken in Gollum 4.0.1

It is only broken until the first page is committed.

**Comment by dometto** [comment]
Actually, I cannot reproduce this in either `4.0.1`, `4.1`, or `5.x` (unreleased), with either the `grit` or `rugged` adapters, so this does not appear to be an issue anymore. Closing.
