### ISSUE TITLE
Cannot delete home page on .com

### ISSUE THREAD

**Issue by ymendel** [gollum/gollum#450]
I accidentally (somehow? I'm not even sure what I did) created a wiki for my dotfiles repo, as you can see at https://github.com/ymendel/dotfiles/wiki

I think I may have done this by navigating to https://github.com/ymendel/dotfiles/wiki, which auto-creates the 'Home' page, and I can't remove this page because it redirects me to the same place.

**Comment by aymericbeaumet** [comment]
Still cannot delete the `Home` page on the .com, cloning the wiki and manually removing it worked though.

Not sure if it belongs here as I believe GitHub's Gollum differs from this one.

**Comment by dometto** [comment]
> Not sure if it belongs here as I believe GitHub's Gollum differs from this one.
That's right.
