### ISSUE TITLE
Rename does not allow moving directories

### ISSUE THREAD

**Issue by giga** [gollum/gollum#480]
The rename button on the interface does not allow moving the page to another directory.

Maybe renaming `/plop/test` to `glou/test` should move it to `/plop/glou/test` and renaming `/plop/test` to `/glou/test` should move it to `/glou/test`?

**Comment by bartkamphorst** [comment]
> Maybe renaming /plop/test to glou/test should move it to /plop/glou/test and renaming /plop/test to /glou/test should move it to /glou/test?

This is already the current behavior, at least on `5.x`.

**Comment by dometto** [comment]
Cool, didn't know that! Maybe reflect this fact in the text in the rename dialog, though? ("Rename file or directory" or some such?)

**Comment by bartkamphorst** [comment]
The dialog currently says **"Renamed page will be under [CURRENT PATH] unless an absolute path is given."** So when renaming `/plop/test` it will say that the renamed page will be under **/plop** unless an absolute path is given. Do you have a clearer formulation?

**Comment by dometto** [comment]
Sorry, I misread and thought this issue was about being able to rename a whole directory!
