### ISSUE TITLE
Keyboard Shortcuts?

### ISSUE THREAD

**Issue by victorhooi** [gollum/gollum#496]
Hi,

Would it be possible to implement keyboard shortcuts in Gollum?

For example, Confluence has a fair few (https://confluence.atlassian.com/display/DOC/Keyboard+Shortcuts) which are quite useful, and greatly speedup workflow.

When viewing any page on the wiki, you can press "e" to edit that page.

Cheers,
Victor

**Comment by dometto** [comment]
This will come for free when changing the default editor to `ace` in `v5.x`, as implemented in #1173 (closing to de-clutter the issue tracker).

**Comment by dometto** [comment]
In `5.x` we'll move to ACE as the default editor, and we'll inherit ACE's default keyboard shortcuts. See #1173.
