### ISSUE TITLE
Testing gollum

### ISSUE THREAD

**Issue by bootstraponline** [gollum/gollum#499]
Gollum needs tests running against a live instance to prevent issues such as #495 from occurring. A few things are required before this can happen:
- Free host
  - [gollum on openshift](https://github.com/bootstraponline/gollum-openshifted)
- Free testing service
  - SauceLabs
- Authentication
  - Sinatra route pre-emption as mentioned in #390?

The only missing piece is authentication. Basic auth, the easiest way, doesn't work with selenium webdriver so some other way such as oauth is required.

**Comment by dometto** [comment]
A live instance would be great (See #1444) but if we're going to test the front end, wouldn't be less difficult to use something like Selenium?
