### ISSUE TITLE
Replace encodeURIComponent with escape_utils

### ISSUE THREAD

**Issue by bootstraponline** [gollum/gollum#506]
It looks like [escape_utils](https://github.com/brianmario/escape_utils) provides a much faster replacement for encodeURIComponent.

There are apparently some differences. EscapeUtils.escape_uri('a+b') does not match the behavior of escaping + as is done in JavaScript's encodeURIComponent.

Blocked on [#23](https://github.com/brianmario/escape_utils/issues/23)

**Comment by dometto** [comment]
We don't want this anymore because `escape_utils` has native extensions, which breaks `jruby` support.
