### ISSUE TITLE
When renaming a page, leave redirects behind

### ISSUE THREAD

**Issue by scribu** [gollum/gollum#516]
In MediaWiki, if you create a page `Shiny_Feature` and then rename it to `Renamed_Feature`, when you access `/Shiny_Feature` you'll get automatically redirected to `Renamed_Feature`.

Any chance gollum could support something like this?

Without it, if you don't want users to get 404s, you'd have to manually create a stub page with a link to the new location.

**Comment by dometto** [comment]
Closing ing favor of #1023

**Comment by TallTed** [comment]
Reinventing wheels should come much closer to an approximation of a circle than a square. Redirects and/or "page moved" are basic features of every wiki in wide use. Why does Github's "better than the others because we made it" wiki not support these basic features?
