### ISSUE TITLE
Cannot create a page in subdirectory or with unicode characters in Openshift

### ISSUE THREAD

**Issue by ghost** [gollum/gollum#534]
I can't create a page in a subdirectory or containing unicode characters in Openshift.  
But it works fine when it is running localy or when I click on a dead link containing those characters.

For exemple creating page with a name like :
- `/directory/page` gave me `http://app-user.rhcloud.com/%2Fdirectory%2Fpage` instead of `http://localhost:9292/create/directory/page` when I run it localy
- `unicôde` gave me `http://app-user.rhcloud.com/unicôde` instead of `http://localhost:9292/create/unicôde` when I run it localy

**Comment by dometto** [comment]
Can't reproduce this on `4.1.0`.
