### ISSUE TITLE
Automatic Redirects?

### ISSUE THREAD

**Issue by axkibe** [gollum/gollum#536]
Since (github) Gollum had the "brilliant" idea to force the change the URL as Title of the page instead of the first title, I had to rename some pages to fit the titles again. (Which I consider a bad decision, since cool URIs don't change, but titles might). Additionally I had to put in prefixes in the titles, since Github-Gollum doesn't support directories either, I had to make some redicolous seperators to make it semi-look-good anyway. Now I get complains that URL broke that are out there in the web.

So how do I put in automatic redirects? An no manual redirect page is not a solution I look for.

**Comment by dometto** [comment]
Closing in favor of #1023
