### ISSUE TITLE
Preview/show uncommited local changes

### ISSUE THREAD

**Issue by sol** [gollum/gollum#545]
I  use my text editor to edit wiki pages.  And I would like to use gollum to preview changes *before* I commit them.

Currently I always have to commit changes before I can review them, which is not very convenient.

I understand that this is a special use case, and I'm not sure if/how this can be integrated in a consistent way.  Anything that solves my use case would be fine with me (e.g. guarding it with a flag, say `--render-uncommitted`).

**Comment by kostaz** [comment]
+1
Any update on this feature?
Any time estimation?

**Comment by elliotpotts** [comment]
+1 for this feature!

**Comment by PaulMakepeace** [comment]
+1

**Comment by rgroux** [comment]
+1

**Comment by icaromedeiros** [comment]
+1

**Comment by dometto** [comment]
Implementing #1031 would fix this, so I'm closing this as a duplicate. PRs very welcome.

**Comment by jansegre** [comment]
@dometto, however this seems simpler to implement given that the presence of git may be assumed, as opposed to a simpler version not assuming git as #1031 suggests.

**Comment by markmoser** [comment]
This guard workflow might be a decent stop-gap measure. At least, it works great for me.

https://gist.github.com/markmoser/f668ed9fb7fd63c5c0453cd39fcb9530

Very similar to what @jakajancar [mentioned above](https://github.com/gollum/gollum/issues/545#issuecomment-16348760),  but without a sleep loop.
