### ISSUE TITLE
Cursive text doesn't work inside code blocks with MediaWiki format

### ISSUE THREAD

**Issue by jakeboxer** [gollum/gollum#562]
Example here: https://github.com/lucaswerkmeister/JFractalizer/wiki/Command-Line-Options

On that wiki, `inputFileName` should be italicized in the code block under "General Structure". It works on the Wikipedia sandbox and in other places with MediaWiki format.

**Comment by dometto** [comment]
The italics in codeblocks issue was never reported, I've asked the maintainer whether he considers it a bug: https://github.com/nricciar/wikicloth/issues/76

**Comment by dometto** [comment]
The issue with the lists appears to be solved in the latest version of gollum.

**Comment by dometto** [comment]
The formatting issue in `<code>` blocks is confirmed to be a wikicloth issue, see wikicloth#76. For those who want to help out with this issue,  please see there.
