### ISSUE TITLE
Intra-page wiki links to header anchors (Markdown)

### ISSUE THREAD

**Issue by kislyuk** [gollum/gollum#587]
I haven't found a way to link to headers in the same page. If I type

``` markdown
# Header1
# Header2

[[Link-name1|#Header1]]
[Link-name2](#Header2)
```

the first link points to `/%23Header1#Header1`, the second one to `#wiki-Header2`. How can I make a link to the header anchor?

**Comment by iiebat** [comment]
# `heel****`

**Comment by entotsu** [comment]
Click **chain icon** beside header.
Then, you can see url of it.

**Comment by juanArias8** [comment]
Example
Page name ==> Page
Header name ==> Header Number Two

[link-to](page#markdown-header-header-number-two)
...
...
...
---
# Header Number Two 

For me works.

**Comment by galiuskas24** [comment]
[header name](header_id)
You can open inspector and copy-paste id="header-id"

**Comment by g10guang** [comment]
Don't Work if the header is all chinese.

# 你好

[你好](#你好)

I don't know why.

**Comment by SooJungChae** [comment]
Don't work if the header using Korean.
[do테스트](#do테스트)

## do테스트
