### ISSUE TITLE
Formats handle double backslash in math mode incosistently

### ISSUE THREAD

**Issue by jedbrown** [gollum/gollum#613]
This renders correctly from Creole

$$\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$$

but in Markdown, we need extra escaping

$$\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \end{pmatrix}$$

Meanwhile, neither renders correctly in reStructuredText.

**Comment by dometto** [comment]
Markdown now doesn't need the extra escaping anymore.
