### ISSUE TITLE
BibTeX citations from wiki pages

### ISSUE THREAD

**Issue by jedbrown** [gollum/gollum#614]
Ability to handle BibTeX citations would make the wiki a viable medium for technical documentation. Here are two projects that may be helpful to produce HTML output
- http://code.google.com/p/bibtex-js/
- http://homes.cs.washington.edu/~mernst/software/bibtex2web.html
- http://www.mediawiki.org/wiki/Extension:Bibtex

Although editing BibTeX from the web interface would occasionally be convenient, it's not a bad workflow for me to build the web page output along with the documentation embedded in the source code (primarily manual pages), as long as it is an easy to link from wiki pages.

**Comment by anderflash** [comment]
We could summarize some features for scientific publishing:
- Math equations (with references)
- Proofs/Theorems/Corollary/Lemma
- Example/Exercises
- Bibliography
- TOC
- Subfigures (captions, labels, references)
- (Good for teaching) Ability to handle SVG, Canvas, WebGL...
- Everything above with labels and references

Some features could be present by linking with some JS libraries. Some others allowing the person to create JS scripts and custom HTML tags. Others, I think, will need extension of Markdown parsers. Oh, there are two other tools the institutions are recently using:

Thanks
- IPython notebooks (using IPython API to process embedded code, for example)
- Revealjs slideshows (a wiki article could be transformed into a slide presentation by user indication in an option)

**Comment by dometto** [comment]
Those interested in this may want to weigh in on https://github.com/gollum/gollum-lib/pull/272 and https://github.com/gollum/gollum-lib/pull/271. Suggestions welcome.

**Comment by dometto** [comment]
This is implemented in the `5.x` branch. See two PRs I mentioned above for more information. (It may be a while before `5.x` is released though)
