### ISSUE TITLE
Show preview in tab

### ISSUE THREAD

**Issue by mojavelinux** [gollum/gollum#625]
The preview link in Gollum opens a separate page (when the Ace editor isn't in use). But if you notice on GitHub pull requests, issue reports, etc, the preview is an Ajax-ified tab. Adding that in place preview to Gollum would make for a much more awesome editing experience.

See:

![](https://github-images.s3.amazonaws.com/help/pullrequest-description.png)

**Comment by dometto** [comment]
The idea now would be to integrate a livepreview pane in the normal editor, as discussed in #826.

**Comment by calid** [comment]
just curious if this feature is completely dead in favor of the live preview.  I'm actually a big fan of the preview tab with the simple/default editor.

assuming there's room for both live preview and preview tab functionality I'd be willing to look into implementing this.

**Comment by dometto** [comment]
Thanks for chipping in @calid. Definitely still interested in this. In https://github.com/gollum/gollum/pull/1048#issuecomment-168426391 I've hacked together an implementation of the default editor layout (although using ace) with an ajax based preview pane, based on @rtrvrtg's work. You're free to use any of that, or work on your own implementation. Please let us know if we can help.

**Comment by dometto** [comment]
By the way, @rtrvrtg's branch [here](https://github.com/rtrvrtg/gollum/tree/current-anchorwiki-modern) is a more clean implementation of the ajax preview pane (without my attempts to use ace in the default editor).

**Comment by bartkamphorst** [comment]
Same here; I'm in favor a preview tab. :+1:

**Comment by calid** [comment]
@dometto awesome, thanks, I'll take a look.
