### ISSUE TITLE
Flattened Namespace

### ISSUE THREAD

**Issue by patrickt010** [gollum/gollum#627]
When I run Gollum locally I am able to use hierarchical page namespace but when I push my changes to Github it flattens the namespace as described [here](https://github.com/github/gollum/issues/116) I was wondering if there was a solution to either flatten the namespace locally or allow Github wiki to use a hierarchical namespace.

**Comment by jideshv** [comment]
Given that github.com is unlikely to get the latest version.  Is there a way to find out which version github.com is running?  Or a setting to flatten files?  I want to host a local version so I can preview things when I make significant changes.  For example I need to move files into subdirectories purely to take advantage of custom sidebars.  I hate having to commit just to see if I got it right...

**Comment by bartkamphorst** [comment]
Hi @jideshv , sorry for having to redirect, but this seems like a question for the [Github support team](https://github.com/contact).
