### ISSUE TITLE
Breadcrumb trail

### ISSUE THREAD

**Issue by ghost** [gollum/gollum#629]
Add a new feature to show a breadcrumb trail for all the links clicked

**Comment by dometto** [comment]
Great if anyone could work on a PR for this.

**Comment by bartkamphorst** [comment]
How's this?

![screen shot 2019-01-02 at 17 04 56](https://user-images.githubusercontent.com/571173/50600164-90ed1400-0eb0-11e9-9618-24f7b6bcac78.png)

**Comment by bartkamphorst** [comment]
Alternatively, each element can be a link to the relevant `/pages` view:

![screen shot 2019-01-02 at 17 18 08](https://user-images.githubusercontent.com/571173/50600866-c266df00-0eb2-11e9-83ea-0f83dbbcfa9f.png)

**Comment by bartkamphorst** [comment]
Implemented in `5.x` with https://github.com/gollum/gollum/commit/6fcfe7895e2b25b9f6d68bcbf9f9a1f8d20bff50.
