### ISSUE TITLE
ReST anonymous hyperlinks don't work.

### ISSUE THREAD

**Issue by davedash** [gollum/gollum#642]
```ReST
See `the web site`__.

__ http://www.python.org

See `the web site`__.

.. __: http://www.python.org

```

See
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#anonymous-hyperlinks

Tested on GHE11.10.300

**Comment by dometto** [comment]
Can't reproduce on the latest version gollum/gollum-lib (probably fixed in a newer version of github-markup).
