### ISSUE TITLE
Allow excluding headings from the TOC

### ISSUE THREAD

**Issue by kamalmarhubi** [gollum/gollum#650]
If a wiki page uses a deep hierarchy of headings, the TOC can end up looking a bit cluttered.  This creates an unfortunate tension between organising the page, and ease of navigation.  A strong heading structure can make it easier to navigate, but at the expense of a usable TOC.

It would be nice to allow some headings to be excluded from the TOC. This could be done either on a per-heading basis, or by heading depth.  As an example of the per-heading approach, [Twiki's formatting](http://twiki.org/cgi-bin/view/TWiki/TextFormattingRules#TheHeadings) allows, eg:
```
---++ Sushi
---+++ Maguro
---+++!! Not in TOC
```
(Number of pluses is heading level, always prefixed by dashes.  Appending two exclamation marks excludes the header from the TOC.)

This per-heading approach would require extending the individual formats, and so might not work so well in Gollum's mode; the level-based approach might be better suited.

**Comment by dometto** [comment]
Implemented in https://github.com/gollum/gollum-lib/pull/183. Will try to do a gollum-lib release quickly. Kudos to @ztlpn!
