### ISSUE TITLE
Secure custom css/js

### ISSUE THREAD

**Issue by bootstraponline** [gollum/gollum#665]
There should be a secure way to inject CSS and JS. Currently editing `custom.js` is not possible via the web UI because `.` is translated to `dot`

**Comment by dometto** [comment]
I think a neat way to solve this in `5.x` is just to add `custom.js` and `custom.css` to the SASS (pre)compilation path, thus removing the need to add them to the repository. Makes sense performance-wise, too.

For those who do want to have these files committed to the repo, we can just disallow update and delete requests to their respective paths.

**Comment by bartkamphorst** [comment]
Sounds good.

**Comment by dometto** [comment]
Secure customs available in 5.x. See #1324.
