### ISSUE TITLE
Feature request: directory listing

### ISSUE THREAD

**Issue by directionless** [gollum/gollum#686]
I love gollum. I've using it as a hybrid for various documentation. It bridges nicely between the directory-full-of-notes and web-only-wiki. I especially love having offline access with emacs and grep.

Though one feature I'm missing, is the ability to display files in a directory.

I'm thinking something like /fileview or like apache's autoindexing. I'd love to be able to hit a URL like `.../SubDirOfFiles/` and see the file listing. It would be interesting if it was embeddable, similarly to how `toc` works.

**Comment by fhwedel-hoe** [comment]
It looks like this feature was removed with 012f1fc and I cannot see an alternative in the help. How can I have a directory listing with gollum version 5?
