### ISSUE TITLE
git hooks are not firing when using gollum web interface

### ISSUE THREAD

**Issue by ghost** [gollum/gollum#69]
In my wiki git repository, I created a post-commit hook which should push the commit changes to the remote server

```
#!/usr/bin/env bash
git push myserver master
exit
```

Manual commits fire the hook, however commits when editing gollum interface do not seem to fire post-commit hook. Am I missing something and/or doing something outrageously odd way?

I'm new to both gollum and git, so please be patient to my ignorance.

**Comment by pejvan** [comment]
It's been 4 years since this ticket has been closed, and I'm sure rugged/libgit2 has evolved quite a bit during that time. I'm not a ruby guy, but any chance to reopen this item?

**Comment by dometto** [comment]
Based on the discussion [here](https://github.com/libgit2/libgit2/issues/964), it looks like libgit2 doesn't support hooks yet (and will do so in the future only to the extent that the library will provide callbacks with info about local hooks). However, in the mean time, gollum has implemented it's own post-commit callbacks: see https://github.com/gollum/gollum-lib#api-documentation. Such gollum-specific hooks can be set in the optional `config.rb` file (but of course, the hooks will not be run when committing from outside the gollum webinterface). Hope that's useful to you!

**Comment by pejvan** [comment]
@dometto — thanks for the detailed reply along with a solution! It looks like there's a very good reason for me to learn some basic Ruby then.
The fact that hooks are not ran outside of the web interface is fine

**Comment by dkozel** [comment]
@pejvan Did you get your hook working? I am hoping to implement a post-commit hook to push the repo to a remote master.

**Comment by pejvan** [comment]
Hi Derek.
As I'm not a Ruby guy by any means, I spent some time looking for some
documentation which I never found.
I have an idea about I would implement it, but I'm really *really*
surprised nobody has ever implemented such a hook and added it to the
Gollum code tree...
I still have this as a todo item, but it's not a high priority item in the
long list, so currently, we do manual pushes from time to time.
If you have implemented a hook already, i'm a taker :-)
Many thanks,
Pejvan

**Comment by k00p** [comment]
To get gollum to respect git hooks, in a `config.rb` file I added:

```ruby
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
        system('/path/to/wiki/.git/hooks/post-commit')
```

This file then has to be specified using the `--config` option.

**Comment by pReya** [comment]
@k00p Is this code specific to the used git adapter? Will this run both on grit and rugged? Also is there any way to debug this? Doesn't seem to get called in my case. Not a ruby developer. Can I just print to stdout to verify this snippet is being called?

**Comment by k00p** [comment]
@pReya It has been a really long time since I was working with this, but I can tell you that I was working on synchronizing a GitLab based project wiki with a local Gollum instance running in a RedHat 6.5 environment. I no longer have access to that project, so I can’t really provide much more detail, I’m afraid. I do recall writing some instrumentation to confirm that it was running, so it should be possible to write to a log or a terminal. I wish I could help more. Best of luck to you.

**Comment by bartkamphorst** [comment]
@pReya I can confirm that @k00p 's snippet still works on gollum `5.0.1` with the rugged adapter.

> Can I just print to stdout to verify this snippet is being called?

Yes, `puts` statements show up in your gollum server log.
```ruby
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
  puts "post commit hook called"
end
```

**Comment by pReya** [comment]
@bartkamphorst Thanks! I got it working! Not sure what the problem was. Probably wrong path for the config file.

**Comment by bartkamphorst** [comment]
Good to hear!
