### ISSUE TITLE
Last edited by

### ISSUE THREAD

**Issue by kunguz** [gollum/gollum#702]
I have a very basic question sorry for asking. When one edits a Gollum wiki, the page always says "last edited by anonymous" how do I set users so that I can know which user has edited that page?

**Comment by jgeorgeson** [comment]
How do I set the commit author when running Gollum in Docker container?

**Comment by diegosasw** [comment]
I have the same question when running as a docker container.

Would be an option to set the author's name as a container environment variable such as
```
docker run -e AUTHOR=Joe --rm --name gollum -d -v $(pwd):/wiki -p 4567:4567 gollumwiki/gollum:latest
```

or maybe have it automatically read from the git's configuration `user.name`?

Thanks

**Comment by magnusviri** [comment]
I have the same question about using the Docker image. It looks like [this image](https://github.com/pjeby/gollum-portable) solves it. Can this be added to the official image? If I submit a pull request can it be added?

**Comment by magnusviri** [comment]
I just created [PR 1784](https://github.com/gollum/gollum/pull/1784), which adapts [pjeby/gollum-portable](https://github.com/pjeby/gollum-portable) for this project.

**Comment by magnusviri** [comment]
I re-submitted my changes as PR 1789.
