### ISSUE TITLE
Is there any way to escape angle brackets?

### ISSUE THREAD

**Issue by x-yuri** [gollum/gollum#713]
If I do it as follows

```
<id>
```

I see nothing: <id>. If I use character entity references

```
&lt;id&gt;
```

I see character entity references: &lt;id&gt;.

**Comment by cabo** [comment]
You can write \<foo> as `\<foo>` in GFM.

**Comment by gsf-sellis** [comment]
> You can write as `\<foo>` in GFM.

Best answer by far, thanks cabo.
