### ISSUE TITLE
Multimarkdown support

### ISSUE THREAD

**Issue by masochist** [gollum/gollum#720]
Seems no one else has asked for this yet (or the search isn't finding it) so here we are. I of course am referring to [this multimarkdown](http://fletcherpenney.net/multimarkdown/), which has a number of useful features not present in vanilla markdown. I don't think there are any backwards-compat issues, either. This would probably fix more paged than it would break. I know that more than once I've written some multimarkdown on github, only to see it break.

**Comment by brendanokane** [comment]
+1.

**Comment by dometto** [comment]
PRs very welcome!

**Comment by dometto** [comment]
MultiMarkdown is not supported by `github-markup`, and we won't hack in support for it, but you can enable it yourself using gollum's `--config` flag. See [here](https://github.com/gollum/gollum/wiki/Custom-rendering-gems#using-multimarkdown) for documentation.

**Comment by dometto** [comment]
It may be worth noting that `github-markup` supports a number of new markdown renderers out of the box since this issue was opened, including support for CommonMark and Discount (see [here](https://github.com/github/markup/blob/master/lib/github/markup/markdown.rb)).
