### ISSUE TITLE
Dashes in wiki page titles are silently replaced with spaces

### ISSUE THREAD

**Issue by izuzak** [gollum/gollum#764]
It seems that dashes in wiki page titles are silently replaced with spaces.

Steps to reproduce:
1. Create new Wiki page with title "a-b-c d-e-f"
2. Notice that the page has the title "a b c d e f"

Interestingly, the preview of the new Wiki page doesn't replace dashes with spaces.

**Comment by haggen** [comment]
Just so you know, I worked around this using the unicode character `‐` ([Hyphen](http://unicode-table.com/en/2010/) or `U+2010`) as opposed to the `-` ([Minus-Hyphen](http://unicode-table.com/en/002D/) or `U+002D`).

![screen shot 2015-11-24 at 14 49 51](https://cloud.githubusercontent.com/assets/270076/11373726/aa5022cc-92ba-11e5-84b5-30e58291e309.png)

**Comment by jcastrov** [comment]
Hey @haggen thank you. Does anyone know an unicode valid character like plus sign character?

**Comment by it-praktyk** [comment]
@haggen , thank you for suggestion but I don't get it. Could you provide an exact example?

Thank you.

**Comment by haggen** [comment]
@it-praktyk Sure. Say you want a title like "Follow-me". If you just type that out you'll end up with "Follow me" (space instead of your dash). This happens, as explained by @bartkamphorst because gollum use dashes to instead of spaces when naming files and then translate them back to spaces when rendering the page. To work around it, I simply suggested using a character that looks very similar to a dash, but isn't one, in this case a hyphen. This `‐` isn't the same character as this one `-`.

**Comment by it-praktyk** [comment]
Thank you for your reply. General idea I understand but I tried use 
`	
&#8208;
`
and 
`
&%8208
` but without result.

**Comment by haggen** [comment]
Simply copy and paste from here: `‐`

**Comment by it-praktyk** [comment]
Thank you, sometimes the simplest options are the best .

**Comment by zachlatta** [comment]
God, this is so frustrating. Really wish there was a better default here.

I have a habit of putting ISO-8601 dates in filenames (ex. `2017-06-04_june_newsletter.md`) and this makes it quite difficult to read dates.

**Comment by bartkamphorst** [comment]
@zachlatta This will be resolved in version 5.x.

**Comment by bpj** [comment]
Why not support a YAML metadata block like [pandoc](https://github.com/jgm/pandoc/blob/master/MANUAL.txt#L2633) does, with a field `pagetitle`, or if that is missing use the first level one heading as the page title if there is one, so that the page title can be independent of the file name?

**Comment by bartkamphorst** [comment]
This will be included in version 5.x.

**Comment by bpj** [comment]
When will that be rolled out? I'd rather forgo kludges with [U+2010](https://unicode-table.com/en/2010/) and/or [U+2024](https://unicode-table.com/en/2024/) when a page title is/contains a file name, as when the wiki contains documentation. I'm concerned that someone will copy the 'file name' with the non-ASCII characters.

**Comment by dometto** [comment]
It may be a couple of months still til `5.x` is rolled out. We're sorry about this, but we'd rather concentrate the time we can work on gollum on delivering a fresh and maintainable `5.x` then solving bugs in the current `master`.

**Comment by the-j0k3r** [comment]
Thank you at @haggen for the tip, it worked great to solve my still existing issue.

**Comment by tloredo** [comment]
I'm still experiencing this problem, over a year after this thread said the issue would soon be addressed in v5. Is there a technical issue such that we should never expect to be able to use dashes/hyphens in wiki page titles?

**Comment by dometto** [comment]
5.x is simply still not out. In 4.x the problem is that grit, the git interaction gem, can't properly deal with spaces, as it uses command line calls. We have to wait for some work on the replacement git interaction gem, rugged, before we can release 5.x (there is also plenty of other work to be done).

**Comment by tloredo** [comment]
Thanks for the clarification. I was mistakenly presuming that the current version was 5.x, because of the "couple months" expectation; I should have checked the release history. You can close this again.

**Comment by alkisg** [comment]
> Why not support a YAML metadata block like [pandoc](https://github.com/jgm/pandoc/blob/master/MANUAL.txt#L2633) does, with a field `pagetitle`, or if that is missing use the first level one heading if any as the page title, so that the page title can be independent of the file name?

Isn't that ^ ideal? Why does that require changes in grit, since the filenames will remain the same and without spaces?

**Comment by dometto** [comment]
YAML support is also implemented in 5.x

**Comment by dometto** [comment]
...and it will include the option of setting the title via YAML

**Comment by Betlista** [comment]
What is meant by version 5, isn't current version 2? Where I can see the version?

**Comment by bartkamphorst** [comment]
@Betlista Run `gollum --version`. Latest release version of gollum is 4.1.4. The `5.x` branch on github contains all the latest changes for the next major release.

**Comment by wm-marting** [comment]
Tilde: the B dash.

**Comment by marnen** [comment]
Closed 7 years ago, but the problem persists on GitHub. When will this be fixed for GitHub wikis?

**Comment by bartkamphorst** [comment]
> Closed 7 years ago, but the problem persists on GitHub. When will this be fixed for GitHub wikis?

@marnen Though gollum aims to be compatible with Github wikis, the project is no longer affiliated with Github. So you're best bet is to contact [Github Support](https://support.github.com/) and ask your question there.
