### ISSUE TITLE
Livepreview doesn't update local git repository

### ISSUE THREAD

**Issue by ruurdadema** [gollum/gollum#777]
When I edit a *.markdown file with the built in live preview editor the local repository isn't updated with the new commit. When I do a `git status` the working directory contains changes. When I do a `git commit -am 'Test'` the changes are reverted back.
So basically, every time after editing a file with the live-preview editor I have to `git reset --hard` at the CLI to not commit back to the old version.

Is this the normal behaviour? Or could this be a bug?

Start gollum:

![screen shot 2013-12-03 at 15 26 45](https://f.cloud.github.com/assets/4981772/1664477/f8c0994e-5c27-11e3-973c-f4a6145dc639.png)

Gollum running:

![screen shot 2013-12-03 at 15 27 01](https://f.cloud.github.com/assets/4981772/1664480/02e2c514-5c28-11e3-9b78-76f703b20f24.png)

Edit .markdown file:

![screen shot 2013-12-03 at 15 27 24](https://f.cloud.github.com/assets/4981772/1664481/121f0236-5c28-11e3-9f98-f9a7b9d098a0.png)

Commit changes:

![screen shot 2013-12-03 at 15 27 55](https://f.cloud.github.com/assets/4981772/1664488/27d6ab92-5c28-11e3-86a3-b608958b6f98.png)

Changes processed:

![screen shot 2013-12-03 at 15 28 14](https://f.cloud.github.com/assets/4981772/1664491/3229a766-5c28-11e3-8df8-22d64c029f57.png)

Git status afterwards:

![screen shot 2013-12-03 at 15 28 58](https://f.cloud.github.com/assets/4981772/1664495/46517da4-5c28-11e3-97b0-e255aa6a80ae.png)

Git diff HEAD:

![screen shot 2013-12-03 at 15 29 18](https://f.cloud.github.com/assets/4981772/1664499/531b703a-5c28-11e3-8f7a-14269bbba250.png)

Result after committing from the commandline:

![screen shot 2013-12-03 at 15 29 50](https://f.cloud.github.com/assets/4981772/1664501/5db48464-5c28-11e3-8160-5f088b80b473.png)

Both commits:

![screen shot 2013-12-03 at 15 39 00](https://f.cloud.github.com/assets/4981772/1664527/c158eb5e-5c28-11e3-9509-d36da342487a.png)

**Comment by dometto** [comment]
Unable to reproduce this with `gollum-3.1.1` and `gollum-lib 4.0.1`:
```
dawa$ uname -a
Darwin friedrich.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
dawa$ git --version
git version 2.2.0
dawa$ ruby --version
ruby 1.9.3p362 (2012-12-25 revision 38607) [x86_64-darwin11.4.2]
```
Some updates have occurred that might have fixed this issue:
1. grit version has been updated to recent gitlab-grit
2. implementation of checkout (after commit) abstracted to `gollum-grit_adapter` gem
3. various jumps in OS X and git version numbers

Could someone who experienced this issue in the past please let me know if they can still reproduce it?

**Comment by ruurdadema** [comment]
I just tried, can't reproduce either!

Thanks

```
$ uname -a
Darwin Ruurds-MacBook-Pro.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
$ git --version
git version 1.8.4
$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
$ gollum --version
Gollum 3.1.1
```

**Comment by dometto** [comment]
Great!
