### ISSUE TITLE
creole external links are not creole standard conformant

### ISSUE THREAD

**Issue by Kissaki** [gollum/gollum#78]
Creole 1.0 defines the syntax for named external links as:
`[[http://www.wikicreole.org/|Visit the WikiCreole website]]`
See http://www.wikicreole.org/wiki/Creole1.0#section-Creole1.0-LinksInternalExternalAndInterwiki

However, (at least) the github wiki (/gollum) parses and displays it under help the other way around:
`[[Visit the WikiCreole website|http://www.wikicreole.org/]]`
That is not Creole 1.0 standard conform.

This issue is related to issue #3

(Was pointed here by github stuff,
noticed this in githubs wiki.
http://support.github.com/discussions/site/2257-creole-syntax-is-wrong )

**Comment by dometto** [comment]
Just merged https://github.com/gollum/gollum-lib/pull/130. Creole named links (internal and external) will be standard-conformant starting from the next minor-level release of `gollum-lib`. Please note that this will break existing Creole pages that use the (reversed) gollum syntax for named links.

**Comment by berezovskyi** [comment]
FYI, this is still not fixed in Github Wikis

**Comment by dometto** [comment]
@berezovskyi Github wikis are no longer using gollum. If you want to submit an issue, you should contact github staff.
