### ISSUE TITLE
POD links should link wiki-internally

### ISSUE THREAD

**Issue by ailin-nemui** [gollum/gollum#796]
Wiki Links in POD mode should work properly, e.g ```L<Somepage/Somesection>``` should link to ```.../wiki/Somepage#wiki-Somesection```, with the same weird replacements that gollum does to the pod output applied. Currently it links to perldoc ;-(

**Comment by dometto** [comment]
This requires setting a base url for the generated html, which `Pod::Simple::HTML` does not seem to support. Even if it did, it's not possible at the moment to set such a base url parameter through `github/markup` (the gem gollum uses for rendering). However, it's possible to override `GitHub::Markup`'s pod rendering command as follows. In `config.rb`:
```ruby
require 'github/markup'
GitHub::Markup.markups.delete_if {|x| x.regexp == /pod/}
base_url = 'http://localhost/wiki' # Your wiki's base url
command =  "/usr/bin/env perl -MPod::Simple::XHTML -e \"my \\$p = Pod::Simple::XHTML->new; \\$p->perldoc_url_prefix('#{base_url}');\\$p->parse_string_document(<STDIN>);\""
GitHub::Markup.command(command, /pod/)
```
