### ISSUE TITLE
Source code in org-mode parsed incorrectly

### ISSUE THREAD

**Issue by feilong** [gollum/gollum#810]
It seems that double brackets in source codes are still parsed as file links.
If I write something in org-mode like
```
#+BEGIN_SRC python
nested_list = [['a','b'], ['c','d']]
#+END_SRC
```
It would appear in the page like
```
nested_list = 'a','b'], ['c', 'd'
```
with a file link.

**Comment by dometto** [comment]
Resolved in gollum-lib `master` by https://github.com/gollum/gollum-lib/issues/128. This was a duplicate #256.
