### ISSUE TITLE
Images are not served out of a bare repository

### ISSUE THREAD

**Issue by wconrad** [gollum/gollum#811]
It appears that images are not served out of a bare repository.
# When non-bare

If I do this:

```
git clone https://github.com/mojombo/gollum-demo gollum-demo-nonbare
cd gollum-demo-nonbare
gollum --show-all
```

And then browse

```
http://localhost:4567/Mordor/Eye-Of-Sauron
```

I see the pictures of the eye of Sauron.
# When bare

If I do this

```
git clone --bare https://github.com/mojombo/gollum-demo gollum-demo-bare
cd gollum-demo-bare
mkdir .git
mv * .git
gollum --show-all
```

And then browse

```
http://localhost:4567/Mordor/Eye-Of-Sauron
```

I see no images.
# Versions
- gollum (2.7.0)
- gollum-lib (2.0.0)
- ruby 1.9.3p484 (2013-11-22 revision 43786) [i686-linux]
- gollum-demo 0c5e1292
# Possibly related

https://github.com/gollum/gollum/issues/809 ~~may or may not be the same issue: Whether or not the repository is bare is never mentioned in that issue.~~ ~~is probably not the same issue as this one: That issue occurred with a non-bare repository~~ is not the same issue as this one: That issue has been resolved, but this one persists.

**Comment by VoldemarLeGrand** [comment]
`--bare` flag did not work for my bare repository named `/home/user/test` producing Gollum::InvalidGitRepositoryError at [git_layer_grit.rb:288](https://github.com/gollum/grit_adapter/blob/master/lib/grit_adapter/git_layer_grit.rb#L288) provoqued by Grit::InvalidGitRepositoryError at [repo.rb:52](https://github.com/gollum/grit/blob/master/lib/grit/repo.rb#L51)

I found that grit consider repository as bare when the name of its directory ends with `.git`. 
So renaming the repository directory to `/home/user/test.git` make Gollum work with and without `--bare` flag.

**Comment by wconrad** [comment]
I just got back to this.  @VoldemarLeGrand 's fix of renaming the git repo from `wiki` to `wiki.git` did the trick for me.

Sorry about the long delay, and thanks for your work on it.

**Comment by orodbhen** [comment]
Why is gollum using such a "dumb" method for determining a bare repository, when git provides a smarter way to do this? Is it just a lacking functionality in Grit?
