### ISSUE TITLE
URL and title Capitalization

### ISSUE THREAD

**Issue by darkfeline** [gollum/gollum#824]
The page name affects the URL of the page and the page title (the HTML title element in the head element, what shows up in the window or tab).  The capitalization of the page name also leaks to the URL.  Capitalization in the URL is BAD.  I could always use all lowercase page names, but then that means the page titles will be lowercase as well.  This means that if I want a properly capitalized page title, I must mangle the capitalization of the URL of the page.

Instead, the URLs should all be in lowercase.

**Comment by dometto** [comment]
I think case-sensitive URLs could be achieved simply by modifying [this line](https://github.com/gollum/gollum-lib/blob/gollum-lib-5.x/lib/gollum-lib/page.rb#L372), and adding/modifying relevant tests.

**Comment by 0sc** [comment]
@dometto is this change still need? I could submit a PR to gollum-lib with the fix

**Comment by bartkamphorst** [comment]
@0sc , yes, this issue is still relevant. You're welcome to work on a PR!

**Comment by 0sc** [comment]
Cool. On it!

**Comment by dometto** [comment]
@0sc Just a quick pointer: be sure to develop against and target the 5.x branch in your PR! Thanks in advance

**Comment by stepan-stulov** [comment]
Any RE-capitalization or RE-casing is a bad idea because people who write documentation in real industrial companies have to often respect weird capitalization of other company's names, products, etc. but also want their URLs uniform. Why not just have page title AND page url? I think the best answer to transforming one into another is that: not transforming.

**Comment by dometto** [comment]
@stepan-stulov thanks for weighing in. Yes, the latest idea was already to go for case-sensitive titles and URLs (I assumed that was what @0sc is working on, given that I posted the link to the relevant bit of `gollum-lib` recently).

**Comment by dometto** [comment]
Thanks to @0sc page names and URLs are now case sensitive in `5.x`!
