### ISSUE TITLE
Live Preview user experience roadmap?

### ISSUE THREAD

**Issue by rtrvrtg** [gollum/gollum#826]
Hi,

I work for a company that uses Gollum for internal documentation. I'm interested in working on user interface enhancements for Live Preview, and am interested to see what intentions the Gollum community had in mind for it.

I've been mulling over a few ideas for improvements to the user experience, and wanted to see if anyone else was interested, or that the developers had a particular user experience roadmap in place, before I started hacking away on these ideas on my own branch.
### Shortcut key combinations

There seem to be a rather limited set of key combinations used in live preview at present, and they don't feel particularly discoverable.  Would anyone be interested in any additions to what there is at present?

One candidate that seems logical is Ctrl+S for Save (and maybe Ctrl+Shift+S for Save with Comment). I know that some people might feel leery of this idea given that it hijacks common browser commands, but I feel that there's sufficient precedent for this with Google Docs and other web-based editors that this might change people's expectations, allowing this to work in a different way from the default. 
### Implementation of fragments in Live Preview

I've done a little exploring and think it might be possible to render custom fragments of Markdown server-side, allowing things like links and custom macros to be depicted accurately on the client side. This might not be the ideal way to integrate custom markup, but it should be a way of doing so without having to hand off too much to Gollum's internal preview.

Would anyone else be interested in such a feature?
### Toolbar icons

In terms of the toolbar icons that are used in Gollum's Live Preview mode, we figured that they should be brought in line with the major features from the non-live editor.

This would mean that it'd contain buttons such as:
- Link
- Bold / Italic / Underline
- Lists (ordered and unordered)
- Quotes
- Horizontal Rule
- Headings
- Links
- Images
- Contextual Markdown help

It may make sense to retain Preview, but only if we weren't able to preview every single bit of the page using Live Preview.

Separating Save and Save with Comment don't make any sense; it might be useful to include some sort of contextual switch between them, or to expose the comment as an option when you save.

Also, the pane-switching icon seems kind of superfluous. I'm wondering if this isn't something we could conceal behind something else.
### Per-user settings

The bit about the pane-swapping icon made me wonder if there's any scope for global user preferences in this project to cover features such as this. The reason behind this is that most users won't need to swap the order of editing and preview panes more than once, but they'll probably want to do so on a global basis.

It might be possible to implement something trivial on the front-end only using localStorage, but since this is highly dependent on browser capabilities, I figured we ought to explore other possibilities first.
### Front-end performance

Live Preview in particular is kind of heavy on the front-end, particularly with the number of HTTP requests it performs to load assets. While I know you can throw Rack::Cache in front of it to reduce the number of requests that it makes, it still loads an awful lot of assets as separate files when really they should be aggregated into one.

We know that there's r.js to aggregate all the JS files into one, using require.js to work out which ones are needed. So far we haven't had much success, and are be interested to know if there are any other possibilities to explore.

---

I know this is kind of out of the blue, but we're committed to using Gollum, and would like to make any contributions back to the community that that we can.  I'd like the Live Preview tool to have all the good stuff that the static editor does, while retaining all the benefits of editing Markdown in real time.

If you have any ideas that might make Live Preview better, I'm all ears; we might have a common purpose.

**Comment by dometto** [comment]
@rtrvrtg, have you made any progress with the livepreview? I'm thinking that at first it would be okay to support only markdown, and keep the current 'Preview' functionality intact for all other markups. Would that make it easier to implement the rest of the changes you proposed?

An additional issue that the livepreview currently uses sundown.js, and sundown is deprecated/no longer maintained. We should probably switch to something like [marked](https://github.com/chjj/marked), which also supports GFM.

**Comment by rtrvrtg** [comment]
Hi @dometto, I did manage to get the livepreview to a point where I was happy with, but time got away from me and I wasn't able to put together a PR. I think I ended up using https://github.com/evilstreak/markdown-js to handle the parsing – switched it into Maruku for the preview mode.

If you'd like to see what we did with it, the branch that we've got running on our internal wiki currently is at https://github.com/rtrvrtg/gollum/tree/current-anchorwiki-modern
It's probably too big a change to drop on people to review as is, so maybe we should break it up into a couple of PRs that move towards replacing the livepreview with an in-place preview pane. Maybe we could start with some simple changes, like changing the Markdown parser and setting up the AJAX calls for server-side partial rendering.

**Comment by dometto** [comment]
That's sounds great @rtrvrtg! However, are you sure that's the right branch? I don't see any changes to `/lib/gollum/public/gollum/livepreview/js` compared to master (although I can see you've enabled livepreview by default).

If markdown-js (as opposed to mark) is working well for you, I'm all in favour of it. Would welcome any PRs, and the markdown parsers does seem like a good place to start. :+1:

**Comment by dometto** [comment]
Ah, d'oh -- the changes have been incorporated in the main editor. :)

Although some people might be keen on the ACE editor, I personally like the idea of integrating livepreview into the main editor. Dropping the ACE dependency will make everything easier to maintain. @sunny, do you also think that would be an acceptable change, or do you think ACE should be kept in somehow?

**Comment by sunny** [comment]
I agree, now would be the right time to drop ACE.

Le Wed Jan 21 2015 at 12:13:47 PM, Dawa Ometto <notifications@github.com> a
écrit :

**Comment by dometto** [comment]
@rtrvrtg, just played around a bit with your branch and I rather like the new editor and live-preview! Feels much cleaner than the current implementation.

> I'd also like to think a bit about how we might use ACE editor within the main editor. 

Any thoughts about that? If it's easy to do it might be nice to have the syntax highlighting and such.

**Comment by simonzack** [comment]
I like using the default editor in live preview too, it gives a more uniform look to gollum. But I agree with @dometto about the markdown syntax highlighting, losing that really feels like something's missing. If this could be brought into the default editor (using ace or perhaps `contenteditable`) it would be perfect.

**Comment by andreabedini** [comment]
@rtrvrtg  this is an old thread but I just wanted to mention that https://github.com/asciidoctor/asciidoctor.js does client-side asciidoc rendering.

**Comment by bartkamphorst** [comment]
It would be cool to include some of these improvements in gollum's master branch. @rtrvrtg would you have time to prepare (chunks of) your changes into a PR?

**Comment by dometto** [comment]
The consensus seems to be that getting rid of the two editors is the way to go, but that losing ace would be unfortunate.

I tried my hand at this, merging @rtrvrtg's changes (incorporating livepreview into the default editor, responsive theme) and moving the default editor to use ace (but keeping our own look and feel), in #1048.

**Comment by dometto** [comment]
The default editor has moved to ace. We are working on integrating a preview pane into the editor (as on GitHub). Combined with ACE syntax highlighting, and hotkeys for switching between the editor and preview panes, we are hoping that will obviate the need for a livepreview function. The Preview function would thus be doing a server-side request each time, which is not cheap. But on the upside, it will support all markups.

I'll close this issue for now, if anyone feels strongly about this, please let us know.
