### ISSUE TITLE
Using Gollum in Tomcat

### ISSUE THREAD

**Issue by SkyCrawl** [gollum/gollum#836]
Hello,

I have gollum running locally and would like to make it running in Tomcat, if possible. Has anyone tried it before? Can it be done with warbler? Or perhaps rake, as stated on the repository's main page? Or is the python dependency really going to be a problem?
If Tomcat is impossible or very hard to achieve, what other webservers would you most recommend?

To clarify, what I want to achieve: a single webserver serving both gollum and another java web application.

Many thanks for any answers :).

**Comment by dometto** [comment]
For the record, gollum is now fully jruby compatible. Haven't tried Warbler yet, but there should be no principled reason why it wouldn't work. :)

**Comment by SkyCrawl** [comment]
Great to know @dometto , thank you :).
