### ISSUE TITLE
Adding frame to an image prevents it from being centered

### ISSUE THREAD

**Issue by penguinpowernz** [gollum/gollum#838]
When you do `[[/uploads/example.png|frame|align=center]]` one would expect it to be framed and centered, however this is not the case.  I tried switching the arguments around to be like this:  `[[/uploads/example.png|align=center|frame]]` but that didn't work either (turns out if frame is specified the only class on the generated span is `frame` whereas the `align=center` causes the class `align-center` to be used).

This is the HTML generated:

``` html
<span class="frame">
  <span>
    <img src="/uploads/nav-alerts.png">
  </span>
</span>
```

I tried to figure out what was causing this using the Chrome developers tools.  At first I thought it was because everything was a created by the filter/macro was `display: block` but disabling that on both the `span`s and the `img` didn't work.  I tried setting `margin: 0px auto` on them but that didn't work either.  I tried making the class on the generated span `frame align-center` but that didn't work.

I even have a `custom.css` file with this rule:

``` css
.center {
  text-align: center;
}
```

And tried using the following:

``` html
<div class="center">
  [[/uploads/example.png|frame]]
</div>
```

But that didn't work either.

I think this would be a cool feature, but I can't figure out what is causing it to not work and I don't have any more time right now to spend on this.  Maybe someone else knows what would cause this?

**Comment by dometto** [comment]
On `5.x` it seems that an image can have only either `frame` or `align=center` as a class. When I inject the additional `frame` class through the browser, however, @penguinpowernz's original issue is still present: the frame cancels the alignment. So this is a CSS and `gollum-lib` issue in `5.x`.

**Comment by dometto** [comment]
Ah, I just realized that the syntax for image attributes changed in `5.x`, you need to use [comma-separated](https://github.com/gollum/gollum-lib/commit/745136ccf2cd4383234ffb1488f17ec228f61209#diff-9c66db1000504e8fd86544f23961803eR156) options now. So the right syntax is e.g.:

`[[image.jpg|align=center,frame,alt=bla]]`

That leaves the CSS issue.

**Comment by dometto** [comment]
@bartkamphorst just looked at this issue and wondered why I chose comma as a separator for image options in 5.x. The idea was to move away from using | as this clashed unhelpfully with the syntax for links and alt texts. But space separation for the options after the | in an image tag would work just as well, methinks, and might be more intuitive. So:

`[img.jpg | frame alt=bla]`

Does that make more sense?

**Comment by bartkamphorst** [comment]
> [[img.jpg | frame alt=bla]]

Depends on how it is parsed I guess. One should be able to also write [[img.jpg | frame alt = bla die bla bla other_option = 1]]. Using commas might be a safer option.

**Comment by bartkamphorst** [comment]
The `span.frame` class defined in template.css adds `float: left` to both the span and the nested img. Removing these in the browser inspector centers the image but widens the border for some reason:

![Screen Shot 2019-09-06 at 13 52 01](https://user-images.githubusercontent.com/571173/64426062-e1ef8080-d0ad-11e9-8e40-3d43cf2dc5ac.png)

Even stranger: removing the `float: left` statements in template.css does not seem to result in the same behavior since `float: left` still shows up in the inspector initially. Perhaps this has to do with browser caching locally, but I don't have time to investigate that further now. To be continued.

**Comment by dometto** [comment]
> float: left still shows up in the inspector initially. Perhaps this has to do with browser caching locally, but I don't have time to investigate that further now. To be continued.

Or it may be that `Primer` sets this attribute for `span.frame`?

**Comment by bartkamphorst** [comment]
Resolved in https://github.com/gollum/gollum-lib/pull/347.
