### ISSUE TITLE
Unpleasant slow-down upon adding many javadoc html files

### ISSUE THREAD

**Issue by SkyCrawl** [gollum/gollum#839]
Hello,

everything was working right and fast up until I added MANY generated javadoc HTML files into the repository (in classical directory structure). Since then, ANY page load takes about 1-3 seconds when there's no apparent reason to. The "All" and "Files" views are affected too, despite none of the files are displayed in them (which is correct of course).

Is there maybe a configuration/optimization to get rid of this or is gollum indeed somehow dealing with many files/filenames upon each page request, maybe in some internal variables? :)

**Comment by SkyCrawl** [comment]
Ah, damn... looks like I missed this somehow :(. Sorry, I promise I will test it eventually, @dometto :)

**Comment by dometto** [comment]
Closed in favor of #1078 (same issue, see there for state of the art).
