### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by schmunk42** [gollum/gollum#843]
I am having the following error, when editing pages via gollum, which were modified with an editor (PHPstorm or Mou) and pushed back into the wiki repo - and there as usually located two levels (folders) below root.

```
Encoding::CompatibilityError at /edit/my-page
incompatible character encodings: UTF-8 and ASCII-8BIT

file: index.rb location: % line: 176
```

I've looked through several encoding issues I've found [here](https://github.com/gollum/gollum/search?q=encoding&ref=cmdform&type=Issues). And came to the conclusion, that this is an error with `grit` (fork from gitlab).

I've tried different version of ruby (1.9.3, 2.1.2) and gollum (2.1.0, 2.5.0, 3.0.0) to fix the problem, but the only way (for me) to work around this issue, was modifiying [this line](https://github.com/gitlabhq/grit/blob/c2541d93618f0dfcfc8cfeeddb74b07ac6d520c2/lib/grit/index.rb#L176) to:

```
tree_contents[k] = "%s %s\0%s" % [tmode, obj.name.force_encoding('ASCII-8BIT'), sha]
```

Which does not really look right to me. 
Is there any way to fix this in gollum or even via `config.rb`?

Error Stacktrace:
```
localhost - - [28/Jul/2014:19:31:17 CEST] "GET /javascript/editor/langs/markdown.js?_=1406568677805 HTTP/1.1" 200 11837
http://localhost:4567/edit/intern/orga/my-page -> /javascript/editor/langs/markdown.js?_=1406568677805
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT:
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:176:in `%'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:176:in `block in write_tree'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:171:in `each'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:171:in `write_tree'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:198:in `block in write_tree'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:180:in `each'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:180:in `write_tree'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:198:in `block in write_tree'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:180:in `each'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:180:in `write_tree'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gitlab-grit-2.6.7/lib/grit/index.rb:123:in `commit'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gollum-lib-3.0.0/lib/gollum-lib/committer.rb:170:in `commit'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/gollum-3.0.0/lib/gollum/app.rb:248:in `block in <class:App>'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/opt/local/lib/ruby1.9/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
	/opt/local/lib/ruby1.9/1.9.1/webrick/httpserver.rb:138:in `service'
	/opt/local/lib/ruby1.9/1.9.1/webrick/httpserver.rb:94:in `run'
	/opt/local/lib/ruby1.9/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

**Comment by dometto** [comment]
@schmunk42 gollum@`master` can now use the new `gollum-rugged_adapter` gem (beta). It would be great to know if that solves this issue (although the adapter needs more refactoring and testing before being production ready, it is almost fully functional). Steps to do this:
1. clone gollum@`master`
2. Add `gollum-rugged_adapter` to the `Gemfile` and `bundle install`
3. `bundle exec gollum --adapter rugged`

**Comment by dometto** [comment]
I've managed to reproduce this myself, and can confirm that the problem is gone when using the [rugged adapter](https://github.com/gollum/rugged_adapter). We will not be able to solve this issue when using the grit adapter (unless someone wants to fix the underlying issue in `gitlab_grit`), so @schmunk42's workaround is all we can offer for that use case. The rugged adapter is still in beta, but almost fully functional -- please check it out if you are suffering from unicode problems.

**Comment by schmunk42** [comment]
@dometto I am using gem and rackup in my [Docker setup](https://github.com/hrzg/docker-gollum), could you guide me how to add rugged there?

**Comment by dometto** [comment]
I have no experience with docker, but looking at your setup I imagine something like:
```
RUN gem install --no-ri --no-rdoc \
    gollum \
    gollum-rugged_adapter \
    github-markdown \
    rack-cache
```
And then in `config.ru`, *before* you require `gollum-lib` (through `gollum/app`):
```ruby
Gollum::GIT_ADAPTER = 'rugged'
```
P.S. If you're interested, gollum now has a `contrib` directory to which your Docker setup could be added.

**Comment by bennibu** [comment]
@dometto Thanks for the new adapter. It seems to work fine on my ubuntu 14.04. But when I deploy on my server (debian squeeze, git 1.7.10.4) I got a the error `Rugged::ConfigError: Config value 'user.name' was not found` when creating a new wiki page. I can't reproduce this error on my local machine (ubuntu 14.04), but as the git version differs I assume this is related? Any Idea?

**Comment by dometto** [comment]
@benibu: Rugged is based on libgit2 and doesn't require the presence of a git binary on the system, so git version should be irrelevant. Maybe the debian system has an older version of libgit2? (although I think libgit2 should be compiled when installing the rugged gem)

**Comment by schmunk42** [comment]
@dometto Thanks for the advice and notice about the contrib section. Will check that.

**Comment by tnt** [comment]
Exactly this error occurs when the directory contains a file with non-ascii charcaters in the  name. To reproduce this the following should work:

```bash
$ echo "# Just Nothing" > blöd.md
$ git add blöd.md
$ git commit
```
If you now try to save an arbitrary file from the Gollum front-end you should get the error.

**Comment by bartkamphorst** [comment]
Which adapter are you using @tnt ?

**Comment by bartkamphorst** [comment]
> I got a the error Rugged::ConfigError: Config value 'user.name' was not found when creating a new wiki page.

BTW, @bennibu This was traced in issue https://github.com/gollum/rugged_adapter/issues/11 and has been addressed by https://github.com/jhominal/rugged_adapter/commit/10b6da7d175b78a89436400ffd3526e3a4a0e382 .

**Comment by tnt** [comment]
@bartkamphorst gitlab-grit?

**Comment by edusantana** [comment]
Using `gollum-rugged_adapter` worked for me, it requires `cmake` to build:

```bash
sudo apt-get install cmake
sudo gem install gollum-rugged_adapter
gollum --adapter rugged
```

After that, it worked without the error.

**Comment by wangluzhou** [comment]
@edusantana  Thanks! It works. but it just succeeded at a sudden. I remember in the early I input thw command
```
gollum --port 4567 --adapter rugged 

```
It gives me the error info below:
```
/Users/luke/.bundle/gems/gollum-lib-4.2.7/lib/gollum-lib.rb:11:in `require': cannot load such file -- rugged_adapter (LoadError)
	from /Users/luke/.bundle/gems/gollum-lib-4.2.7/lib/gollum-lib.rb:11:in `<top (required)>'
	from /Users/luke/.bundle/bundler/gems/gollum-6de0914788e2/lib/gollum/app.rb:4:in `require'
	from /Users/luke/.bundle/bundler/gems/gollum-6de0914788e2/lib/gollum/app.rb:4:in `<top (required)>'
	from /Users/luke/.bundle/bundler/gems/gollum-6de0914788e2/bin/gollum:242:in `require'
	from /Users/luke/.bundle/bundler/gems/gollum-6de0914788e2/bin/gollum:242:in `<top (required)>'
	from /Users/luke/.rvm/gems/ruby-2.4.0/bin/gollum:23:in `load'
	from /Users/luke/.rvm/gems/ruby-2.4.0/bin/gollum:23:in `<main>'
	from /Users/luke/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/luke/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

```
It is really confusing me, but I can not remember what I have done to make the error disappear.

**Comment by runech** [comment]
I added the rugged-adapter and this problem disappeared. 
Insted, sarch, which worked earlier, no failsl with "invalid byte sequence in UTF-8"

**Comment by fhwedel-hoe** [comment]
With the rugged adapter, file upload works as @runech describes. Search does not. For a wiki, this is a major inconvenience. I am on 64bit Ubuntu 16.04.4 LTS.

Installed gems:

    *** LOCAL GEMS ***

    afm (0.2.2)
    Ascii85 (1.0.2)
    asciidoctor (1.5.4)
    bigdecimal (1.2.8)
    blankslate (3.1.3)
    builder (3.2.2)
    charlock_holmes (0.7.3)
    coderay (1.1.1)
    creole (0.5.0)
    did_you_mean (1.0.0)
    diff-lcs (1.2.5)
    expression_parser (0.9.1)
    gemojione (3.3.0)
    github-markup (1.7.0)
    gitlab-grit (2.8.2)
    gollum (4.1.2)
    gollum-grit_adapter (1.0.1)
    gollum-lib (4.2.7)
    gollum-rugged_adapter (0.4.1)
    hashery (2.1.1)
    i18n (0.7.0)
    io-console (0.4.5)
    json (1.8.3)
    kramdown (1.9.0)
    mime-types (2.6.1)
    minitest (5.8.4)
    mustache (0.99.8)
    net-telnet (0.1.1)
    nokogiri (1.6.7.2)
    org-ruby (0.9.12)
    pdf-core (0.5.1)
    pdf-reader (1.4.0)
    posix-spawn (0.3.11)
    power_assert (0.2.7)
    prawn (2.0.2)
    prawn-table (0.2.1)
    psych (2.0.17)
    rack (1.6.4)
    rack-protection (1.5.3)
    rake (10.5.0)
    rdoc (4.2.1)
    RedCloth (4.2.9)
    rinku (1.7.3)
    rouge (2.2.1)
    ruby-rc4 (0.1.5)
    rubypants (0.2.0)
    rugged (0.24.0, 0.23.3)
    sanitize (2.1.0)
    sinatra (1.4.7)
    stringex (2.8.4)
    test-unit (3.1.7)
    tilt (2.0.1)
    ttfunk (1.4.0)
    useragent (0.16.10)
    wikicloth (0.8.1)

Error message:

    application error
    Encoding::CompatibilityError at /search
    incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
    file: git_layer_rugged.rb location: match line: 170
    BACKTRACE
    (condense)

    JUMP TO: GET POST COOKIES ENV
    /usr/lib/ruby/vendor_ruby/rugged_adapter/git_layer_rugged.rb in match
                next unless line.match(/#{Regexp.escape(query)}/i)
    /usr/lib/ruby/vendor_ruby/rugged_adapter/git_layer_rugged.rb in match
                next unless line.match(/#{Regexp.escape(query)}/i)
    /usr/lib/ruby/vendor_ruby/rugged_adapter/git_layer_rugged.rb in block (2 levels) in grep
                next unless line.match(/#{Regexp.escape(query)}/i)
    /usr/lib/ruby/vendor_ruby/rugged_adapter/git_layer_rugged.rb in each_line
              blob.content.each_line do |line|
    /usr/lib/ruby/vendor_ruby/rugged_adapter/git_layer_rugged.rb in block in grep
              blob.content.each_line do |line|
    /usr/lib/ruby/vendor_ruby/rugged/tree.rb in block in walk_blobs
          self.walk(mode) { |root, e| yield root, e if e[:type] == :blob }
    /usr/lib/ruby/vendor_ruby/rugged/tree.rb in walk
          self.walk(mode) { |root, e| yield root, e if e[:type] == :blob }
    /usr/lib/ruby/vendor_ruby/rugged/tree.rb in walk_blobs
          self.walk(mode) { |root, e| yield root, e if e[:type] == :blob }
    /usr/lib/ruby/vendor_ruby/rugged_adapter/git_layer_rugged.rb in grep
            tree.walk_blobs(:postorder) do |root, entry|
    /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/wiki.rb in search
          @repo.git.grep(query, options).each do |hit|
    /var/lib/gems/2.3.0/gems/gollum-4.1.2/lib/gollum/app.rb in block in <class:App>
          @results = wiki.search(@query).sort { |a, b| (a[:count] <=> b[:count]).nonzero? || b[:name] <=> a[:name] }.reverse
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in call
              proc { |a,p| unbound_method.bind(a).call }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block in compile!
              proc { |a,p| unbound_method.bind(a).call }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block (3 levels) in route!
                route_eval { block[*args] }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in route_eval
          throw :halt, yield
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block (2 levels) in route!
                route_eval { block[*args] }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block in process_route
            block ? block[self, values] : yield(self, values)
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in catch
          catch(:pass) do
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in process_route
          catch(:pass) do
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block in route!
              returned_pass_block = process_route(pattern, keys, conditions) do |*args|
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in each
            routes.each do |pattern, keys, conditions, block|
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in route!
            routes.each do |pattern, keys, conditions, block|
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block in dispatch!
            route!
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block in invoke
          res = catch(:halt) { yield }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in catch
          res = catch(:halt) { yield }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in invoke
          res = catch(:halt) { yield }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in dispatch!
          invoke do
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block in call!
          invoke { dispatch! }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block in invoke
          res = catch(:halt) { yield }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in catch
          res = catch(:halt) { yield }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in invoke
          res = catch(:halt) { yield }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in call!
          invoke { dispatch! }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in call
          dup.call!(env)
    /usr/lib/ruby/vendor_ruby/rack/protection/xss_header.rb in call
            status, headers, body = @app.call(env)
    /usr/lib/ruby/vendor_ruby/rack/protection/path_traversal.rb in call
            app.call env
    /usr/lib/ruby/vendor_ruby/rack/protection/json_csrf.rb in call
            status, headers, body = app.call(env)
    /usr/lib/ruby/vendor_ruby/rack/protection/base.rb in call
            result or app.call(env)
    /usr/lib/ruby/vendor_ruby/rack/protection/base.rb in call
            result or app.call(env)
    /usr/lib/ruby/vendor_ruby/rack/protection/frame_options.rb in call
            status, headers, body        = @app.call(env)
    /usr/lib/ruby/vendor_ruby/rack/nulllogger.rb in call
          @app.call(env)
    /usr/lib/ruby/vendor_ruby/rack/head.rb in call
        status, headers, body = @app.call(env)
    /usr/lib/ruby/vendor_ruby/sinatra/show_exceptions.rb in call
          @app.call(env)
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in call
          result, callback = app.call(env), env['async.callback']
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in call
          @stack.call(env)
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in block in call
            synchronize { prototype.call(env) }
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in synchronize
              yield
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb in call
            synchronize { prototype.call(env) }
    /usr/lib/ruby/vendor_ruby/rack/handler/webrick.rb in service
            status, headers, body = @app.call(env)
    /usr/lib/ruby/2.3.0/webrick/httpserver.rb in service
          si.service(req, res)
    /usr/lib/ruby/2.3.0/webrick/httpserver.rb in run
              server.service(req, res)
    /usr/lib/ruby/2.3.0/webrick/server.rb in block in start_thread
              block ? block.call(sock) : run(sock)
    GET
    Variable	Value
    q	
    "ö"
    POST
    No POST data.

    COOKIES
    No cookie data.

    Rack ENV
    Variable	Value
    GATEWAY_INTERFACE	
    CGI/1.1
    HTTP_ACCEPT	
    text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
    HTTP_ACCEPT_ENCODING	
    gzip, deflate
    HTTP_ACCEPT_LANGUAGE	
    de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
    HTTP_CONNECTION	
    Keep-Alive
    HTTP_HOST	
    localhost:4567
    HTTP_REFERER	
    http://REDACTED/Home
    HTTP_UPGRADE_INSECURE_REQUESTS	
    1
    HTTP_USER_AGENT	
    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
    HTTP_VERSION	
    HTTP/1.1
    HTTP_X_FORWARDED_FOR	
    REDACTED
    HTTP_X_FORWARDED_HOST	
    REDACTED
    HTTP_X_FORWARDED_SERVER	
    REDACTED
    PATH_INFO	
    /search
    QUERY_STRING	
    q=%C3%B6
    REMOTE_ADDR	
    127.0.0.1
    REMOTE_HOST	
    127.0.0.1
    REQUEST_METHOD	
    GET
    REQUEST_PATH	
    /search
    REQUEST_URI	
    http://REDACTED/search?q=%C3%B6
    SCRIPT_NAME	
    SERVER_NAME	
    REDACTED
    SERVER_PORT	
    80
    SERVER_PROTOCOL	
    HTTP/1.1
    SERVER_SOFTWARE	
    WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26)
    rack.errors	
    #<Object:0x00000001ca7d98>
    rack.hijack	
    #<Proc:0x00000001940f38@/usr/lib/ruby/vendor_ruby/rack/handler/webrick.rb:76 (lambda)>
    rack.hijack?	
    true
    rack.hijack_io	
    nil
    rack.input	
    #<StringIO:0x000000019411e0>
    rack.logger	
    #<Rack::NullLogger:0x00000001dbf758 @app=#<Rack::Protection::FrameOptions:0x00000001dbfa50 @app=#<Rack::Protection::HttpOrigin:0x00000001dbfb90 @app=#<Rack::Protection::IPSpoofing:0x00000001dbfca8 @app=#<Rack::Protection::JsonCsrf:0x00000001dbfd70 @app=#<Rack::Protection::PathTraversal:0x00000001dbfe38 @app=#<Rack::Protection::XSSHeader:0x00000001dbff50 @app=#<Precious::App:0x00000001e94138 @default_layout=:layout, @preferred_extension=nil, @app=nil, @template_cache=#<Tilt::Cache:0x00000001e941b0 @cache={}>>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :xss_mode=>:block, :nosniff=>true, :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :frame_options=>:sameorigin, :except=>[:session_hijacking, :remote_token]}, @frame_options="SAMEORIGIN">>
    rack.multiprocess	
    false
    rack.multithread	
    true
    rack.request.cookie_hash	
    {}
    rack.request.query_hash	
    {"q"=>"ö"}
    rack.request.query_string	
    q=%C3%B6
    rack.run_once	
    false
    rack.url_scheme	
    http
    rack.version	
    [1, 3]
    sinatra.accept	
    [#<Sinatra::Request::AcceptEntry:0x0000000193ae30 @entry="text/html", @type="text/html", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x0000000193ac28 @entry="application/xhtml+xml", @type="application/xhtml+xml", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x0000000193a6b0 @entry="image/webp", @type="image/webp", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x0000000193a390 @entry="image/apng", @type="image/apng", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x0000000193aa48 @entry="application/xml;q=0.9", @type="application/xml", @params={}, @q=0.9>, #<Sinatra::Request::AcceptEntry:0x0000000193a1b0 @entry="*/*;q=0.8", @type="*/*", @params={}, @q=0.8>]
    sinatra.error	
    #<Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)>
    sinatra.route	
    GET /search

Funny thing is: Gollum 4.1.1 works on another server just fine (and without the rugged adapter). Installed gems on working server:

    *** LOCAL GEMS ***

    bigdecimal (1.2.8)
    charlock_holmes (0.7.3)
    did_you_mean (1.0.0)
    diff-lcs (1.3)
    gemojione (3.2.0)
    github-markup (1.6.0)
    gitlab-grit (2.8.1)
    gollum (4.1.1)
    gollum-grit_adapter (1.0.1)
    gollum-lib (4.2.5)
    io-console (0.4.5)
    json (1.8.3)
    kramdown (1.9.0)
    mime-types (2.99.3)
    mini_portile2 (2.1.0)
    minitest (5.8.4)
    mustache (0.99.8)
    net-telnet (0.1.1)
    nokogiri (1.6.8.1)
    posix-spawn (0.3.13)
    power_assert (0.2.7)
    psych (2.0.17)
    rack (1.6.8)
    rack-protection (1.5.3)
    rake (10.5.0)
    rdoc (4.2.1)
    rouge (2.1.0)
    sanitize (2.1.0)
    sinatra (1.4.8)
    stringex (2.7.1)
    test-unit (3.1.7)
    tilt (2.0.7)
    useragent (0.16.8)
