### ISSUE TITLE
Redirecting to a user defined custom home page(instead of the default one) when starting gollum 

### ISSUE THREAD

**Issue by boddhisattva** [gollum/gollum#849]
Is there way to defined a custom home page when we run gollum? I don't see an easy way of doing this. The reason why this can be very helpful is , currently on kick starting the app, it basically redirects a user to the 'create' page. But what if only a certain set of authorized users can perform the create, edit, delete stuff but all can view the created wiki's. I know gollum originally doesn't control user authorization but having a customizable root page can be quite handy IMHO.

I tried using the base-path config option, but this seems to change the URL. I want the kick started home page to show an index of all wikis when I run gollum. Could one please tell me how can I customize gollum to achieve this?

Also, please let me know in case this is already configurable and I'm missing something.

Thanks.

**Comment by dummys** [comment]
Dear @boddhisattva I think what you search for is: <<GlobalTOC()>>
