### ISSUE TITLE
Deleting uploaded files

### ISSUE THREAD

**Issue by apfohl** [gollum/gollum#855]
Is it possible to delete uploaded files via the web interface? I didn't find a way to do it.

**Comment by tomcashman** [comment]
+1

**Comment by andreabedini** [comment]
a simple improvement could be that when started with `--allow-uploads page` gollum deletes the page uploads folder along with the page.

**Comment by winniehell** [comment]
Yes, please! :+1: Using GitLab (especially gitlab.com) it is currently not possible to delete files.

**Comment by bartkamphorst** [comment]
PRs welcome!

**Comment by zakuni** [comment]
+1

**Comment by apfohl** [comment]
If you tell me, where to put that functionality in the web interface, I will try to build it. Maybe in the **File Overview**?

**Comment by dometto** [comment]
Thanks @apfohl! Yes, in the file overview would be great! Two things to note:
* the delete button or link should not appear if the `--no-edit` option is enabled
* the route that handles the action should be a DELETE or POST request. If it's a GET request it would still work when `--no-edit` is enbabled.

Let us know if you need any help!

**Comment by luxflux** [comment]
Just stumbled over this as well... Were you able to do something already, @apfohl? May I help somehow?

**Comment by apfohl** [comment]
@luxflux I havn't started yet. But feel free. It's my first contribution to Gollum, thus I need to become comfortable with the code first. But if you are more experienced go ahead.

**Comment by bartkamphorst** [comment]
@apfohl @luxflux Is this still something you would consider implementing? There's no rush, but it is functionality we'd like to include in a future release.

**Comment by luxflux** [comment]
Sorry for my late reply. Unfortunately, I didn't have the time to start it and even though we still use Gollum lost the urgent need for it.
Long story short, please don't count on me for the implementation, sorry.

**Comment by bartkamphorst** [comment]
Perfectly fine, thanks for letting us know!
