### ISSUE TITLE
Can't run custom JS on Chrome

### ISSUE THREAD

**Issue by frank06** [gollum/gollum#856]
`Refused to execute script from 'http://localhost:4567/custom.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

Gollum 3.0.0

**Comment by SkyCrawl** [comment]
@bartkamphorst @dometto 
In case you'd like to make a hotfix, I'm having the same issue with (at least) `<script src='../javascript/jquery-1.7.2.min.js'></script>` in [here](https://github.com/gollum/gollum/blob/master/lib/gollum/public/gollum/livepreview/index.html).

**Comment by bartkamphorst** [comment]
No worries. :+1:
