### ISSUE TITLE
MathJax.js not found

### ISSUE THREAD

**Issue by ovhaag** [gollum/gollum#865]
When I start Gollum with --mathjax the Math formulas are not rendered. 
This is because the resource behind the link gollum creates 
`<script src="https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">`
can not be found
`<html><h1>Not Found</h1><p>The resource could not be found.</p></html>`

I don't know if this is a real bug or if only a server is temporary down.
The Gollum installation is new (yesterday, Gollum 3.0.0).

**Comment by RoyiAvital** [comment]
Does it means MathJaX works on Wiki Pages in GitHub?

They write about it here:

https://www.mathjax.org/github-chooses-mathjax-for-math-support/

**Comment by dometto** [comment]
@RoyiAvital: no. This project is standalone and divorced from github, so our implementation of MathJax doesn't mean you can use it on github (although that's not to rule out that GH has also implemented mathjax).
