### ISSUE TITLE
How to enable Asciidoctor Diagram in Gollum wiki?

### ISSUE THREAD

**Issue by saurabh-zz** [gollum/gollum#877]
How to enable [Asciidoctor Diagram](https://github.com/asciidoctor/asciidoctor-diagram) in Gollum wiki?

As per my understanding I would need to load & register these extensions in Ruby code (somewhere). Can you point out where the modifications need to happen (am complete n00b to Ruby)? Also is the scope of work correct?

Thanks.

**Comment by rmchale** [comment]
I am interested in this as well.  Did you get this working?  Do you have full instructions?

**Comment by mpcjanssen** [comment]
Probably the best way to handle this for gollum is to use the asciidoctor `:data-uri:`  document attribute. This will include the generated images in the actual html file.

See https://asciidoctor.org/docs/user-manual/#managing-images for details.
