### ISSUE TITLE
CommonMark support

### ISSUE THREAD

**Issue by chrisalley** [gollum/gollum#882]
There is a ongoing effort to create a strongly specified spec for Markdown called [CommonMark](http://www.commonmark.org). Extensions are planned once the core implemention is complete, and some features will likely be taken from other implementations such as MultiMarkdown and Github Flavored Markdown. I suggest CommonMark is considered for use in Gollum, although currently there is no Ruby implementation.

**Comment by dometto** [comment]
CommonMark is now supported by `github-markup`, so if you `gem install commonmarker` gollum will use it.
