### ISSUE TITLE
Tables are not being rendered properly

### ISSUE THREAD

**Issue by nlowe** [gollum/gollum#907]
I just updated to 3.1 to see if that corrects the issue. It does not.

Given the following sample table

``` markdown
| P | Q | P * Q |
| - | - | - |
| T | T | T |
| T | F | F |
| F | T | F |
| F | F | F |
```

Gollum renders it as one line, not as a table:

![gollum-render](https://cloud.githubusercontent.com/assets/794251/5263363/4c557d78-79fe-11e4-95f8-2139437217fd.png)

[atom](http://github.com/atom/atom) renders it like a table:

![image](https://cloud.githubusercontent.com/assets/794251/5263357/2a0dd5b2-79fe-11e4-8b79-65dc2e1c7b1a.png)

According to the [GFM wiki](https://help.github.com/articles/github-flavored-markdown/#tables), tables are supported.

**Comment by VladUreche** [comment]
I'd like to open this again, for gollum 4.0.0 -- it's not even rendering the table above.

**Comment by bartkamphorst** [comment]
@VladUreche Which markdown gem do you have installed?

**Comment by VladUreche** [comment]
@bartkamphorst, thanks for the quick answer! This is what I get with `--version`:
```
$ gollum --version
Gollum 4.0.0
```
Is there a better way to check? (sorry, Ruby noob, I come from the JVM world)

**Comment by bartkamphorst** [comment]
@VladUreche No worries, welcome to the Ruby community. :+1: Gollum depends on [github-markup](https://github.com/github/markup) for rendering markups, which in turn uses [kramdown](https://github.com/gettalong/kramdown) as its default markdown renderer. If I do an out-of-the-box install of gollum with `gem install gollum` the example table renders just fine.
![gollum_table](https://cloud.githubusercontent.com/assets/571173/8125699/7195fcb2-10e8-11e5-8918-bf956dbf1cd4.png)
Which makes me wonder about your particular setup. Could you elaborate a bit, for example on  how you installed gollum? Did you change any of the default settings? Is the page (with the table) that you are trying to render a markdown page?

**Comment by dometto** [comment]
`gem install gollum` should automatically install kramdown as markdown renderer. You could try doing `gem install github-markdown` and see if it renders correctly with that (@bartkamphorst, is it possible that you were accidentally using github-markdown in your test?).

**Comment by bartkamphorst** [comment]
Strangely, yes, though I thought I used a clean gemset. Thanks @dometto , that clears some things up. @VladUreche I can reproduce the issue with just kramdown. Using `github-markdown` as @dometto suggested resolves the issue for me.

**Comment by VladUreche** [comment]
>  You could try doing gem install github-markdown and see if it renders correctly with that

Thanks a lot @dometto and @bartkamphorst, this solves my problem! What is strange is that my setup was quite close to a stock setup.

> Which makes me wonder about your particular setup. Could you elaborate a bit, for example on how you installed gollum? 

I ran into this problem on two machines:
* my laptop running Ubuntu 14.04 with the following gems:
    * `jekyll`
    * `bundler`
    * `github-pages`
    * `gollum`
* a virtual machine running Ubuntu 12.10, where I installed just `gollum` following the instructions on the wiki.

> Did you change any of the default settings? 

No changes, just `git clone https://github.com/miniboxing/ildl-plugin.wiki.git && gollum`.

> Is the page (with the table) that you are trying to render a markdown page?

Yes, the page is taken from a github wiki: https://github.com/miniboxing/ildl-plugin/wiki/Sample-~-Data-Encoding

Thanks a lot for your kind help!

**Comment by techwiz24** [comment]
Perhaps we could improve the `--version` switch to provide gem names and versions for certain gems where there are multiple available (eg: markdown renderer, syntax highlighter, etc.)?

**Comment by dometto** [comment]
@VladUreche: the 'stock' version of gollum comes with a markup renderer (kramdown) that's close to github-style markdown, but may deviate in certain cases (like this one). However, gollum is designed to use github-markdown (or various other markdown renderers) when present.

@techwiz24, that's a nice idea!

**Comment by PaulMakepeace** [comment]
This may be related to redcarpet not rendering tables by default. github-markdown does though.

Worked for me (after `require 'gollum/app'`),

```ruby
# "parse tables, PHP-Markdown style"
# https://github.com/vmg/redcarpet/tree/master#and-its-like-really-simple-to-use
module GitHub
  module Markup
    class Markdown < Implementation
      MARKDOWN_GEMS['redcarpet'] = proc do |content|
        Redcarpet::Markdown.new(Redcarpet::Render::HTML, tables: true).render(content)
      end
    end
  end
end
```

Created after reading https://github.com/github/markup/blob/master/lib/github/markup/markdown.rb#L10

**Comment by arianf** [comment]
I just install a brand new fresh version of Gollum. I am not able to see tables.

<img width="980" alt="screen shot 2015-09-24 at 3 27 26 pm" src="https://cloud.githubusercontent.com/assets/7397857/10089559/098688a0-62da-11e5-9c28-c496e38e4e03.png">
<img width="765" alt="screen shot 2015-09-24 at 3 27 36 pm" src="https://cloud.githubusercontent.com/assets/7397857/10089558/098545a8-62da-11e5-9d53-9cfcdbdb48ea.png">

```bash
gollum --version
Gollum 4.0.1
```

**Comment by congaframe** [comment]
Hi,
I have similar issue. It renders fine in Preview Panel. 
But not the front one. 
I installed Gollum 4.0.1 as well as github-markdown (0.6.9) 
|hostname|IP address|Comment|
|-----|-----|-----|
|   |   |   |

Result: 
|hostname|IP address|Comment| |-----|-----|-----| | | | |

**Comment by zeigerpuppy** [comment]
same issue here, fine in preview

**Comment by dometto** [comment]
@zeigerpuppy you can use the `--css` option to inject custom css, but this option is not perfect: you need to commit the css file, and so it can be edited by wiki users.

**Comment by dometto** [comment]
@lopopolo reports that the following snippet in `config.rb` can be used to activate tables even when using `kramdown` (so without `github-markdown`):
```ruby
GitHub::Markup::Markdown::MARKDOWN_GEMS['kramdown'] = proc { |content|
  Kramdown::Document.new(content, :auto_ids => false).to_html
}
```

**Comment by dometto** [comment]
Basically to preserve old behavior when we moved from github-markdown to kramdown as default renderer. I suggest moving to default kramdown for `5.x`.

**Comment by bartkamphorst** [comment]
👍 Maybe open an improvement issue for that?

**Comment by yellela** [comment]
|A|B|C|AA|
| --- | --- | --- | --- |
|Q|W   |    E | RR     |

**Comment by matt-wallis** [comment]
After installing Gollum 4.1.2, the github-markdown gem was not installed. Here are the gems that were installed:
```
bombyx:~/.gem/ruby$ ls 2.4.0/gems/
charlock_holmes-0.7.5		gollum-grit_adapter-1.0.1	mustache-0.99.8			sanitize-2.1.0
diff-lcs-1.3			gollum-lib-4.2.7		nokogiri-1.8.1			sinatra-1.4.8
gemojione-3.3.0			kramdown-1.9.0			posix-spawn-0.3.13		stringex-2.7.1
github-markup-1.6.1		mime-types-3.1			rack-1.6.8			tilt-2.0.8
gitlab-grit-2.8.2		mime-types-data-3.2016.0521	rack-protection-1.5.3		useragent-0.16.8
gollum-4.1.2			mini_portile2-2.3.0		rouge-2.2.1
```
Manually installing github-markdown fixed the table problem. Does this point to an error in the dependencies for the gollum gem?

**Comment by piprrr** [comment]
I can echo this problem still exists.  I also installed `github-markdown` and it *did not* fix the problem.

**Comment by bunnybooboo** [comment]
Try editing your wiki page again @piprrr I had the same issue on a fresh install. This fixed it for me.

**Comment by mravery** [comment]
@piprrr Were you able to resolve your tables/markdown issue? I'm running into the same issue: tables aren't being rendered properly even though `github-markdown` is installed.

**Comment by bodi000** [comment]
Hello,
I had the same problem with a table containing two hyphens | --|--|; after adding a hyphen |---|---|, the table rendered correctly. 

I have the following versions:
`ruby` 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
`gem` 2.7.6
`gollum` (4.1.4)
`github-markdown` (0.6.9)
`kramdown` (1.9.0)

**Comment by mravery** [comment]
@bodi000 `gollum` 4.1.4 doesn't render tables properly. Try `gollum` 5. If you've installed the gem, I would uninstall everything (that's what I did), clone the git repo and select the `5.x` branch. Then build that (`rake` I think) and then install that. 

Just FYI, I was informed that Github wiki is no longer using `gollum` which the fundamental reason for me to use it.
