### ISSUE TITLE
Header numbering

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#908]
@SkyCrawl in #906:

> Gollum should, in my opinion, offer to number headers automatically. As an example, this is what I have in mind. The best way to achieve it would probably be an "annotation" like [[_TOC_]], perhaps [[_HN_]]?

@sunny on achieving this with Macro's or syntax helpers:

> Even if it's not on the body you would still need some DOM that wraps the whole text, at the least. Or get some help from JavaScript.

Dumping javascript into the page's rendered data doesn't seem very tidy. But now that I think of it, if we would implement a syntax helper `[[_HN_]]`, we could make it replace those tags and wrap the rest of the data in a `<div class="counter">` or whatever. Would that work?

**Comment by SkyCrawl** [comment]
A small update: as a part of my big initiative to convert CSS into SASS, I've also started to change `gollum-lib` a bit and safely parsing YAML front matter (with the option to number headers of course) is already implemented and working. You were right @sunny, it is a much more elegant solution :). I think you'll excited by the new versions I'm making and that they will certainly end up being major version updates. They'll still take some (indeterminate) time though as I've bumped into many issues on the way and it is in my nature to produce "featurefull" (within certain bounds of course), quality code.

**Comment by bartkamphorst** [comment]
Very cool! Looking forward.

**Comment by sunny** [comment]
Awesome!

Le mar. 31 mars 2015 12:08, Bart Kamphorst <notifications@github.com> a
écrit :

**Comment by dometto** [comment]
Great!

**Comment by dometto** [comment]
[YAML frontmatter](https://github.com/gollum/gollum/wiki/5.0-release-notes#metadata-yaml-frontmatter) is now available in `5.x`, so all that's needed is to add a CSS-counting class to header tags conditional on the presence of a `count-headers: true` (or some such) in the YAML frontmatter.

We could even have a `count-headers: roman`, `count-headers: arabic`, etc., for different kinds of enumeration.

**Comment by dometto** [comment]
Implemented in `5.x`
