### ISSUE TITLE
Video integration

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#909]
Integrate video.js support. @SkyCrawl in #906:

> I missed this a lot, so I wrote some javascript to integrate open-source video.js and dynamically transform something like <div class="video-container"><code class="vc-mime">{VIDEO MIME/FORMAT}</code> <a class="vc-source">{VIDEO URL}</a></div> to something that looks like this.

Should video.js be included as source (it is distributed under the Apache Licence) or through a CDN? If the latter, should it be enabled by default?

**Comment by SkyCrawl** [comment]
@dometto @bartkamphorst @sunny 
As it turns out, it is not necessary to use `video.js`. Video can also easily be embedded in pages using HTML5 :). The downside is that there are no special features... bare HTML5 video is a little minimalistic but still does its job. I already a video-embedding macro implemented in my forks, would you like me rewrite it into (and let the user take advantage of as much as reasonably possible) `video.js` anyway?

**Comment by dometto** [comment]
@SkyCrawl, HTML5 video seems good enough for now then. :) Always nice if someone wants to include `video.js` but it shouldn't be a priority I think.

**Comment by bartkamphorst** [comment]
> Video can also easily be embedded in pages using HTML5

Cool. And this works out of the box in gollum? If so, I would opt for leaving out video.js for now.

**Comment by sunny** [comment]
Good for me too. HTML5 Video support is really good in modern browsers.

Choosing a common video format is still a pain, though, so perhaps the syntax should allow multiple souces, like HTML5.

**Comment by SkyCrawl** [comment]
> Choosing a common video format is still a pain, though

Why do you think so, @sunny ? Seems to me MP4 is well supported by now:
http://www.w3schools.com/html/html5_video.asp

But you may be right that sometimes multiple source syntax could be useful :).

**Comment by sunny** [comment]
I still occasionally ran into problems with some versions of old "modern"
browsers or mobile browsers. But yeah, MP4 should cover it all now.

**Comment by bartkamphorst** [comment]
Does this mean embedding mp4 videos works in gollum without a hitch?
