### ISSUE TITLE
Include other pages/partials

### ISSUE THREAD

**Issue by fredkelly** [gollum/gollum#914]
Would it be possible to add support for some form of includes, either via asciidoc's `include` directive, or some other means?

The ideal solution would enable partials of content to be included in multiple full pages, referenced by a filename or title.

**Comment by dometto** [comment]
@fredkelly, don't know how I forgot about this, but it looks like someone else already reported the fact that asciidoc's include is not working, and suggested a fix:
https://github.com/gollum/gollum/issues/878
Hope that's useful to you.

**Comment by fredkelly** [comment]
Awesome, will take a look :)
