### ISSUE TITLE
File Link don't work

### ISSUE THREAD

**Issue by noppelmax** [gollum/gollum#918]
Hey

i tried serving a pdf from my repo. I want the wiki-user to be able to download the file via a link.
I found this
`[[download|foo.pdf]]`
but it didn't work. By clicking on it, gollum wants me to create a new page called "foo dot pdf". How to do a Downloadlink? I also tried `[[download|file:foo.pdf]]` and `[download]([file:foo.pdf])` and ...

Thanks,
Max

**Comment by abcfy2** [comment]
I have the same issue.

Gollum version is `4.0.1`.

```
$ ls development/knowledge/ppts/MongoDB迁移HBase方案实施细节.pptx 
development/knowledge/ppts/MongoDB迁移HBase方案实施细节.pptx
```

But I cannot reference this file in markdown:
```markdown
[[/development/knowledge/ppts/MongoDB迁移HBase方案实施细节.pptx]]
```

But created a new page, not downloading.
