### ISSUE TITLE
Support global TOC via a Macro

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#921]
Previous versions of gollum apparently showed a TOC of all the pages in the wiki when the default `Home` page did not exist. See #123. Current behavior is to redirect the user to `/create/Home`. However, the user should still be able to generate a list of all the pages in the wiki. It seems easiest to do this using a new Macro. Perhaps it could use the `/pages/`logic for nesting. What would be a good name for this macro? Perhaps `<<GlobalTOC()>>`?

**Comment by vorou** [comment]
Thanks for the feature! Is it available in the latest gem?
With gollum (4.0.0) & gollum-lib (4.0.3) this text `<<GlobalTOC()>>` results into 
> !!!Unknown macro: GlobalTOC!!!

**Comment by dometto** [comment]
It's in the just released gollum-lib 4.1, so you should be able to use it after updating!
