### ISSUE TITLE
All Pages list is not in alphabetical order

### ISSUE THREAD

**Issue by techwiz24** [gollum/gollum#922]
At the bottom of the `All Pages` special page are a few pages which are not in alphabetical order:

![image](https://cloud.githubusercontent.com/assets/794251/5529952/5560a966-89e8-11e4-92fb-cfe570e53691.png)

**Comment by techwiz24** [comment]
I think this is because of they way it's treating the mixed case. Pages that start with a lowercase letter appear at the bottom of the `All Pages` List.

**Comment by techwiz24** [comment]
Changing

```ruby
@results     = wiki.pages
@results     += wiki.files if settings.wiki_options[:show_all]
```

to

```ruby
@results     = wiki.pages.sort_by { |p| p.name.downcase }
@results     += wiki.files.sort_by { |p| p.name.downcase } if settings.wiki_options[:show_all]
```

in [app.rb](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L451-L452) seems to have fixed it. I'll submit a proper PR later tonight for it.

**Comment by dometto** [comment]
Would welcome a PR! However, wouldn't we rather want to sort `@results` after adding the files? And is sorting by `p.name.downcase` what we want, rather than by plain `p.name`?

**Comment by techwiz24** [comment]
Because if you don't call `downcase` the sort function will sort `A-Z` and then `a-z`, so `['Zzz','Abc','def','zzz']` becomes `['Abc','Zzz','def','zzz']` instead of `['Abc','def','Zzz','zzz']`. I didn't have time last night, but I should have a PR ready by the end of the day.

Also, I agree sorting `@results` would probably be better (new to ruby, so I thought it was an instance variable rather than a method level variable)
