### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by dekatzenel** [gollum/gollum#923]
Sometimes, using the built-in search on our wiki returns the following error page: 
![screenshot from 2014-12-22 15 19 01](https://cloud.githubusercontent.com/assets/4731168/5530474/135be962-89ee-11e4-99c6-2d18766833f7.png)

The function referenced is the following in app.rb:
    get '/search' do
    @query = params[:q]
    wiki = wiki_new
    # Sort wiki search results by count (desc) and then by name (asc)
    @results = wiki.search(@query).sort { |a, b| (a[:count] <=> b[:count]).nonzero? || b[:name] <=> a[:name] }.reverse
    @name = @query
    mustache :search
    end

Some quick research on Ruby suggests that a[:count] and b[:count] may not be comparable - a case in which <=> returns `nil`.

**Comment by dekatzenel** [comment]
Is there a scheduled or estimated release date for this fix?

**Comment by dometto** [comment]
There is no schedule, although we should think about release cycles. Quite some bugs were fixed in gollum and gollum-lib, so I think we should do one pretty soon (i.e. sometime the next two weeks).

**Comment by dometto** [comment]
Just released gollum-lib v4.0.2 in which this is fixed.
