### ISSUE TITLE
MediaWiki TOC styling

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#925]
...looks wrong:
![screen shot 2014-12-29 at 15 13 56](https://cloud.githubusercontent.com/assets/147111/5569260/6eb2f768-8f6d-11e4-9ed2-de2346d82912.png)

Wikicloth is giving the TOC table the `toc` class, so it's using the styling of gollum's own TOC. However, that's not working out very well, since it's a table (and not a div, like gollum's own TOC). Unfortunately, wikicloth does not support setting custom css or class for the TOC.

**Comment by dometto** [comment]
It's possible to redefine `WikiCloth::Parser.toc`, but that's not really an option for us, since we're calling `wikicloth` through `github-markup`. Best thing to do is probably to define proper CSS for `.table toc`.

**Comment by SkyCrawl** [comment]
@dometto 
I can most probably make both versions work but is MediaWiki's TOC any different from Gollum's in terms of functionality? If not, we might as well consider dynamically switching to Gollum's TOC if MediaWiki's TOC is found. All the more reason to do it if there are more markups having this exact problem :).

**Comment by dometto** [comment]
@skycrawl, I think disabling wikicloth's TOC should be possible, and should be fine (especially when we we have your YAML frontmatter). Not sure if the current TOC supports as many (or abitrary) levels of subsections as wikicloth's, if not, that would be a nice addition (but not critical).

**Comment by SkyCrawl** [comment]
Gollum's TOC searches for H1-H6, so maximum of 6 levels :). What HTML elements are MediaWiki's "headers" translated into? H1 to H6 as well?

**Comment by dometto** [comment]
Yes, h1-h<n> anyway :) 6 levels should be fine of course.

**Comment by dometto** [comment]
@bartkamphorst what do you think? Do we want to tweak the CSS for the wikicloth-generated table, or override wikicloth's behavior by catching instances of `__TOC__` (that's mediawiki syntax) and replacing them with `[[_TOC_]]` (gollum-style)?

**Comment by dometto** [comment]
Ping @bartkamphorst

**Comment by bartkamphorst** [comment]
>  Do we want to tweak the CSS for the wikicloth-generated table, or override wikicloth's behavior by catching instances of __TOC__ (that's mediawiki syntax) and replacing them with [[_TOC_]] (gollum-style)?

I definitely prefer adding proper CSS for the wikicloth-generated table. In general, I think it's fine for gollum to _add_ functionality (and to be able to use gollum's TOC with mediawiki if so desired), but it should stay out of the way of things that individual renderers already provide.

**Comment by dometto** [comment]
On 5.x, the normal TOC and mediawiki TOC look the same:
<img width="1143" alt="Screenshot 2019-09-11 at 11 39 43" src="https://user-images.githubusercontent.com/147111/64686448-fc986f80-d488-11e9-9588-6fa1de975c0f.png">
<img width="987" alt="Screenshot 2019-09-11 at 11 40 08" src="https://user-images.githubusercontent.com/147111/64686452-fd310600-d488-11e9-9157-1d1d89b8ba77.png">

However, as you can see, the TOC spans the width of the content div. Is that intentional, @bartkamphorst ?

**Comment by dometto** [comment]
My bad, I was using a gollum TOC by mistake. Fixed the CSS for wikicloth tables: https://github.com/gollum/gollum/pull/1418

**Comment by dometto** [comment]
@bartkamphorst there is still a separate question about the styling (width) of gollum's own toc div. If you think it should be changed, please open a new issue for it (I'm fine with either).

**Comment by dometto** [comment]
Fixed in #1418

**Comment by bartkamphorst** [comment]
> it actually looks find and we should keep it this way.

Agreed.
