### ISSUE TITLE
Graphviz support?

### ISSUE THREAD

**Issue by craibuc** [gollum/gollum#931]
Please consider adding support for [Graphviz](http://graphviz.org/) syntax.

**Comment by dometto** [comment]
Note that gollum already supports Web Sequence Diagrams: https://github.com/gollum/gollum/wiki#Sequence. I'm not familiar with either WSD or Graphviz, but is there any reason why we'd need to support both? If so, we'd certainly welcome a PR!

**Comment by craibuc** [comment]
WSD doesn't seem to support entity-relationship diagrams.  [Graphviz does](http://graphviz.org/content/ER).

**Comment by hsanson** [comment]
A tool like http://plantuml.sourceforge.net/ would be better. It uses graphviz underneath and can generate more diagram types than websenquencediagram.com.

Also generating the diagrams locally is more appealling for corporations that want to keep their internal documentation private. As far as I can tell there is no way to limit access to th generated diagrams on webdsequencediagrams even when using a registered API key.

**Comment by dometto** [comment]
> As far as I can tell there is no way to limit access to th generated diagrams on webdsequencediagrams even when using a registered API key.

@hsanson that seems like a fair argument in favor of moving away from WSD. However, we would like to keep gollum as free as possible of external dependencies. If there is a pure ruby or JS implementation of something graphviz-like, that would be preferable.

**Comment by dometto** [comment]
PlantUML support implemented in https://github.com/gollum/gollum-lib/pull/138, will be in the next minor update to gollum-lib. Thanks to @hsanson.
