### ISSUE TITLE
Register .asc .adoc extensions

### ISSUE THREAD

**Issue by craibuc** [gollum/gollum#933]
The [Page Files](https://github.com/gollum/gollum/wiki#page-files) section mentions that additional extensions can be registered--I'd like to associate `.asc` and `.adoc` with AsciiDoctor.  It's not apparent how to do this, however.

The example seems to demonstrate register a Markup, not associating an extension with a Markup:

```
Gollum::Markup.register(:angry, "Angry") do |content|
  content.upcase
end
```
If multiple extensions are registered, which one is used for new files?

**Comment by dometto** [comment]
I think those docs are outdated, because `github-markup` no longer supports `GitHub::Markup.register`. We should find a way to re-implement this.

**Comment by bartkamphorst** [comment]
I'm a little confused, as github-markup already associates those file extensions with AsciiDoctor:
```ruby
markup(:asciidoctor, /adoc|asc(iidoc)?/) do |content|
  Asciidoctor.render(content, :safe => :secure, :attributes => %w(showtitle idprefix idseparator=- env=github env-github source-highlighter=html-pipeline))
end
```
What am I missing here?

**Comment by dometto** [comment]
@bartkamphorst, perhaps those extensions have been added in a recent version of github-markup? It does look like this can be closed, though.

**Comment by craibuc** [comment]
Using Gollum 4.0.0, I created a new page named 'Foo'--`Foo.asciidoc` was created in the root folder.  Is there a setting that will allow me to change AsciiDoc's default extension to `.adoc`?

I manually created a file (outside of Gollum) in the wiki's folder:
~~~
$ echo 'testing 123' > Bar.adoc
$ git add .
$ git commit -m 'Adding Bar'
~~~
I restarted Gollum.  The page was displayed as Foo.adoc.  When I clicked the link, Safari attempted to download the file (rather than render it).

**Comment by bartkamphorst** [comment]
I think the `.adoc` extension, while known by github-markup, is not recognized by gollum as a valid page extension.

> Is there a setting that will allow me to change AsciiDoc's default extension to .adoc?

I haven't tested this, but I would suspect something like
```ruby
    Gollum::Markup.register(:adoc,  "AsciiDoc")
```

would help with this issue.

**Comment by SkyCrawl** [comment]
@bartkamphorst @dometto 
Elegantly solved in my forks :).

**Comment by ellipticview** [comment]
Besides recognizing the .asc and .adoc extensions, it would be useful to have the ability to **configure** the **default** extension for asciidoc for new pages.

**Comment by SkyCrawl** [comment]
Yes. Way ahead of you... this has already been taken care of in my forks :).

**Comment by SkyCrawl** [comment]
@craibuc @dometto @bartkamphorst @ellipticview 
Gollum config (`config.rb`) to solve this:
```ruby
# Always remove this:
Gollum::Page.send :remove_const, :FORMAT_NAMES if defined? Gollum::Page::FORMAT_NAMES

# REGISTERED FORMAT INFORMATION:
# puts Gollum::Markup.formats.inspect
=begin
{
    # primary-extension => { markup-name, markup-file-extension-regex }
    
    :markdown => { :name => "Markdown", :regexp => /md|mkdn?|mdown|markdown/ },
    :textile => { :name => "Textile", :regexp => /textile/ },
    :rdoc => { :name => "RDoc", :regexp => /rdoc/ },
    :org => { :name => "Org-mode", :regexp => /org/ },
    :creole => { :name => "Creole", :regexp => /creole/ },
    :rest => { :name => "reStructuredText", :regexp => /re?st(\.txt)?/ },
    :asciidoc => { :name => "AsciiDoc", :regexp => /asciidoc/ },
    :mediawiki => { :name => "MediaWiki", :regexp => /(media)?wiki/ },
    :pod => { :name => "Pod", :regexp => /pod/ },
    :txt => { :name => "Plain Text", :regexp => /txt/ }
}
=end

# WHAT TO DO:
# As can be seen, primary extension for AsciiDoc is defined as ".asciidoc". Also, the only extension that Gollum recognizes for AsciiDoc markup is ".asciidoc". Let's change that - first remove the original information:
Gollum::Markup.formats.delete(:asciidoc)

# and then redefine it - ".asc" is the new primary extension:
Gollum::Markup.formats[:asc] = {
    :name => "AsciiDoc",
    :regexp => /(?:asc|adoc|asciidoc)/
}
```

Tested and working! With this, the issue can be closed.

**Comment by ellipticview** [comment]
Nice! I can confirm that this works. Thanks SkyCrawl.

**Comment by bartkamphorst** [comment]
:+1:
