### ISSUE TITLE
Path prefix for serving gollum as rack app

### ISSUE THREAD

**Issue by deric** [gollum/gollum#937]
I have a following structure of repository:

```
 \ - .git
 \- config.ru
 \- Gemfile
 \- public
   \- Home.md
   \- ...  
```
I'd like to serve this as an rack app, which means that I can't have `config.ru` in the `public` directory but it must be one level higher.  

When I set `--page-file-dir public` I'll get title `public/Home`, but I'd like to have just `Home`, so a prefix that won't be included within URI and titles of all my pages. Would it be possible to introduce a parameter e.g. `path_prefix` for loading and storing of all pages and static content?

**Comment by dometto** [comment]
If this is just cosmetic, note that you can set your own titles by enabling the :h1_title option.

Something like you describe should be possible to implement, but should probably be handled as part of a more comprehensive overhaul of the way gollum handles subdirectories. The logic is quite complex now, with page_file_dir, base_dir, and gollum passing around subdirectories as separate arguments internally (gollum-lib#11).

**Comment by deric** [comment]
I know about `:h1_title`, but this is more general issue. If I want to deploy Gollum as a Rack app which is a standard for all Ruby webservers (Passenger, Unicorn, Puma, ...) I can't have website root in a subdirectory of my git repo. All internal URI in wiki have to start with this `prefix`. It would be nice to have such a parameter.

I think [gollum-lib#11](https://github.com/gollum/gollum-lib/issues/11) is something different.

**Comment by dometto** [comment]
Yes, https://github.com/gollum/gollum-lib/issues/11 is different. But I was trying to point out that gollum's way of dealing with paths and prefixes is complex, and not even consistent, and we should avoid making things worse by just adding a new parameter to the existing bunch. We should rather try to clean up the messy logic, write some good helper methods for constructing URI's and titles, and consistently apply those throughout gollum-lib. Then implementing this would be much easier.

**Comment by dometto** [comment]
Moved the discussion to https://github.com/gollum/gollum-lib/issues/133.
