### ISSUE TITLE
Page's commit history

### ISSUE THREAD

**Issue by craibuc** [gollum/gollum#941]
Is there a way to include a page's commit history in the page itself?  

Something like:

    Thu Jan 15 15:47:29 2015 -0600 - John Doe : Updated Foo (asciidoc)
    Thu Jan 15 15:43:09 2015 -0600 - Jane Doe : Updated Foo (asciidoc)
    Thu Jan 15 15:41:20 2015 -0600 - Frodo : Created Foo (asciidoc)

I suppose this could be implemented as a macro, but how do you 1) execute a Git command 2) get the current page's file name?

**Comment by dometto** [comment]
As you can easily see in [macro.rb](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/macro.rb), you have `@page` and `@wiki` available inside your macro. Please ask general questions for help about how to write certain code elsewhere; this issue tracker is for reporting bugs and requesting features.

When you try to come up with an implementation yourself and run into problems with gollum code, we'd be happy to take a look of course.
