### ISSUE TITLE
make use of wide screen

### ISSUE THREAD

**Issue by xu4wang** [gollum/gollum#945]
When I use Chrome with gollum, there are some blank area on the left and right of the browser.  Is there any configuration I can do to make gollum use the whole browser area?

Thanks,
WX.￼

**Comment by techwiz24** [comment]
I second this! I personally apply a patch after the gem gets updated to do this, but I would love to have the option to do it within gollum itself!

Perhaps this could be incorporated as a part of #917?

**Comment by dometto** [comment]
Yeah, this seems like something we need to tackle as part of #917. Perhaps you can post a link to your patch there? Any help with the CSS changes is very welcome, btw.
@xu4wang: as a workaround you may find it useful to include custom css by using the `--custom-css` argument.

**Comment by dometto** [comment]
@xu4wang also see the patch @techwiz24 just posted in #917. Since this should be part of #917 I'll close this.
