### ISSUE TITLE
nested list is not rendered correctly with live preview

### ISSUE THREAD

**Issue by xu4wang** [gollum/gollum#947]
below lists can demonstrate the issue

```
* l1
  * l2
     * l3
```

In the live preview window, l2 and l3 is in the same level.  
If save the file, it will be rendered as expected.

**Comment by dometto** [comment]
Likely a bug in the (old, deprecated) javascript compilation of sundown that the livepreview is using. We should switch to a newer markdown library. See #826.

**Comment by dometto** [comment]
Livepreview has been removed from `5.x` in favor the improved ACE editor.
