### ISSUE TITLE
Directory Index Directive

### ISSUE THREAD

**Issue by maxchill** [gollum/gollum#948]
Would be handy to have a keyword which automatically creates a list of all files / wiki links in a directory.

Defaults to current directory, and allows specifying a directory.

Here is a some ugly sample syntax.  

__ DIR_TOC__
__ DIR_TOC[/Directory/Subdirectory]__

This would help avoid some redundancies in manually creating lists of wiki pages, when we can just use the filesystem structure as the source of this data.

**Comment by bartkamphorst** [comment]
Implementing a custom Macro is probably the best way to go here. See for an example the [GlobalTOC() Macro](https://github.com/gollum/gollum-lib/pull/126/files). If you include a test, we'd happily accept a pull request.

**Comment by dometto** [comment]
This has been merged in https://github.com/gollum/gollum-lib/pull/182
