### ISSUE TITLE
file uploaded to wrong directory when "--allow-uploads page"

### ISSUE THREAD

**Issue by xu4wang** [gollum/gollum#955]
I started gollum with below parameter:
```
--allow-uploads page
```

Uploaded one file name "oc.zip" under page compiler.md, checking Latest Changes:

```
Wang Xu
January 27, 2015:  Uploaded file to wiki/compiler/oc.zip [476e1a0] 
                               wiki/wiki/compiler/oc.zip
```

I expected to find the file oc.zip under wiki/compiler , but it was not there.
It was also not under wiki/wiki/compiler/oc.zip

It appears after git checkout
```
WangXudeMacBook-Pro:gollum_wiki wangxu$ git checkout
D	wiki/wiki/compiler/oc.zip
```

Looks like the file was uploaded to wrong directory, and was deleted.

**Comment by dometto** [comment]
@xu4wang, I suppose you're using the `--page-file-dir` option as well? It looks like it's passing the page file dir as part of the upload path, then adding the page file dir prefix again.

**Comment by xu4wang** [comment]
@dometto  you are right. I'm using

```
gollum --host 127.0.0.1 --port 9046 --css --live-preview --allow-uploads page --page-file-dir wiki gollum_wiki
```

I'm expecting : 
* every wiki page stored in gollum_wiki/wiki
* every attachment for page_name stored in gollum_wiki/wiki/page_name/attachement_name

is there any way to accomplish above two?  if only we have #956 fixed? 

Thanks,
X.

**Comment by dometto** [comment]
#956 fixes it. It will be in the next patch-level (3.1.x) release of the gem. If you want to use the fix now already, you can try cloning `master` and running gollum from there.

**Comment by alexgorbatchev** [comment]
I'm seeing all uploads being put into `/uploads` folder with `allow_uploads` being set to `page` instead of the same location as the page. Could this be related?

```
Precious::App.set(:wiki_options, {
  :mathjax => false,
  :live_preview => false,
  :universal_toc => false,
  :allow_uploads => 'page',
  :user_icons => 'gravatar',
  :css => true,
  :h1_title => true,
  :css => true,
})
```

**Comment by dometto** [comment]
@alexgorbatchev the issue is with your setup. You need to set both `:allow_uploads` and `:per_page_uploads` to `true`. See https://github.com/gollum/gollum/wiki/Using-Gollum-with-Rack

**Comment by alexgorbatchev** [comment]
@dometto thanks! That made it work, but I noticed that URL generated by drag and drop on Edit page is incorrect...

![index 2015-01-30 10-24-47](https://cloud.githubusercontent.com/assets/65633/5980935/41625edc-a86a-11e4-83d1-61b94f0f4714.png)

**Comment by bartkamphorst** [comment]
Thanks for reporting the issue @alexgorbatchev .
