### ISSUE TITLE
Expose editor to allow configuring the live editor.

### ISSUE THREAD

**Issue by simonzack** [gollum/gollum#957]
Can the `editor` and `editorSession` variables be exposed in window to allow the live editor to be configured? In the code I see that `$.editorSession` is currently exported "for testing".

Another approach I can think of would be to fire some event or call some function in `initAce`. This has the advantage of killing any flickers when setting a different theme.

**Comment by dometto** [comment]
As I said in the PR this seems reasonable to me. Note that we're discussing moving away from ACE in #826, the idea being to integrate live preview into gollum's default editor. If you have any thoughts on that please let us know.

**Comment by dometto** [comment]
Resolved by #965.
