### ISSUE TITLE
config latest_changes_count

### ISSUE THREAD

**Issue by xu4wang** [gollum/gollum#960]
Hello,

I'd like to config latest_changes_count to be 50, 10 is too small for me.

I checked the code, and cannot find a good way.  Tried passing --latest_changes_count to gollum but:
```
gollum: invalid option: --latest_changes_count
gollum: try 'gollum --help' for more information
```

Is there anyway to config this parameter? 

PS.
Sorry for this Ruby newbie question,  is there a user mail list or wiki for gollum users to ask this kind of question?

Thanks,
X.

**Comment by dometto** [comment]
Use the `--config config.rb` option to load `config.rb`, then in that file do:
```ruby
Precious::App::wiki_options[:latest_changes_count] = 50
```
You can set all other wiki options like that too. Ruby questions you can ask on the ruby-talk mailinglist; also be sure to read gollum's [wiki](https://github.com/gollum/gollum/wiki) for questions like this one.

**Comment by xu4wang** [comment]
thanks @dometto
