### ISSUE TITLE
showing attachment list for each page

### ISSUE THREAD

**Issue by xu4wang** [gollum/gollum#961]
When the page has an attachment, or several attachments,
I'd like to show them one by one on the bottom of the page in a list, each list item is a downloadable link for downloading this attachment.

At the moment, when a file is uploaded, there is no indication.
The page viewer don't know if there is any attachment.

**Comment by dometto** [comment]
File uploads are not technically 'attachments' to pages. You can link to an upload from any page in the wiki. The 'page' option for `--allow-uploads' is only intended to make manual linking from within page to an upload easier. If you want to auto-generate a list of files in some location in the wiki, you can implement this yourself using a Macro (see the wiki).
