### ISSUE TITLE
Server error on searches containing apostrophes

### ISSUE THREAD

**Issue by alin-luminoso** [gollum/gollum#963]
On our gollum 3.1.2 installation, searching for `it's`, or any other string containing a single apostrophe, yields "Internal Server Error: undefined method `join' for #<String:0x007f5ff86f57e8>" (or the like).

Interestingly, searching for `'its'`, or other strings containing an even number of apostrophes, does not trigger the error.

**Comment by dometto** [comment]
The `join' is related to this sinatra/rack issue: https://github.com/sinatra/sinatra/pull/907. It's masking the real cause of the problem, which you can see from looking at the backtrace on the console:
`ArgumentError - Unmatched double quote: "it's":`
That's being thrown by `Shellwords` when trying to split the query into different shellwords. I've fixed this [here](https://github.com/gollum/grit_adapter/commit/adf5e13272d431c3739dbe47de13bde98f8679c3). I'm doing a bugfix release of the grit_adapter in a second. So do `gem update gollum-grit_adapter` and it should be fixed.

**Comment by bartkamphorst** [comment]
Nice catch @dometto ! :+1:

**Comment by alin-luminoso** [comment]
Confirmed, thank you!
