### ISSUE TITLE
Can create a page but unable to load it

### ISSUE THREAD

**Issue by alexgorbatchev** [gollum/gollum#966]
Hey friends, I'm having an issues I can't seem to find an answer. I've installed Gollum and it's running ok. I was able to create the default `Home` page and can see `Home.md` in the GIT repo. However, trying to visit `/Home` or `/` always redirects me to `/create/Home`?

Is this a common symptom of a configuration mistake? What did I do wrong?

**Comment by dometto** [comment]
That sounds like a problem with your setup. Please give an overview of version numbers and your gollum configuration.

**Comment by alexgorbatchev** [comment]
You were right. Thank you!
