### ISSUE TITLE
Allowing data urls

### ISSUE THREAD

**Issue by isaacrg** [gollum/gollum#968]
How do I allow data urls to work, through my config.rg. E.g.

`data:text/html, <html contenteditable><a href="http://localhost:4567" title="Ctrl-Click this.">Home</a><hr /><b>This is cool.</b>`

**Comment by dometto** [comment]
I'm not sure what your question is. Data uri's are rendered client side, so if you want to use them all you have to do is put them in the relevant pages. It's possible the sanitization filter is disallowing the use of the `data:` protocol. In that case, you can override the sanitization settings as explained [here](https://github.com/gollum/gollum/blob/master/docs/sanitization.md).

**Comment by dometto** [comment]
Not sure how I can help you, but please re-open if you think there is a gollum-specific issue to addressed here.
