### ISSUE TITLE
Add PlantUML documentation

### ISSUE THREAD

**Issue by hsanson** [gollum/gollum#972]
I wrote documentation for the Gollum Wiki with details on how to use the PlantUML diagrams in Gollum pages.

I could not find a way to create a pull request for github wiki pages so I created a diff patch from the latest wiki master:

  - https://gist.github.com/hsanson/f9a6e0678ff137e07c63#file-gistfile1-txt

If there is a better way to contribute to the Wiki please let me know.

**Comment by dometto** [comment]
Thanks for the documentation, @hsanson. You should actually just be able to edit the gollum wiki yourself, when you're logged in on github.

**Comment by hsanson** [comment]
Though was bad manners to edit someones else wiki pages....   I added the changes directly to the wiki so closing this issue.

**Comment by dometto** [comment]
Thanks!
