### ISSUE TITLE
I think Torchpad is based on Gollum

### ISSUE THREAD

**Issue by ringe** [gollum/gollum#974]
Nice wiki interface at
https://torchpad.com/

I really think Torchpad is built with Gollum, which is fine. Just interesting.

What do you say?
Would you prefer a git-storage in Taiwan or on your own computer?

**Comment by bartkamphorst** [comment]
Thanks for the link. As I see no problem description, I'm closing this issue.

**Comment by ringe** [comment]
True. :) Just wanted to let you know.

**Comment by darkdragon-001** [comment]
Torchpad looks great, but I would like a self-hosted solution...
Has anyone seen/build a similar open-source version?
Specifically adding simple user management and export feature to base Gollum?
