### ISSUE TITLE
Question: Is there a way to link to a section on the same page?

### ISSUE THREAD

**Issue by exabrial** [gollum/gollum#975]
Question: Is there a way to link to a section on the same page?

Sorry, didn't know where else to ask this... I read through the docs and couldn't find an answer. Thank you!

**Comment by dometto** [comment]
You'll have to use the current page's name in your link:
```
[[Section|Home#section]]

# Section
```
Would be nice if it would automatically assume the current page as target when linking to `[[Section|#section]]`, but that would require changes to https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/tags.rb. Pull requests welcome. :-)
