### ISSUE TITLE
grit is no longer maintained: will gollum switch to rugged?

### ISSUE THREAD

**Issue by pberto** [gollum/gollum#977]
Also could Gollum be able to run on a (I know, lame but our company intranet has windows servers...) work on windows with Rugged?

**Comment by bartkamphorst** [comment]
@pberto It is already possible to run gollum with rugged. See [the wiki](https://github.com/gollum/gollum/wiki/Git-adapters). The rugged adapter is still in beta though, so you may want to refrain from using it in production just yet. But testers are very welcome!

RE Windows-support, I think that's still blocked on some gems having 'posix-spawn' as a dependency. We're doing our best to resolve that, but I'm not sure whether we'll actually offer support for Windows (as none of the maintainers use it as far as I know).
