### ISSUE TITLE
allow untracked uploads

### ISSUE THREAD

**Issue by l3iggs** [gollum/gollum#980]
I just noticed that the files uploaded witht he `allow-uploads` feature get committed to the git repo. That's pretty cool, but sometimes I don't want the files I upload to be comitted (as in a large binary for example).

I think it would be useful if there was an `allow-untracked-uploads` feature that would make a tickbox marked "Untracked" to appear in the upload dialog. So that if the user ticks that box and then uploads a file it is not committed to the repo. That file should probably be stored in an "untracked-uploads" folder if you've enabled the central upload location mode so there's no confusion.

**Comment by dometto** [comment]
If anyone disagrees please reopen this, but I think this is not within the scope of gollum: the goal of the project is to have a fully git-based wiki, and this would basically require us to support some other kind of no-sql storage on the side (even when just using the filesystem, that would require us to deal with possible overwrites and such).
