### ISSUE TITLE
TOC with HTML tag in heading

### ISSUE THREAD

**Issue by lihuanshuai** [gollum/gollum#982]
I am writing HTML & JS tutorials in Markdown, and there is a issue:

Sometimes, I have to use HTML tag in headings, like 

```markdown
## What is a `<script>` tag
```

The result of generated page is OK, except that the TOC part is not correct. Can it be fixed in some way?

**Comment by dometto** [comment]
Thanks for reporting this. This happens, I think, because the TOC is inserted after the rest of the rendering has been done. Maybe it's possible to perform some of the rendering steps on the TOC data before inserting it. I won't have time to look at this the coming month, but feel free free! The relevant code is here:

**Comment by SkyCrawl** [comment]
@lihuanshuai 
Thank you for reporting this. At the moment, I'm in the process of reorganizing/rewriting gollum and will certainly look at this eventually but it seems to me you should do this instead: `## I include an '&lt;html&gt;' tag`. Feel free to replace the single quotes with double quotes or (maybe) something else.

I haven't tested it but if the above is not inside backtick characters (and thus will NOT render in a `<code>` block, unlike here on GitHub), it should work as expected and the TOC should correctly display your tags.
Although it's not so pretty, it's actually the correct way to do this :). The TOC generates anchor tags, as far as I know, which do NOT like having `<code>` blocks inside them. I imagine that if you succeeded in what you were trying to do previously, the result would be quite ugly :).

Try this, please, and let us know :).

**Comment by lihuanshuai** [comment]
@SkyCrawl It works. Thanks!
