### ISSUE TITLE
how to make /compare/ use --word-diff

### ISSUE THREAD

**Issue by mdik** [gollum/gollum#983]
Hi,

I want to hack gollum a bit to make it more usable for collaborative editing of prose, so I cloned the "compare" view into a view "word_diff". Now, how can i make the line
```
diffs     = wiki.repo.diff(@versions.first, @versions.last, @page.path)
```
from app.rb behave like git would if used with "--word-diff=porcelain"?

Thanks a lot in advance,

Malte

**Comment by bartkamphorst** [comment]
@mdik Apologies for the late response. You would have to look at the git adapter you are using. With the [grit adapter](https://github.com/gollum/grit_adapter/blob/master/lib/grit_adapter/git_layer_grit.rb) for example you could override the diff method to make a native call to the git system binary for diffing, so in principle you should be able to add your flag there. Hope this helps!

**Comment by mdik** [comment]
Thanks. I'm a bit swamped right now myself. So will look into it when there is a bit more free time.
