### ISSUE TITLE
wiki_options[:base_path] setting ignored

### ISSUE THREAD

**Issue by craibuc** [gollum/gollum#984]
It appears that the `wiki_options[:base_path]` setting is ignored when starting Gollum as a Rack app.

Starting Gollum via command:

`$ gollum --config config.rb --allow-uploads page --user-icons identicon --base-path foo/bar`

Gollum served at `http://localhost:4567/foo/bar/`

Starting Gollum via Rackup:

`$ rackup -p 4567`

Gollum served at `http://localhost:4567/`

config.ru:

```
#!/usr/bin/env ruby
require 'rubygems'
require 'gollum/app'

wiki_options = {}
wiki_options[:universal_toc] = false
wiki_options[:base_path] = 'foo/bar' # Equivalent to --base-path
wiki_options[:allow_editing] = true # # Equivalent to --no-edit
wiki_options[:live_preview] = true # Equivalent to --live-preview
wiki_options[:allow_uploads] = true # Equivalent to --allow-uploads
wiki_options[:per_page_uploads] = true # When :allow_uploads is set, store uploads under a directory named after the page, as when using --allow-uploads page
wiki_options[:user_icons] = "identicon" # Equivalent to --user-icons ; gravatar, identicon, none. Default: none.
wiki_options[:show_all] = true # Equivalent to --show-all
wiki_options[:collapse_tree] = true # Equivalent to --collapse-tree
wiki_options[:h1_title] = true # Equivalent to --h1-title

gollum_path = File.expand_path(File.dirname(__FILE__)) # CHANGE THIS TO POINT TO YOUR OWN WIKI REPO

Precious::App.set(:gollum_path, gollum_path)
Precious::App.set(:default_markup, :asciidoc) # set your favorite markup language
Precious::App.set(:wiki_options, wiki_options)
run Precious::App
```

Using Gollum 3.1.2.

**Comment by bartkamphorst** [comment]
Thanks for reporting the issue @craibuc . We're pretty swamped at the moment, so I can't give you a timeline for a fix. But if you could help out by investigating the cause, that would certainly speed things up!

**Comment by dometto** [comment]
@craibuc, it seems that base_path is unavailable as an option when running gollum as a rack app. This is because the base_path option is implemented via a simple [piece of middleware](https://github.com/gollum/gollum/blob/master/bin/gollum#L209-L229) when running gollum via `bin/gollum`. You'll have to add the same middleware to your `config.ru` to get the desired result.

I'll update the wiki accordingly.

**Comment by dometto** [comment]
See https://github.com/gollum/gollum/wiki/Using-Gollum-with-Rack
