### ISSUE TITLE
command not found: gollum

### ISSUE THREAD

**Issue by saintbird** [gollum/gollum#986]
I run "bundle install" under gollum directory on mac os 10.9.5 and get the successful message "Your bundle is complete!". However, when I run "gollum --v", I get such message "zsh: command not found: gollum".

Can anybody help? Thanks.

**Comment by dometto** [comment]
When running from source, use `bundle exec gollum`. The method you're trying will only work when gollum is installed as a gem, i.e. `gem install gollum`.
