### ISSUE TITLE
Markdown inside <div> ignored

### ISSUE THREAD

**Issue by svoop** [gollum/gollum#989]
Not sure whether this is a feature or a bug.

I have defined a few DIV classes to highlight page content, e.g. the warn class which will simply render a yellowish box around the content. Unfortunately, Markdown (GFM to be exact) does not work within this DIV:

    <div class="warn">
    Markdown like [this link](https://github.com) won't be parsed.
    ```
    However, this fenced code will render normally.
    ```
    </div>

    [This link](https://github.com) will be parsed normally again.

**Comment by sunny** [comment]
<div>
I'm afraid this is a *feature* of Markdown, so I'm closing the issue here. I don't know of any workarounds, but please share them should you find any.
</div>

**Comment by svoop** [comment]
Well, the obvious, yet ugly one :smile:

<div class="warn">
Markdown like [this link](https://github.com) won't be parsed.
Have to <a href="https://github.com">do it with plain ole HTML</a> instead.
</div>
