### ISSUE TITLE
MediaWiki: Table cells colors and background don't seem to be taken into account?

### ISSUE THREAD

**Issue by rubisher** [gollum/gollum#996]
Hello all,

During years I spend as system admin, I wrote many procedures, documents, tips, ... which are now scattered over different places (in a same boxes or not) and it becomes more and more difficult recover the information, so I would like to gather most of those material into a personal wiki at a first glance.

As I didn't find (yet) any easy way to convert my 'ODT' files (which also contain few special format) into a wiki, I bring myself to do it manually in a lightweight wiki tool.

The only special thing I would really have in my selected wiki is the capability to create tables with cells of different background and colors like I can do in my 'moinmoin' test or like I read in Mediawiki (http://en.wikipedia.org/wiki/Help:Table).

As gollum is a lightweight wiki which can manage several format, I just install the gem package in my recent rvm update (2.2.1) with additional wikicloth.
I just try to test a simple mediawiki page like:
{| border="1"
|Orange
|Apple
|align="right"|12,333.00
|-
|Bread
|style="color: white; background: red;"|Pie
|align="right"|500.00
|- style="font-style:italic; color:green;"
|Butter
|Ice cream
|align="right"|1.00
|}

but colors rendering failed to me.

So I try to investigate a bit and copy this file in ~/.rvm/gems/ruby-2.2.1/gems/wikicloth-0.8.3/sample_documents to run the 'run_tests.rb' and check how wikicloth manage it and the result looks correct and in the html page I can effectively read:
...
\<tr>
\<td>
Bread
\</td>
\<td style="color: white; background: red;">
Pie
\</td>
\<td align="right">
500.00
\</td>
\</tr>
...

while the page generated by my gollum install just contains:
...
\<tr>
\<td>
Bread
\</td>
\<td>
Pie
\</td>
\<td align="right">
500.00
\</td>
...

I don't see what can I miss in my install. 
Any idea ?

Thanks in advance for further help,

**Comment by dometto** [comment]
@rubisher, I'm 99% sure that what's happening is that gollum's sanitization filter is removing the style tags from your table. See [here](https://github.com/gollum/gollum/blob/master/docs/sanitization.md) for how to override sanitization. Feel free to reopen if that doesn't solve your issue.

**Comment by rubisher** [comment]
Hello dometto,

I well read your <https://github.com/gollum/gollum/blob/master/docs/sanitization.md> and even the wikicloth one <https://github.com/nricciar/wikicloth/wiki/Html-Sanitization> and also <https://github.com/rgrove/sanitize> but I don't yet understand how should I simply add an "allowed attribute" like here 'style' to the default gollum Sanitization.

If ever you would have a simpler example may be would it be more clear to me (with age everything goes slowly :( )

Anyhow thanks again for your kind attention,
J.

**Comment by dometto** [comment]
@rubisher, see the example in `sanitization.md`. You need:
```ruby
sanitizer = Gollum::Sanitization.new
sanitizer.attributes['td'].push 'style' # Attributes
Precious::App.set(:wiki_options, {:sanitization => sanitizer})
```
That goes in your `config.rb` file, then run gollum with the option `--config config.rb`.

**Comment by rubisher** [comment]
too cool :) 
(but still failing because looking for push method ...? I will investigate that later)

Many tx,
J.

**Comment by rubisher** [comment]
using:
sanitizer.attributes[:all].push 'style' # Attributes

make the drill for my concern (my cell is well color white with a background red :)).
That definitely confort me to use gollum for my personal wiki: _GREAT_.

Many thanks again,
J.

**Comment by dometto** [comment]
Good to hear and thanks for letting know about `attributes[:all]`!

**Comment by bartkamphorst** [comment]
Which leaves open the question whether we think the Sanitize default that gollum currently has is sane. I can imagine colored table cells being quite useful at times. What, if any, are the security risks of enabling style attributes by default?
