### ISSUE TITLE
Request Params in Macro

### ISSUE THREAD

**Issue by svoop** [gollum/gollum#997]
I've created two simple macros: `<<Tag(foobar)>>` to define tags on a page and `<<AllPagesWithTag(foobar)>>` to list all pages with a specific tag. The next logical step would be a generic wiki page "All Pages with Tag" calling the latter macro without argument – which then would read the tag from the request params instead (example: *http://gollum.com/All-Pages-with-Tag?tag=foobar*). This way, it would be possible to link to tag index pages without having to hardcode a page for every tag.

Inside the macros `render`, I can access `@page` and `@wiki`, but I don't see a way to get the request params. It would be nice to have this possibility. (Or is it already possible and I'm too blind to see?)

**Comment by SkyCrawl** [comment]
Macros are processed in the `gollum-lib` backend while request params can only be accessed in the frontend (sinatra routes). Thank you for reporting this... we should maybe consider accessing request params in the backend for future Gollum releases :).

Anyway, back to your question. I think you're trying to do it the "hard way". How is `TAG_SPECIAL_PAGE` different from `<<tag(special_page)>>`? If I understand correctly, you wish to include some "searchable" tag syntax to your pages. The best way to do that would be in the `<!--- ... -->` top HTML comment, where page title is also defined. That way, the tags won't be displayed on your page but you can still FIND them.

So, a page:
```
<!--
--- title: My Page
tags: TAG_SPECIAL_PAGE
-->

... page content
```

And a link: `localhost:4567/search?q=tag_special_page`

Gollum's search should definitely find all pages with the tag although I'm not completely sure with the URL - haven't tested it. I think search ignores case but again, it needs to be tested :).

Would you please try and let us know? :)

**Comment by dometto** [comment]
I think it would be best to implement this via YAML frontmatter, see #774.

**Comment by SkyCrawl** [comment]
Indeed, but I think you should still consider providing access to request parameters to macros (and possibly filters too).
