### ISSUE TITLE
somtimes crash when I update an article which already exists

### ISSUE THREAD

**Issue by todototry** [gollum/gollum#998]

**Comment by todototry** [comment]
1. sometimes crash when I  update an article which already exists  
 2. if I modify the title to be same with one which already exists ,  it will not create a new article, but modify the older one instead, and sometimes clear the older one.
3. there is a high frequency that unicode contents will kill this app.

**Comment by dometto** [comment]
@todotry, you might want to check out the rugged adapter (https://github.com/gollum/rugged_adapter).

**Comment by dometto** [comment]
> if I modify the title to be same with one which already exists , it will not create a new article, but modify the older one instead, and sometimes clear the older one.
That seems like desired behavior, although a warning to the user would be appropriate.

**Comment by SkyCrawl** [comment]
@todototry 
I'm not completely sure about your terminology... Did you actually mean a "page" when you mentioned an "article"? Did you mean "filename" when you mentioned "title"?

If so, `it will not create a new article, but modify the older one instead, and sometimes clear the older one` might be a bug @dometto ?

@todototry 
> there is a high frequency that unicode contents will kill this app

Could you please give us some examples? :)

**Comment by dometto** [comment]
Without a warning that the rename will overwrite an existing page it's definitely a bug. Not sure what's meant by the old page sometimes being cleared out, though?

**Comment by SkyCrawl** [comment]
As far as my fantasy goes, I think the only possible meaning is that the new content is not written and the page is left empty (truncated). Possible reference to the encodings?

**Comment by dometto** [comment]
I'll close this for now for lack of information. @todototry, if you can provide more details, I'll be happy to re-open.
